#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = sokoban
ASM_TO_OBJS     = sokobanJBitmaps.asm sokobanManager.asm
UI_TO_RDFS      = sokoban.ui
SRCS            = sokoban.asm sokobanApplication.asm sokobanBitmaps.asm\
                  sokobanDocument.asm sokobanEditor.asm sokobanJBitmaps.asm\
                  sokobanLevels.asm sokobanManager.asm sokobanMove.asm\
                  sokobanScores.asm sokobanSolve.asm sokobanSounds.asm\
                  sokobanUI.asm sokoban.def screens.ui sokoban.ui\
                  sokobanEditor.ui sokobanStrings.ui
OBJS            = sokobanJBitmaps.obj sokobanManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
