#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = prefmgr
ASM_TO_OBJS     = prefmgr.asm
UI_TO_RDFS      = prefmgr.ui
SRCS            = customSpin.asm prefmgr.asm prefmgrApplication.asm\
                  prefmgrDialogGroup.asm prefmgrDynamic.asm\
                  prefmgrFormats.asm prefmgrInitExit.asm prefmgrModem.asm\
                  prefmgrModule.asm prefmgrModuleList.asm prefmgrMtdHan.asm\
                  prefmgrPrinter.asm prefmgrReboot.asm prefmgrSerial.asm\
                  prefmgrText.asm prefmgrTitledSummons.asm prefmgrUtils.asm\
                  prefPrinter.asm commonUtils.asm prefmgrApplication.def\
                  prefmgrClass.def prefmgrConstant.def prefmgrGeode.def\
                  prefmgrMacros.def prefmgrVariable.def prefmgr.ui
OBJS            = prefmgr.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
