#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = macror
MACRODEM        = MACRODEM.GOC
MACROENG        = MacroengManager.asm
UI_TO_RDFS      =
OBJS            = MACRODEM.obj
COMMON          = MACROENG.DEF MACROENG.H
MODULES         = MACROENG
CMODULES        = MACRODEM
SRCS            = $(MACRODEM) $(MACROENG) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
