#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = SBarP
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = SBarMsg.goc SBarUI.goc SBarApp.goh
OBJS            = SBarMsg.obj SBarUI.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
