#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = PicAlbum
CLASS           = cThumbV.goc popups.goc
MAIN            = mAlbum.goc mImport.goc
PROCESS         = AWATCHER.GOC pBmpOp.goc pCamera.goc pMain.goc pPrint.goc\
                  pSlide.goc pUtils.goc
UI              = uiMain.goc
UICLASS         = uicVDLC.goc
UI_TO_RDFS      =
OBJS            = cThumbV.obj popups.obj mAlbum.obj mImport.obj\
                  AWATCHER.obj pBmpOp.obj pCamera.obj pMain.obj pPrint.obj\
                  pSlide.obj pUtils.obj uiMain.obj uicVDLC.obj
COMMON          = PicAlbum.goh
MODULES         =
CMODULES        = Class Main Process UI UIClass
SRCS            = $(CLASS) $(MAIN) $(PROCESS) $(UI) $(UICLASS) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
