#!/bin/sh -
#

#
#			PrefMgr Convert Script
#
#	Script to convert from the mondo .pcx file containing all of
#	Preferences' icons (in their various resolutions) to the moniker
#	.ui files required by UIC & Esp. 
#
#	The icons are laid out in the standard 6-wise order with the
#	boxes grouped from (0,0) on down (spaced 41 pixels apart in the Y
#	direction):
#		PrefMgr		application icons
#		Interface
#		DateAndTime
#		Background
#		Printer
#		Computer
#		Video
#		Mouse
#		Modem
#		OpSys
#
# $Id: convert,v 1.1 98/04/28 18:42:09 joon Exp $
#

. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps3.pcx 4 PrefMgr -dTM -dTCGA -dYC -dYM $appArgs
cvtpcx -f -m13 -t -z -nPrefMgrTiny prefmgr.tiny.pcx

cvtpcx -f -dSM -dSC -dSCGA -m2 -t -l -x0 -y164 -nPrinter PCX/prefmgr.pcx
cvtpcx -f -dSM -dSC -dSCGA -m2 -t -l -x0 -y328 -nModem PCX/prefmgr.pcx
cvtpcx -f -dSM -dSC -dSCGA -m13 -t -l -x0 -y164 -nText PCX/gprefs2.pcx

