#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = GeoDeck
ASM_TO_OBJS     = geodeck.asm
UI_TO_RDFS      =
SRCS            = CGABubbles.asm CGACheese.asm CGAClassic.asm CGAClub2.asm\
                  CGAClub3.asm CGAClub4.asm CGAClub5.asm CGAClub6.asm\
                  CGAClub7.asm CGAClub8.asm CGAClub9.asm CGAClubA.asm\
                  CGAClubJ.asm CGAClubK.asm CGAClubQ.asm CGAClubT.asm\
                  CGADiamond2.asm CGADiamond3.asm CGADiamond4.asm\
                  CGADiamond5.asm CGADiamond6.asm CGADiamond7.asm\
                  CGADiamond8.asm CGADiamond9.asm CGADiamondA.asm\
                  CGADiamondJ.asm CGADiamondK.asm CGADiamondQ.asm\
                  CGADiamondT.asm CGAEagle.asm CGAFlowers.asm\
                  CGAFractal1.asm CGAFractal2.asm CGAGeoback.asm\
                  CGAGrapes.asm CGAHeart2.asm CGAHeart3.asm CGAHeart4.asm\
                  CGAHeart5.asm CGAHeart6.asm CGAHeart7.asm CGAHeart8.asm\
                  CGAHeart9.asm CGAHeartA.asm CGAHeartJ.asm CGAHeartK.asm\
                  CGAHeartQ.asm CGAHeartT.asm CGAHinge.asm CGAJoker.asm\
                  CGAMasks.asm CGANefertite.asm CGAPyramid.asm\
                  CGASpade2.asm CGASpade3.asm CGASpade4.asm CGASpade5.asm\
                  CGASpade6.asm CGASpade7.asm CGASpade8.asm CGASpade9.asm\
                  CGASpadeA.asm CGASpadeJ.asm CGASpadeK.asm CGASpadeQ.asm\
                  CGASpadeT.asm CGAWin.asm geodeck.asm LCBubbles.asm\
                  LCCheese.asm LCClassic.asm LCClub2.asm LCClub3.asm\
                  LCClub4.asm LCClub5.asm LCClub6.asm LCClub7.asm\
                  LCClub8.asm LCClub9.asm LCClubA.asm LCClubJ.asm\
                  LCClubK.asm LCClubQ.asm LCClubT.asm LCDiamond2.asm\
                  LCDiamond3.asm LCDiamond4.asm LCDiamond5.asm\
                  LCDiamond6.asm LCDiamond7.asm LCDiamond8.asm\
                  LCDiamond9.asm LCDiamondA.asm LCDiamondJ.asm\
                  LCDiamondK.asm LCDiamondQ.asm LCDiamondT.asm LCEagle.asm\
                  LCFlowers.asm LCFractal1.asm LCFractal2.asm LCGeoback.asm\
                  LCGrapes.asm LCHeart2.asm LCHeart3.asm LCHeart4.asm\
                  LCHeart5.asm LCHeart6.asm LCHeart7.asm LCHeart8.asm\
                  LCHeart9.asm LCHeartA.asm LCHeartJ.asm LCHeartK.asm\
                  LCHeartQ.asm LCHeartT.asm LCHinge.asm LCJoker.asm\
                  LCMasks.asm LCNefertite.asm LCPyramid.asm LCSpade2.asm\
                  LCSpade3.asm LCSpade4.asm LCSpade5.asm LCSpade6.asm\
                  LCSpade7.asm LCSpade8.asm LCSpade9.asm LCSpadeA.asm\
                  LCSpadeJ.asm LCSpadeK.asm LCSpadeQ.asm LCSpadeT.asm\
                  LCWin.asm LMBubbles.asm LMCheese.asm LMClassic.asm\
                  LMClub2.asm LMClub3.asm LMClub4.asm LMClub5.asm\
                  LMClub6.asm LMClub7.asm LMClub8.asm LMClub9.asm\
                  LMClubA.asm LMClubJ.asm LMClubK.asm LMClubQ.asm\
                  LMClubT.asm LMDiamond2.asm LMDiamond3.asm LMDiamond4.asm\
                  LMDiamond5.asm LMDiamond6.asm LMDiamond7.asm\
                  LMDiamond8.asm LMDiamond9.asm LMDiamondA.asm\
                  LMDiamondJ.asm LMDiamondK.asm LMDiamondQ.asm\
                  LMDiamondT.asm LMEagle.asm LMFlowers.asm LMFractal1.asm\
                  LMFractal2.asm LMGeoback.asm LMGrapes.asm LMHeart2.asm\
                  LMHeart3.asm LMHeart4.asm LMHeart5.asm LMHeart6.asm\
                  LMHeart7.asm LMHeart8.asm LMHeart9.asm LMHeartA.asm\
                  LMHeartJ.asm LMHeartK.asm LMHeartQ.asm LMHeartT.asm\
                  LMHinge.asm LMJoker.asm LMMasks.asm LMNefertite.asm\
                  LMPyramid.asm LMSpade2.asm LMSpade3.asm LMSpade4.asm\
                  LMSpade5.asm LMSpade6.asm LMSpade7.asm LMSpade8.asm\
                  LMSpade9.asm LMSpadeA.asm LMSpadeJ.asm LMSpadeK.asm\
                  LMSpadeQ.asm LMSpadeT.asm LMWin.asm
OBJS            = geodeck.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
