X10DRVR.obj \
X10DRVR.eobj: GEOS.DEF FILE.DEF GEODE.DEF RESOURCE.DEF EC.DEF DRIVER.DEF \
                LMEM.DEF HEAP.DEF SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF \
                TIMER.DEF INITFILE.DEF INTERNAL/INTERRUP.DEF X10INIT.ASM \
                X10STRAT.ASM X10SEND.ASM X10SLEEP.ASM

X10DRVREC.geo X10DRVR.geo : GEOS.LDF 