#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = ttype
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = ttresult.goc ttype.goc ttui.goc ttdb.goc ttedit.goc\
                  ttkeyobj.goc ttkeyhan.goc options.goh ttclass.goh\
                  bboxreg.goh ttdefs.goh externs.goh tticons.goh
OBJS            = ttresult.obj ttype.obj ttui.obj ttdb.obj ttedit.obj\
                  ttkeyobj.obj ttkeyhan.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
