#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = ttype
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = ttdb.goc ttedit.goc ttkeyhan.goc ttkeyobj.goc\
                  ttresult.goc ttui.goc ttype.goc bboxreg.goh externs.goh\
                  options.goh ttclass.goh ttdefs.goh tticons.goh
OBJS            = ttdb.obj ttedit.obj ttkeyhan.obj ttkeyobj.obj\
                  ttresult.obj ttui.obj ttype.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
