#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = TTYPE
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = TTDB.GOC TTEDIT.GOC TTKEYHAN.GOC TTKEYOBJ.GOC\
                  TTRESULT.GOC TTUI.GOC TTYPE.GOC BBOXREG.GOH EXTERNS.GOH\
                  OPTIONS.GOH TTCLASS.GOH TTDEFS.GOH TTICONS.GOH
OBJS            = TTDB.obj TTEDIT.obj TTKEYHAN.obj TTKEYOBJ.obj\
                  TTRESULT.obj TTUI.obj TTYPE.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
