MS7MANAGER.obj \
MS7MANAGER.eobj: COMMON/DOS7GEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF \
                RESOURCE.DEF EC.DEF LMEM.DEF SYSTEM.DEF LOCALIZE.DEF \
                SLLANG.DEF DRIVE.DEF DISK.DEF FILE.DEF DRIVER.DEF \
                TIMEDATE.DEF SEM.DEF TIMER.DEF INITFILE.DEF GCNLIST.DEF \
                OBJECTS/METAC.DEF OBJECT.DEF CHUNKARR.DEF GEOWORKS.DEF \
                GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF \
                INTERNAL/SEMINT.DEF INTERNAL/INTERRUP.DEF \
                INTERNAL/DOS.DEF FILEENUM.DEF INTERNAL/FILEINT.DEF \
                INTERNAL/DRIVEINT.DEF INTERNAL/DISKINT.DEF \
                INTERNAL/FSD.DEF INTERNAL/LOG.DEF INTERNAL/HEAPINT.DEF \
                SYSSTATS.DEF INTERNAL/GEODESTR.DEF INTERNAL/FILESTR.DEF \
                INTERNAL/LOCALINT.DEF CHAR.DEF INTERNAL/FSDRIVER.DEF \
                INTERNAL/DOSFSDR.DEF INTERNAL/PRODFEATURES.DEF ASSERT.DEF \
                INTERNAL/THREADIN.DEF MS7INTERFACE.DEF \
                COMMON/DOS7CONSTANT.DEF COMMON/DOS7MACRO.DEF \
                DOSSTRINGS.ASM COMMON/DOS7VARIABLE.DEF MS7STRINGS.ASM \
                MSVARIABLE.DEF MS7UTILS.ASM MS7PATH.ASM DOSENTRY.ASM \
                COMMON/DOS7DISK.ASM DOSDRIVE.ASM MSDRIVE.ASM \
                COMMON/DOS7PATH.ASM COMMON/DOS7ENUM.ASM DOSFORMAT.ASM \
                DOSFORMATINIT.ASM DOSDISKCOPY.ASM COMMON/DOS7IO.ASM \
                DOSPRIMARY.ASM DOSINITEXIT.ASM COMMON/DOS7INITEXIT.ASM \
                DOSCRITICAL.ASM COMMON/DOS7UTILS.ASM \
                COMMON/DOS7VIRTUAL.ASM DOSWAITPOST.ASM MSSFT.ASM \
                DOSSUSPEND.ASM COMMON/DOS7LINK.ASM DOSIDLE.ASM \
                COMMON/DOS7FILECHANGE.ASM

ms7EC.geo ms7.geo : GEOS.LDF 