#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = megafile
ASM_TO_OBJS     = megafileManager.asm
UI_TO_RDFS      =
SRCS            = megafileManager.asm megafileDevSpec.asm gfsDisk.asm\
                  gfsEntry.asm gfsEnum.asm gfsExtAttrs.asm gfsInitExit.asm\
                  gfsIO.asm gfsMapPath.asm gfsPath.asm gfsUtils.asm\
                  megafileConstant.def megafileVariable.def
OBJS            = megafileManager.obj
LOBJS           =
LIBNAME         = fsd
PROTOCONST      = FS

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
