#!/bin/csh
# $Id: convert,v 1.1.20.1 97/03/29 10:29:15 canavese Exp $
#
cvtpcx -j -m0 -x1 -y1 -w72 -h72 -nViolet paint.pcx
cvtpcx -j -m0 -x1 -y73 -w72 -h72 -nGreen paint.pcx
cvtpcx -j -m0 -x1 -y145 -w72 -h72 -nRed paint.pcx
cvtpcx -j -m0 -x1 -y217 -w72 -h72 -nBlue paint.pcx
cvtpcx -j -m0 -x1 -y289 -w72 -h72 -nYellow paint.pcx
