#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = grafcalc
MAIN            = bereich.goc Calcvalue.goc edit.goc Funktion.goc\
                  grprop.goc Keyboard.goc Options.goc Parser.goc\
                  process.goc sprachenwahl.goc view.goc grafcalc.goh
UI              = appui.goc appui.goh
UI_TO_RDFS      =
OBJS            = bereich.obj Calcvalue.obj edit.obj Funktion.obj\
                  grprop.obj Keyboard.obj Options.obj Parser.obj\
                  process.obj sprachenwahl.obj view.obj appui.obj
COMMON          =
MODULES         =
CMODULES        = Main UI
SRCS            = $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
