#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = grafcalc
MAIN            = bereich.goc calcvalue.goc edit.goc funktion.goc\
                  grprop.goc keyboard.goc options.goc parser.goc\
                  process.goc sprachenwahl.goc view.goc grafcalc.goh\
                  lmacros.goh
UI              = appui.goc appui.goh
UI_TO_RDFS      =
OBJS            = bereich.obj calcvalue.obj edit.obj funktion.obj\
                  grprop.obj keyboard.obj options.obj parser.obj\
                  process.obj sprachenwahl.obj view.obj appui.obj
COMMON          =
MODULES         =
CMODULES        = Main UI
SRCS            = $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
