#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = GrafCalc
MAIN            = bereich.goc edit.goc Funktion.goc grprop.goc Keyboard.goc\
                  Options.goc PROCESS.GOC view.goc
UI              = APPUI.GOC APPUI.GOH
UI_TO_RDFS      =
OBJS            = bereich.obj edit.obj Funktion.obj grprop.obj Keyboard.obj\
                  Options.obj PROCESS.obj view.obj APPUI.obj
COMMON          = GRAFCALC.GOH LMACROS.GOH MATHFUNC.GOH
MODULES         =
CMODULES        = MAIN UI
SRCS            = $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
