#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bbxbrow
ASMTOOLS        = asmtoolsManager.asm
HTMLVIEW        = AWATCHER.goc GLBANIM.goc HTMLVIEW.goc ImportG.goc\
                  LoadURL.goc OpenClos.goc scrapbk.goc StatText.goc\
                  UIAction.goc UIOften.goc UIRare.goc
INIT            = INIT.goc
NAVIGATE        = BOOKCLAS.goc BOOKMARK.goc FAVORCLS.goc FAVORITE.goc\
                  NAVCACHE.goc NAVIGATE.goc
URLDOC          = LOCALPAG.goc URLDOC.goc
URLDOCCT        = URLDOCCT.goc
URLFETCH        = URLFETCH.goc
URLFRAME        = FRFETCH.goc URLFRAME.goc
URLTEXT         = URLTEXT.goc URLTEXT2.goc
UI_TO_RDFS      =
OBJS            = AWATCHER.obj GLBANIM.obj HTMLVIEW.obj ImportG.obj\
                  LoadURL.obj OpenClos.obj scrapbk.obj StatText.obj\
                  UIAction.obj UIOften.obj UIRare.obj INIT.obj BOOKCLAS.obj\
                  BOOKMARK.obj FAVORCLS.obj FAVORITE.obj NAVCACHE.obj\
                  NAVIGATE.obj LOCALPAG.obj URLDOC.obj URLDOCCT.obj\
                  URLFETCH.obj FRFETCH.obj URLFRAME.obj URLTEXT.obj\
                  URLTEXT2.obj
COMMON          = bookclas.goh bookmark.goh favorcls.goh favorite.goh\
                  glbanim.goh htmlview.goh htmlv_ui.goh importg.goh\
                  javascr.h options.goh prodbbx.goh prodgpc.goh prodndo.goh\
                  stattext.goh urlfetch.goh
MODULES         = ASMTOOLS
CMODULES        = htmlview init navigate urldoc urldocct urlfetch urlframe\
                  urltext
SRCS            = $(ASMTOOLS) $(HTMLVIEW) $(INIT) $(NAVIGATE) $(URLDOC)\
                  $(URLDOCCT) $(URLFETCH) $(URLFRAME) $(URLTEXT) $(COMMON)
LOBJS           =

PRODUCTS        = AB 

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(AB/$(DEPFILE))
#include "AB/$(DEPFILE)"
#endif
