#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bbxbrow
ASMTOOLS        = asmtoolsManager.asm
HTMLVIEW        = AWATCHER.goc GLBANIM.goc ImportG.goc LoadURL.goc\
                  scrapbk.goc StatText.goc UIOften.goc HTMLVIEW.goc\
                  OpenClos.goc UIAction.goc UIRare.goc
INIT            = INIT.goc
JS              = browser.goc sebrowse.goc
NAVIGATE        = BOOKCLAS.goc FAVORCLS.goc FAVORITE.goc NAVCACHE.goc\
                  BOOKMARK.goc NAVIGATE.goc
URLDOC          = LOCALPAG.goc URLDOC.goc
URLDOCCT        = URLDOCCT.goc
URLFETCH        = URLFETCH.goc
URLFRAME        = FRFETCH.goc URLFRAME.goc
URLTEXT         = URLTEXT.goc URLTEXT2.goc
UI_TO_RDFS      =
OBJS            = AWATCHER.obj GLBANIM.obj ImportG.obj LoadURL.obj\
                  scrapbk.obj StatText.obj UIOften.obj HTMLVIEW.obj\
                  OpenClos.obj UIAction.obj UIRare.obj INIT.obj browser.obj\
                  sebrowse.obj BOOKCLAS.obj FAVORCLS.obj FAVORITE.obj\
                  NAVCACHE.obj BOOKMARK.obj NAVIGATE.obj LOCALPAG.obj\
                  URLDOC.obj URLDOCCT.obj URLFETCH.obj FRFETCH.obj\
                  URLFRAME.obj URLTEXT.obj URLTEXT2.obj
COMMON          = bookclas.goh bookmark.goh bookui.goh favorcls.goh\
                  favorite.goh glbanim.goh javascr.h prodndo.goh sebrowse.h\
                  stattext.goh urlfetch.goh favorui.goh\
                  htmlv_ui_dlg_dwnl.goh htmlv_ui_men_autobrowse.goh\
                  htmlv_ui_men_history.goh htmlv_ui_men_html.goh\
                  htmlv_ui_men_js.goh htmlv_ui_men_kidguard.goh\
                  htmlv_ui_men_nav.goh htmlv_ui_men_search.goh\
                  htmlv_ui_toolb_big.goh htmlv_ui_toolb_small.goh\
                  localui.goh htmlv_ui_dlg_kidguard.goh\
                  htmlv_ui_main_wrapper.goh htmlv_ui_url.goh importg.goh\
                  prodgpc.goh htmlv_ui_main_wrapper_fg.goh\
                  htmlv_ui_status_indctrs.goh htmlv_ui_men_edit.goh\
                  htmlv_ui.goh htmlv_ui_men_options.goh\
                  htmlv_ui_men_view.goh htmlv_ui_toolb_simple.goh\
                  htmlview.goh options.goh prodbbx.goh\
                  htmlv_ui_men_file.goh
MODULES         = ASMTOOLS
CMODULES        = htmlview init js navigate urldoc urldocct urlfetch\
                  urlframe urltext
SRCS            = $(ASMTOOLS) $(HTMLVIEW) $(INIT) $(JS) $(NAVIGATE)\
                  $(URLDOC) $(URLDOCCT) $(URLFETCH) $(URLFRAME) $(URLTEXT)\
                  $(COMMON)
LOBJS           =

PRODUCTS        = AB JSAB 

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(AB/$(DEPFILE))
#include "AB/$(DEPFILE)"
#endif

#if exists(JSAB/$(DEPFILE))
#include "JSAB/$(DEPFILE)"
#endif
