#
# This Makefile is for use when distributing Tcl to the outside world.
# It is simplified so that it doesn't include any Sprite-specific stuff.
#

OBJS 		= tclBasic.o tclCmdAH.o tclCmdIZ.o tclExpr.o tclProc.o \
                  tclUtil.o

CSRCS 		= tclBasic.c tclCmdAH.c tclCmdIZ.c tclExpr.c tclProc.c \
                  tclUtil.c

CC		= gcc -fstrength-reduce -fcombine-regs -finline-functions
CFLAGS		= -g -O

#include	<makelib.mk>

libtcl.a	: libtcl.a(${OBJS}) .EXPORTSAME			MAKELIB
	
tags		: $(CSRCS)
	ctags -wt $(CSRCS)

TAGS		: $(CSRCS)
	etags -wt $(CSRCS) *.h

tclTest		: tcl.o libtcl.a .EXPORTSAME
	$(CC) $(CFLAGS) $(.ALLSRC) -o $(.TARGET)
#ifdef is68k
tclTest		: ../sys/libsys.a
#endif

tsh		: tsh.o libtcl.a .EXPORTSAME
	$(CC) $(CFLAGS) $(.ALLSRC) -o $(.TARGET)

# DO NOT DELETE THIS LINE -- make depend depends on it.

tcl.o: /usr/include/stdio.h /usr/include/sys/time.h tcl.h
tclBasic.o: /usr/include/stdio.h /usr/include/ctype.h tclInt.h tcl.h
tclCmd.o: /usr/include/ctype.h /usr/include/signal.h /usr/include/stdio.h
tclCmd.o: /usr/include/sys/types.h /usr/include/sys/errno.h
tclCmd.o: /usr/include/sys/file.h /usr/include/sys/fcntl.h
tclCmd.o: /usr/include/sys/stat.h /usr/include/sys/wait.h
tclCmd.o: /usr/include/sys/time.h /usr/include/sys/resource.h tclInt.h tcl.h
tclCmdAH.o: /usr/include/ctype.h /usr/include/signal.h /usr/include/stdio.h
tclCmdAH.o: /usr/include/sys/types.h /usr/include/sys/errno.h
tclCmdAH.o: /usr/include/sys/file.h /usr/include/sys/fcntl.h
tclCmdAH.o: /usr/include/sys/stat.h /usr/include/sys/time.h
tclCmdAH.o: /usr/include/sys/resource.h /usr/include/sys/wait.h tclInt.h
tclCmdAH.o: tcl.h
tclCmdIZ.o: /usr/include/ctype.h /usr/include/stdio.h
tclCmdIZ.o: /usr/include/sys/types.h /usr/include/sys/file.h
tclCmdIZ.o: /usr/include/sys/fcntl.h /usr/include/sys/stat.h
tclCmdIZ.o: /usr/include/sys/time.h tclInt.h tcl.h
tclExpr.o: /usr/include/stdio.h /usr/include/ctype.h tcl.h
tclProc.o: /usr/include/stdio.h /usr/include/ctype.h tclInt.h tcl.h
tclUtil.o: /usr/include/ctype.h tcl.h tclInt.h /usr/include/stdio.h
tclUtil.o: /usr/include/varargs.h
