#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = NINFNT
ASM_TO_OBJS     = ninfnt.asm ninfntList.asm
UI_TO_RDFS      = NINFNT.UI
SRCS            = fontInstall.asm ninfnt.asm ninfntChar.asm ninfntFile.asm\
                  ninfntFont.asm ninfntIDs.asm ninfntList.asm\
                  ninfntStrings.asm ninfntTables.asm ninfntUtils.asm\
                  ninfntVariable.asm string.asm fontInstall.def\
                  ninfntConstant.def ninfntNimbusConstant.def ninfnt.ui
OBJS            = ninfnt.obj ninfntList.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
