DOCUMENT.obj \
DOCUMENT.eobj: Document/DocumentMANAGER.ASM \
                DRAWGEODE.DEF GEOS.DEF SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF \
                INITFILE.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF \
                OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF VM.DEF \
                FILE.DEF TIMEDATE.DEF USERINFO.DEF OBJECTS/WINC.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF PRODUCT.DEF \
                OBJECTS/INPUTC.DEF INTERNAL/PRINTDR.DEF DRIVER.DEF \
                PRINT.DEF INTERNAL/SPOOLINT.DEF INTERNAL/SERIALDR.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/PARALLDR.DEF \
                INTERNAL/VIDEODR.DEF HUGEARR.DEF UI.DEF INPUT.DEF HWR.DEF \
                OBJECTS/PROCESSC.DEF GCNLIST.DEF OBJECTS/TEXT/TCOMMON.DEF \
                STYLESH.DEF IACP.DEF OBJECTS/UIINPUTC.DEF \
                OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF \
                INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF DISK.DEF DRIVE.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF INTERNAL/PRODFEATURES.DEF \
                DBASE.DEF BITMAP.DEF OBJECTS/SPLINE.DEF RULER.DEF \
                GROBJ.DEF OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF \
                OBJECTS/TEXT/TCTRLC.DEF IMPEX.DEF IECOMMON.DEF \
                LIBRARY.DEF DRAWCONSTANT.DEF DRAWGLOBAL.DEF DRAWLEVEL.DEF \
                DRAWAPPLICATION.DEF DRAWDISPLAY.DEF DOCUMENTCONSTANT.DEF \
                ../UI/UICONSTANT.DEF DRAWDOCUMENT.DEF DRAWGROBJBODY.DEF \
                DOCUMENT12XCONVERSIONCONSTANT.DEF DOCUMENTMANAGER.RDEF \
                DOCUMENTBODY.ASM DOCUMENTDOCUMENT.ASM DOCUMENTCONVERT.ASM \
                INTERNAL/CONVERT.DEF DOCUMENTUTILS.ASM DOCUMENTPRINT.ASM \
                DOCUMENTDISPLAY.ASM
MAIN.obj \
MAIN.eobj: Main/MainMANAGER.ASM \
                DRAWGEODE.DEF GEOS.DEF SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF \
                INITFILE.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF \
                OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF VM.DEF \
                FILE.DEF TIMEDATE.DEF USERINFO.DEF OBJECTS/WINC.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF PRODUCT.DEF \
                OBJECTS/INPUTC.DEF INTERNAL/PRINTDR.DEF DRIVER.DEF \
                PRINT.DEF INTERNAL/SPOOLINT.DEF INTERNAL/SERIALDR.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/PARALLDR.DEF \
                INTERNAL/VIDEODR.DEF HUGEARR.DEF UI.DEF INPUT.DEF HWR.DEF \
                OBJECTS/PROCESSC.DEF GCNLIST.DEF OBJECTS/TEXT/TCOMMON.DEF \
                STYLESH.DEF IACP.DEF OBJECTS/UIINPUTC.DEF \
                OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF \
                INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF DISK.DEF DRIVE.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF INTERNAL/PRODFEATURES.DEF \
                DBASE.DEF BITMAP.DEF OBJECTS/SPLINE.DEF RULER.DEF \
                GROBJ.DEF OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF \
                OBJECTS/TEXT/TCTRLC.DEF IMPEX.DEF IECOMMON.DEF \
                LIBRARY.DEF DRAWCONSTANT.DEF DRAWGLOBAL.DEF DRAWLEVEL.DEF \
                DRAWAPPLICATION.DEF DRAWDISPLAY.DEF MAININIT.ASM
UI.obj \
UI.eobj: UI/UIMANAGER.ASM \
                DRAWGEODE.DEF GEOS.DEF SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF \
                INITFILE.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF \
                OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF VM.DEF \
                FILE.DEF TIMEDATE.DEF USERINFO.DEF OBJECTS/WINC.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF PRODUCT.DEF \
                OBJECTS/INPUTC.DEF INTERNAL/PRINTDR.DEF DRIVER.DEF \
                PRINT.DEF INTERNAL/SPOOLINT.DEF INTERNAL/SERIALDR.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/PARALLDR.DEF \
                INTERNAL/VIDEODR.DEF HUGEARR.DEF UI.DEF INPUT.DEF HWR.DEF \
                OBJECTS/PROCESSC.DEF GCNLIST.DEF OBJECTS/TEXT/TCOMMON.DEF \
                STYLESH.DEF IACP.DEF OBJECTS/UIINPUTC.DEF \
                OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF \
                INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF DISK.DEF DRIVE.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF INTERNAL/PRODFEATURES.DEF \
                DBASE.DEF BITMAP.DEF OBJECTS/SPLINE.DEF RULER.DEF \
                GROBJ.DEF OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF \
                OBJECTS/TEXT/TCTRLC.DEF IMPEX.DEF IECOMMON.DEF \
                LIBRARY.DEF DRAWCONSTANT.DEF DRAWGLOBAL.DEF DRAWLEVEL.DEF \
                DRAWAPPLICATION.DEF DRAWDISPLAY.DEF SPELL.DEF \
                UICONSTANT.DEF DRAWDOCUMENT.DEF UIMANAGER.RDEF \
                UIDRAWAPPLICATION.ASM UIMAIN.ASM UITEMPLATE.ASM \
                UIGIFIMAGE.ASM UIGIFIMAGE.DEF
DOCUMENTMANAGER.rdef: GENERIC.UIH PRODUCT.UIH GROBJ.UIH OBJECTS/COLORC.UIH \
                OBJECTS/STYLES.UIH BITMAP.UIH OBJECTS/TEXT/TCTRL.UIH \
                RULER.UIH DOCUMENT/DOCUMENTDATA.UI
UIMANAGER.rdef: GENERIC.UIH PRODUCT.UIH IMPEX.UIH SPOOL.UIH GROBJ.UIH \
                OBJECTS/COLORC.UIH OBJECTS/STYLES.UIH BITMAP.UIH \
                OBJECTS/TEXT/TCTRL.UIH RULER.UIH OBJECTS/SPLINE.UIH \
                SPELL.UIH INTERNAL/PRODFEATURES.UIH UI/UIDRAWDOCUMENT.UIH \
                UI/UIMAIN.UI ART/MKRGEODRAWDOC.UI ART/MKRGEODRAW.UI \
                ART/MKRGEODRAWTINY.UI ART/MKRBITMAPPTRTOOL.UI \
                UI/UIDOCUMENT.UI UI/UILEVEL.UI USRLEVEL.UIH \
                UI/UITEMPLATE.UI ART/WIZARDHEADER.UI ART/MKRWIZARDPREV.UI \
                ART/MKRWIZARDNEXT.UI

drawEC.geo draw.geo : UI.LDF GROBJ.LDF SPOOL.LDF GEOS.LDF RULER.LDF BITMAP.LDF SPLINE.LDF TEXT.LDF SPELL.LDF CONVERT.LDF 