VGA16MANAGER.obj \
VGA16MANAGER.eobj: VIDCOMGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF DRIVER.DEF LMEM.DEF INTERNAL/SEMINT.DEF \
                GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF WIN.DEF \
                CHAR.DEF LOCALIZE.DEF SLLANG.DEF SYSTEM.DEF \
                INTERNAL/HEAPINT.DEF SYSSTATS.DEF INTERNAL/GSTATE.DEF \
                INTERNAL/TMATRIX.DEF INTERNAL/FONTDR.DEF FILE.DEF \
                INTERNAL/WINDOW.DEF INTERNAL/INTERRUP.DEF \
                INTERNAL/THREADIN.DEF INTERNAL/VIDEODR.DEF HUGEARR.DEF \
                INITFILE.DEF VGA16CONSTANT.DEF VIDCOMCONSTANT.DEF \
                VGA16MACRO.DEF VIDCOMMACRO.DEF VGA16DEVINFO.ASM \
                VIDCOMTABLES.ASM VGA16TABLES.ASM VIDCOMVARIABLE.DEF \
                VGA16VARIABLE.DEF VGA16STRINGTAB.ASM VIDCOMENTRY.ASM \
                VIDCOMOUTPUT.ASM VIDCOMCHARS.ASM VIDCOMFONT.ASM \
                VGA16UNDER.ASM VIDCOMUTILS.ASM VIDCOMREGION.ASM \
                VIDCOMXOR.ASM VIDCOMINFO.ASM VIDCOMESCAPE.ASM \
                VIDCOMPALETTE.ASM VGA16OUTPUT.ASM VGA16GENCHAR.ASM \
                VGA16UTILS.ASM VGA16CHARS.ASM VGA16POINTER.ASM \
                VGA16ESCTAB.ASM VGA16PALETTE.ASM VGA16DITHER.ASM \
                VIDCOMPOLYGON.ASM VIDCOMLINE.ASM VIDCOMPUTLINE.ASM \
                VIDCOMRASTER.ASM VGA16RASTER.ASM VGA16ADMIN.ASM \
                VIDCOMEXCLBOUNDS.ASM

VGA16EC.geo VGA16.geo : GEOS.LDF 