#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = vga16
ASM_TO_OBJS     = vga16Manager.asm
UI_TO_RDFS      =
SRCS            = vga16Admin.asm vga16Chars.asm vga16DevInfo.asm\
                  vga16Dither.asm vga16Escape.asm vga16EscTab.asm\
                  vga16GenChar.asm vga16Manager.asm vga16Output.asm\
                  vga16Palette.asm vga16Pointer.asm vga16Raster.asm\
                  vga16StringTab.asm vga16Tables.asm vga16Under.asm\
                  vga16Utils.asm vidcomTables.asm vidcomEntry.asm\
                  vidcomOutput.asm vidcomChars.asm vidcomFont.asm\
                  vidcomUtils.asm vidcomRegion.asm vidcomXOR.asm\
                  vidcomInfo.asm vidcomEscape.asm vidcomPalette.asm\
                  vidcomPolygon.asm vidcomLine.asm vidcomPutLine.asm\
                  vidcomRaster.asm vidcomExclBounds.asm vga16Constant.def\
                  vga16Macro.def vga16Variable.def
OBJS            = vga16Manager.obj
LOBJS           =
LIBNAME         = video
PROTOCONST      = VIDEO

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
