#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = comm
ASM_TO_OBJS     = commManager.asm
UI_TO_RDFS      =
SRCS            = comm.asm commEC.asm commInit.asm commManager.asm\
                  commOpenClose.asm commStrings.asm commUtil.asm slip.asm\
                  commConstant.def commMacro.def commVariable.def
OBJS            = commManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
