ARTICLE.obj \
ARTICLE.eobj: Article/ArticleMANAGER.ASM \
                STUDIOGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF CHUNKARR.DEF FILE.DEF VM.DEF DBASE.DEF \
                CHAR.DEF INPUT.DEF HWR.DEF THREAD.DEF \
                INTERNAL/THREADIN.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                OBJECTS/WINC.DEF WIN.DEF OBJECTS/METAC.DEF GEOWORKS.DEF \
                OBJECTS/INPUTC.DEF UI.DEF TEXT.DEF LOCALIZE.DEF \
                SLLANG.DEF OBJECTS/PROCESSC.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SPOOL.DEF PRINT.DEF INTERNAL/PRODFEATURES.DEF IMPEX.DEF \
                IECOMMON.DEF RULER.DEF GROBJ.DEF OBJECTS/SPLINE.DEF \
                OBJECTS/COLORC.DEF OBJECTS/VTEXTC.DEF HUGEARR.DEF \
                OBJECTS/STYLES.DEF BITMAP.DEF SSMETA.DEF HYPRLNK.DEF \
                HOTSPOT.DEF OBJECTS/VLTEXTC.DEF CONVIEW.DEF COMPRESS.DEF \
                TIMER.DEF HELPFILE.DEF STUDIOCONSTANT.DEF \
                STUDIODOCUMENT.DEF STUDIOARTICLE.DEF ARTICLEARTICLE.ASM
DOCUMENT.obj \
DOCUMENT.eobj: Document/DocumentMANAGER.ASM \
                STUDIOGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF CHUNKARR.DEF FILE.DEF VM.DEF DBASE.DEF \
                CHAR.DEF INPUT.DEF HWR.DEF THREAD.DEF \
                INTERNAL/THREADIN.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                OBJECTS/WINC.DEF WIN.DEF OBJECTS/METAC.DEF GEOWORKS.DEF \
                OBJECTS/INPUTC.DEF UI.DEF TEXT.DEF LOCALIZE.DEF \
                SLLANG.DEF OBJECTS/PROCESSC.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SPOOL.DEF PRINT.DEF INTERNAL/PRODFEATURES.DEF IMPEX.DEF \
                IECOMMON.DEF RULER.DEF GROBJ.DEF OBJECTS/SPLINE.DEF \
                OBJECTS/COLORC.DEF OBJECTS/VTEXTC.DEF HUGEARR.DEF \
                OBJECTS/STYLES.DEF BITMAP.DEF SSMETA.DEF HYPRLNK.DEF \
                HOTSPOT.DEF OBJECTS/VLTEXTC.DEF CONVIEW.DEF COMPRESS.DEF \
                TIMER.DEF HELPFILE.DEF STUDIOCONSTANT.DEF \
                STUDIODOCUMENT.DEF STUDIOAPPLICATION.DEF \
                STUDIODISPLAY.DEF STUDIOPROCESS.DEF SYSTEM.DEF \
                GSTRING.DEF LIBRARY.DEF INTERNAL/GRWININT.DEF \
                INTERNAL/CONVERT.DEF OBJECTS/TEXT/TCTRLC.DEF MATH.DEF \
                CELL.DEF PARSE.DEF SSHEET.DEF STUDIOARTICLE.DEF \
                STUDIOGROBJHEAD.DEF STUDIOGROBJBODY.DEF STUDIOHDRFTR.DEF \
                FLOWREGION.DEF DOCUMENTMANAGER.RDEF DOCUMENTDATA.ASM \
                DOCUMENTDOCUMENT.ASM DOCUMENTOPENCLOSE.ASM \
                DOCUMENTCONTENT.ASM DOCUMENTARTICLE.ASM \
                DOCUMENTSECTION.ASM DOCUMENTPAGE.ASM DOCUMENTDRAW.ASM \
                DOCUMENTMANIP.ASM DOCUMENTUTILS.ASM DOCUMENTFLOW.ASM \
                DOCUMENTFRAME.ASM DOCUMENTNOTIFY.ASM DOCUMENTMISC.ASM \
                DOCUMENTPRINT.ASM DOCUMENTMERGE.ASM \
                DOCUMENTMERGESCRAP.ASM DOCUMENTHEAD.ASM \
                DOCUMENTATTRMGR.ASM DOCUMENTBODY.ASM DOCUMENTHDRFTR.ASM \
                DOCUMENTUSERSECTION.ASM DOCUMENTPAGESETUP.ASM \
                DOCUMENTREGION.ASM DOCUMENTMASTERPAGE.ASM \
                DOCUMENTDISPLAY.ASM DOCUMENTSCROLL.ASM DOCUMENTIMPEX.ASM \
                DOCUMENTVARIABLE.ASM DOCUMENTCONVERT.ASM DOCUMENTHELP.ASM \
                DOCUMENTSEARCHSP.ASM
MAIN.obj \
MAIN.eobj: Main/MainMANAGER.ASM \
                STUDIOGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF CHUNKARR.DEF FILE.DEF VM.DEF DBASE.DEF \
                CHAR.DEF INPUT.DEF HWR.DEF THREAD.DEF \
                INTERNAL/THREADIN.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                OBJECTS/WINC.DEF WIN.DEF OBJECTS/METAC.DEF GEOWORKS.DEF \
                OBJECTS/INPUTC.DEF UI.DEF TEXT.DEF LOCALIZE.DEF \
                SLLANG.DEF OBJECTS/PROCESSC.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SPOOL.DEF PRINT.DEF INTERNAL/PRODFEATURES.DEF IMPEX.DEF \
                IECOMMON.DEF RULER.DEF GROBJ.DEF OBJECTS/SPLINE.DEF \
                OBJECTS/COLORC.DEF OBJECTS/VTEXTC.DEF HUGEARR.DEF \
                OBJECTS/STYLES.DEF BITMAP.DEF SSMETA.DEF HYPRLNK.DEF \
                HOTSPOT.DEF OBJECTS/VLTEXTC.DEF CONVIEW.DEF COMPRESS.DEF \
                TIMER.DEF HELPFILE.DEF STUDIOCONSTANT.DEF \
                STUDIOPROCESS.DEF STUDIODOCUMENT.DEF \
                STUDIOAPPLICATION.DEF FLOWREGION.DEF INITFILE.DEF \
                OBJECTS/TEXT/TCTRLC.DEF STUDIOCONTROL.DEF MAINPROCESS.ASM \
                MAINAPP.ASM MAINAPPUI.ASM
UI.obj \
UI.eobj: UI/UIMANAGER.ASM \
                STUDIOGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF CHUNKARR.DEF FILE.DEF VM.DEF DBASE.DEF \
                CHAR.DEF INPUT.DEF HWR.DEF THREAD.DEF \
                INTERNAL/THREADIN.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                OBJECTS/WINC.DEF WIN.DEF OBJECTS/METAC.DEF GEOWORKS.DEF \
                OBJECTS/INPUTC.DEF UI.DEF TEXT.DEF LOCALIZE.DEF \
                SLLANG.DEF OBJECTS/PROCESSC.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SPOOL.DEF PRINT.DEF INTERNAL/PRODFEATURES.DEF IMPEX.DEF \
                IECOMMON.DEF RULER.DEF GROBJ.DEF OBJECTS/SPLINE.DEF \
                OBJECTS/COLORC.DEF OBJECTS/VTEXTC.DEF HUGEARR.DEF \
                OBJECTS/STYLES.DEF BITMAP.DEF SSMETA.DEF HYPRLNK.DEF \
                HOTSPOT.DEF OBJECTS/VLTEXTC.DEF CONVIEW.DEF COMPRESS.DEF \
                TIMER.DEF HELPFILE.DEF SPELL.DEF STUDIOCONSTANT.DEF \
                STUDIODOCUMENT.DEF STUDIOAPPLICATION.DEF \
                STUDIOPROCESS.DEF STUDIODISPLAY.DEF STUDIOGROBJHEAD.DEF \
                STUDIOCONTROL.DEF GSTRING.DEF OBJECTS/TEXT/TCTRLC.DEF \
                UIMANAGER.RDEF UI/UIPAGENAME.ASM
DOCUMENTMANAGER.rdef: GENERIC.UIH PRODUCT.UIH GROBJ.UIH OBJECTS/COLORC.UIH \
                OBJECTS/STYLES.UIH BITMAP.UIH OBJECTS/TEXT/TCTRL.UIH \
                RULER.UIH HOTSPOT.UIH DOCUMENT/DOCUMENTDATA.UI
UIMANAGER.rdef: GENERIC.UIH PRODUCT.UIH IMPEX.UIH SPOOL.UIH GROBJ.UIH \
                OBJECTS/COLORC.UIH OBJECTS/STYLES.UIH BITMAP.UIH \
                OBJECTS/TEXT/TCTRL.UIH RULER.UIH SPELL.UIH \
                OBJECTS/SPLINE.UIH HYPRLNK.UIH UI/UISTUDIO.UIH \
                UI/UIMAIN.UI ART/MKREDITTEXTTOOL.UI \
                ART/MKRBITMAPPTRTOOL.UI ART/MKRSTUDIO.UI UI/UIPRINT.UI \
                UI/UIPAGESETUP.UI UI/UIEDIT.UI UI/UIVIEW.UI \
                UI/UIOPTIONS.UI USRLEVEL.UIH UI/UILAYOUT.UI \
                UI/UIGRAPHICS.UI UI/UITEXT.UI UI/UIHELPEDIT.UI \
                UI/UIPLATFORM.UI UI/UIDOCUMENT.UI UI/UIDISPLAY.UI \
                UI/UIDOCMONIKER.UI ART/MKRMBOOKDOC.UI ART/MKRCBOOKDOC.UI \
                ART/MKRSTUDIODOC.UI

BinderyEC.geo Bindery.geo : GEOS.LDF UI.LDF TEXT.LDF GROBJ.LDF RULER.LDF BITMAP.LDF HYPRLNK.LDF HOTSPOT.LDF SPOOL.LDF IMPEX.LDF SPELL.LDF SSMETA.LDF CONVERT.LDF COMPRESS.LDF 