#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = Bindery
ARTICLE         = articleArticle.asm articleManager.asm
DOCUMENT        = documentArticle.asm documentAttrMgr.asm documentBody.asm\
                  documentContent.asm documentConvert.asm documentData.asm\
                  documentDisplay.asm documentDocument.asm documentDraw.asm\
                  documentFlow.asm documentFrame.asm documentHdrFtr.asm\
                  documentHead.asm documentHelp.asm documentImpex.asm\
                  documentManager.asm documentManip.asm\
                  documentMasterPage.asm documentMerge.asm\
                  documentMergeScrap.asm documentMisc.asm\
                  documentNotify.asm documentOpenClose.asm documentPage.asm\
                  documentPageSetup.asm documentPrint.asm\
                  documentRegion.asm documentScroll.asm\
                  documentSearchSp.asm documentSection.asm\
                  documentUserSection.asm documentUtils.asm\
                  documentVariable.asm documentData.ui documentManager.ui
MAIN            = mainApp.asm mainAppUI.asm mainManager.asm mainProcess.asm
UI              = uiFixed.asm uiManager.asm uiPageName.asm uiRowColumn.asm\
                  uiAppMoniker.ui uiDisplay.ui uiDocMoniker.ui\
                  uiDocument.ui uiEdit.ui uiFixed.ui uiGraphics.ui\
                  uiHelpEdit.ui uiLayout.ui uiMain.ui uiManager.ui\
                  uiOptions.ui uiPageSetup.ui uiPlatform.ui uiPrint.ui\
                  uiRowColumn.ui uiText.ui uiView.ui
UI_TO_RDFS      = DOCUMENTMANAGER.UI UIMANAGER.UI
OBJS            =
COMMON          = flowRegion.def studioApplication.def studioArticle.def\
                  studioConstant.def studioControl.def studioDisplay.def\
                  studioDocument.def studioGeode.def studioGrObjBody.def\
                  studioGrObjHead.def studioHdrFtr.def studioProcess.def
MODULES         = Article Document Main UI
CMODULES        =
SRCS            = $(ARTICLE) $(DOCUMENT) $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
