#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = BStartup
ASM_TO_OBJS     = bstartup.asm
UI_TO_RDFS      = BSTARTUP.UI
SRCS            = bsCalibrate.asm bsPrimary.asm bsProcess.asm bstartup.asm\
                  bsTimeDate.asm bsWelcome.asm bstartup.def bstartup.ui
OBJS            = bstartup.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
