ETHODIMANAGER.obj \
ETHODIMANAGER.eobj: GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF THREAD.DEF \
                SEM.DEF DRIVER.DEF LMEM.DEF SYSTEM.DEF LOCALIZE.DEF \
                SLLANG.DEF MEDIUM.DEF ASSERT.DEF DISK.DEF FILE.DEF \
                DRIVE.DEF INTERNAL/INTERRUP.DEF UI.DEF VM.DEF TEXT.DEF \
                FONTID.DEF GRAPHICS.DEF FONT.DEF COLOR.DEF CHAR.DEF \
                WIN.DEF INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF OBJECT.DEF CHUNKARR.DEF GEOWORKS.DEF \
                GCNLIST.DEF TIMEDATE.DEF OBJECTS/TEXT/TCOMMON.DEF \
                STYLESH.DEF IACP.DEF OBJECTS/UIINPUTC.DEF \
                OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF \
                INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                INTERNAL/NETUTILS.DEF SOCKET.DEF INTERNAL/SOCKETINT.DEF \
                INTERNAL/HEAPINT.DEF INTERNAL/SEMINT.DEF SYSSTATS.DEF \
                INTERNAL/IP.DEF INTERNAL/SOCKETDR.DEF SOCKMISC.DEF \
                TIMER.DEF INTERNAL/IM.DEF ACCPNT.DEF \
                ../ETHERCOM/ETHERCOMCONSTANT.DEF \
                ../ETHERCOM/ETHERCOMMACRO.DEF ARP.DEF ETHODICONSTANT.DEF \
                ../ETHERCOM/ETHERCOMVARIABLE.DEF ETHODIVARIABLE.DEF \
                ../ETHERCOM/ETHERCOMUTIL.ASM \
                ../ETHERCOM/ETHERCOMSTRATEGY.ASM \
                ../ETHERCOM/ETHERCOMGETINFO.ASM \
                ../ETHERCOM/ETHERCOMTRANSCEIVE.ASM \
                ../ETHERCOM/ETHERCOMLINK.ASM \
                ../ETHERCOM/ETHERCOMCLIENT.ASM \
                ../ETHERCOM/ETHERCOMOPTION.ASM \
                ../ETHERCOM/ETHERCOMMEDIUM.ASM \
                ../ETHERCOM/ETHERCOMPROCESS.ASM ETHODIINIT.ASM \
                ETHODIPROTOCOL.ASM ETHODITRANSCEIVE.ASM ETHODIARP.ASM

EtherODIEC.geo EtherODI.geo : GEOS.LDF NETUTILS.LDF ACCPNT.LDF 