#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = etherodi
ASM_TO_OBJS     = ethodiManager.asm
UI_TO_RDFS      =
SRCS            = ethodiTransceive.asm ethodiInit.asm ethodiManager.asm\
                  ethodiProtocol.asm ethodiArp.asm\
                  ../EtherCom/ethercomUtil.asm\
                  ../EtherCom/ethercomStrategy.asm\
                  ../EtherCom/ethercomGetInfo.asm\
                  ../EtherCom/ethercomTransceive.asm\
                  ../EtherCom/ethercomLink.asm\
                  ../EtherCom/ethercomClient.asm\
                  ../EtherCom/ethercomOption.asm\
                  ../EtherCom/ethercomMedium.asm\
                  ../EtherCom/ethercomProcess.asm arp.def\
                  ethodiConstant.def ethodiVariable.def
OBJS            = ethodiManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
