#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = GPCChat
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = Interfac.goc miscpro.goc process.goc routines.goc\
                  sortlis.goc textlim.goc TXT_STRS.GOC APPICONS.GOH\
                  BBOX.GOH externs.goh gpcchat.goh
OBJS            = Interfac.obj miscpro.obj process.obj routines.obj\
                  sortlis.obj textlim.obj TXT_STRS.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
