DOCUMENT.obj \
DOCUMENT.eobj: Document/DocumentMANAGER.ASM \
                LOCALIZEGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                THREAD.DEF EC.DEF VM.DEF DBASE.DEF OBJECT.DEF LMEM.DEF \
                WIN.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF \
                FILE.DEF CHUNKARR.DEF CHAR.DEF INITFILE.DEF ASSERT.DEF \
                DISK.DEF DRIVE.DEF UI.DEF TEXT.DEF INPUT.DEF HWR.DEF \
                LOCALIZE.DEF SLLANG.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF BITMAP.DEF LOCALIZECONSTANT.DEF \
                LOCALIZEGLOBAL.DEF LOCALIZEMACRO.DEF LOCALIZEERRORS.DEF \
                LOCALIZEDOCUMENT.DEF LOCALIZECONTENT.DEF LOCALIZETEXT.DEF \
                LOCALIZELOC.DEF LOCALIZEPROCESS.DEF OBJECTS/INPUTC.DEF \
                GSTRING.DEF INTERNAL/VIDEODR.DEF DRIVER.DEF \
                DOCUMENTIMPEXP.ASM SYSTEM.DEF LIBRARY.DEF \
                DOCUMENTPATCH.ASM INTERNAL/PATCH.DEF INTERNAL/FILESTR.DEF \
                INTERNAL/GEODESTR.DEF OBJECTS/WINC.DEF \
                DOCUMENTOPENCLOSE.ASM INTERNAL/THREADIN.DEF \
                INTERNAL/SPECUI.DEF DOCUMENTPATH.ASM \
                DOCUMENTSOURCEVIEW.ASM DOCUMENTTRANSVIEW.ASM \
                DOCUMENTDB.ASM DOCUMENTLIST.ASM DOCUMENTPARSE.ASM \
                DOCUMENTRESOURCE.ASM DOCUMENTUPDATE.ASM DOCUMENTBUILD.ASM \
                DOCUMENTMISC.ASM DOCUMENTMNEMONIC.ASM DOCUMENTSEARCH.ASM \
                DOCUMENTCLIPBOARD.ASM DOCUMENTUTILITIES.ASM \
                DOCUMENTKEYBOARD.ASM DOCUMENTINITFILE.ASM \
                DOCUMENTPRINT.ASM DOCUMENTCOUNT.ASM DOCUMENTDRAW.ASM
MAIN.obj \
MAIN.eobj: Main/MainMANAGER.ASM \
                LOCALIZEGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                THREAD.DEF EC.DEF VM.DEF DBASE.DEF OBJECT.DEF LMEM.DEF \
                WIN.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF \
                FILE.DEF CHUNKARR.DEF CHAR.DEF INITFILE.DEF ASSERT.DEF \
                DISK.DEF DRIVE.DEF UI.DEF TEXT.DEF INPUT.DEF HWR.DEF \
                LOCALIZE.DEF SLLANG.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF BITMAP.DEF LOCALIZECONSTANT.DEF \
                LOCALIZEERRORS.DEF LOCALIZEGLOBAL.DEF LOCALIZEMACRO.DEF \
                LOCALIZEPROCESS.DEF LOCALIZEDOCUMENT.DEF \
                LOCALIZECONTENT.DEF INTERNAL/FILEINT.DEF FILEENUM.DEF \
                INTERNAL/DOS.DEF INTERNAL/DRIVEINT.DEF \
                INTERNAL/SEMINT.DEF OBJECTS/INPUTC.DEF MAINPROCESS.ASM \
                MAINLIST.ASM MAINBATCH.ASM SYSTEM.DEF
TEXT.obj \
TEXT.eobj: Text/TextMANAGER.ASM \
                LOCALIZEGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                THREAD.DEF EC.DEF VM.DEF DBASE.DEF OBJECT.DEF LMEM.DEF \
                WIN.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF \
                FILE.DEF CHUNKARR.DEF CHAR.DEF INITFILE.DEF ASSERT.DEF \
                DISK.DEF DRIVE.DEF UI.DEF TEXT.DEF INPUT.DEF HWR.DEF \
                LOCALIZE.DEF SLLANG.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF BITMAP.DEF LOCALIZECONSTANT.DEF \
                LOCALIZEGLOBAL.DEF LOCALIZEMACRO.DEF LOCALIZEERRORS.DEF \
                LOCALIZEDOCUMENT.DEF LOCALIZECONTENT.DEF LOCALIZETEXT.DEF \
                OBJECTS/INPUTC.DEF TEXTDRAW.ASM
UI.obj \
UI.eobj: UI/UIMANAGER.ASM \
                LOCALIZEGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                THREAD.DEF EC.DEF VM.DEF DBASE.DEF OBJECT.DEF LMEM.DEF \
                WIN.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF \
                FILE.DEF CHUNKARR.DEF CHAR.DEF INITFILE.DEF ASSERT.DEF \
                DISK.DEF DRIVE.DEF UI.DEF TEXT.DEF INPUT.DEF HWR.DEF \
                LOCALIZE.DEF SLLANG.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF BITMAP.DEF LOCALIZECONSTANT.DEF \
                LOCALIZEGLOBAL.DEF LOCALIZEMACRO.DEF LOCALIZEPROCESS.DEF \
                LOCALIZEDOCUMENT.DEF LOCALIZECONTENT.DEF LOCALIZETEXT.DEF \
                GSTRING.DEF UIMANAGER.RDEF
UIMANAGER.rdef: GENERIC.UIH PRODUCT.UIH OBJECTS/TEXT/TCTRL.UIH RULER.UIH \
                OBJECTS/COLORC.UIH OBJECTS/STYLES.UIH SPELL.UIH SPOOL.UIH \
                BITMAP.UIH LOCALIZECONSTANT.UIH UI/UIMAIN.UI \
                DOCUMENT/../ART/MKRRESEDIT.UI UI/UIDOCUMENT.UI \
                DOCUMENT/../ART/MKRDIALOGPATHSIC.UI \
                DOCUMENT/../ART/MKRDIALOGPATHSIM.UI \
                DOCUMENT/../ART/MKRDIALOGBATCHIC.UI \
                DOCUMENT/../ART/MKRDIALOGBATCHIM.UI UI/UIDISPLAY.UI \
                UI/UIFILE.UI UI/UIPROJECT.UI UI/UIPRINT.UI \
                UI/UISTRINGS.UI UI/UIIMPEXP.UI

LOCALIZEEC.geo LOCALIZE.geo : GEOS.LDF UI.LDF TEXT.LDF SPOOL.LDF 