#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = hinv10
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = HINV10.goc I2MTHDS.goc I3MTHDS.goc IIMTHDS.goc\
                  INVMTHDS.goc IPMTHDS.goc UIMTHDS.goc hiicons.goh\
                  hivar.goh imtxtstr.goh txtstrs.goh
OBJS            = HINV10.obj I2MTHDS.obj I3MTHDS.obj IIMTHDS.obj\
                  INVMTHDS.obj IPMTHDS.obj UIMTHDS.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
