APPUI.obj \
APPUI.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH AIM.GOH SIMPTREE.GOH EXTUI/TREE.GOH \
                EXTUI/TABLE.GOH TOCPROTO.GOH SOCKET.GOH TOCCFG.GOH \
                ART/BIMICONS.GOH BBOX.GOH ART/OPARROW.GOH ART/CLARROW.GOH \
                ART/AWAY.GOH ART/ARRIVED.GOH ART/DEPARTED.GOH \
                ART/OPFOLDER.GOH ART/CLFOLDER.GOH
APPUI.obj \
APPUI.eobj: APPUI.GOC GEOS.H \
                HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H MEDIUM.H
DEBUG.obj \
DEBUG.eobj: OBJECTS/GPROCC.GOH UI.GOH OBJECTS/METAC.GOH OBJECT.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VTEXTC.GOH OBJECTS/VISC.GOH OBJECTS/GCTRLC.GOH \
                OBJECTS/GINTERC.GOH OBJECTS/GENC.GOH GCNLIST.GOH \
                OBJECTS/GVIEWC.GOH SPOOL.GOH
DEBUG.obj \
DEBUG.eobj: DEBUG.GOC GEOS.H \
                FILE.H OBJECT.H GEODE.H \
                LMEM.H ANSI/STDLIB.H ANSI/STDIO.H \
                ANSI/STRING.H \
                ANSI/CTYPE.H VM.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H \
                DRIVE.H GEOWORKS.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                INPUT.H CHAR.H HWR.H WIN.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H SLLANG.H OBJECTS/GINTERC.H TIMEDATE.H DRIVER.H \
                THREAD.H PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H \
                PARALLDR.H HUGEARR.H DBASE.H
ERROR.obj \
ERROR.eobj: 
ERROR.obj \
ERROR.eobj: ERROR.GOC GEOS.H \
                HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H MEDIUM.H
MISCFUNC.obj \
MISCFUNC.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH SOCKET.GOH
MISCFUNC.obj \
MISCFUNC.eobj: MISCFUNC.GOC GEOS.H \
                HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H MEDIUM.H ANSI/STDIO.H \
                ANSI/STRING.H \
                MISCFUNC.H
PROCESS.obj \
PROCESS.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH SOCKET.GOH AIM.GOH SIMPTREE.GOH \
                TOC.GOH TOCCFG.GOH TOCPROTO.GOH EXTERN.GOH ERROR.GOH
PROCESS.obj \
PROCESS.eobj: PROCESS.GOC GEOS.H \
                HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H MEDIUM.H SOCKMISC.H ANSI/STDLIB.H \
                ANSI/STDIO.H \
                ANSI/STRING.H MISCFUNC.H DEBUG.H
SIMPTREE.obj \
SIMPTREE.eobj: SIMPTREE.GOH OBJECTS/GITEMGC.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECT.GOH OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH OBJECTS/GENC.GOH OBJECTS/VISC.GOH \
                OBJECTS/GDLISTC.GOH
SIMPTREE.obj \
SIMPTREE.eobj: SIMPTREE.GOC GEOS.H \
                HEAP.H OBJECT.H GEODE.H \
                LMEM.H CHUNKARR.H EC.H GSTRING.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H OBJECTS/HELPCC.H FILE.H DISK.H DRIVE.H \
                GEOWORKS.H INPUT.H CHAR.H HWR.H WIN.H
TOC.obj \
TOC.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH AIM.GOH SIMPTREE.GOH TOC.GOH \
                TOCCFG.GOH TOCPROTO.GOH SOCKET.GOH EXTERN.GOH ERROR.GOH
TOC.obj \
TOC.eobj: TOC.GOC GEOS.H \
                HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H ANSI/STDIO.H \
                SOUND.H MEDIUM.H \
                MISCFUNC.H
TOCCFG.obj \
TOCCFG.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH AIM.GOH SIMPTREE.GOH TOCCFG.GOH \
                TOCPROTO.GOH SOCKET.GOH TOC.GOH EXTERN.GOH ERROR.GOH
TOCCFG.obj \
TOCCFG.eobj: TOCCFG.GOC GEOS.H \
                HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H ANSI/STDIO.H \
                MEDIUM.H MISCFUNC.H
TOCPROTO.obj \
TOCPROTO.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH SOCKET.GOH AIM.GOH SIMPTREE.GOH \
                TOCPROTO.GOH ERROR.GOH EXTERN.GOH
TOCPROTO.obj \
TOCPROTO.eobj: TOCPROTO.GOC GEOS.H \
                HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H MEDIUM.H SOCKMISC.H ANSI/STRING.H \
                SEM.H INIT.H DEBUG.H MISCFUNC.H
INIT.obj \
INIT.eobj: GEOS.H HEAP.H LMEM.H INITFILE.H \
                SYSTEM.H GEODE.H ANSI/STRING.H

BimEC.geo Bim.geo : GEOS.LDF UI.LDF SOCKET.LDF ANSIC.LDF EXTUI.LDF SOUND.LDF 