#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bim
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = init.c debug.h init.h miscfunc.h appui.goc debug.goc\
                  error.goc miscfunct.goc process.goc simptree.goc toc.goc\
                  toccfg.goc tocproto.goc aim.goh aolicon.goh error.goh\
                  extern.goh simptree.goh toc.goh toccfg.goh tocproto.goh
OBJS            = init.obj appui.obj debug.obj error.obj miscfunct.obj\
                  process.obj simptree.obj toc.obj toccfg.obj tocproto.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
