#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = Bim
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = INIT.C DEBUG.H INIT.H MISCFUNC.H APPUI.GOC DEBUG.GOC\
                  ERROR.GOC MISCFUNC.GOC PROCESS.GOC SIMPTREE.GOC TOC.GOC\
                  TOCCFG.GOC TOCPROTO.GOC AIM.GOH AOLICON.GOH BBOX.GOH\
                  ERROR.GOH EXTERN.GOH SIMPTREE.GOH TOC.GOH TOCCFG.GOH\
                  TOCPROTO.GOH
OBJS            = INIT.obj APPUI.obj DEBUG.obj ERROR.obj MISCFUNC.obj\
                  PROCESS.obj SIMPTREE.obj TOC.obj TOCCFG.obj TOCPROTO.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
