#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bim
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = init.c miscfunc.h init.h debug.h simptree.goc toc.goc\
                  error.goc debug.goc miscfunct.goc process.goc appui.goc\
                  tocproto.goc toccfg.goc aolicon.goh extern.goh\
                  simptree.goh bbox.goh bbxreg.goh toccfg.goh error.goh\
                  aim.goh tocproto.goh toc.goh
OBJS            = init.obj simptree.obj toc.obj error.obj debug.obj\
                  miscfunct.obj process.obj appui.obj tocproto.obj\
                  toccfg.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
