#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = maze
ASM_TO_OBJS     = maze.asm
UI_TO_RDFS      = maze.ui
SRCS            = mzsolve.asm maze.asm mazeScreenSave.asm maze.def maze.ui
OBJS            = maze.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
