#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = gdipointer
LIBNAME         = mouse
PROTOCONST      = MOUSE
ASM_TO_OBJS     = GDIPointer.asm
UI_TO_RDFS      =
SRCS            = GDIPointer.asm GDIPointer.def
OBJS            = GDIPointer.obj
LOBJS           =

PRODUCTS        = DBCS

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(DBCS/$(DEPFILE))
#include "DBCS/$(DEPFILE)"
#endif
