#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = CANONBJC
LIBNAME         = print
PROTOCONST      = PRINT
ASM_TO_OBJS     = canonBJCManager.asm
UI_TO_RDFS      = canonBJC.ui
SRCS            = canonBJCControlCodes.asm canonBJCDialog.asm\
                  canonBJCDriverInfo.asm canonBJCManager.asm\
                  canonBJCcmykInfo.asm canonBJCcmyInfo.asm\
                  canonBJCmonoInfo.asm UI/uiGetNoMain.asm\
                  UI/uiGetOptions.asm UI/uiEval.asm UI/uiEvalDummyASF.asm\
                  printcomEntry.asm printcomInfo.asm printcomAdmin.asm\
                  printcomTables.asm printcomNoEscapes.asm\
                  printcomCanonBJCJob.asm printcomASFOnlyPage.asm\
                  printcomCanonBJCCursor.asm printcomStream.asm\
                  printcomCanonBJCColor.asm printcomCanonBJCGraphics.asm\
                  printcomNoStyles.asm printcomNoText.asm\
                  Buffer/bufferCreate.asm Buffer/BufferDestroy.asm\
                  canonBJCConstant.def canonBJC.ui
OBJS            = canonBJCManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
