#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = DUMP
ASM_TO_OBJS     = bmp.asm clipboard.asm eps.asm epsTiff.asm fps.asm gif.asm\
                  input.asm jpeg.asm jpegerr.asm pcx.asm psc.asm tiff.asm\
                  dump.asm
UI_TO_RDFS      = DUMP.UI
SRCS            = bmp.asm clipboard.asm eps.asm epsTiff.asm fps.asm gif.asm\
                  input.asm jpeg.asm jpegerr.asm pcx.asm psc.asm tiff.asm\
                  dump.asm dump.def psc.def dump.ui bmp_c.goc gif_c.goc\
                  jpeg_c.goc chkcol.goc
OBJS            = bmp.obj clipboard.obj eps.obj epsTiff.obj fps.obj gif.obj\
                  input.obj jpeg.obj jpegerr.obj pcx.obj psc.obj tiff.obj\
                  dump.obj bmp_c.obj gif_c.obj jpeg_c.obj chkcol.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
