#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = dump
ASM_TO_OBJS     = epsTiff.asm clipboard.asm pcx.asm eps.asm bmp.asm\
                  jpegerr.asm gif.asm dump.asm tiff.asm jpeg.asm fps.asm\
                  input.asm psc.asm
UI_TO_RDFS      = dump.ui
SRCS            = epsTiff.asm clipboard.asm pcx.asm eps.asm bmp.asm\
                  jpegerr.asm gif.asm dump.asm tiff.asm jpeg.asm fps.asm\
                  input.asm psc.asm psc.def dump.def dump.ui gif_c.goc\
                  jpeg_c.goc chkcol.goc bmp_c.goc
OBJS            = epsTiff.obj clipboard.obj pcx.obj eps.obj bmp.obj\
                  jpegerr.obj gif.obj dump.obj tiff.obj jpeg.obj fps.obj\
                  input.obj psc.obj gif_c.obj jpeg_c.obj chkcol.obj\
                  bmp_c.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
