#!/bin/sh -
#
# This script copies source files to the CD-Rom image directory.
#
# $Id: copySrcFiles,v 1.5 94/03/28 17:51:17 jimmy Exp $
#

MAKETOOLPATH=/staff/pcgeos/Tools/scripts/sdk
export MAKETOOLPATH


if [ "$1" = "" ] || [ "$2" = "" ]; then
	echo "Usage: copySrcFiles <branch> <CD-Rom dir>"
	echo "Ex.: copySrcFiles Release20X /n/intl_disks"
	exit 1
fi


if ( cd /staff/pcgeos/$1/Installed ); then
	cd /staff/pcgeos/$1/Installed
	echo ""
	echo "copySrcFiles Started On `hostname` At `date` running as $USER"
else
	echo "$1 is not a PC/GEOS development tree. (e.g., . or Release20X)"
	exit 1
fi


#==============================================================================
# Copy all the ASM stuff (for documentation purposes only, I presume)
#==============================================================================

cd ../Include
echo ""
echo "----------------------------------------------------------------------"
echo "The following files are from `pwd`:"
echo "----------------------------------------------------------------------"

find .  \(  \( -name \*.def -o \
	       -name \*.uih \
	    \) \
	    -a ! \
	    \( -name bullet.def -o \
	       -name cdrom.def -o \
	       -name cvttool.def -o \
	       -name ffile.def -o \
	       -name fmtool.def -o \
	       -name iclas.def -o \
	       -name wshell.def -o \
	       -name anarchy.uih -o \
	       -name blip.uih -o \
	       -name bullet.uih -o \
	       -name iclas.uih \
	    \) \
	    -exec $MAKETOOLPATH/copy_for_sdk -u {} $2/pcgeos/Include \; \
	\) -o \
	\(  -type d \
		\( -name Internal \
		\) \
	    -prune \
	\)

$MAKETOOLPATH/copy_for_sdk -u Internal/vUtils.def $2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/gUtils.def $2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/uProcC.def $2/pcgeos/Include

$MAKETOOLPATH/copy_for_sdk -u Internal/DMADrv.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/cardid.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/fsd.def		$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/grWinInt.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/heapInt.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/im.def		$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/interrup.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/kbdDr.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/kbdMap.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/mouseDr.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/pcmciaDr.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/semInt.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/serialDr.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/soundDrv.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/soundFmt.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/strDrInt.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/streamDr.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/videoDr.def	$2/pcgeos/Include

$MAKETOOLPATH/copy_for_sdk -u Internal/powerDr.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/serialIO.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/diskInt.def	$2/pcgeos/Include
$MAKETOOLPATH/copy_for_sdk -u Internal/zpcmDr.def	$2/pcgeos/Include

#==============================================================================
# Now all the CInclude stuff
#==============================================================================

cd ../CInclude
echo ""
echo "----------------------------------------------------------------------"
echo "The following files are from `pwd`:"
echo "----------------------------------------------------------------------"

find .  \(  \( -name \*.goh -o \
	       -name \*.h -o \
	       -name \*.pat -o \
	       -name send -o \
	       -name \*.pdg \
	    \) \
	    -a ! \
	    \( -name fmtool.goh -o \
	       -name cvttool.goh -o \
	       -name iclas.h \
	    \) \
	    -exec $MAKETOOLPATH/copy_for_sdk -u {} $2/pcgeos/Include \; \
	\) -o \
	\(  -type d \
		\( -name Internal \
		\) \
	    -prune \
	\)


#==============================================================================
#  Now all the SDK_C source.
#==============================================================================

cd ..
echo ""
echo "----------------------------------------------------------------------"
echo "The following files are from `pwd`:"
echo "----------------------------------------------------------------------"

find Appl/SDK_C	Library/SDK_C Appl/SDK_Asm \
	\(  \( -name \*.goc   -o -name \*.goh   -o -name \*.h     -o \
	       -name \*.asm   -o -name \*.def   -o -name \*.ui    -o \
	       -name \*.uih   -o -name \*.gp    -o -name local.mk -o \
	       -name readme.txt \) \
	    -exec $MAKETOOLPATH/copy_for_sdk -u {} $2/pcgeos \; \
	\) -o \
	\(  -type d \
		\( -name List -o \
		   -name Template -o \
		   -name Hello4 -o \
		   -name ListSamp2 -o \
		   -name no_go -o \
		   -name GstrMoniker \
		\) \
	    -prune \
	\)

# HACK
mv $2/pcgeos/Library/SDK_C/MSet/AsmCalc/acManager.asm \
   $2/pcgeos/Library/SDK_C/MSet/AsmCalc/Manager.asm


#==============================================================================
#  Now copy GeoFile source files
#==============================================================================
echo ""
echo "----------------------------------------------------------------------"
echo "The following files are from `pwd`:"
echo "----------------------------------------------------------------------"

find Appl/GeoFile \
	\( -name \*.goc -o -name \*.goh -o -name \*.gp -o \
	   -name \*.asm -o -name \*.def -o -name \*.ui -o \
	   -name local.mk \) \
	-exec $MAKETOOLPATH/copy_for_sdk -u {} $2/pcgeos \; 

# Get Art files from trunk

cd /staff/pcgeos
find Appl/GeoFile/Art \
	\( -name \*.goc -o -name \*.goh -o -name \*.gp -o \
	   -name \*.asm -o -name \*.def -o -name \*.ui -o \
	   -name local.mk \) \
	-exec $MAKETOOLPATH/copy_for_sdk -u {} $2/pcgeos \; 

# HACK
mv $2/pcgeos/Appl/GeoFile/DocAsm/docasmManager.asm \
   $2/pcgeos/Appl/GeoFile/DocAsm/manager.asm


#==============================================================================
#  Now copy help files from trunk
#==============================================================================
echo ""
echo "----------------------------------------------------------------------"
echo "The following files are from `pwd`:"
echo "----------------------------------------------------------------------"

find Appl/SDK_C/Help -name \*.000 \
		     -exec $MAKETOOLPATH/copy_for_sdk {} $2/pcgeos \;

echo copySrcFiles Ended At `date`
