#!/bin/sh -
#
# This script copies a bunch of misc. files to the CD-Rom image directory.
#
# $Id: copyMiscFiles,v 1.4 94/02/08 13:41:06 jon Exp $
#

MAKETOOLPATH=/staff/pcgeos/Tools/scripts/sdk
export MAKETOOLPATH


if [ "$1" = "" ] || [ "$2" = "" ]; then
	echo "Usage: copyMiscFiles <branch> <CD-Rom dir>"
	echo "Ex.: copyMiscFiles Release20X /n/intl_disks"
	exit 1
fi


if ( cd /staff/pcgeos/$1/Installed ); then
	cd /staff/pcgeos/$1/Installed
	echo ""
	echo "copyMiscFiles Started On `hostname` At `date` running as $USER"
else
	echo "$1 is not a PC/GEOS development tree. (e.g., . or Release20X)"
	exit 1
fi


#==============================================================================
# Copy everything from TMAIL to the destination.... no longer needed jon 7feb94
#==============================================================================

#cd /n/nevada/tools/pcgeos
#find tmail -type f -exec $MAKETOOLPATH/copy_for_sdk {} $2 \;

#==============================================================================
# Copy text files from /staff/pcgeos/Installed/ProductFiles/SDK
#==============================================================================

cd /staff/pcgeos/Installed/ProductFiles/SDK
echo ""
echo "----------------------------------------------------------------------"
echo "The following files are from `pwd`:"
echo "----------------------------------------------------------------------"

$MAKETOOLPATH/copy_for_sdk    install.exe		$2
$MAKETOOLPATH/copy_for_sdk -u install.txt		$2
$MAKETOOLPATH/copy_for_sdk -u readme.txt		$2
$MAKETOOLPATH/copy_for_sdk -u support.txt		$2
$MAKETOOLPATH/copy_for_sdk -u training.txt		$2
$MAKETOOLPATH/copy_for_sdk -u license.txt		$2
$MAKETOOLPATH/copy_for_sdk -u install.txt		$2/install
$MAKETOOLPATH/copy_for_sdk    install/geossdk.grp	$2
$MAKETOOLPATH/copy_for_sdk    install/grpedit.exe	$2
$MAKETOOLPATH/copy_for_sdk -u install/existing.txt	$2
$MAKETOOLPATH/copy_for_sdk -u install/serial.txt	$2
$MAKETOOLPATH/copy_for_sdk -u install/zoomer_1.txt	$2
$MAKETOOLPATH/copy_for_sdk -u install/geosec.txt	$2
$MAKETOOLPATH/copy_for_sdk -u install/geosnc.txt	$2
$MAKETOOLPATH/copy_for_sdk -u install/zoomec.txt	$2
$MAKETOOLPATH/copy_for_sdk -u install/zoomnc.txt	$2


#==============================================================================
# Copy pccom.com, pcsend.com, and swat.exe
#==============================================================================

cd /staff/pcgeos/Tools/com43
echo ""
echo "----------------------------------------------------------------------"
echo "The following files are from `pwd`:"
echo "----------------------------------------------------------------------"

$MAKETOOLPATH/copy_for_sdk pccom.com $2


cd /staff/pcgeos/Tools/pctrans
echo ""
echo "----------------------------------------------------------------------"
echo "The following files are from `pwd`:"
echo "----------------------------------------------------------------------"

$MAKETOOLPATH/copy_for_sdk pcsend.com $2/install


cd /staff/pcgeos/Tools/swat/Stub/LowMem
echo ""
echo "----------------------------------------------------------------------"
echo "The following files are from `pwd`:"
echo "----------------------------------------------------------------------"

$MAKETOOLPATH/copy_for_sdk swat.exe $2
