#!/bin/sh
#
# This script removes all unnecessary Zoomer files and directory from the
# CD-Rom image directory after zoomer target files have been shipped.
#
# $Id: removeZoomerFiles,v 1.3 93/12/22 18:01:42 joon Exp $

if [ "$1" = "" ]; then
	echo "Usage: remove.zoomer.files <CD-Rom dir>"
	echo "Ex.: remove.zoomer.files /n/intl_disks"
	exit 1
fi

if ( cd $1/target/zoom ); then
	cd $1
	echo ""
	echo "removeZoomerFiles Started On `hostname` At `date` running as $USER"
else
	echo "Unable to find Zoomer target files in $1."
	echo "Perhaps you should ship Zoomer files there first."
	exit 1
fi

echo ""
echo "========================================================================"
echo "Removing non-essential zoomer target files from $1..."
echo "========================================================================"

set -x
rm -f target/zoom/zoomec/netec.ini
rm -f target/zoom/zoomec/privdata/langx/langx.dat
rm -f target/zoom/zoomec/system/book.geo
rm -f target/zoom/zoomec/system/hwrrom.geo
rm -f target/zoom/zoomec/system/palmui.geo
rm -f target/zoom/zoomec/system/pqdb.geo
rm -f target/zoom/zoomec/token_da.000
rm -f target/zoom/zoomec/userdata/dicts/ukeng.def
rm -f target/zoom/zoomec/userdata/dicts/ukeng.ndx
rm -f target/zoom/zoomec/userdata/dicts/ukeng.ths
rm -f target/zoom/zoomec/userdata/help/addhelp.000
rm -f target/zoom/zoomec/userdata/help/birthsto.000
rm -f target/zoom/zoomec/userdata/help/calchelp.000
rm -f target/zoom/zoomec/userdata/help/clothing.000
rm -f target/zoom/zoomec/userdata/help/country_.000
rm -f target/zoom/zoomec/userdata/help/cviewerh.000
rm -f target/zoom/zoomec/userdata/help/datehelp.000
rm -f target/zoom/zoomec/userdata/help/dicthelp.000
rm -f target/zoom/zoomec/userdata/help/fcalchel.000
rm -f target/zoom/zoomec/userdata/help/internat.000
rm -f target/zoom/zoomec/userdata/help/langxhel.000
rm -f target/zoom/zoomec/userdata/help/notehelp.000
rm -f target/zoom/zoomec/userdata/help/nutritio.000
rm -f target/zoom/zoomec/userdata/help/pq______.000
rm -f target/zoom/zoomec/userdata/help/pyramid_.000
rm -f target/zoom/zoomec/userdata/help/solitair.000
rm -f target/zoom/zoomec/userdata/help/topics.000
rm -f target/zoom/zoomec/userdata/help/uki_____.000
rm -f target/zoom/zoomec/userdata/help/wclockhe.000
rm -f target/zoom/zoomec/userdata/help/world_ai.000
rm -f target/zoom/zoomec/userdata/help/z_librar.000
rm -f target/zoom/zoomec/userdata/help/zodiac_s.000
rm -f target/zoom/zoomec/userdata/palm.wav
rm -f target/zoom/zoomec/userdata/wclock/world.wcm
rm -f target/zoom/zoomec/world/c/@dirname.000
rm -f target/zoom/zoomec/world/desk_acc.000/alarm.geo
rm -f target/zoom/zoomec/world/desk_acc.000/calc.geo
rm -f target/zoom/zoomec/world/dict.geo
rm -f target/zoom/zoomec/world/fcalc.geo
rm -f target/zoom/zoomec/world/games/pyramidec.geo
rm -f target/zoom/zoomec/world/games/soliec.geo
rm -f target/zoom/zoomec/world/games/ukiec.geo
rm -f target/zoom/zoomec/world/langx.geo
rm -f target/zoom/zoomec/world/main/addrbook.geo
rm -f target/zoom/zoomec/world/main/datebk.geo
rm -f target/zoom/zoomec/world/main/note.geo
rm -f target/zoom/zoomec/world/main/pq.geo
rm -f target/zoom/zoomec/world/main/wclock.geo
rm -f target/zoom/zoomec/world/referenc.000/consum.geo
rm -f target/zoom/zoomec/world/referenc.000/winfo.geo
rm -f target/zoom/zoomnc/net.ini
rm -f target/zoom/zoomnc/privdata/langx/langx.dat
rm -f target/zoom/zoomnc/system/book.geo
rm -f target/zoom/zoomnc/system/hwrrom.geo
rm -f target/zoom/zoomnc/system/palmui.geo
rm -f target/zoom/zoomnc/system/pqdb.geo
rm -f target/zoom/zoomnc/token_da.000
rm -f target/zoom/zoomnc/userdata/dicts/ukeng.def
rm -f target/zoom/zoomnc/userdata/dicts/ukeng.ndx
rm -f target/zoom/zoomnc/userdata/dicts/ukeng.ths
rm -f target/zoom/zoomnc/userdata/help/addhelp.000
rm -f target/zoom/zoomnc/userdata/help/birthsto.000
rm -f target/zoom/zoomnc/userdata/help/calchelp.000
rm -f target/zoom/zoomnc/userdata/help/clothing.000
rm -f target/zoom/zoomnc/userdata/help/country_.000
rm -f target/zoom/zoomnc/userdata/help/cviewerh.000
rm -f target/zoom/zoomnc/userdata/help/datehelp.000
rm -f target/zoom/zoomnc/userdata/help/dicthelp.000
rm -f target/zoom/zoomnc/userdata/help/fcalchel.000
rm -f target/zoom/zoomnc/userdata/help/internat.000
rm -f target/zoom/zoomnc/userdata/help/langxhel.000
rm -f target/zoom/zoomnc/userdata/help/notehelp.000
rm -f target/zoom/zoomnc/userdata/help/nutritio.000
rm -f target/zoom/zoomnc/userdata/help/pq______.000
rm -f target/zoom/zoomnc/userdata/help/pyramid_.000
rm -f target/zoom/zoomnc/userdata/help/solitair.000
rm -f target/zoom/zoomnc/userdata/help/topics.000
rm -f target/zoom/zoomnc/userdata/help/uki_____.000
rm -f target/zoom/zoomnc/userdata/help/wclockhe.000
rm -f target/zoom/zoomnc/userdata/help/world_ai.000
rm -f target/zoom/zoomnc/userdata/help/z_librar.000
rm -f target/zoom/zoomnc/userdata/help/zodiac_s.000
rm -f target/zoom/zoomnc/userdata/palm.wav
rm -f target/zoom/zoomnc/userdata/wclock/world.wcm
rm -f target/zoom/zoomnc/world/c/@dirname.000
rm -f target/zoom/zoomnc/world/desk_acc.000/alarm.geo
rm -f target/zoom/zoomnc/world/desk_acc.000/calc.geo
rm -f target/zoom/zoomnc/world/dict.geo
rm -f target/zoom/zoomnc/world/fcalc.geo
rm -f target/zoom/zoomnc/world/games/pyramid.geo
rm -f target/zoom/zoomnc/world/games/soli.geo
rm -f target/zoom/zoomnc/world/games/uki.geo
rm -f target/zoom/zoomnc/world/langx.geo
rm -f target/zoom/zoomnc/world/main/addrbook.geo
rm -f target/zoom/zoomnc/world/main/datebk.geo
rm -f target/zoom/zoomnc/world/main/note.geo
rm -f target/zoom/zoomnc/world/main/pq.geo
rm -f target/zoom/zoomnc/world/main/wclock.geo
rm -f target/zoom/zoomnc/world/referenc.000/consum.geo
rm -f target/zoom/zoomnc/world/referenc.000/winfo.geo
rmdir target/zoom/zoomnc/userdata/dicts
rmdir target/zoom/zoomnc/privdata/langx
rmdir target/zoom/zoomnc/userdata/wclock
rmdir target/zoom/zoomec/userdata/dicts
rmdir target/zoom/zoomec/privdata/langx
rmdir target/zoom/zoomec/userdata/wclock
set +x
