#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1991 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	bugs
# FILE: 	sdkbugs
# AUTHOR: 	Jon Witort, October 7, 1993
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	jon	7 oct 1993	initial revision
#
# DESCRIPTION:
#	Generates a listing of all the bugs associated with the SDK
#
#	Usage: sdkbugs
#
#	$Id: sdkbugs,v 1.3 94/02/09 16:25:26 jenny Exp $
#
###############################################################################
#
# If this is being run from a remote site, use rshowbugs; else, use showbugs.
#
if [ -f /staff/pcgeos/.GINSTALL_SITE_NAME ]; then
	rshowbugs $* -g sdk swat goc glue icon resedit sampleapp tcl mset -c NOT CLOSED -f ONELINE -s STATUS SEVERITY GEODE -l "SDK bugs"
	exit 0
fi
showbugs $* -g sdk swat goc glue icon resedit sampleapp tcl mset -c NOT CLOSED -f ONELINE -s STATUS SEVERITY GEODE -l "SDK bugs"
