#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = GPCBnkr
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = Act_mtds.goc BNKR_UI.GOC Catstrs.goc ckp_mtds.goc\
                  DOC_MTDS.GOC Exp_mtds.goc Fnctns.goc Imp_mtds.goc\
                  Lst_mtds.goc Mlt_mtds.goc Rcn_mtds.goc Reg_mtds.goc\
                  Rpt_mtds.goc Sch_mtds.goc Trn_mtds.goc TXT_STRS.GOC\
                  Xfr_mtds.goc appicons.goh BBOX.GOH btnicons.goh\
                  externs.goh gpcbnkr.goh rpticons.goh
OBJS            = Act_mtds.obj BNKR_UI.obj Catstrs.obj ckp_mtds.obj\
                  DOC_MTDS.obj Exp_mtds.obj Fnctns.obj Imp_mtds.obj\
                  Lst_mtds.obj Mlt_mtds.obj Rcn_mtds.obj Reg_mtds.obj\
                  Rpt_mtds.obj Sch_mtds.obj Trn_mtds.obj TXT_STRS.obj\
                  Xfr_mtds.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
