name laserl.app
longname "Laser Letters"
type    appl, process, single
class   LaserLettersProcessClass
appobj  LaserLettersApp
tokenchars "LasL"
tokenid 16431
library geos
library ui
library ansic
resource APPRESOURCE ui-object
resource INTERFACE ui-object
resource STRINGS data object
resource LASERLETTERSART1 lmem read-only
resource ICONRESOURCE ui-object

platform geos201

usernotes "Copyright 1994 - 2001   Breadbox Computer Company LLC  All Rights Reserved"

