#
# Copyright (c) 1980 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
#	@(#)Makefile	5.1 (Berkeley) 6/7/85
#
# curses package
#
CFILES		=	addch.c addstr.c box.c clear.c clrtobot.c clrtoeol.c \
                        cr_put.c cr_tty.c curses.c delch.c deleteln.c delwin.c\
                        egetstr.c endwin.c erase.c fullname.c getch.c getstr.c\
                        idlok.c id_subwins.c initscr.c insch.c insertln.c \
                        longname.c move.c mvprintw.c mvscanw.c mvwin.c \
                        newwin.c overlay.c overwrite.c printw.c putchar.c \
                        refresh.c scanw.c scroll.c scrollnow.c toucholap.c \
                        standout.c touchwin.c tstp.c unctrl.c
OBJS		=	$(CFILES:.c=.o)

CTAGS		=	ctags
DEFS		=
CFLAGS		=	-O $(DEFS)
CC		=   	gcc -g -fstrength-reduce -fcombine-regs \
                        -finline-functions
TAGSFILE	=   	tags

#include    <makelib.mk>

libcurses.a	: libcurses.a(${OBJS})	    	    	    MAKELIB
	
tags		:
	cwd=`pwd`; \
	    for i in ${CFILES}; do \
	    ctags -a -f ${TAGSFILE} $$cwd/$$i; \
	    done
	
clean		:
	rm -f ${OBJS} profiled/*.o a.out core test errs \
	    libcurses libcurses_p tags
	
ctags		:
	${CTAGS} ${CFILES} curses.h
	
lint		:
	lint -hxb ${CFILES} -lcurses > lint.out
	
test		:	libcurses.a test.o
	${CC} ${LDFLAGS} ${CFLAGS} -o test test.o libcurses.a -ltermlib
	
test.o		:	test.c
	${CC} ${CFLAGS} -c test.c
	
ar		:
	ar crv curses.ar ${CFILES} curses.h curses.ext Makefile
