#!/bin/sh -
#
# $Id: checkFileSizeAndPermission,v 1.1 93/12/21 18:48:23 joon Exp $
#

MAKETOOLPATH=/staff/pcgeos/Tools/scripts/sdk
export MAKETOOLPATH

if [ "$1" = "" ]; then
	echo "Usage: $0 <check_dir>"
	exit 1
fi

echo "Checking $1 for 0 byte files..."
echo "----------------------------------------------------------------"
find $1 -size 0 -print

echo "Checking $1 for files with bad permissions..."
echo "----------------------------------------------------------------"
find $1 \( -perm 000 -o -perm 400 -o -perm 440 -o -perm 444 \) -print
