#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1992 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	copy_doc_file
# FILE: 	copy_doc_file
# AUTHOR: 	Adam de Boor, Jul 26, 1992
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	ardeb	7/26/92		Initial Revision
#
# DESCRIPTION:
#
#	Usage: copy_doc_file <file> <destination path>
#
#	Copy doc files unix2dos'd with '^DOC:' lines stripped out.
#
#	$Id: copy_doc_file,v 1.1 94/01/12 14:48:29 joon Exp $
#
###############################################################################

d=`expr $1 : '\.*/*\(.*\)/[^/]*$'`
mkdir -p $2/$d

if ( egrep -v '^DOC:' $1 > $2/$1 ); then
    echo -n "Copied $1 to $2/$1 "
    if ( unix2dos $2/$1 ); then
	echo "and unix2dos'd"
    else
	echo "-- apparent error unix2dos'ing"
    fi
else
    echo "apparent error copying file $1 to $2/$1"
fi
