#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1992 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	cp_for_sdk
# FILE: 	cp_for_sdk
# AUTHOR: 	Adam de Boor, Jul 26, 1992
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	ardeb	7/26/92		Initial Revision
#
# DESCRIPTION:
#	Usage: cp_for_sdk [-u] <src> <dest>
#
#	If the file is a .sym file, it will have all source-file information
#	and extraneous identifiers stripped out of it during the copy. Anything
#	else is copied over verbatim.
#
#	If -u is specified, the file will be run though unix2dos.
#
#	$Id: cp_for_sdk,v 1.1 93/12/21 18:47:06 joon Exp $
#
###############################################################################

unix2dos="no"

if [ "$1" = "-u" ]; then unix2dos="yes"; shift; fi

d=`expr $2 : '\.*/*\(.*\)/[^/]*$'`
mkdir -p $d

case $1 in
	*.sym) 	if ( stripsym $1 $2 ); then
		    echo "StripSym'd $1 to $2"
		    if [ $unix2dos = "yes" ]; then
			echo " ** You don't want to unix2dos .sym files! **"
		    fi
		else
		    echo "apparent error stripsym'ing file $1 to $2"
		fi
		;;
	*)	if ( cp $1 $2 ); then
		    echo -n "Copied $1 to $2 "
		    if [ "$unix2dos" = "yes" ]; then
			if ( unix2dos $2 ); then
			    echo "and unix2dos'd"
			else
			    echo "-- apparent error unix2dos'ing"
			fi		
		    else
			echo ""
		    fi
		else
		    echo "apparent error copying file $1 to $2"
		fi
		;;
esac
