#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = text
ASM_TO_OBJS     = loader.asm
UI_TO_RDFS      =
SRCS            = loader.asm main.asm locate.asm strings.asm ini.asm\
                  load.asm heap.asm path.asm gpmi.asm videoDetect.asm
OBJS            = loader.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
