IRLAP.rdef: GENERIC.UIH PRODUCT.UIH
IRLAPADDRESSCONTROL.rdef: GENERIC.UIH PRODUCT.UIH
IRLAPPREFCONTROL.rdef: GENERIC.UIH PRODUCT.UIH INTERNAL/PRODFEATURES.UIH \
                CONFIG.UIH OBJECTS/COLORC.UIH
IRLAPMANAGER.obj \
IRLAPMANAGER.eobj: GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF SYSTEM.DEF \
                LOCALIZE.DEF SLLANG.DEF INTERNAL/INTERRUP.DEF OBJECT.DEF \
                LMEM.DEF TIMER.DEF TIMEDATE.DEF DRIVER.DEF ASSERT.DEF \
                DISK.DEF FILE.DEF DRIVE.DEF THREAD.DEF \
                INTERNAL/SEMINT.DEF SEM.DEF INTERNAL/HEAPINT.DEF \
                SYSSTATS.DEF INITFILE.DEF MEDIUM.DEF \
                INTERNAL/PRODFEATURES.DEF INTERNAL/STREAMDR.DEF \
                INTERNAL/SERIALDR.DEF UI.DEF VM.DEF TEXT.DEF FONTID.DEF \
                GRAPHICS.DEF FONT.DEF COLOR.DEF CHAR.DEF WIN.DEF \
                INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                CONFIG.DEF OBJECTS/COLORC.DEF OBJECTS/VTEXTC.DEF \
                SPOOL.DEF PRINT.DEF HUGEARR.DEF DBASE.DEF \
                OBJECTS/WINC.DEF OBJECTS/INPUTC.DEF SAC.DEF \
                INTERNAL/NETUTILS.DEF SOCKET.DEF INTERNAL/SOCKETINT.DEF \
                INTERNAL/IRLAPDR.DEF INTERNAL/SOCKETDR.DEF SOCKMISC.DEF \
                IRLAP.DEF IRLAPINT.DEF IRLAPMACRO.DEF \
                IRLAPADDRESSCONTROL.DEF IRLAP.RDEF \
                IRLAPADDRESSCONTROL.RDEF IRLAPPREFCONTROL.RDEF \
                IRLAPEVENT.ASM IRLAPTABLES.ASM IRLAPINITEXIT.ASM \
                IRLAPDISCOVERY.ASM IRLAPACTIONS.ASM IRLAPCONNECT.ASM \
                IRLAPPXFER.ASM IRLAPSXFER.ASM IRLAPSNIFF.ASM \
                IRLAPXCHG.ASM IRLAPUTIL.ASM IRLAPEC.ASM IRLAP.ASM \
                IRLAPSOCKET.ASM IRLAPSTRINGS.ASM IRLAPCONTROL.ASM \
                IRLAPADDRESSCONTROL.ASM IRLAPPREFCONTROL.ASM

IRLAPEC.geo IRLAP.geo : GEOS.LDF NETUTILS.LDF UI.LDF SOCKET.LDF SERIAL.LDF 