#!/bin/sh -f
#
#$Id: convert,v 1.2.4.1 97/03/29 10:46:14 canavese Exp $
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon

CArgs="-f -u -t -L -dLC -dLM -dSM -dLCGA -dSCGA -dYM -dTC -dTM -dTCGA"
MArgs="-f -u -t -L -dLC -dLM -dSC -dLCGA -dYC -dTC -dTM -dTCGA"
maskColor="3"

cvtfile file2gr.pcx 6 CBookDoc $CArgs
cvtfile file2gr.pcx 7 MBookDoc $MArgs

cvtpcx -f -u -t -m3 -x131 -y83 -nStudio file2gr.pcx
cvtpcx -f -u -t -m3 -x131 -y124 -nStudioDoc file2gr.pcx

cvtpcx -f -m2 -t -z -x0 -y192 -nEditTextTool grobj.pcx
cvtpcx -f -m2 -t -z -x48 -y0 -nBitmapPtrTool grobj.pcx
