#!/bin/sh
##############################################################################
#
# 	Copyright (c) GeoWorks 1991 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	basebox
# FILE: 	basebox
# AUTHOR: 	Falk Rehwagen, Oct 26, 2020
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	fr	26/10/20	Initial Revision
#
# DESCRIPTION:
#	The basebox itself, currently mapped to a to be installed dosbox.
#
#	Usage: basebox 
#
#	$Id: basebox,v 1.18 97/02/12 17:08:40 stevey Exp $
#
###############################################################################

export SDK_TARGET=$1
rm -rf $SDK_TARGET
mkdir $SDK_TARGET/
mkdir $SDK_TARGET/Installed/
mkdir $SDK_TARGET/Installed/Include/
mkdir $SDK_TARGET/CInclude/
mkdir $SDK_TARGET/Include/
mkdir $SDK_TARGET/Include/Appl/
mkdir $SDK_TARGET/Include/Appl/SDK_C/
mkdir $SDK_TARGET/Include/Appl/SDK_Asm/
mkdir $SDK_TARGET/Include/Library/
mkdir $SDK_TARGET/Include/Library/SDK_C/
mkdir $SDK_TARGET/Tools/
mkdir $SDK_TARGET/Tools/swat/
mkdir $SDK_TARGET/Tools/swat/lib.new/
mkdir $SDK_TARGET/bin/

cd $ROOT_DIR/Installed/
find . -name '*.geo' | cpio -pdm $SDK_TARGET/Installed/
find . -name '*.sym' | cpio -pdm $SDK_TARGET/Installed/
find . -name '*.gym' | cpio -pdm $SDK_TARGET/Installed/
find . -name '*.exe' | cpio -pdm $SDK_TARGET/Installed/
find . -name '*.com' | cpio -pdm $SDK_TARGET/Installed/

cd $ROOT_DIR/Installed/Include/
find . -name '*.plt' | cpio -pdm $SDK_TARGET/Installed/Include/
find . -name '*.ldf' | cpio -pdm $SDK_TARGET/Installed/Include/

cp $ROOT_DIR/Include/*.* $SDK_TARGET/Include/
cp $ROOT_DIR/CInclude/*.* $SDK_TARGET/CInclude/
cp $ROOT_DIR/bin/*.* $SDK_TARGET/bin/


cd $ROOT_DIR/CInclude/Objects/
find . -name '*.*' | cpio -pdm $SDK_TARGET/CInclude/Objects/

cd $ROOT_DIR/CInclude/Mailbox/
find . -name '*.*' | cpio -pdm $SDK_TARGET/CInclude/Mailbox/

cd $ROOT_DIR/Include/Mailbox/
find . -name '*.*' | cpio -pdm $SDK_TARGET/Include/Mailbox/

cd $ROOT_DIR/Include/Objects/
find . -name '*.*' | cpio -pdm $SDK_TARGET/Include/Objects/

cd $ROOT_DIR/Include/Win32/
find . -name '*.*' | cpio -pdm $SDK_TARGET/Include/Win32/

cd $ROOT_DIR/CInclude/Ansi/
find . -name '*.*' | cpio -pdm $SDK_TARGET/CInclude/Ansi/

cd $ROOT_DIR/CInclude/SDK_C/
find . -name '*.*' | cpio -pdm $SDK_TARGET/CInclude/SDK_C/

cd $ROOT_DIR/Appl/SDK_C/
find . -name '*.*' ! -path '*/no_go/*'| cpio -pdm $SDK_TARGET/Appl/SDK_C/

cd $ROOT_DIR/Appl/SDK_Asm/
find . -name '*.*' ! -path '*/no_go/*'| cpio -pdm $SDK_TARGET/Appl/SDK_Asm\

cd $ROOT_DIR/Library/SDK_C/
find . -name '*.*' ! -path '*/no_go/*'| cpio -pdm $SDK_TARGET/Library/SDK_C/

cd $ROOT_DIR/Tools/swat/lib.new/
find . -name '*.*' | cpio -pdm $SDK_TARGET/Tools/swat/lib.new/
