#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = amateur
ASM_TO_OBJS     = amateurMain.asm
UI_TO_RDFS      = amateur.ui
SRCS            = amateurBitmap.asm amateurBlaster.asm amateurCloud.asm\
                  amateurClown.asm amateurCommon.asm amateurContent.asm\
                  amateurDisplay.asm amateurHiScore.asm amateurJoke.asm\
                  amateurMain.asm amateurPeanut.asm amateurPellet.asm\
                  amateurProcess.asm amateurRandom.asm amateurSound.asm\
                  amateurTomato.asm amateurConstants.def amateurMacros.def\
                  amateurObjects.def circles.def amateur.ui
OBJS            = amateurMain.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
