#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = geoladder
MAIN            = ladgame.goc process.goc visobj.goc sndwork.goc\
                  sndwork.goh
UI              = appui.goc appui.goh
UI_TO_RDFS      =
OBJS            = ladgame.obj process.obj visobj.obj sndwork.obj appui.obj
COMMON          = ladder.goh
MODULES         =
CMODULES        = Main UI
SRCS            = $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
