#!/bin/sh -
#
#
# Project:	PC GEOS
# Module:	Text Editor
# File:		convert
#
# Author:	brianc
#
#	This file contains the convert information for this application.
#
# 	$Id: convert,v 1.1 98/05/14 00:12:50 joon Exp $
#
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps3.pcx 0 TextEditor -dTM -dTCGA $appArgs
cvtpcx -f -m13 -t -z -nTextEditorTiny tedit.tiny.pcx
