#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = NTAKER
DOCUMENT        = Appl.goc Proc.goc Doc.goc Display.goc
UI              = ntakerui.goc
UI_TO_RDFS      =
OBJS            = Appl.obj Proc.obj Doc.obj Display.obj ntakerui.obj
COMMON          = ntaker.goh
MODULES         =
CMODULES        = Document UI
SRCS            = $(DOCUMENT) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
