rem All Rem'd so I don't accidentally regenerate ;-)

rem cvtpcx -2 -w48 -h30 -m1 -G -nqTip1 -oqTip1.goh tip1.pcx
rem cvtpcx -2 -w66 -h24 -m1 -G -nqTip2 -oqTip2.goh tip2.pcx
rem cvtpcx -2 -w100 -h81 -m1 -G -nqTip3 -oqTip3.goh tip3.pcx

rem cvtpcx -2 -w47 -h30 -m1 -G -nqTTip1 -oqTTip1.goh hint1.pcx
rem cvtpcx -2 -w66 -h24 -m1 -G -nqTTip2 -oqTTip2.goh hint2.pcx
rem cvtpcx -2 -w157 -h50 -m1 -G -nqTTip3 -oqTTip3.goh hint3.pcx

