#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1995 -- All Rights Reserved
#
# PROJECT:	
# MODULE:	
# FILE: 	build_cache
# AUTHOR: 	Adam de Boor, Mar  1, 1995
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	ardeb	3/ 1/95		Initial Revision
#
# DESCRIPTION:
#	A script to build up a .symdir file for a tree, for use by Swat
#
# USAGE:
#	build_cache <top>
#
#	$Id: build_cache,v 1.2 95/10/26 17:10:38 guggemos Exp $
#
###############################################################################
find $1 -name \*.geo -print |
    while read file; do
	# the sed script actually plucks out the two halves of the permanent
	# name from the two lines on which they appear, then quits
	name=`exam $file | sed -n -e '
    	    /^\$0120/s/^.*\(....\)"$/\1/p
    	    /^\$0130/s/^.*"\(....\).*$/\1/p
	    /^\$0140/q' | tr -d '\012' && echo`
	# form the directory in which the file sits
    	dir=`expr $file : '\(.*\)/[^/]*$'`
	# put out both on a single line
	if [ "$name" ]; then
	    echo $name $dir
	else
	    echo error: $file has no permanent name, or something 2>&1
	fi
    done | sort -u > $1/.symdir
