#!/usr/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1992 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	checkclass
# FILE: 	checkclass
# AUTHOR: 	Andrew Wilson, Jan 22, 1992
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	CT	9/12/94		Initial version
#
# DESCRIPTION:
#	This script checks that a localization .vm file is valid.
#       There is reason to suspect .VM files, because at the time
#	of this writing, the PC SDK creates bogus .VM files.
#
#	Usage:	checkvm <file>
#
#	Returns: in sh, $? = 1 if invalid
#			$? = 0 if OK
#
#		 Also prints 0 if invalid, non-0 if OK
#
#	Example: checkvm isvgeode.vm
#
#
#	$Id: checkvm,v 1.1 95/09/12 09:05:30 cthomas Exp $
#
###############################################################################

pvm $1 | grep -c '(lmem)'
