#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1992 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	checkC
# FILE: 	checkC
# AUTHOR: 	Adam de Boor, Feb 19, 1992
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	ardeb	2/19/92		Initial Revision
#
# DESCRIPTION:
#	A script to ensure consistency between installed .def and .goh files
#
# 	Do it find any discrepancies, be assured it'll send mail to the
#	last parson t'touch the file...
#
#	$Id: checkC,v 1.4 94/10/14 22:13:29 guggemos Exp $
#
###############################################################################
USER=root
export USER
objects=`cd /staff/pcgeos/Include; find . -name \*.def -print | sed -e 's/\.def$//g' -e 's/^\.\///g'`
for i in $objects; do
	if [ -f /staff/pcgeos/CInclude/$i.goh ]; then
	    if checkclass $i > /tmp/err$$; then
		: do nothing
	    else
		owner=`ls -l /staff/pcgeos/Include/$i.def | awk '{print $3}'`
		cat /tmp/err$$
		echo ::::: $i.def owned by $owner :::::

		cat - /tmp/err$$ << EOF | /usr/ucb/Mail -s "Differences between $i.def and $i.goh" $owner
The nightly comparison of .def and .goh files has found some differences
between the $i.def and $i.goh files, and you are the last person
known to have modified $i.def.

The differences are listed below (left-arrow lines are those in the .def
file, right-arrow lines are those in the .goh file).

Please fix these differences as soon as possible, as there are people who
depend on these definitions...probably.

Please contact Adam and have him fix his script if you feel you have
reached this recording in error. 

The C Police

EOF
	    fi
	else
	    echo $i has no C interface
	fi
done

rm -f /tmp/err$$
