#!/bin/sh -
##############################################################################
#
# 	Copyright (c) Berkeley Softworks 1989 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts -- Cleans up locks
# FILE: 	cleanLocks
# AUTHOR: 	chris 
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	chris	7/ 1/91		Initial Revision
#
# DESCRIPTION:
#	Shell script for cleaning your names out of all the LOCKS files
#	below the current directory.
#	Requires Tools/scripts/SedScripts/rm.sed.
#
#	$Id: cleanLocks,v 1.1 91/07/01 14:38:27 chris Exp $
#
###############################################################################
user=`whoami`
files=""
for i in "$@"; do 
    case $i in
	*)  files="$files $i"
	    ;;
    esac
done

if [ ! "$files" ]; then
    echo "This program takes one or more LOCKS files as arguments"
    echo "and removes lines with the current user name from those files."
else

   for i in $files; do
	mv $i $i~; sed -e /\ $user\ /d $i~ > $i; 
   done

fi

