#!/bin/sh
##############################################################################
#
# 	Copyright (c) Geoworks 1998.  All rights reserved.
#       GEOWORKS CONFIDENTIAL
#
# PROJECT:	GEOS
# MODULE:	
# FILE: 	cmprcsid
# AUTHOR: 	Chris Thomas, Jan 09, 1998
#
# REVISION HISTORY:
#	Name		Date		Description
#	----		----		-----------
#	cthomas 	1/09/98   	Initial Revision
#
# DESCRIPTION:
#
#	Compares the rcs ID's of the local & fusion copies of
#	files.
#
# USAGE:
#
#	cmprcsid file1 file2 .... filen
#
# EXAMPLES:
#
#       cmprcsid /staff/pcgeos/CInclude/geos.h
#
#	cmprcsid `checkgupdate`
#	
#	$Id: cmprcsid,v 1.2 98/01/09 20:30:56 cthomas Exp $
#
###############################################################################

echo fusion
rsh fusion grep '\$Id' $* 2>&1 > /tmp/cmprcsid1.$$.$USER
echo local
grep '\$Id' $*  2>&1 >> /tmp/cmprcsid2.$$.$USER

diff /tmp/cmprcsid1.$$.$USER /tmp/cmprcsid2.$$.$USER | \
  grep \<\\\|\> | \
  sort +1 +0

rm /tmp/cmprcsid1.$$.$USER /tmp/cmprcsid2.$$.$USER
