#!/bin/sh -
###############################################################################
# 	Copyright (c) Berkeley Softworks 1989 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts
# FILE: 	copy_host_to_g
# AUTHOR: 	jimmy
# DESCRIPTION:  copy stuff over to the g drive from t drive
#
#	$Id: copy_host_to_g,v 1.3 93/02/22 18:25:31 jimmy Exp $
#
###############################################################################

cd /n/nevada/tools/pcgeos
echo copying Loader...
cp -Rp Loader /n/company/sdk_inst.all/pcgeos
echo copying Driver...
cp -Rp Driver /n/company/sdk_inst.all/pcgeos
echo copying Appl...
cp -Rp Appl /n/company/sdk_inst.all/pcgeos
echo copying Library...
cp -Rp Library /n/company/sdk_inst.all/pcgeos
echo copying bin...
cp -Rp bin /n/company/sdk_inst.all/pcgeos
echo copying include...
cp -Rp include /n/company/sdk_inst.all/pcgeos
echo copyinng tcl...
cp -Rp tcl /n/company/sdk_inst.all/pcgeos

