#!/usr/public/perl
# -*- perl -*-
##############################################################################
#
# 	Copyright (c) Geoworks 1996 -- All Rights Reserved
#       GEOWORKS CONFIDENTIAL
#
# PROJECT:	
# MODULE:	
# FILE: 	dumpmake
# AUTHOR: 	Chris Thomas, Aug  5, 1996
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	CT	8/ 5/96   	Initial Revision
#
# DESCRIPTION:
#     
#       Given a pattern (regular expression), and some pmake output,
#	prints only the output of the pmake jobs whose header lines
#	match the pattern after the '--- ' characters
#
# USAGE:
#
#	dumpmake <pattern> [make]
#
#         <pattern>:	Regular expression (perl style) to match in
#			'--- ' lines, anchored immediately after
#			those characters
#	  [make]:	File containing the output of pmake.
#			If not supplied, reads from stdin.
#		
# EXAMPLE:
#
#	dumpmake serial /staff/pcgeos/Installed/night.alameda.out
#
#		prints only the pmake jobs for the serial driver
#
#	$Id: dumpmake,v 1.1 97/09/30 08:14:00 cthomas Exp $
#
###############################################################################

$pat = $ARGV[0];
shift;
if ($#ARGV < 0) {
    $ARGV[0] = '-';
}
$inpat = 0;

while (<>) {
    if (/^--- /) {
	$inpat = /^--- $pat/o;
    }
} continue {
    print if $inpat;
}
