#!/bin/csh -f
#
#	Recursively searches cwd for geodes, then looks for the specified 
#	string in them (in chunks).
#
#	Paul Canavese, 12/18/95
#
#	> findstring Print
#
# 	$Id: findstring,v 1.1 96/01/03 15:10:05 canavese Exp $

# Make sure we were passed a pattern.

if ($#argv == 0) then
    echo This script recursively searches the current working directory
    echo for geodes, then looks for the specified string in them (in
    echo chunks).
    echo 
    echo Usage: findstring <pattern>
    exit 0
endif

# Find all the geodes in this directory and below.

echo -n " 0%"
set pattern="$*"
set files=`find . -name \*.geo -print`
set filecount=`echo $files | wc -w`
@ counter=0

# Search for the string in each geode.

foreach file ($files)
    set result=`strings $file | grep "$pattern"`
    if ( "$result" != "" ) then
	echo "$file"
	strings $file | grep "$pattern"
	echo -n "   "
    endif

@ percent = (100 * $counter) / $filecount
if ( $percent < 10 ) then
    echo -n " "
endif
echo -n "$percent%"

@ counter= $counter + 1

end

echo -n ""
