#!/bin/csh -f
##############################################################################
#
# 	Copyright (c) GeoWorks 1992 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Shell scripts
# FILE: 	fnchange
# AUTHOR: 	Chris Boyke, Aug  6, 1992
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	CB	8/ 6/92		Initial Revision
#
# DESCRIPTION:
#
# Change a set of filenames using a regular expression or a set of
# regular expressions
# 
# Usage:
#
# 	fnchange <old> <new> <filelist>
#
# OR
#	fnchange -f <filename> <filelist>
#
#
# Examples:
#	
#	fnchange x y *.asm
#
# will change all .asm files so that the letter "x" in each filename
# replaced with the letter "y"
# 
#	fnchange -f <filename> *.asm
#	
#	 If <filename> contains:
#		foo	bar
#		xyz	abc
#	
#	 and the filenames are:
#	 	foo.asm
#		xyzTemp.asm
#	 
#	 they'll be renamed to:
#		bar.asm
#		abcTemp.asm
#	
#
#	$Id: fnchange,v 1.1 92/10/21 10:11:20 chrisb Exp $
#
#
set temp = "/tmp/fnchange.out"

echo $argv[3-]  > $temp

# oldlist is the list of BEFORE filenames
set oldlist = `cat $temp`

global $1 $2 $temp

# newlist is the AFTER filenames
set newlist = `cat $temp`

while ( `expr $#oldlist \> 0` )
	mv $oldlist[1] $newlist[1]		
	shift oldlist
	shift newlist
end

/bin/rm $temp

