#!/bin/sh -
##############################################################################
#
# 	Copyright (c) Berkeley Softworks 1989 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts -- profile
# FILE: 	formatLog
# AUTHOR: 	Adam de Boor, July 24, 1989
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	ianp	12/20/94	Initial Revision
#
# DESCRIPTION:
#
#	Used by the elisp file profile.el to create nicely formatted ouput
#
#	$Id: formatLog,v 1.1 94/12/20 18:50:43 ian Exp $
#
###############################################################################
awk '
BEGIN {
	ClockRate = 1193180 
	TotalTime = 0
	print ".TS\nc s s\nl c c c.\n"
}
{
	if ($1 == "Total") {
		TotalTime = ($3/ClockRate)
		printf "Total Time: %fs\n", TotalTime
	}
	else if (n = index($1,"MSG_")) {
		Time = ($2/ClockRate)
		Percentage = ((Time/TotalTime)*100)
		printf "%s\t Time:%fs\t%%%.2f\t#%d\n",$1,Time,Percentage,$3
	}
	
}
END {
	print ".TE"
} ' $* | tbl | nroff


