#!/bin/sh -
##############################################################################
#
# 	Copyright (c) Berkeley Softworks 1989 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts -- File Installation and Checkout
# FILE: 	gmail
# AUTHOR: 	Tony, Adam, Aug 29, 1989
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	tony	8/29/89		Initial Revision
#
# DESCRIPTION:
#	Shell script to send mail to all people who have a file locally
#
#	$Id: gmail,v 1.4 89/11/02 11:17:37 adam Exp $
#
###############################################################################
#
#	Usage: gmail file <mail-header> <mail-string>
#	Usage: gcheck file
#
#	This one script does both gmail and gcheck.  gcheck writes to standard
#	output the names of everybody else who has the file
#
#	Expects:
#		$rootdir - root directory
#		$idir - installed directory
#		$cwd - cwd
#

#
# Common code -- more trouble than it's worth to keep it in a separate
# file.
#
if [ ! "$cwd" ]; then
    cwd=`pwd`
    rootdir=`expr "$cwd" : '^\(.*/'${ROOTDIR-pcgeos}'\).*$'`
    idir=$rootdir/`expr "$cwd" : $rootdir'/[^/]*/\(.*\)$'`
fi

#
#	Use /staff/'${ROOTDIR-pcgeos}' for all checks as that's the place that has the
#	links to everyone's development tree. If we didn't do this, people
#	installing on a workstation wouldn't actually find things for the
#	other people, as they'd be doing it from their own development system
#
rootdir=/staff/`expr "$rootdir" : '.*/\('${ROOTDIR-pcgeos}'.*\)$'`
idir=/staff/`expr "$idir" : '.*/\('${ROOTDIR-pcgeos}'.*\)$'`

case $1 in
    */*) tail=`basename $1 ""`
	 dir=$idir/`expr $1 : '\(.*\)/[^/]*$'`
	 ;;
    *)	 tail=$1
	 dir=$idir
	 ;;
esac

mailTo=""
if [ -f /bin/sun ]; then link=h; else link=l; fi
subdir="`expr $dir : $rootdir'/\(.*\)$'`"
others="`echo $rootdir/*/$subdir/$tail`"
for other in $others; do
    name=`expr $other : $rootdir'/\([^/0-9]*\)[0-9]*/'`
    if [ ! -$link "$other" -a \
	 "$name" != "*" -a \
	 "$name" != "$USER" -a \
	 "$name" != "Installed" ];
    then
	mailTo="$mailTo $name"
    fi
done

if [ `basename $0 ""` = "gmail" ]; then
    if [ "$mailTo" ]; then
	echo "$3" | mail -s "$2" $mailTo
    fi
else
    if [ "$mailTo" ]; then
	echo "$mailTo"
    fi
fi
