#!/bin/sh -
#
# A shell script for changing to the installed directory.
# Simply prints the name of the directory to which the shell should change.
#
# Add the following alias to .cshrc file:
#
#	alias cdi 'cd `idir`; echo $cwd'
#
#
#	$Id: idir,v 1.1 89/07/27 10:19:24 matt Exp $
# 
cwd=`pwd`
# Extract /staff/pcgeos or /staff/pcgeos/$USER whichever is the current trunk
rootdir=`expr "$cwd" : '\(.*/pcgeos\)/.*$' \| "$cwd" : '\(.*/pcgeos\)$'`
if [ "$rootdir" = "0" ]; then
	echo "idir only works in pcgeos tree" 1>&2
	exit 1
fi

case "$cwd" in
    $rootdir/${USER}*)
    	echo $rootdir/`expr "$cwd" : $rootdir'/[^/]*/\(.*\)$'`
	;;
    *)
	echo "."
	;;
esac

