#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1992 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts 
# FILE: 	killall
# AUTHOR: 	Taylor Gautier, Feb 20, 1997
#
# REVISION HISTORY:
#	Name		Date		Description
#	----		----		-----------
#	tgauiter	2/20/97		Initial Revision
#
# DESCRIPTION:
#
#	script to kill all processes by a certain name.
#
#	$Id: killall,v 1.1 97/02/20 12:26:44 tgautier Exp $
#
###############################################################################
ps -x | grep $1 | grep -v grep | grep -v killall | awk '{print $1}' | xargs kill
