#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1992 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts 
# FILE: 	netclean
# AUTHOR: 	Gene Anderson, May 11, 1992
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	eca	5/11/92		Initial Revision
#
# DESCRIPTION:
#
#	Verifies that you aren't attached to the network before
#	attempting to delete files there.  This is to prevent
#	the server from crashing horribly...
#
#	$Id: netclean,v 1.6 94/08/31 10:48:46 chrisb Exp $
#
###############################################################################

usageString="Usage: netclean path [no]"

if [ $# -eq 1 ]; then
    cmd="-exec rm -f {} ;"
elif [ $# -eq 2 ]; then
    if [ "$2" != "no" ]; then
	echo $usageString
	exit 0
    fi
    cmd=""
else
    echo $usageString
    exit 0
fi

find $1 -name \*.geo -print $cmd
