#!/bin/sh -
##############################################################################
#
# 	Copyright (c) Berkeley Softworks 1989 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts -- File Installation and Checkout
# FILE: 	nowhite
# AUTHOR: 	Tony, Sep 29, 1989
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	tony	9/29/89		Initial Revision
#
# DESCRIPTION:
#	Shell script to remove white space at the end of lines
#
#	$Id: nowhite,v 1.1 89/09/29 10:51:30 tony Exp $
#
###############################################################################
#
sed -e 's/[ 	]*$//g' $1 > $1.temp
mv $1.temp $1
