#!/bin/sh
#
#	Script to edit PC files on the host
#
#	$Id: pcvi,v 1.3 89/11/12 23:06:05 gene Exp $
#
    if [ $* ]; then
	a=$cwd
	cd /tmp
	pcget $*
	vi $*
	pcsend $*
	/bin/rm -f $*
	cd $a
    else
	echo 'nothing to edit -- pcvi aborted.'
    fi
