#!/usr/bin/sh
##############################################################################
#
# 	Copyright (c) GeoWorks 1992 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Shell scripts
# FILE: 	releaselog
# AUTHOR: 	Chris Thomas, Sep 20, 1995
#
# DESCRIPTION:
#
#	Add a timestamped/userstamped log message to
#       /staff/pcgeos/<branch>/releaseNotes
#
#
# USAGE:
# 	releaselog branch*  < stdin
#
# 	$Id: releaselog,v 1.1 95/09/20 10:53:38 cthomas Exp $
#
#

# Use whatever branches were passed
#
branches=$*

#
# But if none were passed, default to ReleaseJedi
#
branches=${branches:-ReleaseJedi}

base=/staff/pcgeos
temp=/tmp/$USER.log.$$
logfile=releaseNotes

#
# Write log entry to a single temp file, so we can append it to multiple
# log files later
#
echo >> $temp
date +"$USER %D %T" >> $temp
echo ------------------------- >> $temp
cat >> $temp

#
# Append entry to each log file in $branches
#

for branch in $branches; do
  cat $temp >> $base/$branch/$logfile
  chmod -f 666 $base/$branch/$logfile
done

#
# clean up
#
rm -f $temp

