#!/bin/sh -
##############################################################################
#
# 	Copyright (c) Berkeley Softworks 1990 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	saveNonEC
# FILE: 	saveNonEC
# AUTHOR: 	Adam de Boor, Aug  8, 1990
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	ardeb	8/ 8/90		Initial Revision
#
# DESCRIPTION:
#	not-so-simple script to save all non-ec .sym and .geo files elsewhere
#
#   	Usage: saveNonEC <destdir>
#
#	$Id: saveNonEC,v 1.1 90/08/24 20:03:21 adam Exp $
#
###############################################################################

if [ $# -ne 1 ]; then
    echo "Usage: $0 <destdir>"
    exit 1
fi

cd /staff/pcgeos/Installed
(find Appl/* Library/* Driver/* -type d -print; echo Kernel Include) |
    while read dir; do
    	files="`echo $dir/*.sym $dir/*.geo $dir/*.exe $dir/*.ldf | tr ' ' '\012' | sed -e '/\*\./d' -e '/ec\./d' | tr '\012' ' '`"

    	if [ "$files" ]; then
    	    echo copy $files to $1/$dir
	    mkdir -p $1/$dir
	    cp -p $files $1/$dir
    	fi
    done
