#!/bin/sh -
#
#	unlink <dirs>
#
# 	A single line of output from find -ls looks like this:
#
# inode	  size	bits	    links	owner	group	     size  mo  dy  yr
# 2142    1 	lrwxrwxrwx  1 		root     staff          41 Nov 21  1989
#
# file				    arrow  dest
# /usr/public/lib/pmake/linksprite.mk -> /n/li/sun3/public/lib/pmake/linksprite.mk
#
# Of course, it's all on one line. Use the "read" command until EOF to read the
# individual fields and Do The Right Thing (go Spike!)
#
find $* -type l -ls |
while read inode size bits links owner group size month day year file arrow dest; do
    case $dest in
	/n/*)	
	    if [ -f $dest ]; then
		echo Copying $file from $dest...
		rm -f $file
		cp -p $dest $file
	    else
		echo "$file is a real nowhere link ($dest)"
	    fi
	    ;;
    esac
done

