#!/bin/sh -
#
# A shell script for switching to the working pcgeos directory.
# Simply prints the name of the directory to which the shell should change.
#
# Add the following alias(es) to .cshrc file:
#
#	alias cdw 'cd `wdir`; echo $cwd'
#	alias lsw 'ls `idir`'
#
#
#	$Id: wdir,v 1.1 89/07/27 10:19:53 matt Exp $
# 
cwd=`pwd`
# Extract /staff/pcgeos or /staff/pcgeos/$USER whichever is the current trunk
rootdir=`expr "$cwd" : '\(.*/pcgeos\)/.*$' \| "$cwd" : '\(.*/pcgeos\)$'`
if [ "$rootdir" = "0" ]; then
	echo "wdir only works in pcgeos tree" 1>&2
	exit 1
fi

case "$cwd" in
    $rootdir/${USER}*)
	echo "."
	;;
    *)
    	echo $rootdir/$USER/`expr "$cwd" : '^'$rootdir'/\(.*\)$'`
	;;
esac
