#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bbxcd
MAIN            = DISPLAY.H KEY.H PCODE.H SUBCODE.H TIMEVENT.H bbxcd.goc\
                  DISPLAY.GOC KEY.GOC PCODE.GOC PROCESS.GOC SUBCODE.GOC\
                  TIMEVENT.GOC TXT_STRS.GOC DISPLAY.GOH PCODE.GOH\
                  PROCESS.GOH SUBCODE.GOH TIMEVENT.GOH
UI              = UIMAIN.GOC UIMAX.GOC DEFINE.GOH UIMAIN.GOH UIMAX.GOH
UI_TO_RDFS      =
OBJS            = bbxcd.obj DISPLAY.obj KEY.obj PCODE.obj PROCESS.obj\
                  SUBCODE.obj TIMEVENT.obj TXT_STRS.obj UIMAIN.obj\
                  UIMAX.obj
COMMON          = bbxcd.H
MODULES         =
CMODULES        = MAIN UI
SRCS            = $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
