NOID.obj \
NOID.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH OBJECTS/COLORC.GOH GAME.GOH \
                ART/ICON.GOH ART/BALL.GOH ART/OPPON1.GOH ART/OPPON2.GOH \
                ART/OPPON3.GOH ART/OPPON4.GOH ART/OPPON5.GOH \
                ART/BRICK1.GOH ART/BRICK2.GOH ART/BRICK3.GOH \
                ART/BRICK4.GOH ART/BRICK5.GOH ART/BRICK6.GOH \
                ART/BRICK7.GOH ART/BRICK8.GOH ART/BRICK9.GOH \
                ART/BRICK10.GOH ART/BRICK11.GOH ART/BRICK12.GOH \
                ART/BRICK13.GOH ART/BRICK14.GOH ART/BRICK15.GOH \
                ART/QTIP1.GOH ART/QTIP2.GOH
NOID.obj \
NOID.eobj: NOID.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H OBJECT.H \
                LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H GSTRING.H \
                TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H TIMEDATE.H \
                FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H INITFILE.H \
                SOUND.H SEM.H

NoidEC.geo Noid.geo : GEOS.LDF UI.LDF SOUND.LDF GAME.LDF COLOR.LDF 