#!/bin/sh -f
# $Id: convert,v 1.1 98/04/28 10:55:00 joon Exp $
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps1.pcx 4 GeoCalc $appArgs
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps1.pcx 5 GeoCalcDoc $docArgs

cvtpcx -f -m13 -t -z -nGeoCalcTiny newcalc.tiny.pcx
cvtpcx -f -m2 -t -z -x0 -y192 -nSSTool grobj.pcx
cvtpcx -f -m2 -t -z -x48 -y0 -nBitmapPtrTool grobj.pcx


