#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = webbox
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = uimenu2.goc msgmenu3.goc men2str.goc msgmenu2.goc\
                  msgmenu4.goc text.goc msgsptag.goc uisptag.goc\
                  msgmenu1.goc uibutton.goc uimenu1.goc uiabout.goc\
                  men1str.goc uistat.goc msgproc.goc msgprim.goc\
                  bstrings.goc msgbuton.goc men2str.goh men1str.goh app.goh\
                  bstrings.goh global.goh
OBJS            = uimenu2.obj msgmenu3.obj men2str.obj msgmenu2.obj\
                  msgmenu4.obj text.obj msgsptag.obj uisptag.obj\
                  msgmenu1.obj uibutton.obj uimenu1.obj uiabout.obj\
                  men1str.obj uistat.obj msgproc.obj msgprim.obj\
                  bstrings.obj msgbuton.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
