#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = webbox
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = bstrings.goc men1str.goc men2str.goc msgbuton.goc\
                  msgmenu1.goc msgmenu2.goc msgmenu3.goc msgmenu4.goc\
                  msgprim.goc msgproc.goc msgsptag.goc text.goc\
                  uibutton.goc uimenu1.goc uimenu2.goc uisptag.goc\
                  uistat.goc app.goh bstrings.goh global.goh men1str.goh\
                  men2str.goh
OBJS            = bstrings.obj men1str.obj men2str.obj msgbuton.obj\
                  msgmenu1.obj msgmenu2.obj msgmenu3.obj msgmenu4.obj\
                  msgprim.obj msgproc.obj msgsptag.obj text.obj\
                  uibutton.obj uimenu1.obj uimenu2.obj uisptag.obj\
                  uistat.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
