#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = xwm
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = export.goc import.goc process.goc xwmui.goc xwm.goh\
                  doc.goh bboxreg.goh app.goh appicon.goh externs.goh\
                  docicon.goh
OBJS            = export.obj import.obj process.obj xwmui.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
