#!/usr/public/perl
# -*- perl -*-
# $Id: checkDocumentDir,v 1.2 95/09/20 19:52:40 jacob Exp $
# Author:	Jacob Gabrielson
# Usage:	checkDocumentDir <path>

$ourname = $0;
$ourname =~ s,^.*/([^/]+)$,\1,;

$EXPENSE_REPORT_TEMPLATE = "expense_.000";
$TEMPLATE_FLAG_OFFSET = 43;
$TEMPLATE_FLAG_MASK   = 128;

## These MUST be there.
%requiredFiles = ('book_rea.000', 1,
		  $EXPENSE_REPORT_TEMPLATE, 1,
		  'jotter.000', 1,
		  'notepad.ndb', 1,
		  'wtromdb.000', 1,
		  'compact_.gdb', 1,
		  'finance.fdb', 1,
		  'master.mdb', 1,
		  'phone.pdb', 1);

## If these are present, they don't indicate any problems, so don't complain.
%dontCareFiles = ('appt.adb', 1, 
		  'jwtime.wdb', 1);

## Get a list of files in passed dir.
chdir($ARGV[0] || ".") || die;
opendir(DOCUMENT, ".");
@files = readdir(DOCUMENT);
closedir(DOCUMENT);

$status = 0;			# exit value

## Scan thru them all, checking them for validity.
foreach $file (@files) {
    
    ## Ignore directories and other weird types of files.
    next unless (-f $file);

    ## Yell und scream if an unexpected file exists.
    if (!$requiredFiles{$file} && !$dontCareFiles{$file}) {
	$bad .= "$ourname WARNING: Found unexpected file '$file'.\n";
	$status = 1;
    }
}

## Now do the reverse -- make sure all the files we require are present.
foreach $file (keys %requiredFiles) {
    if (! -f $file ) {
	$bad .= "$ourname WARNING: '$file' is missing.\n";
	$status = 1;
    }
}

## Now fix up the expense report template.
if ( -f $EXPENSE_REPORT_TEMPLATE ) {

    ## Open the file.
    open(TEMP, "+<$EXPENSE_REPORT_TEMPLATE") || die;
    binmode TEMP;

    ## Read out the byte containing the upper-half of the GeosFileHeaderFlags.
    seek(TEMP, $TEMPLATE_FLAG_OFFSET, 0);
    die if (sysread(TEMP, $buf, 1) != 1);
    
    $flags = unpack("C", $buf);
    #print $flags, "\n";
    if (!($flags & $TEMPLATE_FLAG_MASK)) {
	$bad .= "'$EXPENSE_REPORT_TEMPLATE' does not have the template bit set.\n";
	$status = 1;
    }

    ## Actually, don't do this.  I don't want to mess with the file
    ## from here.  I'd feel safer if we always did it with GeoManager.
    #print $flags, "\n";
    #$buf = pack("C", $flags);
    #seek(TEMP, $TEMPLATE_FLAG_OFFSET, 0);
    #syswrite(TEMP, $buf, 1);

    close TEMP;
}

print STDERR <<EOM if $status;
------------------------------------------------------------------------------
WHOA, STOP, HOLD THE PRESSES..  HAAAAAAAAAAAAAAAANG ON.  Like, 
check out these errors:

$bad
You got this message for at least one of the
following reasons (use the above warnings
to figure out which ones):

1. The Expense Report Template does not
   have the template bit set in its header.
   Use GeoManager to set the template bit.

2. There are unexpected files in:

   $ARGV[0]

   This could mean that we got a new file
   from the localizers, but the DOS name
   hasn't been correct.  So we might ship 
   down the wrong version.

3. There is a file missing from:

   $ARGV[0]

   This could happen due to #2, or else
   because the file is simply missing.

I'm sorry, but the build cannot continue 
safely until these problems have been 
resolved.

If you think this message is in error, mail
me (jacob).

Thanks,

-- Jacob
EOM
exit($status);
