#! /bin/sh -

#
# Copy all the files under the src dir to the dest. dir.
# Syntax:
#	copyToOneDir <src directory> <dest. dirtectory>
# Example:
#	copyToOneDir emu90fr tmpDir
#
# Result: all files copied are on the same level in tmpDir.
#
# $Id: copyToOneDir,v 1.2 95/09/27 10:44:57 cthomas Exp $
#

case $# in
0)	echo "usage: $0 -- Read the header of this script for details."
	exit -1 ;;
1)	echo "usage: $0 -- Read the header of this script for details."
	exit -1 ;;
2) 	
	srcDir=$1
	destDir=$2

	if [ ! -d $srcDir ]; then
		exitCode=$?
		echo "${srcDir}: not a directory."
		exit $exitCode
	fi
	
	if [ ! -d $destDir ]; then
		exitCode=$?
		echo "${destDir}: not a directory."
		exit $exitCode
	fi

	dirList=`find ${srcDir}/ -type f -print`
	for i in $dirList
	do
		cp $i $destDir
	done
	exit 0 ;;
*)	echo "usage: $0 -- Read the header of this script for details."
	exit -1 ;;
esac

