#! /bin/sh -

#
# Copy everything under ProductFiles/Jedi and ProductFiles/JediPC
# NOTE: This operation will overwrite any files in the destination
#       directory. 
#
# Example: 
# copyJProductFiles /staff/pcgeos/JediGerman/Installed/ProductFiles
#
# $Id: copyJProductFiles,v 1.1 95/09/20 13:16:30 jacob Exp $
#
srcDirPrefix=/staff/pcgeos/Release20X/Installed/ProductFiles
srcDir1=Jedi
srcDir2=JediPC

case $# in
0)	echo	"usage: $0 -- Read the header of this script for details." ;;
1)	if [ -d $1 ]; then
	   cd $1
	   cp -R ${srcDirPrefix}/${srcDir1} ${1}
	   cp -R ${srcDirPrefix}/${srcDir2} ${1}
	fi ;;
*)	echo 	"$0 -- Too many arguments."
esac

