#! /bin/sh 

#
# This script is used to restore the Unix filenames from the DOS filenames.
#
# Syntax: fixDOSnames [ec]
#	  ec -- for make ec version filenames. If no argument is given, then
#		make the non-ec version filenames.
#
# $Id: fixDOSnames,v 1.1 95/09/20 13:16:35 jacob Exp $
#
case $1 in
ec) ec=ec;;
*)  ec="";;
esac

nameListec="borlandc.geo \
	    homescre.geo \
	    screendu.geo \
	    jstartup.geo \
	    compress.geo \
	    canon48j.geo \
	    epson24j.geo \
	    propx24j.geo \
	    deskjetj.geo \
	    worldtim.geo \
	    megafile.geo \
	    standard.geo \
	    jedidemo.geo \
	    parallel.geo \
	    genmouse.geo"

nameList="homescre.geo \
	   screendu.geo \
	   worldtim.geo"

if [ $ec ]; then
    listVar=$nameListec
else
    listVar=$nameList
fi

for i in $listVar
do
    if [ -f $i ]; then
	case $i in
	borlandc.geo) mv borlandc.geo borlandc${ec}.geo ;;
	homescre.geo) mv homescre.geo homescreen${ec}.geo ;;
	screendu.geo) mv screendu.geo screendump${ec}.geo ;;
	jstartup.geo) mv jstartup.geo jstartup${ec}.geo ;;
	compress.geo) mv compress.geo compress${ec}.geo ;;
	canon48j.geo) mv canon48j.geo canon48j${ec}.geo ;;
	epson24j.geo) mv epson24j.geo epson24j${ec}.geo ;;
	propx24j.geo) mv propx24j.geo propx24j${ec}.geo ;;
	deskjetj.geo) mv deskjetj.geo deskjetj${ec}.geo ;;
	worldtim.geo) mv worldtim.geo worldtime${ec}.geo ;;
	megafile.geo) mv megafile.geo megafile${ec}.geo ;;
	standard.geo) mv standard.geo standard${ec}.geo ;;
	jedidemo.geo) mv jedidemo.geo jedidemo${ec}.geo ;;
	parallel.geo) mv parallel.geo parallel${ec}.geo ;;
	genmouse.geo) mv genmouse.geo genmouse${ec}.geo ;;
    	esac
    fi
done  
