#!/bin/sh -

#
# This script returns a list of all the geodes necessary for a particular
# version of Jedi.  It should be used by any script that must act
# on the entire set of geodes, in order to do things consistently.
#
# Syntax:
#	jediGeodes <version> [language]
#
# where <version> is one of:
#
#	PC{_EC}		- PC Demo geodes
#	PC_XIP{_EC}	- PC XIP Demo geodes
#	JEDI_XIP	- Hardware XIP geodes
#
# and Language is some reasonable variation on:
#    french{_ALL}
#    german{_ALL}
#    italian{_ALL}
#    portugese{_ALL}
#    spanish{_ALL}
#
#
# Example:
#	jediGeodes JEDI_XIP  ->  lists all geodes that go onto the
#				 prototypes which are common across
#				languages.
#
#	jediGeodes JEDI_XIP french ->  lists only the geodes
#					that don't exist in other
#					languages of jedi
#
#	jediGeodes JEDI_XIP french_ALL -> Lists the union of the
#					above examples.
#
# Note: the list of geodes returned by <language> and <language>_ALL
# should be mutually exclusive.
#
#
# $Id: jediGeodes,v 1.11 96/04/15 19:35:43 todd Exp $
#

# set -x
case $# in
0)	echo "usage: $0 <version>
 Please read the header of this script for details."
	exit 1 ;;
1)	if [ "$1" != "PC" -a "$1" != "PC_EC" -a \
	     "$1" != "PC_XIP_EC" -a "$1" != "PC_XIP" -a \
	     "$1" != "JEDI_XIP" ]; then
		echo "$0 -- The version argument is invalid."
		exit 1
	fi
	;;
2)	language=$2
	;;
*)	echo "$0 -- Too many arguments."
	exit 1 ;;
esac

version=$1

#
# Figure out the ec'ed ness of the version
#
case $version in
*_EC)	ec=ec
	;;
*)	ec=
	;;
esac

if [ "$language" ] ; then
	case "$language" in 
	[Ff][Rr]*)
		capLang=French
		allCapLang=FRENCH
		shortLang=fr
		;;
	[Gg][EeRr]*)
		capLang=German
		allCapLang=GERMAN
		shortLang=gr
		;;
	[Ii][Tt]*)
		capLang=Italian
		allCapLang=ITALIAN
		shortLang=it
		;;
	[Pp][Oo]*)
		capLang=Portugese
		allCapLang=PORT
		shortLang=po
		;;
	[Ss][Pp]*)
		capLang=Spanish
		allCapLang=SPANISH
		shortLang=sp
		;;
	*)
		echo "$0: Invalid language"
		exit 1
		;;
	esac

	case "$language" in
	*_ALL)
		listAll=1
		;;
	*)
		listAll=
		;;
	esac
fi

#
# Some of the geodes in this list are unnecessary, but they are there
# to make the "send" script happy.
# 
pcOnlyList="Library/Swap/swap${ec}.geo \
		Library/Jedi/JediDemo/jedidemo${ec}.geo \
		Library/CoProcessor/Int8087/int8087${ec}.geo \
		Driver/IFS/GEOS/ZoomFS/zoomfs${ec}.geo \
		Driver/Stream/Parallel/parallel${ec}.geo \
		Driver/IFS/DOS/CDROM/cdrom${ec}.geo \
		Driver/IFS/DOS/DRI/dri${ec}.geo \
		Driver/IFS/DOS/MS3/ms3${ec}.geo \
		Driver/IFS/DOS/MSNet/msnet${ec}.geo \
		Driver/IFS/DOS/OS2/os2${ec}.geo \
		Driver/IFS/RFSD/rfsd${ec}.geo \
		Driver/Mouse/AbsGen/absgen${ec}.geo \
		Driver/Mouse/GenMouse/genmouse${ec}.geo \
		Driver/Mouse/KBMouse/kbmouse${ec}.geo \
		Driver/Mouse/LogiSer/logiser${ec}.geo \
		Driver/Mouse/MSBus/msbus${ec}.geo \
		Driver/Mouse/MSSer/msser${ec}.geo \
		Driver/Mouse/MSys/msys${ec}.geo \
		Driver/Mouse/PS2/ps2${ec}.geo \
		Driver/Power/NoPower/nopower${ec}.geo \
		Driver/Swap/Disk/disk${ec}.geo \
		Driver/Swap/EMS/EMM/emm${ec}.geo \
		Driver/Swap/ExtMem/extmem${ec}.geo \
		Driver/Swap/XMS/xms${ec}.geo \
		Driver/Video/Dumb/MCGA/mcga${ec}.geo"

case $version in
PC_XIP*)
	xip=XIP/
	jxip=JediXIP/
	jedif=XIP/
	srcBranch=pcxip

	worldtime=Appl/Jedi/WorldTime/worldtime${ec}.geo

	mtable=Library/Extensions/MTable/mtable${ec}.geo
	math=Library/Math/${xip}math${ec}.geo

	serial=Driver/Stream/Serial/${xip}serial${ec}.geo
	netware=Driver/IFS/DOS/NetWare/${xip}netware${ec}.geo
	gfs=Driver/IFS/GEOS/MegaFile/${xip}megafile${ec}.geo
	jpen=Driver/Mouse/LogiBus/logibus${ec}.geo
	jpower=Driver/Power/NoPowerPCMCIA/nppcm${ec}.geo
	kbd=Driver/Keyboard/kbd.geo
	soundD=Driver/Sound/Standard/standard${ec}.geo
	ucD=""

	loader=Loader/EMMXIP/loader${ec}.exe ;;
PC*)
	xip=""
	jxip=JEDI/
	jedif=""
	srcBranch=pc

	worldtime=Appl/Jedi/WorldTime/worldtime${ec}.geo

	mtable=Library/Extensions/MTable/mtable${ec}.geo
	math=Library/Math/math${ec}.geo

	serial=Driver/Stream/Serial/serial${ec}.geo
	netware=Driver/IFS/DOS/NetWare/${xip}netware${ec}.geo
	gfs=Driver/IFS/GEOS/MegaFile/${xip}megafile${ec}.geo
	jpen=Driver/Mouse/LogiBus/logibus${ec}.geo
	jpower=Driver/Power/NoPowerPCMCIA/nppcm${ec}.geo
	kbd=Driver/Keyboard/kbd.geo
	soundD=Driver/Sound/Standard/standard${ec}.geo
	ucD=""

	loader=Loader/JediVGA/loader${ec}.exe ;;
JEDI_XIP)
	xip=XIP/
	jxip=JediXIP/
	jedif=JediXIP/
	srcBranch=jedixip

	pcOnlyList=""

	worldtime=Appl/Jedi/WorldTime/Borland/worldtime${ec}.geo
	mtable=Library/Extensions/MTable/JEDI/mtable${ec}.geo
	math=Library/Math/JediXIP/math${ec}.geo

	serial=Driver/Stream/Serial/JediXIP/serial${ec}.geo
	netware=""
	gfs=Driver/IFS/GEOS/CVGFS/JediXIP/cvgfs${ec}.geo
	jpen=Driver/Mouse/JediPen/jpen${ec}.geo
	jpower=Driver/Power/Jedi/jpwr${ec}.geo
	if [ "$capLang" = "Portugese" ] ; then
		#
		# kbd is the non-local keyboard to use
		# (if any)
		#
		localKbd=Driver/Keyboard/Jedi/jkbd.geo
	else
		#
		# localKbd is the geode (if any) to use
		# for the language
		#
		localKbd=Driver/Keyboard/Jedi/$capLang/jkbd_${shortLang}.geo
	fi
	soundD=Driver/Sound/Standard/JEDI/standard${ec}.geo
	ucD=Driver/uC/uc${ec}.geo

	loader=Loader/JediXIP/loader${ec}.exe

	;;
esac


langSpecificFiles=
if [ "$language" -o "$listAll" ] ; then

	#
	# List only the files that have language specific
	# versions
	#
	echo 	"Appl/Jedi/JDemo/$allCapLang/jdemo${ec}.geo
		$localKbd
		Appl/Jedi/Finance/$allCapLang/finance${ec}.geo
		Appl/Jedi/HPCalc/$allCapLang/hpcalc${ec}.geo	"

fi

if [ ! "$language" -o "$listAll" ] ; then

	#
	# List the files common to all languages of Jedi
	#

echo 	"Library/Kernel/${jedif}geos${ec}.geo
	Library/AnsiC/${xip}ansic${ec}.geo 
	Library/Math/Compiler/BorlandC/${xip}borlandc${ec}.geo 
	Library/Cards/${jxip}cards${ec}.geo 
	Library/Cell/${xip}cell${ec}.geo 
	Library/Color/color${ec}.geo 
	Library/ConView/${jxip}conview${ec}.geo 
	Library/Jedi/DB/db${ec}.geo 
	Library/Extensions/Gadgets/${xip}gadgets${ec}.geo 
	Library/Jedi/HPMLib/hpmlib${ec}.geo 
	Library/Jedi/JEdit/jedit${ec}.geo 
	Library/Jedi/JError/jerror${ec}.geo 
	Library/Jedi/JLib/jlib${ec}.geo 
	Library/Jedi/JediUI/Jotter/jotter${ec}.geo 
	Library/Jedi/JTable/${xip}jtable${ec}.geo 
	Library/Jedi/JUtils/${xip}jutils${ec}.geo 
	Library/Jedi/JWTime/jwtime${ec}.geo 
	Library/HWR/Key/${jxip}key${ec}.geo 
	Library/HWR/PalmP3/${xip}palm${ec}.geo 
	Library/PCMCIA/${jxip}pcmcia${ec}.geo 
	Library/Pen/${xip}pen${ec}.geo 
	Library/RTCM/${xip}rtcm${ec}.geo 
	Library/Ruler/${xip}ruler${ec}.geo 
	Library/Sound/${xip}sound${ec}.geo 
	Library/SpecUI/JMotif/${xip}jmotif${ec}.geo 
	Library/Spool/${jxip}spool${ec}.geo 
	Library/Spreadsheet/${jxip}ssheet${ec}.geo 
	Library/Styles/${xip}styles${ec}.geo 
	Library/Text/${jxip}text${ec}.geo 
	Library/Extensions/Table/${xip}table${ec}.geo 
	Library/Jedi/Notes/notes${ec}.geo 
	Library/Parse/${xip}parse${ec}.geo 
	Library/PCCom/${xip}pccom${ec}.geo 
	Library/SSMeta/${xip}ssmeta${ec}.geo 
	Library/User/${jxip}ui${ec}.geo 
	Driver/IFS/DOS/MS4/${xip}ms4${ec}.geo 
	Driver/Font/Nimbus/nimbus${ec}.geo 
	Driver/Stream/stream${ec}.geo 
	Driver/Task/NonTS/nonts${ec}.geo 
	Appl/Jedi/Alarm/${xip}alarm${ec}.geo 
	Appl/GeoCalc/${jxip}geocalc${ec}.geo 
	Appl/Jedi/HomeScreen/${jedif}homescreen${ec}.geo 
	Appl/Reader/JEDI/reader${ec}.geo 
	Appl/Jedi/Transfer/${jedif}trans${ec}.geo 
	Appl/Jedi/JPref/${jedif}jpref${ec}.geo 
	Appl/Jedi/ScreenDump/${xip}screendump${ec}.geo 
	Appl/Startup/JStartup/${jedif}jstartup${ec}.geo 
	Appl/Games/Solitaire/${jxip}soli${ec}.geo 
	Appl/Jedi/ApptBk/apptbk${ec}.geo 
	Appl/Jedi/DM/dm${ec}.geo 
	Appl/Jedi/Phone/phone${ec}.geo 
	Appl/Jedi/JApp/japp${ec}.geo 
	Appl/Jedi/Notepad/notepad${ec}.geo 
	Library/CardID/cardid${ec}.geo 
	Library/Compress/compress${ec}.geo 
	Driver/PCMCIA/CID/CIDFS/cidfs${ec}.geo 
	Driver/PCMCIA/CID/CIDSer/cidser${ec}.geo 
	Driver/Stream/Filestr/filestr${ec}.geo 
	Driver/Video/Dumb/VidMem/vidmem${ec}.geo 
	Driver/Video/Dumb/Jedi/jvideo${ec}.geo 
	Driver/Printer/DotMatrix/Canon48/JEDI/canon48j${ec}.geo 
	Driver/Printer/DotMatrix/Epson24/JEDI/epson24j${ec}.geo 
	Driver/Printer/DotMatrix/Propx24/JEDI/propx24j${ec}.geo 
	Driver/Printer/HP/Deskjet/JEDI/deskjetj${ec}.geo 
	Driver/Printer/HP/Pcl4/JEDI/pcl4j${ec}.geo 
	Library/Game/game${ec}.geo 
	Library/StreamC/streamc${ec}.geo 
	Appl/Jedi/PQ/INTERNATIONAL/pq${ec}.geo
	Appl/Jedi/ClipGo/clipgo${ec}.geo
	${worldtime} 
	${mtable} 
	${math} 
	${serial} 
	${gfs} 
	${netware} 
	${loader} 
	${jpen} 
	${jpower} 
	${soundD} 
	${ucD} 
	${pcOnlyList} 
	${kbd}"
fi

exit 0
