#!/bin/sh -
#########################################################################
#				convert					#
# Convert script for GeoFile 						#
# Run this to create the mkrXXX.goh files for GeoFile 			#
# 									#
# $Id: convert,v 1.1 93/09/03 00:12:18 joon Exp $	#
#########################################################################
if [ -f driveicon.sed ]; then
    di_sed=driveicon.sed
else
    di_sed=`otherdir`/driveicon.sed
fi
#
# Convert a pcx file to a moniker, dealing with locating the installed or
# uninstalled version of the file (doesn't deal with branches, I'm afraid)
#
# Usage: cvt <file> <cvtpcx-args>
#
cvt() {
    file=$1
    shift
    if [ ! -f $file ]; then
	file=`otherdir`/$file
    fi
    /usr/public/cvtpcx -G -f "$@" $file
}

#
# Similar to the above, but the pcx file is cvted to a bitmap, rather
# than a gstring moniker. Must be given a -n<name> argument to pass to cvtpcx,
# and result is left in bm<name>.goh, instead of mkr<name>.goh
#
cvtbm() {
    name=""
    for a do
	case $a in
	    -n*)	name=`expr x$a : 'x-n\(.*\)$'` ;;
	esac
    done
    if [ ! "$name" ]; then
	echo $0: missing -n arg for cvtbm
	exit 1
    fi
    cvt "$@" -g
    sed -e 's/Moniker =/Bitmap =/' mkr$name.goh > bm$name.goh
    rm -f mkr$name.goh
}


#########################################################################
#			Application Icons				#
#########################################################################

#-----------------------  Generic DOS App Icon  ------------------------#
#cvt PCX/garrows.pcx -rAppIconArea -t -x0 -y0 -dLC -dLM -dLCGA  -nGarrows
cvt PCX/garrows.pcx -m13 -w21 -h21 -x1 -y1 -nRightArrowSC
cvt PCX/garrows.pcx -b -m13 -w21 -h21 -x23 -y1 -nRightArrowSM
cvt PCX/garrows.pcx -b -averySquished -m13 -w21 -h15 -x45 -y1 -nRightArrowSCGA
cvt PCX/garrows.pcx -m13 -w21 -h21 -x1 -y23 -nLeftArrowSC
cvt PCX/garrows.pcx -b -m13 -w21 -h21 -x23 -y23 -nLeftArrowSM
cvt PCX/garrows.pcx -b -averySquished -m13 -w21 -h15 -x45 -y23 -nLeftArrowSCGA

cvt PCX/23x17.pcx -m13 -w23 -h17 -x1 -y1 -nAscendingSortSC
cvt PCX/23x17.pcx -b -m13 -w23 -h17 -x25 -y1 -nAscendingSortSM
cvt PCX/23x17.pcx -b -averySquished -m13 -w23 -h13 -x49 -y1 -nAscendingSortSCGA
cvt PCX/23x17.pcx -m13 -w23 -h17 -x1 -y19 -nDescendingSortSC
cvt PCX/23x17.pcx -b -m13 -w23 -h17 -x25 -y19 -nDescendingSortSM
cvt PCX/23x17.pcx -b -averySquished -m13 -w23 -h13 -x49 -y19 -nDescendingSortSCGA

cvt PCX/23x17.pcx -m13 -w23 -h17 -x1 -y144 -nFNOBIncPrioritySC
cvt PCX/23x17.pcx -b -m13 -w23 -h17 -x25 -y144 -nFNOBIncPrioritySM
cvt PCX/23x17.pcx -b -averySquished -m13 -w23 -h13 -x49 -y144 -nFNOBIncPrioritySCGA
cvt PCX/23x17.pcx -m13 -w23 -h17 -x1 -y126 -nFNOBDecPrioritySC
cvt PCX/23x17.pcx -b -m13 -w23 -h17 -x25 -y126 -nFNOBDecPrioritySM
cvt PCX/23x17.pcx -b -averySquished -m13 -w23 -h13 -x49 -y126 -nFNOBDecPrioritySCGA

cvt PCX/23x17.pcx -m13 -w23 -h17 -x1 -y144 -nIncPrioritySC
cvt PCX/23x17.pcx -b -m13 -w23 -h17 -x25 -y144 -nIncPrioritySM
cvt PCX/23x17.pcx -b -averySquished -m13 -w23 -h13 -x49 -y144 -nIncPrioritySCGA
cvt PCX/23x17.pcx -m13 -w23 -h17 -x1 -y126 -nDecPrioritySC
cvt PCX/23x17.pcx -b -m13 -w23 -h17 -x25 -y126 -nDecPrioritySM
cvt PCX/23x17.pcx -b -averySquished -m13 -w23 -h13 -x49 -y126 -nDecPrioritySCGA

cvt PCX/arws4jm.pcx -m13 -l -x0 -y0 -dLC -dLM -dLCGA -nSortOrderArrows
cvt PCX/trchgrid.pcx -m13 -l -x0 -y0 -dLC -dLM -dLCGA -nTreasureChest
cvt PCX/f-n-p-l.pcx -m13 -z -x0 -y0 -nPreviousRecord
cvt PCX/f-n-p-l.pcx -m13 -z -x0 -y16 -nNextRecord
cvt PCX/f-n-p-l.pcx -m13 -z -x0 -y32 -nFirstRecord
cvt PCX/f-n-p-l.pcx -m13 -z -x0 -y48 -nLastRecord
cvt PCX/navdir.pcx -m13 -w41 -h30 -x0 -y0 -nRecordNavigationLRSC
cvt PCX/navdir.pcx -b -m13 -w41 -h30 -x40 -y0 -nRecordNavigationLRSM
cvt PCX/navdir.pcx -b -averySquished -m13 -w41 -h24 -x80 -y0 -nRecordNavigationLRSCGA
cvt PCX/navdir.pcx -m13 -w41 -h30 -x0 -y29 -nRecordNavigationTBSC
cvt PCX/navdir.pcx -b -m13 -w41 -h30 -x40 -y29 -nRecordNavigationTBSM
cvt PCX/navdir.pcx -b -averySquished -m13 -w41 -h24 -x80 -y29 -nRecordNavigationTBSCGA

. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps1.pcx 6 GeoFile -G $appArgs
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps1.pcx 7 GeoFileDoc -G $docArgs

