#!/bin/sh -
#
#
# Project:	PC GEOS
# Module:	Sokoban
# File:		convert
#
# Author:	brianc
#
#	This file contains the convert information for this application.
#
# 	$Id: convert,v 1.1.5.1 97/03/29 10:02:28 canavese Exp $
#
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile gsoko.pcx 0 Sokoban $appArgs
cvtfile gsoko.pcx 1 SokobanDoc $appArgs

