#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = safbuild
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = safbuildUtils.goc safbuildUI.goc safbuildApp.goc\
                  safbuildQuestion.goc safbuildDoc.goc safbuildGame.goc\
                  safbuildQuiz.goc safbuildVerify.goc GBicons.goh\
                  global.goh safbuild.goh
OBJS            = safbuildUtils.obj safbuildUI.obj safbuildApp.obj\
                  safbuildQuestion.obj safbuildDoc.obj safbuildGame.obj\
                  safbuildQuiz.obj safbuildVerify.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
