rem All Rem'd so I don't accidentally regenerate ;-)


rem cvtpcx -2 -w53 -h44 -m1 -G -nQTShoot -oQTShoot.goh hint1.pcx
rem cvtpcx -2 -w25 -h25 -m1 -G -nQTMark -oQTMark.goh hint2.pcx
rem cvtpcx -2 -w100 -h50 -m1 -G -nQTLevel -oQTLevel.goh hint3.pcx

rem cvtpcx -2 -w48 -h30 -m1 -G -nQTip1 -oQTip1.goh Tip1.pcx
rem cvtpcx -2 -w48 -h30 -m1 -G -nQTip2 -oQTip2.goh Tip2.pcx
rem cvtpcx -2 -w48 -h30 -m1 -G -nQTip3 -oQTip3.goh Tip3.pcx

