rem All Rem'd so I don't accidentally regenerate ;-)


rem cvtpcx -2 -w53 -h44 -m1 -G -nQTShoot -oqTShoot.goh hint1.pcx
rem cvtpcx -2 -w25 -h25 -m1 -G -nQTMark -oqTMark.goh hint2.pcx
rem cvtpcx -2 -w100 -h50 -m1 -G -nQTLevel -oqTLevel.goh hint3.pcx

rem cvtpcx -2 -w48 -h30 -m1 -G -nQTip1 -oqTip1.goh tip1.pcx
rem cvtpcx -2 -w48 -h30 -m1 -G -nQTip2 -oqTip2.goh tip2.pcx
rem cvtpcx -2 -w48 -h30 -m1 -G -nQTip3 -oqTip3.goh tip3.pcx

