#!/bin/sh -
#
#
# Project:	PC GEOS
# Module:	Calendar
# File:		convert
#
# Author:	andrew
#
#	This file contains the user Interface description for this
# appilication.
#
# 	$Id: convert,v 1.12 98/04/28 11:20:42 joon Exp $
#
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps2.pcx 4 GeoPlanner $appArgs
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps2.pcx 5 GeoPlannerDoc $docArgs

cvtpcx -f -m13 -t -z -nGeoPlannerTiny newplanner.tiny.pcx

############################## RESPONDER ART #############################

#
# Calendar Application Icon (Responder Only)
#
cvtpcx -N -2 -f -t -x0 -y0 -w64 -h50 -nCalendarIcon caleapp.pcx

#
# To-do list title icon (Responder Only)
#
cvtpcx -N -2 -f -g -t -x0 -y0 -w32 -h20 -nToDoTitle to-doti.pcx

#
# Notes in calendar small icon (Responder Only)
#
cvtpcx -N -2 -f -g -t -x0 -y0 -w11 -h13 -m11 -nNotesIcon notesi.pcx

#
# To-do list high priority icon (need two) (Responder Only)
#
cvtpcx -N -2 -f -g -t -x0 -y0 -w11 -h13 -nHighPriority highsi.pcx
cvtpcx -N -2 -f -g -t -x0 -y0 -w11 -h13 -nHighPriority2 highsi.pcx

#
# To-do list completed icon (need two) (Responder Only)
#
cvtpcx -N -2 -f -g -t -x0 -y0 -w11 -h13 -nCompletedIcon complsi.pcx
cvtpcx -N -2 -f -g -t -x0 -y0 -w11 -h13 -nCompletedIcon2 complsi.pcx

#
# Repeated event icon (Responder Only)
#
cvtpcx -N -2 -f -g -t -x0 -y0 -w11 -h13 -nRepeatIcon repeasi.pcx

#
# Alarm bitmaps 1) small event icon 2) big dialog icon (Responder Only)
#
cvtpcx -N -2 -f -g -t -x0 -y0 -w11 -h13 -nAlarmIcon alarmsi.pcx
cvtpcx -N -2 -f -g -t -x0 -y0 -w35 -h35 -nAlarmDialog alarmti2.pcx

#
# Anniversary event icon (Responder Only)
#
cvtpcx -N -2 -f -g -t -x0 -y0 -w11 -h13 -nAnniversaryIcon annisi.pcx

#
# Icon for annual repeating event in day view (Responder/Lizzy only)
#
cvtpcx -N -2 -f -g -t -x0 -y0 -w13 -h15 -nAnnualEventIcon calanev.pcx

#
# Icon dash in front of an untimed event in calendar day view
# (Responder/Lizzy only)
#
cvtpcx -B -2 -f -g -t -x0 -y0 -w13 -h6 -nUntimedEventIcon untimeev.pcx

#
# Icon for sent event in Calnedar day view (Responder/Lizzy only)
#
cvtpcx -N -2 -f -g -t -x0 -y0 -w21 -h13 -nSentEventIcon sentevli.pcx

#
# Icon for daily, weekly or monthly repeating event (Responder/Lizzy only)
#
cvtpcx -N -2 -f -g -t -x0 -y0 -w13 -h15 -nRepeatEventIcon calreev.pcx

#
# Frame to indicate "today" in calendar month view (Responder/Lizzy only)
#
cvtpcx -N -2 -f -g -t -x0 -y0 -w32 -h20 -m11 -nMonthViewTodayFrame todaydv.pcx

#
# Frame to indicate "today" in calendar week view (Responder/Lizzy
# only)
#
cvtpcx -N -2 -f -g -t -x0 -y0 -w47 -h47 -nWeekViewTodayFrame todaywv.pcx

#
# Icon for calendar reservations and requests (Responder/Lizzy only)
# 
cvtpcx -N -2 -f -g -t -x0 -y0 -w32 -h20 -nSMSCardIcon smscard.pcx
