#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = hsttcpip
ASM_TO_OBJS     = hsttcpipManager.asm
UI_TO_RDFS      = tcpipStrings.ui tcpipAddrCtrl.ui
SRCS            = hsttcpipManager.asm tcpipAddrCtrl.asm tcpipEntry.asm\
                  tcpip.def tcpipAddrCtrl.def tcpipGlobal.def\
                  tcpipAddrCtrl.ui tcpipStrings.ui tcpip.goc
OBJS            = hsttcpipManager.obj tcpip.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
