#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = spooltd
ASM_TO_OBJS     = spooltdManager.asm
UI_TO_RDFS      = spooltd.ui
SRCS            = spooltdTransmit.asm spooltdMedium.asm spooltdMisc.asm\
                  spooltdManager.asm spooltdAddress.asm spooltdEntry.asm\
                  spooltdConstant.def spooltdVariable.def spooltd.ui
OBJS            = spooltdManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
