#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = idialup
ASM_TO_OBJS     = IDialppp.asm
UI_TO_RDFS      =
SRCS            = IDialppp.asm IDialppp.def IDialppp.h IDialup.goc\
                  IDialapp.goc IDInfo.goc IDialUI.goc IDialUI.goh\
                  IDialup.goh
OBJS            = IDialppp.obj IDialup.obj IDialapp.obj IDInfo.obj\
                  IDialUI.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
