#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = vga15
ASM_TO_OBJS     = vga15Manager.asm
UI_TO_RDFS      =
SRCS            = vga15Admin.asm vga15Chars.asm vga15DevInfo.asm\
                  vga15Dither.asm vga15EscTab.asm vga15GenChar.asm\
                  vga15Manager.asm vga15Output.asm vga15Palette.asm\
                  vga15Pointer.asm vga15Raster.asm vga15StringTab.asm\
                  vga15Table.asm vga15Under.asm vga15Utils.asm\
                  vidcomTables.asm vidcomEntry.asm vidcomOutput.asm\
                  vidcomChars.asm vidcomFont.asm vidcomUtils.asm\
                  vidcomRegion.asm vidcomXOR.asm vidcomInfo.asm\
                  vidcomEscape.asm vidcomPalette.asm vidcomPolygon.asm\
                  vidcomLine.asm vidcomPutLine.asm vidcomRaster.asm\
                  vidcomExclBounds.asm vga15Constant.def vga15Macro.def\
                  vga15Variable.def
OBJS            = vga15Manager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
