#!/bin/sh
#
#	Conversion script for the Zoomer default deck
#
#
#	Revision History:
#
#	Name	Date		Description
#	----	----		-----------
#	jon	9 nov 1992	initial revision
#
#	$Id: convert,v 1.3.10.1 97/03/29 08:30:26 canavese Exp $
#

echo
echo ------------------------
echo Converting Spades
echo ------------------------

cvtpcx -2 -b -g -m13 -x0 -y0 -w71 -h100 -nLCSpadeA gspades1.pcx
echo "LCSpadeA	label	byte" >LCSpadeA.asm
echo "word	C_BLACK" >>LCSpadeA.asm
tail -r mkrLCSpadeA.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCSpadeA.asm
rm mkrLCSpadeA.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMSpadeA gspades1.pcx
echo "LMSpadeA	label	byte" >LMSpadeA.asm
echo "word	C_BLACK" >>LMSpadeA.asm
tail -r mkrLMSpadeA.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMSpadeA.asm
rm mkrLMSpadeA.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGASpadeA gspades1.pcx
echo "CGASpadeA	label	byte" >CGASpadeA.asm
echo "word	C_BLACK" >>CGASpadeA.asm
tail -r mkrCGASpadeA.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGASpadeA.asm
rm mkrCGASpadeA.ui

cvtpcx -2 -b -g -m13 -x0 -y99 -w71 -h100 -nLCSpade2 gspades1.pcx
echo "LCSpade2	label	byte" >LCSpade2.asm
echo "word	C_BLACK" >>LCSpade2.asm
tail -r mkrLCSpade2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCSpade2.asm
rm mkrLCSpade2.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMSpade2 gspades1.pcx
echo "LMSpade2	label	byte" >LMSpade2.asm
echo "word	C_BLACK" >>LMSpade2.asm
tail -r mkrLMSpade2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMSpade2.asm
rm mkrLMSpade2.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGASpade2 gspades1.pcx
echo "CGASpade2	label	byte" >CGASpade2.asm
echo "word	C_BLACK" >>CGASpade2.asm
tail -r mkrCGASpade2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGASpade2.asm
rm mkrCGASpade2.ui

cvtpcx -2 -b -g -m13 -x0 -y198 -w71 -h100 -nLCSpade3 gspades1.pcx
echo "LCSpade3	label	byte" >LCSpade3.asm
echo "word	C_BLACK" >>LCSpade3.asm
tail -r mkrLCSpade3.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCSpade3.asm
rm mkrLCSpade3.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMSpade3 gspades1.pcx
echo "LMSpade3	label	byte" >LMSpade3.asm
echo "word	C_BLACK" >>LMSpade3.asm
tail -r mkrLMSpade3.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMSpade3.asm
rm mkrLMSpade3.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGASpade3 gspades1.pcx
echo "CGASpade3	label	byte" >CGASpade3.asm
echo "word	C_BLACK" >>CGASpade3.asm
tail -r mkrCGASpade3.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGASpade3.asm
rm mkrCGASpade3.ui

cvtpcx -2 -b -g -m13 -x0 -y297 -w71 -h100 -nLCSpade4 gspades1.pcx
echo "LCSpade4	label	byte" >LCSpade4.asm
echo "word	C_BLACK" >>LCSpade4.asm
tail -r mkrLCSpade4.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCSpade4.asm
rm mkrLCSpade4.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMSpade4 gspades1.pcx
echo "LMSpade4	label	byte" >LMSpade4.asm
echo "word	C_BLACK" >>LMSpade4.asm
tail -r mkrLMSpade4.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMSpade4.asm
rm mkrLMSpade4.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGASpade4 gspades1.pcx
echo "CGASpade4	label	byte" >CGASpade4.asm
echo "word	C_BLACK" >>CGASpade4.asm
tail -r mkrCGASpade4.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGASpade4.asm
rm mkrCGASpade4.ui

cvtpcx -2 -b -g -m13 -x0 -y0 -w71 -h100 -nLCSpade5 gspades2.pcx
echo "LCSpade5	label	byte" >LCSpade5.asm
echo "word	C_BLACK" >>LCSpade5.asm
tail -r mkrLCSpade5.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCSpade5.asm
rm mkrLCSpade5.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMSpade5 gspades2.pcx
echo "LMSpade5	label	byte" >LMSpade5.asm
echo "word	C_BLACK" >>LMSpade5.asm
tail -r mkrLMSpade5.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMSpade5.asm
rm mkrLMSpade5.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGASpade5 gspades2.pcx
echo "CGASpade5	label	byte" >CGASpade5.asm
echo "word	C_BLACK" >>CGASpade5.asm
tail -r mkrCGASpade5.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGASpade5.asm
rm mkrCGASpade5.ui

cvtpcx -2 -b -g -m13 -x0 -y99 -w71 -h100 -nLCSpade6 gspades2.pcx
echo "LCSpade6	label	byte" >LCSpade6.asm
echo "word	C_BLACK" >>LCSpade6.asm
tail -r mkrLCSpade6.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCSpade6.asm
rm mkrLCSpade6.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMSpade6 gspades2.pcx
echo "LMSpade6	label	byte" >LMSpade6.asm
echo "word	C_BLACK" >>LMSpade6.asm
tail -r mkrLMSpade6.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMSpade6.asm
rm mkrLMSpade6.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGASpade6 gspades2.pcx
echo "CGASpade6	label	byte" >CGASpade6.asm
echo "word	C_BLACK" >>CGASpade6.asm
tail -r mkrCGASpade6.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGASpade6.asm
rm mkrCGASpade6.ui

cvtpcx -2 -b -g -m13 -x0 -y198 -w71 -h100 -nLCSpade7 gspades2.pcx
echo "LCSpade7	label	byte" >LCSpade7.asm
echo "word	C_BLACK" >>LCSpade7.asm
tail -r mkrLCSpade7.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCSpade7.asm
rm mkrLCSpade7.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMSpade7 gspades2.pcx
echo "LMSpade7	label	byte" >LMSpade7.asm
echo "word	C_BLACK" >>LMSpade7.asm
tail -r mkrLMSpade7.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMSpade7.asm
rm mkrLMSpade7.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGASpade7 gspades2.pcx
echo "CGASpade7	label	byte" >CGASpade7.asm
echo "word	C_BLACK" >>CGASpade7.asm
tail -r mkrCGASpade7.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGASpade7.asm
rm mkrCGASpade7.ui

cvtpcx -2 -b -g -m13 -x0 -y297 -w71 -h100 -nLCSpade8 gspades2.pcx
echo "LCSpade8	label	byte" >LCSpade8.asm
echo "word	C_BLACK" >>LCSpade8.asm
tail -r mkrLCSpade8.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCSpade8.asm
rm mkrLCSpade8.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMSpade8 gspades2.pcx
echo "LMSpade8	label	byte" >LMSpade8.asm
echo "word	C_BLACK" >>LMSpade8.asm
tail -r mkrLMSpade8.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMSpade8.asm
rm mkrLMSpade8.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGASpade8 gspades2.pcx
echo "CGASpade8	label	byte" >CGASpade8.asm
echo "word	C_BLACK" >>CGASpade8.asm
tail -r mkrCGASpade8.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGASpade8.asm
rm mkrCGASpade8.ui

cvtpcx -2 -b -g -m13 -x0 -y0 -w71 -h100 -nLCSpade9 gspades3.pcx
echo "LCSpade9	label	byte" >LCSpade9.asm
echo "word	C_BLACK" >>LCSpade9.asm
tail -r mkrLCSpade9.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCSpade9.asm
rm mkrLCSpade9.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMSpade9 gspades3.pcx
echo "LMSpade9	label	byte" >LMSpade9.asm
echo "word	C_BLACK" >>LMSpade9.asm
tail -r mkrLMSpade9.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMSpade9.asm
rm mkrLMSpade9.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGASpade9 gspades3.pcx
echo "CGASpade9	label	byte" >CGASpade9.asm
echo "word	C_BLACK" >>CGASpade9.asm
tail -r mkrCGASpade9.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGASpade9.asm
rm mkrCGASpade9.ui

cvtpcx -2 -b -g -m13 -x0 -y99 -w71 -h100 -nLCSpadeT gspades3.pcx
echo "LCSpadeT	label	byte" >LCSpadeT.asm
echo "word	C_BLACK" >>LCSpadeT.asm
tail -r mkrLCSpadeT.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCSpadeT.asm
rm mkrLCSpadeT.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMSpadeT gspades3.pcx
echo "LMSpadeT	label	byte" >LMSpadeT.asm
echo "word	C_BLACK" >>LMSpadeT.asm
tail -r mkrLMSpadeT.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMSpadeT.asm
rm mkrLMSpadeT.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGASpadeT gspades3.pcx
echo "CGASpadeT	label	byte" >CGASpadeT.asm
echo "word	C_BLACK" >>CGASpadeT.asm
tail -r mkrCGASpadeT.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGASpadeT.asm
rm mkrCGASpadeT.ui

cvtpcx -2 -g -m13 -x0 -y198 -w71 -h100 -nLCSpadeJ gspades3.pcx
echo "LCSpadeJ	label	byte" >LCSpadeJ.asm
echo "word	C_BLACK" >>LCSpadeJ.asm
tail -r mkrLCSpadeJ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCSpadeJ.asm
rm mkrLCSpadeJ.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMSpadeJ gspades3.pcx
echo "LMSpadeJ	label	byte" >LMSpadeJ.asm
echo "word	C_BLACK" >>LMSpadeJ.asm
tail -r mkrLMSpadeJ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMSpadeJ.asm
rm mkrLMSpadeJ.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGASpadeJ gspades3.pcx
echo "CGASpadeJ	label	byte" >CGASpadeJ.asm
echo "word	C_BLACK" >>CGASpadeJ.asm
tail -r mkrCGASpadeJ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGASpadeJ.asm
rm mkrCGASpadeJ.ui

cvtpcx -2 -g -m13 -x0 -y297 -w71 -h100 -nLCSpadeQ gspades3.pcx
echo "LCSpadeQ	label	byte" >LCSpadeQ.asm
echo "word	C_BLACK" >>LCSpadeQ.asm
tail -r mkrLCSpadeQ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCSpadeQ.asm
rm mkrLCSpadeQ.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMSpadeQ gspades3.pcx
echo "LMSpadeQ	label	byte" >LMSpadeQ.asm
echo "word	C_BLACK" >>LMSpadeQ.asm
tail -r mkrLMSpadeQ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMSpadeQ.asm
rm mkrLMSpadeQ.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGASpadeQ gspades3.pcx
echo "CGASpadeQ	label	byte" >CGASpadeQ.asm
echo "word	C_BLACK" >>CGASpadeQ.asm
tail -r mkrCGASpadeQ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGASpadeQ.asm
rm mkrCGASpadeQ.ui

cvtpcx -2 -g -m13 -x0 -y297 -w71 -h100 -nLCSpadeK gkings.pcx
echo "LCSpadeK	label	byte" >LCSpadeK.asm
echo "word	C_BLACK" >>LCSpadeK.asm
tail -r mkrLCSpadeK.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCSpadeK.asm
rm mkrLCSpadeK.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMSpadeK gkings.pcx
echo "LMSpadeK	label	byte" >LMSpadeK.asm
echo "word	C_BLACK" >>LMSpadeK.asm
tail -r mkrLMSpadeK.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMSpadeK.asm
rm mkrLMSpadeK.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGASpadeK gkings.pcx
echo "CGASpadeK	label	byte" >CGASpadeK.asm
echo "word	C_BLACK" >>CGASpadeK.asm
tail -r mkrCGASpadeK.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGASpadeK.asm
rm mkrCGASpadeK.ui

echo
echo ------------------------
echo Converting Clubs
echo ------------------------

cvtpcx -2 -b -g -m13 -x0 -y0 -w71 -h100 -nLCClubA gclubs1.pcx
echo "LCClubA	label	byte" >LCClubA.asm
echo "word	C_BLACK" >>LCClubA.asm
tail -r mkrLCClubA.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClubA.asm
rm mkrLCClubA.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMClubA gclubs1.pcx
echo "LMClubA	label	byte" >LMClubA.asm
echo "word	C_BLACK" >>LMClubA.asm
tail -r mkrLMClubA.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClubA.asm
rm mkrLMClubA.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGAClubA gclubs1.pcx
echo "CGAClubA	label	byte" >CGAClubA.asm
echo "word	C_BLACK" >>CGAClubA.asm
tail -r mkrCGAClubA.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClubA.asm
rm mkrCGAClubA.ui

cvtpcx -2 -b -g -m13 -x0 -y99 -w71 -h100 -nLCClub2 gclubs1.pcx
echo "LCClub2	label	byte" >LCClub2.asm
echo "word	C_BLACK" >>LCClub2.asm
tail -r mkrLCClub2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClub2.asm
rm mkrLCClub2.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMClub2 gclubs1.pcx
echo "LMClub2	label	byte" >LMClub2.asm
echo "word	C_BLACK" >>LMClub2.asm
tail -r mkrLMClub2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClub2.asm
rm mkrLMClub2.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGAClub2 gclubs1.pcx
echo "CGAClub2	label	byte" >CGAClub2.asm
echo "word	C_BLACK" >>CGAClub2.asm
tail -r mkrCGAClub2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClub2.asm
rm mkrCGAClub2.ui

cvtpcx -2 -b -g -m13 -x0 -y198 -w71 -h100 -nLCClub3 gclubs1.pcx
echo "LCClub3	label	byte" >LCClub3.asm
echo "word	C_BLACK" >>LCClub3.asm
tail -r mkrLCClub3.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClub3.asm
rm mkrLCClub3.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMClub3 gclubs1.pcx
echo "LMClub3	label	byte" >LMClub3.asm
echo "word	C_BLACK" >>LMClub3.asm
tail -r mkrLMClub3.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClub3.asm
rm mkrLMClub3.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGAClub3 gclubs1.pcx
echo "CGAClub3	label	byte" >CGAClub3.asm
echo "word	C_BLACK" >>CGAClub3.asm
tail -r mkrCGAClub3.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClub3.asm
rm mkrCGAClub3.ui

cvtpcx -2 -b -g -m13 -x0 -y297 -w71 -h100 -nLCClub4 gclubs1.pcx
echo "LCClub4	label	byte" >LCClub4.asm
echo "word	C_BLACK" >>LCClub4.asm
tail -r mkrLCClub4.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClub4.asm
rm mkrLCClub4.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMClub4 gclubs1.pcx
echo "LMClub4	label	byte" >LMClub4.asm
echo "word	C_BLACK" >>LMClub4.asm
tail -r mkrLMClub4.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClub4.asm
rm mkrLMClub4.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGAClub4 gclubs1.pcx
echo "CGAClub4	label	byte" >CGAClub4.asm
echo "word	C_BLACK" >>CGAClub4.asm
tail -r mkrCGAClub4.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClub4.asm
rm mkrCGAClub4.ui

cvtpcx -2 -b -g -m13 -x0 -y0 -w71 -h100 -nLCClub5 gclubs2.pcx
echo "LCClub5	label	byte" >LCClub5.asm
echo "word	C_BLACK" >>LCClub5.asm
tail -r mkrLCClub5.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClub5.asm
rm mkrLCClub5.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMClub5 gclubs2.pcx
echo "LMClub5	label	byte" >LMClub5.asm
echo "word	C_BLACK" >>LMClub5.asm
tail -r mkrLMClub5.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClub5.asm
rm mkrLMClub5.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGAClub5 gclubs2.pcx
echo "CGAClub5	label	byte" >CGAClub5.asm
echo "word	C_BLACK" >>CGAClub5.asm
tail -r mkrCGAClub5.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClub5.asm
rm mkrCGAClub5.ui

cvtpcx -2 -b -g -m13 -x0 -y99 -w71 -h100 -nLCClub6 gclubs2.pcx
echo "LCClub6	label	byte" >LCClub6.asm
echo "word	C_BLACK" >>LCClub6.asm
tail -r mkrLCClub6.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClub6.asm
rm mkrLCClub6.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMClub6 gclubs2.pcx
echo "LMClub6	label	byte" >LMClub6.asm
echo "word	C_BLACK" >>LMClub6.asm
tail -r mkrLMClub6.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClub6.asm
rm mkrLMClub6.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGAClub6 gclubs2.pcx
echo "CGAClub6	label	byte" >CGAClub6.asm
echo "word	C_BLACK" >>CGAClub6.asm
tail -r mkrCGAClub6.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClub6.asm
rm mkrCGAClub6.ui

cvtpcx -2 -b -g -m13 -x0 -y198 -w71 -h100 -nLCClub7 gclubs2.pcx
echo "LCClub7	label	byte" >LCClub7.asm
echo "word	C_BLACK" >>LCClub7.asm
tail -r mkrLCClub7.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClub7.asm
rm mkrLCClub7.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMClub7 gclubs2.pcx
echo "LMClub7	label	byte" >LMClub7.asm
echo "word	C_BLACK" >>LMClub7.asm
tail -r mkrLMClub7.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClub7.asm
rm mkrLMClub7.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGAClub7 gclubs2.pcx
echo "CGAClub7	label	byte" >CGAClub7.asm
echo "word	C_BLACK" >>CGAClub7.asm
tail -r mkrCGAClub7.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClub7.asm
rm mkrCGAClub7.ui

cvtpcx -2 -b -g -m13 -x0 -y297 -w71 -h100 -nLCClub8 gclubs2.pcx
echo "LCClub8	label	byte" >LCClub8.asm
echo "word	C_BLACK" >>LCClub8.asm
tail -r mkrLCClub8.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClub8.asm
rm mkrLCClub8.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMClub8 gclubs2.pcx
echo "LMClub8	label	byte" >LMClub8.asm
echo "word	C_BLACK" >>LMClub8.asm
tail -r mkrLMClub8.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClub8.asm
rm mkrLMClub8.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGAClub8 gclubs2.pcx
echo "CGAClub8	label	byte" >CGAClub8.asm
echo "word	C_BLACK" >>CGAClub8.asm
tail -r mkrCGAClub8.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClub8.asm
rm mkrCGAClub8.ui

cvtpcx -2 -b -g -m13 -x0 -y0 -w71 -h100 -nLCClub9 gclubs3.pcx
echo "LCClub9	label	byte" >LCClub9.asm
echo "word	C_BLACK" >>LCClub9.asm
tail -r mkrLCClub9.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClub9.asm
rm mkrLCClub9.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMClub9 gclubs3.pcx
echo "LMClub9	label	byte" >LMClub9.asm
echo "word	C_BLACK" >>LMClub9.asm
tail -r mkrLMClub9.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClub9.asm
rm mkrLMClub9.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGAClub9 gclubs3.pcx
echo "CGAClub9	label	byte" >CGAClub9.asm
echo "word	C_BLACK" >>CGAClub9.asm
tail -r mkrCGAClub9.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClub9.asm
rm mkrCGAClub9.ui

cvtpcx -2 -b -g -m13 -x0 -y99 -w71 -h100 -nLCClubT gclubs3.pcx
echo "LCClubT	label	byte" >LCClubT.asm
echo "word	C_BLACK" >>LCClubT.asm
tail -r mkrLCClubT.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClubT.asm
rm mkrLCClubT.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMClubT gclubs3.pcx
echo "LMClubT	label	byte" >LMClubT.asm
echo "word	C_BLACK" >>LMClubT.asm
tail -r mkrLMClubT.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClubT.asm
rm mkrLMClubT.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGAClubT gclubs3.pcx
echo "CGAClubT	label	byte" >CGAClubT.asm
echo "word	C_BLACK" >>CGAClubT.asm
tail -r mkrCGAClubT.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClubT.asm
rm mkrCGAClubT.ui

cvtpcx -2 -g -m13 -x0 -y198 -w71 -h100 -nLCClubJ gclubs3.pcx
echo "LCClubJ	label	byte" >LCClubJ.asm
echo "word	C_BLACK" >>LCClubJ.asm
tail -r mkrLCClubJ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClubJ.asm
rm mkrLCClubJ.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMClubJ gclubs3.pcx
echo "LMClubJ	label	byte" >LMClubJ.asm
echo "word	C_BLACK" >>LMClubJ.asm
tail -r mkrLMClubJ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClubJ.asm
rm mkrLMClubJ.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGAClubJ gclubs3.pcx
echo "CGAClubJ	label	byte" >CGAClubJ.asm
echo "word	C_BLACK" >>CGAClubJ.asm
tail -r mkrCGAClubJ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClubJ.asm
rm mkrCGAClubJ.ui

cvtpcx -2 -g -m13 -x0 -y297 -w71 -h100 -nLCClubQ gclubs3.pcx
echo "LCClubQ	label	byte" >LCClubQ.asm
echo "word	C_BLACK" >>LCClubQ.asm
tail -r mkrLCClubQ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClubQ.asm
rm mkrLCClubQ.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMClubQ gclubs3.pcx
echo "LMClubQ	label	byte" >LMClubQ.asm
echo "word	C_BLACK" >>LMClubQ.asm
tail -r mkrLMClubQ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClubQ.asm
rm mkrLMClubQ.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGAClubQ gclubs3.pcx
echo "CGAClubQ	label	byte" >CGAClubQ.asm
echo "word	C_BLACK" >>CGAClubQ.asm
tail -r mkrCGAClubQ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClubQ.asm
rm mkrCGAClubQ.ui

cvtpcx -2 -g -m13 -x0 -y0 -w71 -h100 -nLCClubK gkings.pcx
echo "LCClubK	label	byte" >LCClubK.asm
echo "word	C_BLACK" >>LCClubK.asm
tail -r mkrLCClubK.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClubK.asm
rm mkrLCClubK.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMClubK gkings.pcx
echo "LMClubK	label	byte" >LMClubK.asm
echo "word	C_BLACK" >>LMClubK.asm
tail -r mkrLMClubK.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClubK.asm
rm mkrLMClubK.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGAClubK gkings.pcx
echo "CGAClubK	label	byte" >CGAClubK.asm
echo "word	C_BLACK" >>CGAClubK.asm
tail -r mkrCGAClubK.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClubK.asm
rm mkrCGAClubK.ui

echo
echo ------------------------
echo Converting Hearts
echo ------------------------

cvtpcx -2 -b -g -m13 -x0 -y0 -w71 -h100 -nLCHeartA ghearts1.pcx
echo "LCHeartA	label	byte" >LCHeartA.asm
echo "word	C_LIGHT_RED" >>LCHeartA.asm
tail -r mkrLCHeartA.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHeartA.asm
rm mkrLCHeartA.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMHeartA ghearts1.pcx
echo "LMHeartA	label	byte" >LMHeartA.asm
echo "word	C_BLACK" >>LMHeartA.asm
tail -r mkrLMHeartA.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHeartA.asm
rm mkrLMHeartA.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGAHeartA ghearts1.pcx
echo "CGAHeartA	label	byte" >CGAHeartA.asm
echo "word	C_BLACK" >>CGAHeartA.asm
tail -r mkrCGAHeartA.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHeartA.asm
rm mkrCGAHeartA.ui

cvtpcx -2 -b -g -m13 -x0 -y99 -w71 -h100 -nLCHeart2 ghearts1.pcx
echo "LCHeart2	label	byte" >LCHeart2.asm
echo "word	C_LIGHT_RED" >>LCHeart2.asm
tail -r mkrLCHeart2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHeart2.asm
rm mkrLCHeart2.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMHeart2 ghearts1.pcx
echo "LMHeart2	label	byte" >LMHeart2.asm
echo "word	C_BLACK" >>LMHeart2.asm
tail -r mkrLMHeart2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHeart2.asm
rm mkrLMHeart2.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGAHeart2 ghearts1.pcx
echo "CGAHeart2	label	byte" >CGAHeart2.asm
echo "word	C_BLACK" >>CGAHeart2.asm
tail -r mkrCGAHeart2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHeart2.asm
rm mkrCGAHeart2.ui

cvtpcx -2 -b -g -m13 -x0 -y198 -w71 -h100 -nLCHeart3 ghearts1.pcx
echo "LCHeart3	label	byte" >LCHeart3.asm
echo "word	C_LIGHT_RED" >>LCHeart3.asm
tail -r mkrLCHeart3.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHeart3.asm
rm mkrLCHeart3.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMHeart3 ghearts1.pcx
echo "LMHeart3	label	byte" >LMHeart3.asm
echo "word	C_BLACK" >>LMHeart3.asm
tail -r mkrLMHeart3.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHeart3.asm
rm mkrLMHeart3.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGAHeart3 ghearts1.pcx
echo "CGAHeart3	label	byte" >CGAHeart3.asm
echo "word	C_BLACK" >>CGAHeart3.asm
tail -r mkrCGAHeart3.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHeart3.asm
rm mkrCGAHeart3.ui

cvtpcx -2 -b -g -m13 -x0 -y297 -w71 -h100 -nLCHeart4 ghearts1.pcx
echo "LCHeart4	label	byte" >LCHeart4.asm
echo "word	C_LIGHT_RED" >>LCHeart4.asm
tail -r mkrLCHeart4.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHeart4.asm
rm mkrLCHeart4.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMHeart4 ghearts1.pcx
echo "LMHeart4	label	byte" >LMHeart4.asm
echo "word	C_BLACK" >>LMHeart4.asm
tail -r mkrLMHeart4.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHeart4.asm
rm mkrLMHeart4.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGAHeart4 ghearts1.pcx
echo "CGAHeart4	label	byte" >CGAHeart4.asm
echo "word	C_BLACK" >>CGAHeart4.asm
tail -r mkrCGAHeart4.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHeart4.asm
rm mkrCGAHeart4.ui

cvtpcx -2 -b -g -m13 -x0 -y0 -w71 -h100 -nLCHeart5 ghearts2.pcx
echo "LCHeart5	label	byte" >LCHeart5.asm
echo "word	C_LIGHT_RED" >>LCHeart5.asm
tail -r mkrLCHeart5.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHeart5.asm
rm mkrLCHeart5.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMHeart5 ghearts2.pcx
echo "LMHeart5	label	byte" >LMHeart5.asm
echo "word	C_BLACK" >>LMHeart5.asm
tail -r mkrLMHeart5.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHeart5.asm
rm mkrLMHeart5.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGAHeart5 ghearts2.pcx
echo "CGAHeart5	label	byte" >CGAHeart5.asm
echo "word	C_BLACK" >>CGAHeart5.asm
tail -r mkrCGAHeart5.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHeart5.asm
rm mkrCGAHeart5.ui

cvtpcx -2 -b -g -m13 -x0 -y99 -w71 -h100 -nLCHeart6 ghearts2.pcx
echo "LCHeart6	label	byte" >LCHeart6.asm
echo "word	C_LIGHT_RED" >>LCHeart6.asm
tail -r mkrLCHeart6.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHeart6.asm
rm mkrLCHeart6.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMHeart6 ghearts2.pcx
echo "LMHeart6	label	byte" >LMHeart6.asm
echo "word	C_BLACK" >>LMHeart6.asm
tail -r mkrLMHeart6.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHeart6.asm
rm mkrLMHeart6.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGAHeart6 ghearts2.pcx
echo "CGAHeart6	label	byte" >CGAHeart6.asm
echo "word	C_BLACK" >>CGAHeart6.asm
tail -r mkrCGAHeart6.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHeart6.asm
rm mkrCGAHeart6.ui

cvtpcx -2 -b -g -m13 -x0 -y198 -w71 -h100 -nLCHeart7 ghearts2.pcx
echo "LCHeart7	label	byte" >LCHeart7.asm
echo "word	C_LIGHT_RED" >>LCHeart7.asm
tail -r mkrLCHeart7.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHeart7.asm
rm mkrLCHeart7.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMHeart7 ghearts2.pcx
echo "LMHeart7	label	byte" >LMHeart7.asm
echo "word	C_BLACK" >>LMHeart7.asm
tail -r mkrLMHeart7.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHeart7.asm
rm mkrLMHeart7.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGAHeart7 ghearts2.pcx
echo "CGAHeart7	label	byte" >CGAHeart7.asm
echo "word	C_BLACK" >>CGAHeart7.asm
tail -r mkrCGAHeart7.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHeart7.asm
rm mkrCGAHeart7.ui

cvtpcx -2 -b -g -m13 -x0 -y297 -w71 -h100 -nLCHeart8 ghearts2.pcx
echo "LCHeart8	label	byte" >LCHeart8.asm
echo "word	C_LIGHT_RED" >>LCHeart8.asm
tail -r mkrLCHeart8.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHeart8.asm
rm mkrLCHeart8.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMHeart8 ghearts2.pcx
echo "LMHeart8	label	byte" >LMHeart8.asm
echo "word	C_BLACK" >>LMHeart8.asm
tail -r mkrLMHeart8.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHeart8.asm
rm mkrLMHeart8.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGAHeart8 ghearts2.pcx
echo "CGAHeart8	label	byte" >CGAHeart8.asm
echo "word	C_BLACK" >>CGAHeart8.asm
tail -r mkrCGAHeart8.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHeart8.asm
rm mkrCGAHeart8.ui

cvtpcx -2 -b -g -m13 -x0 -y0 -w71 -h100 -nLCHeart9 ghearts3.pcx
echo "LCHeart9	label	byte" >LCHeart9.asm
echo "word	C_LIGHT_RED" >>LCHeart9.asm
tail -r mkrLCHeart9.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHeart9.asm
rm mkrLCHeart9.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMHeart9 ghearts3.pcx
echo "LMHeart9	label	byte" >LMHeart9.asm
echo "word	C_BLACK" >>LMHeart9.asm
tail -r mkrLMHeart9.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHeart9.asm
rm mkrLMHeart9.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGAHeart9 ghearts3.pcx
echo "CGAHeart9	label	byte" >CGAHeart9.asm
echo "word	C_BLACK" >>CGAHeart9.asm
tail -r mkrCGAHeart9.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHeart9.asm
rm mkrCGAHeart9.ui

cvtpcx -2 -b -g -m13 -x0 -y99 -w71 -h99 -nLCHeartT ghearts3.pcx
echo "LCHeartT	label	byte" >LCHeartT.asm
echo "word	C_LIGHT_RED" >>LCHeartT.asm
tail -r mkrLCHeartT.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHeartT.asm
rm mkrLCHeartT.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMHeartT ghearts3.pcx
echo "LMHeartT	label	byte" >LMHeartT.asm
echo "word	C_BLACK" >>LMHeartT.asm
tail -r mkrLMHeartT.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHeartT.asm
rm mkrLMHeartT.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGAHeartT ghearts3.pcx
echo "CGAHeartT	label	byte" >CGAHeartT.asm
echo "word	C_BLACK" >>CGAHeartT.asm
tail -r mkrCGAHeartT.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHeartT.asm
rm mkrCGAHeartT.ui

cvtpcx -2 -g -m13 -x0 -y198 -w71 -h100 -nLCHeartJ ghearts3.pcx
echo "LCHeartJ	label	byte" >LCHeartJ.asm
echo "word	C_BLACK" >>LCHeartJ.asm
tail -r mkrLCHeartJ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHeartJ.asm
rm mkrLCHeartJ.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMHeartJ ghearts3.pcx
echo "LMHeartJ	label	byte" >LMHeartJ.asm
echo "word	C_BLACK" >>LMHeartJ.asm
tail -r mkrLMHeartJ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHeartJ.asm
rm mkrLMHeartJ.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGAHeartJ ghearts3.pcx
echo "CGAHeartJ	label	byte" >CGAHeartJ.asm
echo "word	C_BLACK" >>CGAHeartJ.asm
tail -r mkrCGAHeartJ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHeartJ.asm
rm mkrCGAHeartJ.ui

cvtpcx -2 -g -m13 -x0 -y297 -w71 -h100 -nLCHeartQ ghearts3.pcx
echo "LCHeartQ	label	byte" >LCHeartQ.asm
echo "word	C_BLACK" >>LCHeartQ.asm
tail -r mkrLCHeartQ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHeartQ.asm
rm mkrLCHeartQ.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMHeartQ ghearts3.pcx
echo "LMHeartQ	label	byte" >LMHeartQ.asm
echo "word	C_BLACK" >>LMHeartQ.asm
tail -r mkrLMHeartQ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHeartQ.asm
rm mkrLMHeartQ.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGAHeartQ ghearts3.pcx
echo "CGAHeartQ	label	byte" >CGAHeartQ.asm
echo "word	C_BLACK" >>CGAHeartQ.asm
tail -r mkrCGAHeartQ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHeartQ.asm
rm mkrCGAHeartQ.ui

cvtpcx -2 -g -m13 -x0 -y99 -w71 -h100 -nLCHeartK gkings.pcx
echo "LCHeartK	label	byte" >LCHeartK.asm
echo "word	C_BLACK" >>LCHeartK.asm
tail -r mkrLCHeartK.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHeartK.asm
rm mkrLCHeartK.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMHeartK gkings.pcx
echo "LMHeartK	label	byte" >LMHeartK.asm
echo "word	C_BLACK" >>LMHeartK.asm
tail -r mkrLMHeartK.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHeartK.asm
rm mkrLMHeartK.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGAHeartK gkings.pcx
echo "CGAHeartK	label	byte" >CGAHeartK.asm
echo "word	C_BLACK" >>CGAHeartK.asm
tail -r mkrCGAHeartK.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHeartK.asm
rm mkrCGAHeartK.ui

echo
echo ------------------------
echo Converting Diamonds
echo ------------------------

cvtpcx -2 -b -g -m13 -x0 -y0 -w71 -h100 -nLCDiamondA gdiam1.pcx
echo "LCDiamondA	label	byte" >LCDiamondA.asm
echo "word	C_LIGHT_RED" >>LCDiamondA.asm
tail -r mkrLCDiamondA.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCDiamondA.asm
rm mkrLCDiamondA.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMDiamondA gdiam1.pcx
echo "LMDiamondA	label	byte" >LMDiamondA.asm
echo "word	C_BLACK" >>LMDiamondA.asm
tail -r mkrLMDiamondA.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMDiamondA.asm
rm mkrLMDiamondA.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGADiamondA gdiam1.pcx
echo "CGADiamondA	label	byte" >CGADiamondA.asm
echo "word	C_BLACK" >>CGADiamondA.asm
tail -r mkrCGADiamondA.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGADiamondA.asm
rm mkrCGADiamondA.ui

cvtpcx -2 -b -g -m13 -x0 -y99 -w71 -h100 -nLCDiamond2 gdiam1.pcx
echo "LCDiamond2	label	byte" >LCDiamond2.asm
echo "word	C_LIGHT_RED" >>LCDiamond2.asm
tail -r mkrLCDiamond2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCDiamond2.asm
rm mkrLCDiamond2.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMDiamond2 gdiam1.pcx
echo "LMDiamond2	label	byte" >LMDiamond2.asm
echo "word	C_BLACK" >>LMDiamond2.asm
tail -r mkrLMDiamond2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMDiamond2.asm
rm mkrLMDiamond2.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGADiamond2 gdiam1.pcx
echo "CGADiamond2	label	byte" >CGADiamond2.asm
echo "word	C_BLACK" >>CGADiamond2.asm
tail -r mkrCGADiamond2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGADiamond2.asm
rm mkrCGADiamond2.ui

cvtpcx -2 -b -g -m13 -x0 -y198 -w71 -h100 -nLCDiamond3 gdiam1.pcx
echo "LCDiamond3	label	byte" >LCDiamond3.asm
echo "word	C_LIGHT_RED" >>LCDiamond3.asm
tail -r mkrLCDiamond3.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCDiamond3.asm
rm mkrLCDiamond3.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMDiamond3 gdiam1.pcx
echo "LMDiamond3	label	byte" >LMDiamond3.asm
echo "word	C_BLACK" >>LMDiamond3.asm
tail -r mkrLMDiamond3.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMDiamond3.asm
rm mkrLMDiamond3.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGADiamond3 gdiam1.pcx
echo "CGADiamond3	label	byte" >CGADiamond3.asm
echo "word	C_BLACK" >>CGADiamond3.asm
tail -r mkrCGADiamond3.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGADiamond3.asm
rm mkrCGADiamond3.ui

cvtpcx -2 -b -g -m13 -x0 -y297 -w71 -h100 -nLCDiamond4 gdiam1.pcx
echo "LCDiamond4	label	byte" >LCDiamond4.asm
echo "word	C_LIGHT_RED" >>LCDiamond4.asm
tail -r mkrLCDiamond4.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCDiamond4.asm
rm mkrLCDiamond4.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMDiamond4 gdiam1.pcx
echo "LMDiamond4	label	byte" >LMDiamond4.asm
echo "word	C_BLACK" >>LMDiamond4.asm
tail -r mkrLMDiamond4.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMDiamond4.asm
rm mkrLMDiamond4.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGADiamond4 gdiam1.pcx
echo "CGADiamond4	label	byte" >CGADiamond4.asm
echo "word	C_BLACK" >>CGADiamond4.asm
tail -r mkrCGADiamond4.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGADiamond4.asm
rm mkrCGADiamond4.ui

cvtpcx -2 -b -g -m13 -x0 -y0 -w71 -h100 -nLCDiamond5 gdiam2.pcx
echo "LCDiamond5	label	byte" >LCDiamond5.asm
echo "word	C_LIGHT_RED" >>LCDiamond5.asm
tail -r mkrLCDiamond5.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCDiamond5.asm
rm mkrLCDiamond5.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMDiamond5 gdiam2.pcx
echo "LMDiamond5	label	byte" >LMDiamond5.asm
echo "word	C_BLACK" >>LMDiamond5.asm
tail -r mkrLMDiamond5.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMDiamond5.asm
rm mkrLMDiamond5.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGADiamond5 gdiam2.pcx
echo "CGADiamond5	label	byte" >CGADiamond5.asm
echo "word	C_BLACK" >>CGADiamond5.asm
tail -r mkrCGADiamond5.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGADiamond5.asm
rm mkrCGADiamond5.ui

cvtpcx -2 -b -g -m13 -x0 -y99 -w71 -h100 -nLCDiamond6 gdiam2.pcx
echo "LCDiamond6	label	byte" >LCDiamond6.asm
echo "word	C_LIGHT_RED" >>LCDiamond6.asm
tail -r mkrLCDiamond6.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCDiamond6.asm
rm mkrLCDiamond6.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMDiamond6 gdiam2.pcx
echo "LMDiamond6	label	byte" >LMDiamond6.asm
echo "word	C_BLACK" >>LMDiamond6.asm
tail -r mkrLMDiamond6.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMDiamond6.asm
rm mkrLMDiamond6.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGADiamond6 gdiam2.pcx
echo "CGADiamond6	label	byte" >CGADiamond6.asm
echo "word	C_BLACK" >>CGADiamond6.asm
tail -r mkrCGADiamond6.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGADiamond6.asm
rm mkrCGADiamond6.ui

cvtpcx -2 -b -g -m13 -x0 -y198 -w71 -h100 -nLCDiamond7 gdiam2.pcx
echo "LCDiamond7	label	byte" >LCDiamond7.asm
echo "word	C_LIGHT_RED" >>LCDiamond7.asm
tail -r mkrLCDiamond7.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCDiamond7.asm
rm mkrLCDiamond7.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMDiamond7 gdiam2.pcx
echo "LMDiamond7	label	byte" >LMDiamond7.asm
echo "word	C_BLACK" >>LMDiamond7.asm
tail -r mkrLMDiamond7.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMDiamond7.asm
rm mkrLMDiamond7.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGADiamond7 gdiam2.pcx
echo "CGADiamond7	label	byte" >CGADiamond7.asm
echo "word	C_BLACK" >>CGADiamond7.asm
tail -r mkrCGADiamond7.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGADiamond7.asm
rm mkrCGADiamond7.ui

cvtpcx -2 -b -g -m13 -x0 -y297 -w71 -h100 -nLCDiamond8 gdiam2.pcx
echo "LCDiamond8	label	byte" >LCDiamond8.asm
echo "word	C_LIGHT_RED" >>LCDiamond8.asm
tail -r mkrLCDiamond8.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCDiamond8.asm
rm mkrLCDiamond8.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMDiamond8 gdiam2.pcx
echo "LMDiamond8	label	byte" >LMDiamond8.asm
echo "word	C_BLACK" >>LMDiamond8.asm
tail -r mkrLMDiamond8.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMDiamond8.asm
rm mkrLMDiamond8.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGADiamond8 gdiam2.pcx
echo "CGADiamond8	label	byte" >CGADiamond8.asm
echo "word	C_BLACK" >>CGADiamond8.asm
tail -r mkrCGADiamond8.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGADiamond8.asm
rm mkrCGADiamond8.ui

cvtpcx -2 -b -g -m13 -x0 -y0 -w71 -h100 -nLCDiamond9 gdiam3.pcx
echo "LCDiamond9	label	byte" >LCDiamond9.asm
echo "word	C_LIGHT_RED" >>LCDiamond9.asm
tail -r mkrLCDiamond9.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCDiamond9.asm
rm mkrLCDiamond9.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMDiamond9 gdiam3.pcx
echo "LMDiamond9	label	byte" >LMDiamond9.asm
echo "word	C_BLACK" >>LMDiamond9.asm
tail -r mkrLMDiamond9.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMDiamond9.asm
rm mkrLMDiamond9.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGADiamond9 gdiam3.pcx
echo "CGADiamond9	label	byte" >CGADiamond9.asm
echo "word	C_BLACK" >>CGADiamond9.asm
tail -r mkrCGADiamond9.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGADiamond9.asm
rm mkrCGADiamond9.ui

cvtpcx -2 -b -g -m13 -x0 -y99 -w71 -h99 -nLCDiamondT gdiam3.pcx
echo "LCDiamondT	label	byte" >LCDiamondT.asm
echo "word	C_LIGHT_RED" >>LCDiamondT.asm
tail -r mkrLCDiamondT.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCDiamondT.asm
rm mkrLCDiamondT.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMDiamondT gdiam3.pcx
echo "LMDiamondT	label	byte" >LMDiamondT.asm
echo "word	C_BLACK" >>LMDiamondT.asm
tail -r mkrLMDiamondT.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMDiamondT.asm
rm mkrLMDiamondT.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGADiamondT gdiam3.pcx
echo "CGADiamondT	label	byte" >CGADiamondT.asm
echo "word	C_BLACK" >>CGADiamondT.asm
tail -r mkrCGADiamondT.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGADiamondT.asm
rm mkrCGADiamondT.ui

cvtpcx -2 -g -m13 -x0 -y198 -w71 -h100 -nLCDiamondJ gdiam3.pcx
echo "LCDiamondJ	label	byte" >LCDiamondJ.asm
echo "word	C_BLACK" >>LCDiamondJ.asm
tail -r mkrLCDiamondJ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCDiamondJ.asm
rm mkrLCDiamondJ.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMDiamondJ gdiam3.pcx
echo "LMDiamondJ	label	byte" >LMDiamondJ.asm
echo "word	C_BLACK" >>LMDiamondJ.asm
tail -r mkrLMDiamondJ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMDiamondJ.asm
rm mkrLMDiamondJ.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGADiamondJ gdiam3.pcx
echo "CGADiamondJ	label	byte" >CGADiamondJ.asm
echo "word	C_BLACK" >>CGADiamondJ.asm
tail -r mkrCGADiamondJ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGADiamondJ.asm
rm mkrCGADiamondJ.ui

cvtpcx -2 -g -m13 -x0 -y297 -w71 -h100 -nLCDiamondQ gdiam3.pcx
echo "LCDiamondQ	label	byte" >LCDiamondQ.asm
echo "word	C_BLACK" >>LCDiamondQ.asm
tail -r mkrLCDiamondQ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCDiamondQ.asm
rm mkrLCDiamondQ.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMDiamondQ gdiam3.pcx
echo "LMDiamondQ	label	byte" >LMDiamondQ.asm
echo "word	C_BLACK" >>LMDiamondQ.asm
tail -r mkrLMDiamondQ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMDiamondQ.asm
rm mkrLMDiamondQ.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGADiamondQ gdiam3.pcx
echo "CGADiamondQ	label	byte" >CGADiamondQ.asm
echo "word	C_BLACK" >>CGADiamondQ.asm
tail -r mkrCGADiamondQ.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGADiamondQ.asm
rm mkrCGADiamondQ.ui

cvtpcx -2 -g -m13 -x0 -y198 -w71 -h100 -nLCDiamondK gkings.pcx
echo "LCDiamondK	label	byte" >LCDiamondK.asm
echo "word	C_BLACK" >>LCDiamondK.asm
tail -r mkrLCDiamondK.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCDiamondK.asm
rm mkrLCDiamondK.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMDiamondK gkings.pcx
echo "LMDiamondK	label	byte" >LMDiamondK.asm
echo "word	C_BLACK" >>LMDiamondK.asm
tail -r mkrLMDiamondK.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMDiamondK.asm
rm mkrLMDiamondK.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGADiamondK gkings.pcx
echo "CGADiamondK	label	byte" >CGADiamondK.asm
echo "word	C_BLACK" >>CGADiamondK.asm
tail -r mkrCGADiamondK.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGADiamondK.asm
rm mkrCGADiamondK.ui

echo
echo ------------------------
echo Converting Joker
echo ------------------------

cvtpcx -2 -g -m13 -x0 -y0 -w71 -h100 -nLCJoker gjoker.pcx
echo "LCJoker	label	byte" >LCJoker.asm
echo "word	C_BLACK" >>LCJoker.asm
tail -r mkrLCJoker.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCJoker.asm
rm mkrLCJoker.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMJoker gjoker.pcx
echo "LMJoker	label	byte" >LMJoker.asm
echo "word	C_BLACK" >>LMJoker.asm
tail -r mkrLMJoker.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMJoker.asm
rm mkrLMJoker.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGAJoker gjoker.pcx
echo "CGAJoker	label	byte" >CGAJoker.asm
echo "word	C_BLACK" >>CGAJoker.asm
tail -r mkrCGAJoker.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAJoker.asm
rm mkrCGAJoker.ui

echo
echo ------------------------
echo Converting backs
echo ------------------------

cvtpcx -2 -g -m13 -x0 -y0 -w71 -h100 -nLCGeoback gcrdbck1.pcx
echo "LCGeoback	label	byte" >LCGeoback.asm
echo "word	C_BLACK" >>LCGeoback.asm
tail -r mkrLCGeoback.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCGeoback.asm
rm mkrLCGeoback.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMGeoback gcrdbck1.pcx
echo "LMGeoback	label	byte" >LMGeoback.asm
echo "word	C_BLACK" >>LMGeoback.asm
tail -r mkrLMGeoback.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMGeoback.asm
rm mkrLMGeoback.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGAGeoback gcrdbck1.pcx
echo "CGAGeoback	label	byte" >CGAGeoback.asm
echo "word	C_BLACK" >>CGAGeoback.asm
tail -r mkrCGAGeoback.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAGeoback.asm
rm mkrCGAGeoback.ui

cvtpcx -2 -g -m13 -x0 -y99 -w71 -h100 -nLCNefertite gcrdbck1.pcx
echo "LCNefertite	label	byte" >LCNefertite.asm
echo "word	C_BLACK" >>LCNefertite.asm
tail -r mkrLCNefertite.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCNefertite.asm
rm mkrLCNefertite.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMNefertite gcrdbck1.pcx
echo "LMNefertite	label	byte" >LMNefertite.asm
echo "word	C_BLACK" >>LMNefertite.asm
tail -r mkrLMNefertite.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMNefertite.asm
rm mkrLMNefertite.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGANefertite gcrdbck1.pcx
echo "CGANefertite	label	byte" >CGANefertite.asm
echo "word	C_BLACK" >>CGANefertite.asm
tail -r mkrCGANefertite.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGANefertite.asm
rm mkrCGANefertite.ui

cvtpcx -2 -g -m2 -x0 -y0 -w71 -h100 -nLCGrapes gcrdbck2.pcx
echo "LCGrapes	label	byte" >LCGrapes.asm
echo "word	C_BLACK" >>LCGrapes.asm
tail -r mkrLCGrapes.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCGrapes.asm
rm mkrLCGrapes.ui

cvtpcx -2 -b -g -m2 -x70 -y0 -w71 -h100 -nLMGrapes gcrdbck2.pcx
echo "LMGrapes	label	byte" >LMGrapes.asm
echo "word	C_BLACK" >>LMGrapes.asm
tail -r mkrLMGrapes.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMGrapes.asm
rm mkrLMGrapes.ui

cvtpcx -2 -b -g -m2 -x140 -y0 -w67 -h41 -nCGAGrapes gcrdbck2.pcx
echo "CGAGrapes	label	byte" >CGAGrapes.asm
echo "word	C_BLACK" >>CGAGrapes.asm
tail -r mkrCGAGrapes.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAGrapes.asm
rm mkrCGAGrapes.ui

cvtpcx -2 -g -m8 -x0 -y0 -w71 -h100 -nLCWin gcrdbck3.pcx
echo "LCWin	label	byte" >LCWin.asm
echo "word	C_BLACK" >>LCWin.asm
tail -r mkrLCWin.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCWin.asm
rm mkrLCWin.ui

cvtpcx -2 -b -g -m8 -x70 -y0 -w71 -h100 -nLMWin gcrdbck3.pcx
echo "LMWin	label	byte" >LMWin.asm
echo "word	C_BLACK" >>LMWin.asm
tail -r mkrLMWin.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMWin.asm
rm mkrLMWin.ui

cvtpcx -2 -b -g -m8 -x140 -y0 -w67 -h41 -nCGAWin gcrdbck3.pcx
echo "CGAWin	label	byte" >CGAWin.asm
echo "word	C_BLACK" >>CGAWin.asm
tail -r mkrCGAWin.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAWin.asm
rm mkrCGAWin.ui

cvtpcx -2 -g -m13 -x0 -y0 -w71 -h100 -nLCClassic gcrdbck4.pcx
echo "LCClassic	label	byte" >LCClassic.asm
echo "word	C_BLACK" >>LCClassic.asm
tail -r mkrLCClassic.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCClassic.asm
rm mkrLCClassic.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMClassic gcrdbck4.pcx
echo "LMClassic	label	byte" >LMClassic.asm
echo "word	C_BLACK" >>LMClassic.asm
tail -r mkrLMClassic.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMClassic.asm
rm mkrLMClassic.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGAClassic gcrdbck4.pcx
echo "CGAClassic	label	byte" >CGAClassic.asm
echo "word	C_BLACK" >>CGAClassic.asm
tail -r mkrCGAClassic.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAClassic.asm
rm mkrCGAClassic.ui

cvtpcx -2 -g -m13 -x0 -y99 -w71 -h100 -nLCPyramid gcrdbck4.pcx
echo "LCPyramid	label	byte" >LCPyramid.asm
echo "word	C_BLACK" >>LCPyramid.asm
tail -r mkrLCPyramid.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCPyramid.asm
rm mkrLCPyramid.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMPyramid gcrdbck4.pcx
echo "LMPyramid	label	byte" >LMPyramid.asm
echo "word	C_BLACK" >>LMPyramid.asm
tail -r mkrLMPyramid.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMPyramid.asm
rm mkrLMPyramid.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGAPyramid gcrdbck4.pcx
echo "CGAPyramid	label	byte" >CGAPyramid.asm
echo "word	C_BLACK" >>CGAPyramid.asm
tail -r mkrCGAPyramid.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAPyramid.asm
rm mkrCGAPyramid.ui

cvtpcx -2 -g -m13 -x0 -y198 -w71 -h100 -nLCEagle gcrdbck4.pcx
echo "LCEagle	label	byte" >LCEagle.asm
echo "word	C_BLACK" >>LCEagle.asm
tail -r mkrLCEagle.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCEagle.asm
rm mkrLCEagle.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMEagle gcrdbck4.pcx
echo "LMEagle	label	byte" >LMEagle.asm
echo "word	C_BLACK" >>LMEagle.asm
tail -r mkrLMEagle.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMEagle.asm
rm mkrLMEagle.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGAEagle gcrdbck4.pcx
echo "CGAEagle	label	byte" >CGAEagle.asm
echo "word	C_BLACK" >>CGAEagle.asm
tail -r mkrCGAEagle.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAEagle.asm
rm mkrCGAEagle.ui

cvtpcx -2 -g -m13 -x0 -y297 -w71 -h100 -nLCHinge gcrdbck4.pcx
echo "LCHinge	label	byte" >LCHinge.asm
echo "word	C_BLACK" >>LCHinge.asm
tail -r mkrLCHinge.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCHinge.asm
rm mkrLCHinge.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMHinge gcrdbck4.pcx
echo "LMHinge	label	byte" >LMHinge.asm
echo "word	C_BLACK" >>LMHinge.asm
tail -r mkrLMHinge.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMHinge.asm
rm mkrLMHinge.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGAHinge gcrdbck4.pcx
echo "CGAHinge	label	byte" >CGAHinge.asm
echo "word	C_BLACK" >>CGAHinge.asm
tail -r mkrCGAHinge.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAHinge.asm
rm mkrCGAHinge.ui

cvtpcx -2 -g -m13 -x0 -y0 -w71 -h100 -nLCBubbles gcrdbck5.pcx
echo "LCBubbles	label	byte" >LCBubbles.asm
echo "word	C_BLACK" >>LCBubbles.asm
tail -r mkrLCBubbles.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCBubbles.asm
rm mkrLCBubbles.ui

cvtpcx -2 -b -g -m13 -x70 -y0 -w71 -h100 -nLMBubbles gcrdbck5.pcx
echo "LMBubbles	label	byte" >LMBubbles.asm
echo "word	C_BLACK" >>LMBubbles.asm
tail -r mkrLMBubbles.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMBubbles.asm
rm mkrLMBubbles.ui

cvtpcx -2 -b -g -m13 -x140 -y0 -w67 -h41 -nCGABubbles gcrdbck5.pcx
echo "CGABubbles	label	byte" >CGABubbles.asm
echo "word	C_BLACK" >>CGABubbles.asm
tail -r mkrCGABubbles.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGABubbles.asm
rm mkrCGABubbles.ui

cvtpcx -2 -g -m13 -x0 -y99 -w71 -h100 -nLCMasks gcrdbck5.pcx
echo "LCMasks	label	byte" >LCMasks.asm
echo "word	C_BLACK" >>LCMasks.asm
tail -r mkrLCMasks.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCMasks.asm
rm mkrLCMasks.ui

cvtpcx -2 -b -g -m13 -x70 -y99 -w71 -h100 -nLMMasks gcrdbck5.pcx
echo "LMMasks	label	byte" >LMMasks.asm
echo "word	C_BLACK" >>LMMasks.asm
tail -r mkrLMMasks.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMMasks.asm
rm mkrLMMasks.ui

cvtpcx -2 -b -g -m13 -x140 -y99 -w67 -h41 -nCGAMasks gcrdbck5.pcx
echo "CGAMasks	label	byte" >CGAMasks.asm
echo "word	C_BLACK" >>CGAMasks.asm
tail -r mkrCGAMasks.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAMasks.asm
rm mkrCGAMasks.ui

cvtpcx -2 -g -m13 -x0 -y198 -w71 -h100 -nLCFlowers gcrdbck5.pcx
echo "LCFlowers	label	byte" >LCFlowers.asm
echo "word	C_BLACK" >>LCFlowers.asm
tail -r mkrLCFlowers.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCFlowers.asm
rm mkrLCFlowers.ui

cvtpcx -2 -b -g -m13 -x70 -y198 -w71 -h100 -nLMFlowers gcrdbck5.pcx
echo "LMFlowers	label	byte" >LMFlowers.asm
echo "word	C_BLACK" >>LMFlowers.asm
tail -r mkrLMFlowers.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMFlowers.asm
rm mkrLMFlowers.ui

cvtpcx -2 -b -g -m13 -x140 -y198 -w67 -h41 -nCGAFlowers gcrdbck5.pcx
echo "CGAFlowers	label	byte" >CGAFlowers.asm
echo "word	C_BLACK" >>CGAFlowers.asm
tail -r mkrCGAFlowers.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAFlowers.asm
rm mkrCGAFlowers.ui

cvtpcx -2 -g -m13 -x0 -y297 -w71 -h100 -nLCCheese gcrdbck5.pcx
echo "LCCheese	label	byte" >LCCheese.asm
echo "word	C_BLACK" >>LCCheese.asm
tail -r mkrLCCheese.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCCheese.asm
rm mkrLCCheese.ui

cvtpcx -2 -b -g -m13 -x70 -y297 -w71 -h100 -nLMCheese gcrdbck5.pcx
echo "LMCheese	label	byte" >LMCheese.asm
echo "word	C_BLACK" >>LMCheese.asm
tail -r mkrLMCheese.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMCheese.asm
rm mkrLMCheese.ui

cvtpcx -2 -b -g -m13 -x140 -y297 -w67 -h41 -nCGACheese gcrdbck5.pcx
echo "CGACheese	label	byte" >CGACheese.asm
echo "word	C_BLACK" >>CGACheese.asm
tail -r mkrCGACheese.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGACheese.asm
rm mkrCGACheese.ui

cvtpcx -2 -g -m2 -x0 -y0 -w71 -h100 -nLCFractal1 gcrdbck6.pcx
echo "LCFractal1	label	byte" >LCFractal1.asm
echo "word	C_BLACK" >>LCFractal1.asm
tail -r mkrLCFractal1.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCFractal1.asm
rm mkrLCFractal1.ui

cvtpcx -2 -b -g -m2 -x70 -y0 -w71 -h100 -nLMFractal1 gcrdbck6.pcx
echo "LMFractal1	label	byte" >LMFractal1.asm
echo "word	C_BLACK" >>LMFractal1.asm
tail -r mkrLMFractal1.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMFractal1.asm
rm mkrLMFractal1.ui

cvtpcx -2 -b -g -m2 -x140 -y0 -w67 -h41 -nCGAFractal1 gcrdbck6.pcx
echo "CGAFractal1	label	byte" >CGAFractal1.asm
echo "word	C_BLACK" >>CGAFractal1.asm
tail -r mkrCGAFractal1.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAFractal1.asm
rm mkrCGAFractal1.ui

cvtpcx -2 -g -m2 -x0 -y99 -w71 -h100 -nLCFractal2 gcrdbck6.pcx
echo "LCFractal2	label	byte" >LCFractal2.asm
echo "word	C_BLACK" >>LCFractal2.asm
tail -r mkrLCFractal2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LCFractal2.asm
rm mkrLCFractal2.ui

cvtpcx -2 -b -g -m2 -x70 -y99 -w71 -h100 -nLMFractal2 gcrdbck6.pcx
echo "LMFractal2	label	byte" >LMFractal2.asm
echo "word	C_BLACK" >>LMFractal2.asm
tail -r mkrLMFractal2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>LMFractal2.asm
rm mkrLMFractal2.ui

cvtpcx -2 -b -g -m2 -x140 -y99 -w67 -h41 -nCGAFractal2 gcrdbck6.pcx
echo "CGAFractal2	label	byte" >CGAFractal2.asm
echo "word	C_BLACK" >>CGAFractal2.asm
tail -r mkrCGAFractal2.ui >foo
tail +2 foo >foofoo
tail -r foofoo >foo
tail +2 foo >>CGAFractal2.asm
rm mkrCGAFractal2.ui

rm foo
rm foofoo

echo
echo ta-da!

