#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = canonrgb
ASM_TO_OBJS     = canonRGBManager.asm
UI_TO_RDFS      = canonRGB.ui
SRCS            = canonRGBInfo.asm canonRGBmono2Info.asm canonRGBDialog.asm\
                  canonRGBmonoInfo.asm canonRGBManager.asm\
                  canonRGBDriverInfo.asm canonRGBControlCodes.asm\
                  canonRGBColor.asm UI/uiGetNoMain.asm UI/uiGetOptions.asm\
                  UI/uiEval.asm printcomEntry.asm printcomInfo.asm\
                  printcomAdmin.asm printcomTables.asm\
                  printcomNoEscapes.asm Job/jobStartCanonRGB.asm\
                  Job/jobEndCanonRGB.asm Job/jobPaperPathNoASFControl.asm\
                  Job/jobPaperInfo.asm Job/jobResetPrinterAndWait.asm\
                  printcomCanonRGBPage.asm printcomCanonBJCCursor.asm\
                  printcomStream.asm printcomCanonBJCColor.asm\
                  Graphics/graphicsCommon.asm Graphics/graphicsCanonRGB.asm\
                  printcomNoStyles.asm printcomNoText.asm\
                  Buffer/bufferCreateCanonRGB.asm Buffer/bufferDestroy.asm\
                  canonRGBConstant.def canonRGB.ui
OBJS            = canonRGBManager.obj
LOBJS           =
LIBNAME         = print
PROTOCONST      = PRINT

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
