rem All Rem'd so I don't accidentally regenerate ;-)

rem cvtpcx -2 -w64 -h57 -m1 -G -nQTip1 -oQTip1.goh tip1.pcx

rem - these two graphics got moved to pics.goh
rem cvtpcx -2 -w27 -h27 -m1 -G -g -nnum1_hi -onum1_hi.goh num1_hi.pcx
rem cvtpcx -2 -w27 -h27 -m1 -G -g -nnum2_hi -onum2_hi.goh num2_hi.pcx

rem cvtpcx -2 -w64 -h57 -m1 -G -nQTArrow -oQTArrow.goh hint1.pcx
rem cvtpcx -2 -w82 -h40 -m1 -G -nQTPlayer -oQTPlayer.goh hint2.pcx
rem cvtpcx -2 -w39 -h50 -m1 -G -nQTLevel -oQTLevel.goh hint3.pcx

