source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1" # installed by `gem jekyll`

gem "just-the-docs", github: "mgroeber9110/just-the-docs", branch: "1210-index-on-web-worker"

group :jekyll_plugins do
  gem "jekyll-github-metadata"
  gem "jekyll-relative-links"
  gem "jekyll-optional-front-matter", github: "mgroeber9110/jekyll-optional-front-matter", branch: "42-keep-pages-sorted-after-adding"
  gem "jekyll-titles-from-headings"
  gem "jekyll-default-layout"
end