#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = Banner
ASM_TO_OBJS     = banner.asm
UI_TO_RDFS      = BANNER.UI
SRCS            = banner.asm bannerDraw.asm bannerPrint.asm bannerUI.asm\
                  bannerConstants.def banner.ui
OBJS            = banner.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
