#!/bin/sh -
#
#
# Project:	PC GEOS
# Module:	Sokoban
# File:		convert
#
# Author:	brianc
#
#	This file contains the convert information for this application.
#
# 	$Id: convert,v 1.2.4.1 97/03/29 10:17:09 canavese Exp $
#
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile g20apps4.pcx 0 Icon -m10 $appArgs -m10
cvtfile g20apps4.pcx 1 IconDoc $appArgs

