#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = VGA
ASM_TO_OBJS     = loader.asm
UI_TO_RDFS      =
SRCS            = loader.asm MAIN.ASM LOCATE.ASM STRINGS.ASM INI.ASM\
                  LOAD.ASM HEAP.ASM PATH.ASM VIDEODETECT.ASM\
                  VIDEODISPLAY.ASM VIDEOVGA.ASM VIDEOSVGA.ASM VIDEOEGA.ASM\
                  VIDEOMCGA.ASM VIDEOCGA.ASM VIDEOHGC.ASM\
                  VIDEOVGAIMAGELOGO.ASM
OBJS            = loader.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
