#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = grafcalc
MAIN            = Bereich.goc Calcvalue.goc Edit.goc Funktion.goc\
                  Grprop.goc Keyboard.goc Options.goc Parser.goc\
                  Process.goc Sprachenwahl.goc View.goc grafcalc.goh\
                  lmacros.goh
UI              = appui.goc appui.goh
UI_TO_RDFS      =
OBJS            = Bereich.obj Calcvalue.obj Edit.obj Funktion.obj\
                  Grprop.obj Keyboard.obj Options.obj Parser.obj\
                  Process.obj Sprachenwahl.obj View.obj appui.obj
COMMON          =
MODULES         =
CMODULES        = Main UI
SRCS            = $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
