DBCS/MODEMMANAGER.obj \
DBCS/MODEMMANAGER.eobj: GEOS.DEF GEODE.DEF RESOURCE.DEF TIMER.DEF HEAP.DEF \
                LOCALIZE.DEF SLLANG.DEF SYSTEM.DEF SEM.DEF CHAR.DEF \
                UNICODE.DEF FILE.DEF INITFILE.DEF DRIVER.DEF LMEM.DEF \
                THREAD.DEF EC.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                INTERNAL/HEAPINT.DEF INTERNAL/SEMINT.DEF SYSSTATS.DEF \
                INTERNAL/IM.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                OBJECT.DEF CHUNKARR.DEF GEOWORKS.DEF INTERNAL/MODEMDR.DEF \
                INTERNAL/STRDRINT.DEF INTERNAL/STREAMDR.DEF \
                INTERNAL/SERIALDR.DEF MODEM.DEF MODEMSTRATEGY.ASM \
                MODEMADMIN.ASM MODEMSEND.ASM MODEMPARSE.ASM

DBCS/ModemEC.geo DBCS/Modem.geo : GEOS.LDF 