#!/bin/sh -
##############################################################################
#
# 	Copyright (c) Geoworks 1996.  All rights reserved.
#       GEOWORKS CONFIDENTIAL
#
# PROJECT:	GEOS
# MODULE:	World Clock
# FILE: 	convert
# AUTHOR: 	Larry Warner, Oct 17, 1996
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	warner	10/17/96   	Added Template and Dove product switch
#
# DESCRIPTION:
#
#	Create UIC-edible bitmaps from PCX files
#
# $Id: convert,v 1.18.1.1 97/03/29 10:58:47 canavese Exp $
#
###############################################################################
#

# Things to be done regardless of product type go here:
cvtpcx -f -t -L -x0 -y164 -dLM -dLC -dSC -dSM -dLCGA -dSCGA -dTM -dTCGA -dYC -nWorldClock PCX/betaicon.pcx

if [ $# -eq 0 ]; then
   cvtpcx -owcmap.ui -2 -g -rWorldMapResource -b -w248 -h141 PCX/wcmap.pcx
   sed -e 1d -e \$d wcmap.ui > wcmap.bitmap
elif [ $1 = "DOVE" ]; then
   cvtpcx -owcmapDove.ui -2 -g -rWorldMapResource -b -w472 -h208 \
		PCX/wcmapDove.pcx 
   sed -e 1d -e \$d wcmapDove.ui > wcmapDove.bitmap
elif [ $1 = "PENELOPE" ]; then
   cvtpcx -owcmapPenelope.ui -2 -g -rWorldMapResource -b -w266 -h116 \
		PCX/wcmapPenelope.pcx 

   sed -e 1d -e \$d wcmapPenelope.ui > wcmapPenelope.bitmap

   cvtpcx -2 -f -t -m11 -x395 -y75 -w14 -h14 -nPeneSun PCX/picons1.pcx

# the next two are not included by other files, but were actually copied
# to the .ui files, so that the names would match existing icon names.
   cvtpcx -2 -f -t -g -m11 -x36 -y102 -w96 -h22 -nNamePlate PCX/alarm.pcx
#   cvtpcx -2 -f -t -g -m11 -x153 -y37 -w112 -h116 -nClockFace PCX/alarm.pcx
   cvtpcx -2 -f -t -g -x0 -y0 -w108 -h108 -nClockFace PCX/clock.pcx
   cvtpcx -2 -f -t -m11 -x5 -y10 -w11 -h11 -nBell PCX/bell.pcx
   cvtpcx -2 -f -t -g -m11 -x3 -y6 -w20 -h18 -nAlarmEvent PCX/event1.pcx
   cvtpcx -2 -f -t -g -b -x13 -y28 -w33 -h3 -nLeftHand PCX/hands.pcx
   cvtpcx -2 -f -t -g -b -x13 -y37 -w23 -h3 -nRightHand PCX/hands.pcx
#   cvtpcx -2 -f -t -g -b -m11 -x32 -y78 -w8 -h8 -nPeneFlag PCX/picons1.pcx
#   cvtpcx -2 -f -t -g -x91 -y27 -w14 -h14 -nPeneSun2 PCX/picons1.pcx

   cvtpcx -2 -f -t -m11 -x12 -y13 -w28 -h28 -nPeneAlarmClock PCX/picons2.pcx
   cvtpcx -2 -f -t -m11 -x45 -y13 -w28 -h28 -nPeneSystemTime PCX/picons2.pcx
   cvtpcx -2 -f -t -m11 -x78 -y13 -w28 -h28 -nPeneHomeCity PCX/picons2.pcx
   cvtpcx -2 -f -t -m11 -x111 -y13 -w28 -h28 -nPeneDestCity PCX/picons2.pcx
   cvtpcx -2 -f -t -m11 -x144 -y13 -w28 -h28 -nPeneUserCity PCX/picons2.pcx
   cvtpcx -2 -f -t -m11 -x177 -y13 -w28 -h28 -nPeneOptions PCX/picons2.pcx

   cvtpcx -2 -f -t -m11 -x8 -y10 -w28 -h28 -nPeneWorldClock PCX/picons3.pcx
   cvtpcx -2 -f -t -m11 -x74 -y10 -w28 -h28 -nPeneSetAlarm PCX/picons3.pcx
fi
