ESCP2MANAGER.obj \
ESCP2MANAGER.eobj: PRINTCOMINCLUDE.DEF GEOS.DEF HEAP.DEF GEODE.DEF \
                RESOURCE.DEF EC.DEF DRIVER.DEF LMEM.DEF FILE.DEF SEM.DEF \
                GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF \
                TEXT.DEF CHAR.DEF WIN.DEF LOCALIZE.DEF SLLANG.DEF \
                CHUNKARR.DEF HUGEARR.DEF TIMER.DEF SYSTEM.DEF \
                INTERNAL/INTERRUP.DEF INTERNAL/GSTATE.DEF \
                INTERNAL/TMATRIX.DEF INTERNAL/FONTDR.DEF \
                INTERNAL/WINDOW.DEF INTERNAL/HEAPINT.DEF \
                INTERNAL/SEMINT.DEF SYSSTATS.DEF INTERNAL/PRINTDR.DEF \
                PRINT.DEF INTERNAL/SPOOLINT.DEF INTERNAL/SERIALDR.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/PARALLDR.DEF \
                INTERNAL/VIDEODR.DEF UI.DEF VM.DEF INPUT.DEF HWR.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF OBJECT.DEF \
                GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SPOOL.DEF INTERNAL/PRODFEATURES.DEF EPSON24INCLUDE.DEF \
                PRINTCOMCONSTANT.DEF ESCP2CONSTANT.DEF PRINTCOMMACRO.DEF \
                EPSON24MACRO.DEF PRINTCOMVARIABLE.DEF EPSON24VARIABLE.DEF \
                PRINTCOMENTRY.ASM PRINTCOMINFO.ASM PRINTCOMSTREAM.ASM \
                STREAM/STREAMWRITE.ASM STREAM/STREAMWRITEBYTE.ASM \
                STREAM/STREAMSENDCODEOUT.ASM ESCP2SETUP.ASM \
                ESCP2CONTROLCODES.ASM ESCP2GRAPHICS.ASM ESCP2CURSOR.ASM \
                ESCP2PAGE.ASM ESCP2DRIVERINFO.ASM ESCP2GENERINFO.ASM \
                ESCP2GENERWINFO.ASM

ESCP2EC.geo ESCP2.geo : GEOS.LDF SPOOL.LDF 