#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = wsm
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = WSM.GOC process.goc routines.goc Import.goc WSMICON.GOH\
                  BBOXREG.GOH wsm.goh externs.goh
OBJS            = WSM.obj process.obj routines.obj Import.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
