#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = CANONRGB
LIBNAME		= print
PROTOCONST	= PRINT
ASM_TO_OBJS     = canonRGBManager.asm
UI_TO_RDFS      = canonRGB.ui
SRCS            = canonRGBControlCodes.asm canonRGBDialog.asm\
                  canonRGBDriverInfo.asm canonRGBManager.asm\
                  canonRGBInfo.asm canonRGBColor.asm UI/UIGETNOMAIN.ASM\
                  UI/UIGETOPTIONS.ASM UI/UIEVAL.ASM UI/UIEVALDUMMYASF.ASM\
                  PRINTCOMENTRY.ASM PRINTCOMINFO.ASM PRINTCOMADMIN.ASM\
                  PRINTCOMTABLES.ASM PRINTCOMNOESCAPES.ASM\
                  Job/JOBSTARTCANONRGB.ASM Job/JOBENDCANONRGB.ASM\
                  Job/JOBPAPERPATHNOASFCONTROL.ASM Job/JOBPAPERINFO.ASM\
                  Job/JOBRESETPRINTERANDWAIT.ASM PRINTCOMASFONLYPAGE.ASM\
                  PRINTCOMCANONBJCCURSOR.ASM PRINTCOMSTREAM.ASM\
                  PRINTCOMCANONBJCCOLOR.ASM Graphics/GRAPHICSCOMMON.ASM\
                  Graphics/GRAPHICSCANONRGB.ASM PRINTCOMNOSTYLES.ASM\
                  PRINTCOMNOTEXT.ASM Buffer/BUFFERCREATE.ASM\
                  Buffer/BUFFERDESTROY.ASM canonRGBConstant.def
OBJS            = canonRGBManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
