#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = vga24
ASM_TO_OBJS     = vga24Manager.asm
UI_TO_RDFS      =
SRCS            = vga24Admin.asm vga24Chars.asm vga24DevInfo.asm\
                  vga24Dither.asm vga24EscTab.asm vga24GenChar.asm\
                  vga24Manager.asm vga24Output.asm vga24Palette.asm\
                  vga24Pointer.asm vga24Raster.asm vga24StringTab.asm\
                  vga24Table.asm vga24Under.asm vga24Utils.asm\
                  vidcomTables.asm vidcomEntry.asm vidcomOutput.asm\
                  vidcomChars.asm vidcomFont.asm vidcomUtils.asm\
                  vidcomRegion.asm vidcomXOR.asm vidcomInfo.asm\
                  vidcomEscape.asm vidcomPalette.asm vidcomPolygon.asm\
                  vidcomLine.asm vidcomPutLine.asm vidcomRaster.asm\
                  vidcomExclBounds.asm vga24Constant.def vga24Macro.def\
                  vga24Variable.def
OBJS            = vga24Manager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
