FILE.obj \
FILE.eobj: File/FileMANAGER.ASM \
                
FSM.obj \
FSM.eobj: FSM/FSMMANAGER.ASM \
                FSMINCLUDE.DEF TERMINCLUDE.DEF GEOS.DEF HEAP.DEF GEODE.DEF \
                RESOURCE.DEF EC.DEF OBJECT.DEF LMEM.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF INPUT.DEF CHAR.DEF HWR.DEF \
                TIMER.DEF TIMEDATE.DEF THREAD.DEF GSTRING.DEF TEXT.DEF \
                FILE.DEF SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF LIBRARY.DEF \
                ASSERT.DEF DISK.DEF DRIVE.DEF WIN.DEF OBJECTS/INPUTC.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF \
                OBJECTS/WINC.DEF INTERNAL/SEMINT.DEF INTERNAL/IM.DEF \
                OBJECTS/PROCESSC.DEF INTERNAL/FILEINT.DEF FILEENUM.DEF \
                INTERNAL/DOS.DEF INTERNAL/DRIVEINT.DEF UI.DEF VM.DEF \
                GCNLIST.DEF OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SOUND.DEF DRIVER.DEF INTERNAL/SOUNDFMT.DEF \
                INTERNAL/SERIALDR.DEF INTERNAL/STREAMDR.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                TERMCONSTANT.DEF TERMMACRO.DEF TERMRESOURCE.DEF \
                FSMCONSTANT.DEF FSMMACRO.DEF FSMIMPORT.DEF \
                FSMVARIABLE.DEF FSMMAIN.ASM FSMMAKETABLES.ASM
MAIN.obj \
MAIN.eobj: Main/MainMANAGER.ASM \
                MAININCLUDE.DEF TERMINCLUDE.DEF GEOS.DEF HEAP.DEF \
                GEODE.DEF RESOURCE.DEF EC.DEF OBJECT.DEF LMEM.DEF \
                GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF INPUT.DEF \
                CHAR.DEF HWR.DEF TIMER.DEF TIMEDATE.DEF THREAD.DEF \
                GSTRING.DEF TEXT.DEF FILE.DEF SYSTEM.DEF LOCALIZE.DEF \
                SLLANG.DEF LIBRARY.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                WIN.DEF OBJECTS/INPUTC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF OBJECTS/WINC.DEF INTERNAL/SEMINT.DEF \
                INTERNAL/IM.DEF OBJECTS/PROCESSC.DEF INTERNAL/FILEINT.DEF \
                FILEENUM.DEF INTERNAL/DOS.DEF INTERNAL/DRIVEINT.DEF \
                UI.DEF VM.DEF GCNLIST.DEF OBJECTS/TEXT/TCOMMON.DEF \
                STYLESH.DEF IACP.DEF OBJECTS/UIINPUTC.DEF \
                OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF \
                INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SOUND.DEF DRIVER.DEF INTERNAL/SOUNDFMT.DEF \
                INTERNAL/SERIALDR.DEF INTERNAL/STREAMDR.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                TERMCONSTANT.DEF TERMMACRO.DEF TERMRESOURCE.DEF \
                INITFILE.DEF MAINCONSTANT.DEF MAINMACRO.DEF \
                MAINIMPORT.DEF MAINVARIABLE.DEF TERMUI.RDEF MAINMAIN.ASM \
                MAINLOCAL.ASM MAINPROTOCOL.ASM MAINCONNECTION.ASM \
                MAINECI.ASM MAINTIMEDDIALOG.ASM
SCREEN.obj \
SCREEN.eobj: Screen/ScreenMANAGER.ASM \
                SCREENINCLUDE.DEF TERMINCLUDE.DEF GEOS.DEF HEAP.DEF \
                GEODE.DEF RESOURCE.DEF EC.DEF OBJECT.DEF LMEM.DEF \
                GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF INPUT.DEF \
                CHAR.DEF HWR.DEF TIMER.DEF TIMEDATE.DEF THREAD.DEF \
                GSTRING.DEF TEXT.DEF FILE.DEF SYSTEM.DEF LOCALIZE.DEF \
                SLLANG.DEF LIBRARY.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                WIN.DEF OBJECTS/INPUTC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF OBJECTS/WINC.DEF INTERNAL/SEMINT.DEF \
                INTERNAL/IM.DEF OBJECTS/PROCESSC.DEF INTERNAL/FILEINT.DEF \
                FILEENUM.DEF INTERNAL/DOS.DEF INTERNAL/DRIVEINT.DEF \
                UI.DEF VM.DEF GCNLIST.DEF OBJECTS/TEXT/TCOMMON.DEF \
                STYLESH.DEF IACP.DEF OBJECTS/UIINPUTC.DEF \
                OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF \
                INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SOUND.DEF DRIVER.DEF INTERNAL/SOUNDFMT.DEF \
                INTERNAL/SERIALDR.DEF INTERNAL/STREAMDR.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                TERMCONSTANT.DEF TERMMACRO.DEF TERMRESOURCE.DEF \
                SCREENCONSTANT.DEF SCREENMACRO.DEF SCREENIMPORT.DEF \
                SCREENVARIABLE.DEF SCREENMAIN.ASM SCREENLOCAL.ASM
SCRIPT.obj \
SCRIPT.eobj: Script/ScriptMANAGER.ASM \
                SCRIPTINCLUDE.DEF TERMINCLUDE.DEF GEOS.DEF HEAP.DEF \
                GEODE.DEF RESOURCE.DEF EC.DEF OBJECT.DEF LMEM.DEF \
                GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF INPUT.DEF \
                CHAR.DEF HWR.DEF TIMER.DEF TIMEDATE.DEF THREAD.DEF \
                GSTRING.DEF TEXT.DEF FILE.DEF SYSTEM.DEF LOCALIZE.DEF \
                SLLANG.DEF LIBRARY.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                WIN.DEF OBJECTS/INPUTC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF OBJECTS/WINC.DEF INTERNAL/SEMINT.DEF \
                INTERNAL/IM.DEF OBJECTS/PROCESSC.DEF INTERNAL/FILEINT.DEF \
                FILEENUM.DEF INTERNAL/DOS.DEF INTERNAL/DRIVEINT.DEF \
                UI.DEF VM.DEF GCNLIST.DEF OBJECTS/TEXT/TCOMMON.DEF \
                STYLESH.DEF IACP.DEF OBJECTS/UIINPUTC.DEF \
                OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF \
                INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SOUND.DEF DRIVER.DEF INTERNAL/SOUNDFMT.DEF \
                INTERNAL/SERIALDR.DEF INTERNAL/STREAMDR.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                TERMCONSTANT.DEF TERMMACRO.DEF TERMRESOURCE.DEF \
                SCRIPTCONSTANT.DEF SCRIPTMACRO.DEF SCRIPTIMPORT.DEF \
                SCRIPTVARIABLE.DEF SCRIPTMAIN.ASM SCRIPTLOCAL.ASM
SERIAL.obj \
SERIAL.eobj: Serial/SerialMANAGER.ASM \
                SERIALINCLUDE.DEF TERMINCLUDE.DEF GEOS.DEF HEAP.DEF \
                GEODE.DEF RESOURCE.DEF EC.DEF OBJECT.DEF LMEM.DEF \
                GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF INPUT.DEF \
                CHAR.DEF HWR.DEF TIMER.DEF TIMEDATE.DEF THREAD.DEF \
                GSTRING.DEF TEXT.DEF FILE.DEF SYSTEM.DEF LOCALIZE.DEF \
                SLLANG.DEF LIBRARY.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                WIN.DEF OBJECTS/INPUTC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF OBJECTS/WINC.DEF INTERNAL/SEMINT.DEF \
                INTERNAL/IM.DEF OBJECTS/PROCESSC.DEF INTERNAL/FILEINT.DEF \
                FILEENUM.DEF INTERNAL/DOS.DEF INTERNAL/DRIVEINT.DEF \
                UI.DEF VM.DEF GCNLIST.DEF OBJECTS/TEXT/TCOMMON.DEF \
                STYLESH.DEF IACP.DEF OBJECTS/UIINPUTC.DEF \
                OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF \
                INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SOUND.DEF DRIVER.DEF INTERNAL/SOUNDFMT.DEF \
                INTERNAL/SERIALDR.DEF INTERNAL/STREAMDR.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                TERMCONSTANT.DEF TERMMACRO.DEF TERMRESOURCE.DEF \
                SERIALCONSTANT.DEF SERIALMACRO.DEF SERIALIMPORT.DEF \
                SERIALVARIABLE.DEF SERIALSCRIPTVAR.DEF SERIALMAIN.ASM \
                SERIALIN.ASM SERIALSCRIPT.ASM
UTILS.obj \
UTILS.eobj: Utils/UtilsMANAGER.ASM \
                UTILSINCLUDE.DEF TERMINCLUDE.DEF GEOS.DEF HEAP.DEF \
                GEODE.DEF RESOURCE.DEF EC.DEF OBJECT.DEF LMEM.DEF \
                GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF INPUT.DEF \
                CHAR.DEF HWR.DEF TIMER.DEF TIMEDATE.DEF THREAD.DEF \
                GSTRING.DEF TEXT.DEF FILE.DEF SYSTEM.DEF LOCALIZE.DEF \
                SLLANG.DEF LIBRARY.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                WIN.DEF OBJECTS/INPUTC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF OBJECTS/WINC.DEF INTERNAL/SEMINT.DEF \
                INTERNAL/IM.DEF OBJECTS/PROCESSC.DEF INTERNAL/FILEINT.DEF \
                FILEENUM.DEF INTERNAL/DOS.DEF INTERNAL/DRIVEINT.DEF \
                UI.DEF VM.DEF GCNLIST.DEF OBJECTS/TEXT/TCOMMON.DEF \
                STYLESH.DEF IACP.DEF OBJECTS/UIINPUTC.DEF \
                OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF \
                INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SOUND.DEF DRIVER.DEF INTERNAL/SOUNDFMT.DEF \
                INTERNAL/SERIALDR.DEF INTERNAL/STREAMDR.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                TERMCONSTANT.DEF TERMMACRO.DEF TERMRESOURCE.DEF \
                UTILSCONSTANT.DEF UTILSMACRO.DEF UTILSIMPORT.DEF \
                UTILSVARIABLE.DEF UTILSMAIN.ASM UTILSLOCAL.ASM
TERMUI.rdef: GENERIC.UIH PRODUCT.UIH ART/MKRGEOCOMM.UI \
                ART/MKRGEOCOMMTINY.UI ART/MKRGEOCOMMDOC.UI

TERMEC.geo TERM.geo : GEOS.LDF UI.LDF TEXT.LDF 