WC.rdef: GENERIC.UIH PRODUCT.UIH WC.UIH UISTRINGS.UI \
                ART/MKRWORLDCLOCK.UI
WCMAIN.obj \
WCMAIN.eobj: WCGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF SEM.DEF OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF FILE.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF \
                TIMEDATE.DEF DBASE.DEF INPUT.DEF HWR.DEF \
                OBJECTS/INPUTC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF OBJECTS/WINC.DEF UI.DEF VM.DEF \
                OBJECTS/PROCESSC.DEF GCNLIST.DEF OBJECTS/TEXT/TCOMMON.DEF \
                STYLESH.DEF IACP.DEF OBJECTS/UIINPUTC.DEF \
                OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF \
                INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF DISK.DEF DRIVE.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF PALM/MACROS.DEF \
                WCCONSTANT.DEF WCCLASSES.DEF WCAPPLICATION.DEF WC.RDEF \
                WCINITFILE.ASM INITFILE.DEF WCINIT.ASM WCUI.ASM \
                WCLISTS.ASM WCUSER.ASM WCALARM.ASM

wclockEC.geo wclock.geo : GEOS.LDF UI.LDF 