#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = wclock
ASM_TO_OBJS     = wcMain.asm
UI_TO_RDFS      = wc.ui
SRCS            = wcUI.asm wcUser.asm wcInitFile.asm wcMain.asm wcLists.asm\
                  wcInit.asm wcAlarm.asm wcGeode.def macros.def\
                  wcApplication.def wcConstant.def wcClasses.def\
                  uiStrings.ui wc.ui
OBJS            = wcMain.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
