#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = solitaire
ASM_TO_OBJS     = solitaire.asm
UI_TO_RDFS      = solitaire.ui
SRCS            = solitaire.asm solitaireHand.asm solitaireTalon.asm\
                  solitaireGame.asm solitaireMacros.def solitaireSizes.def\
                  solitaire.ui
OBJS            = solitaire.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
