STREAM.obj \
STREAM.eobj: GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF OBJECT.DEF \
                LMEM.DEF EC.DEF LIBRARY.DEF THREAD.DEF DRIVER.DEF \
                INTERNAL/SEMINT.DEF INTERNAL/INTERRUP.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/STRDRINT.DEF

StreamEC.geo Stream.geo : GEOS.LDF 