#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = BBXBROW
JS              = browser.goc sebrowse.goc
INIT            = EXPIRE.GOC INIT.GOC EXPIREUI.GOH
ASMTOOLS        = asmtoolsManager.asm
HTMLVIEW        = AWATCHER.GOC IMPORTG.GOC LoadURL.goc scrapbk.goc\
                  STATTEXT.GOC UIOften.goc OpenClos.goc GLBANIM.GOC\
                  HTMLVIEW.GOC UIAction.goc UIRare.goc
NAVIGATE        = BOOKCLAS.GOC BOOKMARK.GOC FAVORCLS.GOC FAVORITE.GOC\
                  NAVCACHE.GOC NAVIGATE.GOC
URLDOC          = LOCALPAG.GOC URLDOC.GOC
URLDOCCT        = URLDOCCT.GOC
URLFETCH        = URLFETCH.GOC
URLFRAME        = FRFETCH.GOC URLFRAME.GOC
URLTEXT         = URLTEXT.GOC URLTEXT2.GOC
UI_TO_RDFS      =
OBJS            = browser.obj sebrowse.obj EXPIRE.obj INIT.obj AWATCHER.obj\
                  IMPORTG.obj LoadURL.obj scrapbk.obj STATTEXT.obj\
                  UIOften.obj OpenClos.obj GLBANIM.obj HTMLVIEW.obj\
                  UIAction.obj UIRare.obj BOOKCLAS.obj BOOKMARK.obj\
                  FAVORCLS.obj FAVORITE.obj NAVCACHE.obj NAVIGATE.obj\
                  LOCALPAG.obj URLDOC.obj URLDOCCT.obj URLFETCH.obj\
                  FRFETCH.obj URLFRAME.obj URLTEXT.obj URLTEXT2.obj
COMMON          = BOOKCLAS.GOH BOOKMARK.GOH BOOKUI.GOH EXPIRE.GOH\
                  FAVORCLS.GOH FAVORITE.GOH FAVORUI.GOH GLBANIM.GOH\
                  HTMLV_UI.GOH HTMLVIEW.GOH IMPORTG.GOH javascr.h\
                  LOCALUI.GOH OPTIONS.GOH prodGPC.goh prodNDO.goh\
                  sebrowse.h STATTEXT.GOH URLFETCH.GOH
MODULES         = ASMTOOLS
CMODULES        = JS init htmlview navigate urldoc urldocct urlfetch\
                  urlframe urltext
SRCS            = $(JS) $(INIT) $(ASMTOOLS) $(HTMLVIEW) $(NAVIGATE)\
                  $(URLDOC) $(URLDOCCT) $(URLFETCH) $(URLFRAME) $(URLTEXT)\
                  $(COMMON)
LOBJS           =

PRODUCTS        = AB  JS JSAB #JSABDBCS JSDBCS ABDBCS DBCS

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(AB/$(DEPFILE))
#include "AB/$(DEPFILE)"
#endif

#if exists(ABDBCS/$(DEPFILE))
#include "ABDBCS/$(DEPFILE)"
#endif

#if exists(DBCS/$(DEPFILE))
#include "DBCS/$(DEPFILE)"
#endif

#if exists(JS/$(DEPFILE))
#include "JS/$(DEPFILE)"
#endif

#if exists(JSAB/$(DEPFILE))
#include "JSAB/$(DEPFILE)"
#endif

#if exists(JSABDBCS/$(DEPFILE))
#include "JSABDBCS/$(DEPFILE)"
#endif

#if exists(JSDBCS/$(DEPFILE))
#include "JSDBCS/$(DEPFILE)"
#endif
