#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = newsread
ART             = ActnBarM.goc NaviBarM.goc MListM.goc GI020G_8.goh\
                  mkrComposeSign.goh GI020H_8.goh NR018_8.goh NR017_8.goh\
                  NR009_8.goh GI020J_8.goh Token.goh NR001_8.goh\
                  NR010_8.goh NR004_8.goh GI020I_8.goh GI020F_8.goh\
                  GI020B_8.goh GI020K_8.goh NR002_8.goh NR003_8.goh\
                  bbxreg.goh NR015_8.goh GI020C_8.goh GI020D_8.goh\
                  GI020L_8.goh GI020A_8.goh GI020N_8.goh NR005_8.goh\
                  NR006_8.goh NR000_8.goh NR007_8.goh GI020M_8.goh\
                  GI020E_8.goh NR016_8.goh GI020O_8.goh NR008_8.goh
UI              = APPUI.goc
MAIN            = BUCKETHA.c utils.goc newsdata.goc NData3.goc NDATA2.goc
SOCKETS         = sockGet.goc sockGrps.goc sockMain.goc sockPost.goc
PROCESS         = AtrList.goc MainView.goc SaveFile.goc PostWin.goc\
                  ActnBar.goc NaviBar.goc PickList.goc MainList.goc\
                  procMain.goc
LOCALIZE        = strings.goc strings.goh
UICLASS         = NewGrpC.goc TitlMkrC.goc NCONTENT.goc gTxtChgC.goc\
                  SettDlgC.goc AddDlgC.goc statdiag.goc NTEXT.goc\
                  ReszeLst.goc HddnBtn.goc glbanim.goc shToolBr.goc\
                  NApp.goc statdiag.goh TitlMkrC.goh glbanim.goh NApp.goh\
                  shToolBr.goh ReszeLst.goh HddnBtn.goh
UI_TO_RDFS      =
OBJS            = ActnBarM.obj NaviBarM.obj MListM.obj APPUI.obj\
                  BUCKETHA.obj utils.obj newsdata.obj NData3.obj NDATA2.obj\
                  sockGet.obj sockGrps.obj sockMain.obj sockPost.obj\
                  AtrList.obj MainView.obj SaveFile.obj PostWin.obj\
                  ActnBar.obj NaviBar.obj PickList.obj MainList.obj\
                  procMain.obj strings.obj NewGrpC.obj TitlMkrC.obj\
                  NCONTENT.obj gTxtChgC.obj SettDlgC.obj AddDlgC.obj\
                  statdiag.obj NTEXT.obj ReszeLst.obj HddnBtn.obj\
                  glbanim.obj shToolBr.obj NApp.obj
COMMON          = newssock.h utils.goh extern.goh news.h options.goh\
                  bucketha.h newsread.goh newsdata.goh errors.goh
MODULES         =
CMODULES        = Art UI Main Sockets Process Localize UIClass
SRCS            = $(ART) $(UI) $(MAIN) $(SOCKETS) $(PROCESS) $(LOCALIZE)\
                  $(UICLASS) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
