#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = newsread
ART             = ActnBarM.goc MListM.goc NaviBarM.goc GI020A_8.goh\
                  GI020B_8.goh GI020C_8.goh GI020D_8.goh GI020E_8.goh\
                  GI020F_8.goh GI020G_8.goh GI020H_8.goh GI020I_8.goh\
                  GI020J_8.goh GI020K_8.goh GI020L_8.goh GI020M_8.goh\
                  GI020N_8.goh GI020O_8.goh mkrComposeSign.goh NR000_8.goh\
                  NR001_8.goh NR002_8.goh NR003_8.goh NR004_8.goh\
                  NR005_8.goh NR006_8.goh NR007_8.goh NR008_8.goh\
                  NR009_8.goh NR010_8.goh NR015_8.goh NR016_8.goh\
                  NR017_8.goh NR018_8.goh Token.goh
LOCALIZE        = strings.goc strings.goh
MAIN            = BUCKETHA.c NDATA2.goc NData3.goc newsdata.goc utils.goc
PROCESS         = ActnBar.goc AtrList.goc MainList.goc MainView.goc\
                  NaviBar.goc PickList.goc PostWin.goc procMain.goc\
                  SaveFile.goc
SOCKETS         = sockGet.goc sockGrps.goc sockMain.goc sockPost.goc
UI              = APPUI.goc
UICLASS         = AddDlgC.goc glbanim.goc gTxtChgC.goc HddnBtn.goc NApp.goc\
                  NCONTENT.goc NewGrpC.goc NTEXT.goc ReszeLst.goc\
                  SettDlgC.goc shToolBr.goc statdiag.goc TitlMkrC.goc\
                  glbanim.goh HddnBtn.goh NApp.goh ReszeLst.goh\
                  shToolBr.goh statdiag.goh TitlMkrC.goh
UI_TO_RDFS      =
OBJS            = ActnBarM.obj MListM.obj NaviBarM.obj strings.obj\
                  BUCKETHA.obj NDATA2.obj NData3.obj newsdata.obj utils.obj\
                  ActnBar.obj AtrList.obj MainList.obj MainView.obj\
                  NaviBar.obj PickList.obj PostWin.obj procMain.obj\
                  SaveFile.obj sockGet.obj sockGrps.obj sockMain.obj\
                  sockPost.obj APPUI.obj AddDlgC.obj glbanim.obj\
                  gTxtChgC.obj HddnBtn.obj NApp.obj NCONTENT.obj\
                  NewGrpC.obj NTEXT.obj ReszeLst.obj SettDlgC.obj\
                  shToolBr.obj statdiag.obj TitlMkrC.obj
COMMON          = bucketha.h errors.goh extern.goh news.h newsdata.goh\
                  newsread.goh newssock.h options.goh utils.goh
MODULES         =
CMODULES        = Art Localize Main Process Sockets UI UIClass
SRCS            = $(ART) $(LOCALIZE) $(MAIN) $(PROCESS) $(SOCKETS) $(UI)\
                  $(UICLASS) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
