#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = NewsRead
ART             = ActnBarM.goc MListM.goc NaviBarM.goc GI020A-8.GOH\
                  GI020B-8.GOH GI020C-8.GOH GI020D-8.GOH GI020E-8.GOH\
                  GI020F-8.GOH GI020G-8.GOH GI020H-8.GOH GI020I-8.GOH\
                  GI020J-8.GOH GI020K-8.GOH GI020L-8.GOH GI020M-8.GOH\
                  GI020N-8.GOH GI020O-8.GOH mkrComposeSign.goh NR000-8.GOH\
                  NR001-8.GOH NR002-8.GOH NR003-8.GOH NR004-8.GOH\
                  NR005-8.GOH NR006-8.GOH NR007-8.GOH NR008-8.GOH\
                  NR009-8.GOH NR010-8.GOH NR015-8.GOH NR016-8.GOH\
                  NR017-8.GOH NR018-8.GOH Token.goh
LOCALIZE        = STRINGS.GOC STRINGS.GOH
MAIN            = BUCKETHA.C NDATA2.goc NData3.goc NEWSDATA.GOC UTILS.GOC
PROCESS         = ActnBar.goc AtrList.goc MainList.goc MainView.goc\
                  NaviBar.goc PickList.goc PostWin.goc procMain.goc\
                  SaveFile.goc
SOCKETS         = sockGet.goc sockGrps.goc sockMain.goc sockPost.goc
UI              = APPUI.GOC
UICLASS         = AddDlgC.goc glbanim.goc gTxtChgC.goc HddnBtn.goc NApp.goc\
                  NCONTENT.GOC NewGrpC.goc NewsApp.goc NTEXT.GOC\
                  ReszeLst.goc SettDlgC.goc shToolBr.goc STATDIAG.GOC\
                  TitlMkrC.goc glbanim.goh HddnBtn.goh NApp.goh\
                  ReszeLst.goh shToolbr.goh STATDIAG.GOH TitlMkrC.goh
UI_TO_RDFS      =
OBJS            = ActnBarM.obj MListM.obj NaviBarM.obj STRINGS.obj\
                  BUCKETHA.obj NDATA2.obj NData3.obj NEWSDATA.obj UTILS.obj\
                  ActnBar.obj AtrList.obj MainList.obj MainView.obj\
                  NaviBar.obj PickList.obj PostWin.obj procMain.obj\
                  SaveFile.obj sockGet.obj sockGrps.obj sockMain.obj\
                  sockPost.obj APPUI.obj AddDlgC.obj glbanim.obj\
                  gTxtChgC.obj HddnBtn.obj NApp.obj NCONTENT.obj\
                  NewGrpC.obj NewsApp.obj NTEXT.obj ReszeLst.obj\
                  SettDlgC.obj shToolBr.obj STATDIAG.obj TitlMkrC.obj
COMMON          = BUCKETHA.H ERRORS.GOH EXTERN.GOH NEWS.H NEWSDATA.GOH\
                  NEWSREAD.GOH NEWSSOCK.H OPTIONS.GOH UTILS.GOH
MODULES         =
CMODULES        = Art Localize Main Process Sockets UI UIClass
SRCS            = $(ART) $(LOCALIZE) $(MAIN) $(PROCESS) $(SOCKETS) $(UI)\
                  $(UICLASS) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
