rem All Rem'd so I don't accidentally regenerate ;-)

rem cvtpcx -2 -w48 -h30 -m1 -G -nQTip1 -oQTip1.goh tip1.pcx

rem cvtpcx -2 -w66 -h66 -m1 -G -nQTFol -oQTFol.goh hint1.pcx
rem cvtpcx -2 -w73 -h50 -m1 -G -nQTOpts -oQTOpts.goh hint2.pcx

rem cvtpcx -2 -w68 -h68 -m1 -G -g -oFoll2.goh flw011-8.pcx
rem cvtpcx -2 -w68 -h68 -m1 -G -g -oFoll6.goh flw012-8.pcx
rem cvtpcx -2 -w68 -h68 -m1 -G -g -oFoll1.goh flw013-8.pcx
rem cvtpcx -2 -w68 -h68 -m1 -G -g -oFoll5.goh flw014-8.pcx
rem cvtpcx -2 -w68 -h68 -m1 -G -g -oFoll4.goh flw015-8.pcx
rem cvtpcx -2 -w68 -h68 -m1 -G -g -oFoll8.goh flw016-8.pcx
rem cvtpcx -2 -w68 -h68 -m1 -G -g -oFoll3.goh flw017-8.pcx
rem cvtpcx -2 -w68 -h68 -m1 -G -g -oFoll7.goh flw018-8.pcx
