#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1991 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	bugs
# FILE: 	browniepoints
# AUTHOR: 	Jon Witort, November 19, 1992
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	jon	19 nov 1992	initial revision
#
#	$Id: browniepoints,v 1.5 93/05/10 15:27:31 chrisb Exp $
#
###############################################################################

PATH=${PATH}:/n/sybase/sqr:/n/sybase/bin
SYBASE="/n/sybase"
export SYBASE
TERM=x11

echo 'select whose, total = count(*), crash = 0, high = 0, med = 0, low = 0, old = 0
into '$USER'reporttable
from bugs
where (status = "FIXED" or status = "CLOSED") and duplicate = NULL
group by whose
go

select whose, crash = count(*) into '$USER'temptable
from bugs
where (status = "FIXED" or status = "CLOSED") and severity = "CRASH" and duplicate = NULL
group by whose
go

update '$USER'reporttable
set '$USER'reporttable.crash = '$USER'temptable.crash
from '$USER'reporttable, '$USER'temptable
where '$USER'reporttable.whose = '$USER'temptable.whose
go

drop table '$USER'temptable
go

select whose, high = count(*) into '$USER'temptable
from bugs
where (status = "FIXED" or status = "CLOSED") and severity = "HIGH" and duplicate = NULL
group by whose
go

update '$USER'reporttable
set '$USER'reporttable.high = '$USER'temptable.high
from '$USER'reporttable, '$USER'temptable
where '$USER'reporttable.whose = '$USER'temptable.whose
go

drop table '$USER'temptable
go

select whose, med = count(*) into '$USER'temptable
from bugs
where (status = "FIXED" or status = "CLOSED") and severity = "MEDIUM" and duplicate = NULL
group by whose
go

update '$USER'reporttable
set '$USER'reporttable.med = '$USER'temptable.med
from '$USER'reporttable, '$USER'temptable
where '$USER'reporttable.whose = '$USER'temptable.whose
go

drop table '$USER'temptable
go

select whose, low = count(*) into '$USER'temptable
from bugs
where (status = "FIXED" or status = "CLOSED") and severity = "LOW" and duplicate = NULL
group by whose
go

update '$USER'reporttable
set '$USER'reporttable.low = '$USER'temptable.low
from '$USER'reporttable, '$USER'temptable
where '$USER'reporttable.whose = '$USER'temptable.whose
go

drop table '$USER'temptable
go

select whose, total_chml = convert(varchar(20),convert(varchar(10),total) + ": " +
convert(varchar(10),crash) + "," +
convert(varchar(10),high) + "," +
convert(varchar(10),med) + "," +
convert(varchar(10),low))
from '$USER'reporttable
order by total desc
go

drop table '$USER'reporttable
go

quit' | /n/sybase/bin/isql -U jon -P jon
