#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1992 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	checkInclude
# FILE: 	checkInclude
# AUTHOR: 	Josh     Wed Nov  4 
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	josh	11/4/92		check @include/#include consistency
#
# DESCRIPTION:
#	A script to ensure consistency between the type of 
#	include (@include/#include) and the file included
#
#	$Id: checkInclude,v 1.1 92/11/04 18:54:12 josh Exp $
#
###############################################################################

echo CInclude files with inconsistent @includes/#includes:
for name in `find /staff/pcgeos/CInclude -name "*h" -print`  
do egrep -l '(#include[ 	].*\.goh)|(@include[ 	].*\.h)' $name;
done
echo checkInclude complete
