#!/bin/sh -
##############################################################################
#
# 	Copyright (c) Berkeley Softworks 1989 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts -- File Installation and Checkout
# FILE: 	countme
# AUTHOR: 	Tony
#
#	$Id: countme,v 1.1 89/11/02 19:49:36 tony Exp $
#
###############################################################################
#
#	Usage: countme <file>
#
#set -x
#
trap "rm -f /tmp/checkme.1 /tmp/checkme.2 /tmp/checkme.3" 0 1 2 3 15
#
sed -n -e 's/.*METHOD_\(.*\),/METHOD_\1/p' $1 \
	| sed -e 's/, \*....:....//' -e 's/, \^l....:....//' \
	| sort > /tmp/checkme.1

awk '
prev1 == "" {
	x = 0
	y = 0
	prev1 = $1
	prev2 = $2
}
$1 == prev1 && $2 == prev2 {
	x = x + 1
}
$1 != prev1 || $2 != prev2 {
	print x " times <" prev1 "> sent to <" prev2 ">"
	x = 1
}
$1 == prev1 {
	y = y + 1
}
$1 != prev1 {
	if (y != 0) {
		print "TOTAL " y " for <" prev1 ">" > "/tmp/checkme.2"
	}
	y = 1
}
{
	prev1 = $1
	prev2 = $2
} 
' /tmp/checkme.1 | sort -n -r > /tmp/checkme.3

sort -n -r +1 /tmp/checkme.2
cat /tmp/checkme.3
