#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1993 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts -- Copy a large branch
# FILE: 	cpLots
# AUTHOR: 	don
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	chris	5/18/93		Initial Revision
#
# DESCRIPTION:
#	Shell script for copying a large branch or number of files
#
# USAGE:
#	cpLots <source> <destination>

#	$Id: cpLots,v 1.1 93/05/20 02:03:09 don Exp $
# 
###############################################################################

if [ "$1" = "" -o "$2" = "" ]; then
	echo "Usage: cpLots <source> <destination>"
else
	echo Source: $1
	echo Destination: $2
	echo "Copying..."
	cd $1
	tar cf - . | (chdir $2 && tar xfBp -)
	echo "Done"
fi
