#!/bin/sh -
##############################################################################
#
# 	Copyright (c) Berkeley Softworks 1989 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts -- Mystery changes made
# FILE: 	createCSamp
# AUTHOR: 	chris 
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	chris	7/ 1/91		Initial Revision
#
# DESCRIPTION:
#	This will set up a very simple sample C app sampnameec.geo in the 
#       directory SampName (under the current directory), create the 
#	appropriate stuff in the installed source directory as well, and 
#	rename various labels to be prefixed with SampName.  The source files
#	are drawn from /staff/pcgeos/SDK_C/Template.  Warning:  createCSamp
#	does not create a directory in the Installed tree.  
#
#	Usage:	
#		createCSamp sampname SampName
#
#	$Id: createCSamp,v 1.11 92/04/06 15:50:06 chris Exp $
#
###############################################################################
templateupper=Template
templatelower=template
cwd=`pwd`
rootdir=`expr "$cwd" : '^\(.*/'${ROOTDIR-pcgeos}'\).*$'`


if [ "$1" = "" ]; then
    echo
    echo "Usage: createCSamp sampname SampName [TemplateDir templatename]"
    echo
    echo "Creates a sample C program \"sampname.geo\" under directory \"SampName\""
    echo "with an empty view and the title \"C SampName Sample Application.\""
    echo "Optional 3rd argument allows the template to come from another directory"
    echo "below Appl/SDK_C, with the 4th argument the text to replace with"
    echo "sampname everywhere (must be a lowercase version of the 3rd argument.)"
    echo "This creates the necessary stuff in the installed source, but does *not*"
    echo "create a directory under Installed."
    exit 1
fi
if [ "$2" = "" ]; then
    echo
    echo "Usage: createCSamp sampname SampName [TemplateDir templatename]"
    echo
    echo "Creates a sample C program \"sampname.geo\" under directory \"SampName\""
    echo "with an empty view and the title \"C SampName Sample Application.\""
    echo "Optional 3rd argument allows the template to come from another directory"
    echo "below Appl/SDK_C, with the 4th argument the text to replace with"
    echo "sampname everywhere (must be a lowercase version of the 3rd argument.)"
    echo "This creates the necessary stuff in the installed source, but does *not*"
    echo "create a directory under Installed."
    exit 1
fi
if [ "$3" != "" ]; then
    templateupper=$3
    templatelower=$4
    if [ "$4" = "" ]; then
    echo
    echo "Usage: createCSamp sampname SampName [TemplateDir templatename]"
    echo
    echo "Creates a sample C program \"sampname.geo\" under directory \"SampName\""
    echo "with an empty view and the title \"C SampName Sample Application.\""
    echo "Optional 3rd argument allows the template to come from another directory"
    echo "below Appl/SDK_C, with the 4th argument the text to replace with"
    echo "sampname everywhere (must be a lowercase version of the 3rd argument.)"
    echo "This creates the necessary stuff in the installed source, but does *not*"
    echo "create a directory under Installed."
    exit 1
    fi
fi


mkdir $2
cd `otherdir`
mkdir $2
cd $2
mkdir RCS
cd `otherdir`
cp $rootdir/Appl/SDK_C/$templateupper/$templatelower.goc .
cp $rootdir/Appl/SDK_C/$templateupper/$templatelower.gp .
chmod +w $templatelower.goc
chmod +w $templatelower.gp
sed -e s/$templatelower/$1/g -e s/$templateupper/$2/g $templatelower.goc > $1.goc
sed -e s/$templatelower/$1/g -e s/$templateupper/$2/g $templatelower.gp > $1.gp
rm $templatelower.goc
rm $templatelower.gp
mkmf
mv Makefile `otherdir`
mv *.mk `otherdir`
ln -s `otherdir`/Makefile

