#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1991 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	scripts
# FILE: 	find_changed
# AUTHOR: 	Adam de Boor, 20 November 1991
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	ardeb	11/20/91	Initial Revision
#
# DESCRIPTION:
#	A script to find what has changed since a particular milestone branch
#	was created
#
#	Usage:	find_changed <X branch> <milestone>
#
#	$Id: find_changed,v 1.1 91/11/20 12:53:50 adam Exp $
#
###############################################################################
if [ ! -f /staff/pcgeos/$2/RELEASED ]; then
    echo $0: RELEASED file not created for milestone $2, you are hosed
    exit 1
fi

find /staff/pcgeos/$1/Appl \
     /staff/pcgeos/$1/Library \
     /staff/pcgeos/$1/Driver \
     /staff/pcgeos/$1/Kernel \
    -type f \! -name \*,v \
    -newer /staff/pcgeos/$2/RELEASED -print |
    sed -e 's,/[^/]*$,,' |
    sort -u |
    while read dir; do
	if [ -f $dir/Makefile ]; then
	    echo $dir
	fi
    done |
    sed -e "s,/staff/pcgeos/$1/,,"
