#!/bin/sh -
##############################################################################
#
# 	Copyright (c) Geoworks 1994 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts
# FILE: 	findMice
# AUTHOR: 	Gene Anderson, January 16, 1993
#
# DESCRIPTION:
#
#	Finds and prints all keyboard devices supported by PC/GEOS drivers
#
# USAGE:
#	Run this from /staff/pcgeos/Driver/Mouse by doing:
#
#		findKbd | sort > kbdList &
#
#	or something like that :)
#
#	$Id: findKbd,v 1.1 94/08/26 12:23:47 gene Exp $
#
###############################################################################

#
# Throw away all characters leading up until the first quote (presumed to be
# preceded by a space or a tab, and then throw away everything after the last
# quote
#
find . \( -name \*.asm \) -print \
	| xargs \egrep -n chunk.char \
	| sed 's/.*[ 	]"//' | sed 's/".*//'

find . \( -name \*.asm \) -print \
	| xargs \egrep -n LocalDefString \
	| sed 's/.*[ 	]<"//' | sed 's/".*//'


