#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1993 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts
# FILE: 	findMice
# AUTHOR: 	Don Reeves, January 16, 1993
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	Don	1/16/93		Initial Revision
#
# DESCRIPTION:
#
#	Finds and prints all printer devices supported by PC/GEOS drivers
#
# USAGE:
#	Run this from /staff/pcgeos/Driver/Mouse by doing:
#
#		findMice | sort > miceList &
#
#	or something like that :)
#
#	$Id: findMice,v 1.1 93/01/16 17:17:52 don Exp $
#
###############################################################################

#
# Throw away all characters leading up until the first quote (presumed to be
# preceded by a space or a tab, and then throw away everything after the last
# quote
#
find . \( -name \*.asm \) -print \
	| xargs egrep -n chunk.char \
	| sed "s/.*[ 	]'//" | sed "s/'.*//"



