#!/bin/sh -
##############################################################################
#
# 	Copyright (c) Berkeley Softworks 1989 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts -- Revision Merging
# FILE: 	fui
# AUTHOR: 	Adam de Boor, July 24, 1989
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	ardeb	7/24/89		Initial Revision
#
# DESCRIPTION:
#
#	finds and prints all files that appear to need to be installed in the 
#	directory and its sub directories
#
#	$Id: fui,v 1.20 96/10/25 21:07:31 canavese Exp $
#
###############################################################################
#
# Usage: fui [<directory>+] [<args for 'find'>+] 
#

#
# VARIABLES:
#	findflags	= flags passed to 'find'
#	dirs		= directories to start searching for 'find'
#	hasfindflags 	= 1 if there is flags for 'find'. Otherwise,
#			  it is empty.
#	diedie		= 1 if any directory argument passed in is not
#			  a directory. Otherwise, it is empty.
#

for i in $@; do
    case $i in
	-*)
	    #
	    # When we detect "-*", we know that we start parsing
	    # 'find' arguments.
	    #
	    findflags="$findflags ""$i"
	    hasfindflags=1
	    ;;
	*)	  
	    if [ "$hasfindflags" ]; then
		#
		# We have 'find' flags that we need to store
		#
		findflags="$findflags $i"
	    else
		#
		# We do not have 'find' flags yet, so keep on checking
		# directories.
		#
		if [ ! -d $i ]; then
		    echo fui: \"$i\" is not a directory >&2
		    diedie=1
		else
		    dirs="$dirs $i"
		fi
	    fi
	    ;;
    esac
done

if [ "$diedie" ]; then exit 1; fi

#
# If there is directory passed, format it. Otherwise, the current
# directory is used as default.
#
if [ "$dirs" ]; then
    # Strip out trailing /'s since find doesn't like them.. sigh..
    dirs=`echo "$dirs" | sed -e 's:/\([ 	]\):\1:g' -e 's:/$::g'`
else
    dirs="."
fi

find $dirs $findflags \( \( -name \*.asm \
	 -o  -name \*.def \
	 -o  -name \*.sec \
	 -o  -name \*.gp \
	 -o  -name \*.ui \
	 -o  -name \*.uih \
	 -o  -name \*.c \
	 -o  -name \*.C \
	 -o  -name \*.cc \
	 -o  -name \*.cpp \
	 -o  -name \*.s \
	 -o  -name \*.y \
	 -o  -name \*.h \
	 -o  -name \*.hi \
	 -o  -name \*.ih \
	 -o  -name \*.bas \
	 -o  -name \*.mk \
	 -o  -name \*.temp \
	 -o  -name \*.tcl \
	 -o  -name \*.pl \
	 -o  -name \*.build \
	 -o  -name \*.filetree \
	 -o  -name \*.ini \
	 -o  -name \*.bat \
	 -o  -name \*.goc \
	 -o  -name \*.goh \) \
	 -a \( \! \( -name \*_e.c \
	          -o -name \*_g.c \
	          -o -name \*_loc.asm \
	          -o -name depends.mk \
	          -o -name dependencies.mk \) \) \
	\) -type f -print

exit 0
