#!/bin/csh -f
#
# A shell script for extracting pcgeos headers from files. Call with:
#
#	hdr [filelist]
#
#	$Id: hdr,v 1.5 89/07/20 15:02:27 matt Exp $
# 
set sedpath = /staff/pcgeos/Tools/scripts/SedScripts
set paginate = 0

# Separate switches and files from list

set files=() switches=() 
foreach i ($*)
    if ($i =~ -*) then
	set switches=($switches $i)
    else
	set files=($files $i)
    endif
end

# Check the switches and do the right thing

foreach i ($switches)
    if ($i =~ *-p*) then
	set paginate = 1
    endif
end

# Go through the supplied file list and extract the header,
# writing each to stdio

foreach i ($files)
   if ($paginate) then
	echo ""
   else
	echo " "
   endif

   echo $i\:
   sed -n -f $sedpath/extractHeader.sed $i
end
