#!/bin/sh -
#
# $Id: lc,v 1.2 95/02/16 15:02:41 chrisb Exp $
#

#
# deal with the arguments, if any
#
suffix="*.eobj"
sym=0
while [ $# -ne 0 ]; do
    case $1 in
	-s)
		suffix="*.sym"
		sym=1
		;;
	-n)	suffix="*.obj"
		;;
	*)	args="$args $1"
		;;
    esac
    shift
done

#
# figure out the directory
#
if [ ! "$args" ]; then
    args=`pwd`
fi
cd $args
echo -n $args

# Do some preprocessing, because I can't figure out how to make this
# work in the main loop

if [ $sym = 1 ]; then
    i=0
    for j in $suffix; do
	case $j in
	    *ec.sym)
	         # do nothing
		;;
	    *)
		i=`expr $i + 1`
		if [ $i = 2 ]; then
		    echo
    		    echo "  multiple symbol files in this directory"
		    exit 1
		fi
		;;
	esac
    done
fi
#
# grep me...
#

for j in $suffix; do
    case $j in 
	*ec.sym)
	    # Do nothing -- ignore EC symbol files
	    ;;
	*)
	    printobj $j | egrep 'line .* at '
	    ;;
    esac
done | wc -l









