#!/bin/sh -
##############################################################################
#
# 	Copyright (c) Geoworks 1990 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts -- Crap
# FILE: 	lines
# AUTHOR: 	Gene	4/25/90
# DESCRIPTION:
#	Count assembly source code lines in specified files & directories.
#
# USAGE:
#	lines [<directory | file>+]
#
#	(if no files or directories are specifed, uses current directory)
#
#	$Id: lines,v 1.1 90/04/25 02:16:03 gene Exp $
#
###############################################################################

#
# Process all the arguments, dealing with flags now, saving targets in $args
# for later.
#
args=""
comments=
while [ $# -ne 0 ]; do
    case $1 in
	-*) 	echo "$0: $1 flag unknown (ignored)";;
	*)	args="$args $1";;
    esac
    shift
done
#
# If no arguments, use the current directory
#
if [ ! "$args" ]; then
    args="."
fi
#
# Find all .asm, .def and .ui files, and count the number of lines in
# each. Get the grand total of all the files found in $total.
#
total=`find $args \( -name \*.asm -o -name \*.def -o -name \*.ui \) -print -exec \wc -l {} \; | sumcol 1`
#
# Print out the results in an entertaining and informative way.
#
echo $args -- $total lines total
