#!/bin/sh -
##############################################################################
#
#       Copyright (c) Berkeley Softworks 1989 -- All Rights Reserved
#
# PROJECT:      PC GEOS
# MODULE:       Tools/scripts -- World Clock
# FILE:         makewcm
# AUTHOR:       Roger Flores (via Paul Canavese), May 16, 1995
#
# REVISION HISTORY:
#       Name    Date            Description
#       ----    ----            -----------
#       pjc     7/24/89         Initial Revision
#
# DESCRIPTION:
#
#       Creates world.wcm (World Clock Data File) from world.asm
#
#       $Id: makewcm,v 1.3 96/10/21 16:39:57 warner Exp $
#
###############################################################################

if [ $# -eq 0 ]; then
	esp -I/staff/pcgeos/Appl/WorldClock/Data -I/staff/pcgeos/Include \
		cities.asm
	glue -Of -m -L/staff/pcgeos/Installed/Include -o world.wcm \
		cities.obj -l/staff/pcgeos/Library/Math/Compiler/HighC/math.lib
elif [ $1 = "DOVE" ]; then
	esp `product_flags esp DOVE` \
		-I/staff/pcgeos/Appl/WorldClock/Data \
		-I/staff/pcgeos/Include citiesDove.asm
	glue `product_flags glue DOVE` -Of -m \
		-L/staff/pcgeos/Installed/Include -o DOVE/world.wcm \
		citiesDove.obj \
		-l/staff/pcgeos/Library/Math/Compiler/HighC/math.lib
elif [ $1 = "PENELOPE" ]; then
	esp `product_flags esp PENELOPE` \
		-I/staff/pcgeos/Appl/WorldClock/Data \
		-I/staff/pcgeos/Include citiesPenelope.asm
	glue `product_flags glue PENELOPE` -Of -m \
		-L/staff/pcgeos/Installed/Include -o PENELOPE/world.wcm \
		citiesPenelope.obj \
		-l/staff/pcgeos/Library/Math/Compiler/HighC/math.lib
fi
