#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1992 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	scripts
# FILE: 	searchxref
# AUTHOR: 	Adam de Boor, Apr 28, 1992
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	ardeb	4/28/92		Initial Revision
#
# DESCRIPTION:
#	
# 	Silly little script to search a pretty-printed (or ugly-printed) xref
#	file for a routine. Use it from inside an alias, like this:
#
#		alias kref 'searchxref \!* /staff/pcgeos/Library/Kernel/xref'
#
# USAGE:
#	searchxref <func> <file>
#
#	$Id: searchxref,v 1.1 92/04/28 10:20:22 adam Exp $
#
###############################################################################
sed -n -e "
/^$1[ 	:]/,/^[^ 	]/{
	/^$1[ 	:]/{
		p
		n
	}
	/^[ 	]/p
	/^[^ 	]/q
}" $2
