#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1994 -- All Rights Reserved
#
# PROJECT:	
# MODULE:	
# FILE: 	shelp
# AUTHOR: 	Adam de Boor, Dec 19, 1994
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	ardeb	12/19/94	Initial Revision
#
# DESCRIPTION:
#	A simple script to extract the first documentation string for a command
#	from the Swat documentation file.
#
# USAGE:
#	shelp <command>
#
#	$Id: shelp,v 1.1 95/04/04 12:53:18 weber Exp $
#
###############################################################################
sed -n -e "/$1\./,//{
	/$1/s///
	//q
	p
}" /staff/pcgeos/Tools/swat/lib.new/DOC | sed -e '1d
	2s/^[0-9][0-9]*://'
