#!/bin/sh -
##############################################################################
#
# 	Copyright (c) GeoWorks 1991 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	clean
# FILE: 	clean
# AUTHOR: 	Adam de Boor, Sep  4, 1991
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	ardeb	9/ 4/91		Initial Revision
#
# DESCRIPTION:
#	A script to clean up after yourself
#
#	Usage: clean [no]
#
#	If you give the argument "no", then the things that would be
#	removed will be printed, but not removed.
#
#	$Id: tclean,v 1.1 92/11/24 12:23:01 asolovay Exp $
#
###############################################################################
usageString="Usage: clean [no]"
if [ $# -gt 1 ]; then
    echo $usageString
    exit 0
elif [ "$1" = "no" ]; then
        rm=""
elif [ $# -eq 1 ]; then
    echo $usageString
    exit 0
else
    rm="-exec rm -f {} ;"
fi

find . \( -name \*.lst -o \
	  -name core -o \
	  -name tags -o \
	  -name \*.out -o \
	  -name \*.obj -o \
	  -name \*.eobj -o \
	  -name \*.gobj -o \
	  -name \*.exe -o \
	  -name \*.ldf -o \
	  -name \*.rdef -o \
	  -name \*.grdef -o \
	  -name \*.geo -o \
	  -name \*_e.c -o \
	  -name \*_g.c -o \
	  -name \*.egc -o \
	  -name \*.map -o \
	  -name \*.o -o \
	  -name \*.a -o \
	  -name \*.sym -o \
	  -name \*~ -o \
	  -name \#\*\# -o \
	  -name \*.recover -o \
	  -name \*.recover.\* -o \
	  -name \*.backup -o \
	  -name LOCK.make \) $rm -print -o \
	\( \( -name lib -o -name tests -o -name lib.new \) -prune \)

