#!/bin/sh -
##############################################################################
#
# 	Copyright (c) Berkeley Softworks 1989 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Swat System Library
# FILE: 	tcltags
# AUTHOR: 	Adam de Boor, Dec 28, 1989
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	ardeb	12/28/89	Initial Revision
#
# DESCRIPTION:
#	This is a simple script to make a tags file for swat tcl scripts.
#
#	Usage:
#		tcltags <file>+
#
#	$Id: tcltags,v 1.4 92/12/18 19:55:33 chrisb Exp $
#
###############################################################################
(
    for file do
	tail=`expr ./${file} : '.*/\([^/]*\)$'`
	echo "$tail	$file	1"
    done
    IFS=" 	:"
    egrep '^\[?(def(var|command|subr|cmd)|proc)' $* /dev/null | \
    	while read file line; do
	    set - $line
	    echo "$2	$file	/^$line\$/"
   	done
) | sort > tags
