VGA8MANAGER.obj \
VGA8MANAGER.eobj: VIDCOMGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF DRIVER.DEF LMEM.DEF INTERNAL/SEMINT.DEF \
                GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF WIN.DEF \
                CHAR.DEF LOCALIZE.DEF SLLANG.DEF SYSTEM.DEF \
                INTERNAL/HEAPINT.DEF SYSSTATS.DEF INTERNAL/GSTATE.DEF \
                INTERNAL/TMATRIX.DEF INTERNAL/FONTDR.DEF FILE.DEF \
                INTERNAL/WINDOW.DEF INTERNAL/INTERRUP.DEF \
                INTERNAL/THREADIN.DEF INTERNAL/VIDEODR.DEF HUGEARR.DEF \
                INITFILE.DEF VGA8CONSTANT.DEF VIDCOMCONSTANT.DEF \
                VGA8MACRO.DEF VIDCOMMACRO.DEF VGA8DEVINFO.ASM \
                VIDCOMTABLES.ASM VGA8TABLES.ASM VIDCOMVARIABLE.DEF \
                VGA8VARIABLE.DEF VGA8STRINGTAB.ASM VIDCOMENTRY.ASM \
                VIDCOMOUTPUT.ASM VIDCOMCHARS.ASM VIDCOMFONT.ASM \
                VGA8UNDER.ASM VIDCOMUTILS.ASM VIDCOMREGION.ASM \
                VIDCOMXOR.ASM VIDCOMINFO.ASM VIDCOMESCAPE.ASM \
                VIDCOMPALETTE.ASM VGA8OUTPUT.ASM VGA8GENCHAR.ASM \
                VGA8UTILS.ASM VGA8CHARS.ASM VGA8POINTER.ASM \
                VGA8ESCTAB.ASM VGA8PALETTE.ASM VGA8DITHER.ASM \
                VIDCOMPOLYGON.ASM VIDCOMLINE.ASM VIDCOMPUTLINE.ASM \
                VIDCOMRASTER.ASM VGA8RASTER.ASM VGA8ADMIN.ASM \
                VIDCOMEXCLBOUNDS.ASM

VGA8EC.geo VGA8.geo : GEOS.LDF 