#!/bin/sh -f
#$Id: convert,v 1.1 98/05/19 19:31:29 joon Exp $


. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile crosswrd.pcx 1 Cword -dLC,LM,TM,TCGA $appArgs
cvtfile crosswrd.pcx 3 CwordDoc -dLC,LM, $docArgs
cvtpcx -f -m13 -t -z -nCwordTiny crosswrd.tiny.pcx


cvtfile cwtips2.pcx 7 QtipsKeyQuestion -otemp -f -R -t -L -dLC,LM,LCGA,SCGA,TM,TCGA,YC,YM,SC
sed 's/GSBeginString/GSBeginString\
		GSSaveState\
		GSSetAreaColor 255,255,255\
		GSFillRect 14,7,34,28\
		GSRestoreState/' temp > mkrQtipsKeyQuestion.ui

cvtfile cwtips2.pcx 6 QtipsKeyTap -otemp -f -R -t -L -dLC,LM,LCGA,SCGA,TM,TCGA,YM,YC,SC
sed 's/GSBeginString/GSBeginString\
		GSSaveState\
		GSSetAreaColor 255,255,255\
		GSFillRect 14,7,34,28\
		GSRestoreState/' temp > mkrQtipsKeyTap.ui

cvtfile cwtips2.pcx 6 QtipsKeyTapTap -otemp -f -R -t -L -dLC,LM,LCGA,SCGA,TM,TCGA,YM,SC,YC
sed 's/GSBeginString/GSBeginString\
		GSSaveState\
		GSSetAreaColor 255,255,255\
		GSFillRect 14,7,34,28\
		GSRestoreState/' temp > mkrQtipsKeyTapTap.ui

cvtfile cwtips2.pcx 8 QtipsKeyClue -otemp -f -R -t -L -dLC,LM,LCGA,SCGA,TM,TCGA,YM,SC,YC
sed 's/GSBeginString/GSBeginString\
		GSSaveState\
		GSSetAreaColor 255,255,255\
		GSFillRect 11,3,35,27\
		GSRestoreState/' temp > mkrQtipsKeyClue.ui

cvtfile cwtips2.pcx 5 QtipsKeyDelete -otemp -R -f -t -L -dLC,LM,LCGA,SCGA,TM,TCGA,YM,SC,YC
sed 's/GSBeginString/GSBeginString\
		GSSaveState\
		GSSetAreaColor 255,255,255\
		GSFillRect 13,8,36,29\
		GSRestoreState/' temp > mkrQtipsKeyDelete.ui



cvtfile cwtips2.pcx 2 QtipsPenQuestion -otemp -R -f -t -L -dLC,LM,LCGA,SCGA,TM,TCGA,YM,SC,YC
sed 's/GSBeginString/GSBeginString\
		GSSaveState\
		GSSetAreaColor 255,255,255\
		GSFillRect 12,7,32,28\
		GSRestoreState/' temp > mkrQtipsPenQuestion.ui

cvtfile cwtips2.pcx 3 QtipsPenTap -otemp -R -f -t -L -dLC,LM,LCGA,SCGA,TM,TCGA,YM,SC,YC
sed 's/GSBeginString/GSBeginString\
		GSSaveState\
		GSSetAreaColor 255,255,255\
		GSFillRect 12,7,32,28\
		GSFillRect 21,0,27,7\
		GSRestoreState/' temp > mkrQtipsPenTap.ui

cvtfile cwtips2.pcx 0 QtipsPenLarger -otemp -R -f -t -L -dLC,LM,LCGA,SCGA,TM,TCGA,YM,SC,YC
sed 's/GSBeginString/GSBeginString\
		GSSaveState\
		GSSetAreaColor 255,255,255\
		GSFillRect 12,6,32,27\
		GSRestoreState/' temp > mkrQtipsPenLarger.ui

cvtfile cwtips2.pcx 4 QtipsPenClue -otemp -R -f -t -L -dLC,LM,LCGA,SCGA,TM,TCGA,YM,SC,YC
sed 's/GSBeginString/GSBeginString\
		GSSaveState\
		GSSetAreaColor 255,255,255\
		GSFillRect 11,3,34,27\
		GSFillRect 25,0,31,3\
		GSRestoreState/' temp > mkrQtipsPenClue.ui

cvtfile cwtips2.pcx 1 QtipsPenMinus -otemp -R -f -t -L -dLC,LM,LCGA,SCGA,TM,TCGA,YM,SC,YC
sed 's/GSBeginString/GSBeginString\
		GSSaveState\
		GSSetAreaColor 255,255,255\
		GSFillRect 12,7,32,28\
		GSRestoreState/' temp > mkrQtipsPenMinus.ui


rm temp




