DBCS/PS2.obj \
DBCS/PS2.eobj: ../MOUSECOMMON.ASM GEOS.DEF HEAP.DEF LMEM.DEF GEODE.DEF \
                RESOURCE.DEF EC.DEF ASSERT.DEF DISK.DEF FILE.DEF \
                DRIVE.DEF DRIVER.DEF INITFILE.DEF CHAR.DEF TIMER.DEF \
                INPUT.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF \
                HWR.DEF TIMEDATE.DEF SEM.DEF INTERNAL/IM.DEF \
                INTERNAL/SEMINT.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF OBJECT.DEF CHUNKARR.DEF GEOWORKS.DEF \
                INTERNAL/HEAPINT.DEF SYSSTATS.DEF INTERNAL/INTERRUP.DEF \
                INTERNAL/KBDMAP.DEF OBJECTS/UIINPUTC.DEF LOCALIZE.DEF \
                SLLANG.DEF INTERNAL/KBDDR.DEF INTERNAL/MOUSEDR.DEF \
                INTERNAL/DOS.DEF FILEENUM.DEF SYSTEM.DEF \
                INTERNAL/POWERDR.DEF UI.DEF VM.DEF TEXT.DEF WIN.DEF \
                GCNLIST.DEF OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF \
                INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF

DBCS/PS2EC.geo DBCS/PS2.geo : GEOS.LDF 
