#!/bin/sh -f
#
#$Id: convert,v 1.1 98/04/28 10:33:10 joon Exp $
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps1.pcx 0 GeoWrite $appArgs
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps1.pcx 1 GeoWriteDoc $docArgs

cvtpcx -f -m13 -t -z -nGeoWriteTiny newwrite.tiny.pcx
cvtpcx -f -m2 -t -z -x0 -y192 -nEditTextTool grobj.pcx
cvtpcx -f -m2 -t -z -x48 -y0 -nBitmapPtrTool grobj.pcx
