ACT_MTDS.obj \
ACT_MTDS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
ACT_MTDS.obj \
ACT_MTDS.eobj: ACT_MTDS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
BNKR_UI.obj \
BNKR_UI.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H BBOX.GOH \
                BBICONS.GOH
BNKR_UI.obj \
BNKR_UI.eobj: BNKR_UI.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H OBJECT.H \
                LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H GSTRING.H \
                TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H TIMEDATE.H \
                FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
CATSTRS.obj \
CATSTRS.eobj: 
CATSTRS.obj \
CATSTRS.eobj: CATSTRS.GOC GEOS.H GEODE.H OBJECT.H LMEM.H
CKP_MTDS.obj \
CKP_MTDS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
CKP_MTDS.obj \
CKP_MTDS.eobj: CKP_MTDS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
DOC_MTDS.obj \
DOC_MTDS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
DOC_MTDS.obj \
DOC_MTDS.eobj: DOC_MTDS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
EXP_MTDS.obj \
EXP_MTDS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
EXP_MTDS.obj \
EXP_MTDS.eobj: EXP_MTDS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
FNCTNS.obj \
FNCTNS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
FNCTNS.obj \
FNCTNS.eobj: FNCTNS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H OBJECT.H \
                LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H GSTRING.H \
                TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H TIMEDATE.H \
                FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
IMP_MTDS.obj \
IMP_MTDS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
IMP_MTDS.obj \
IMP_MTDS.eobj: IMP_MTDS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
LST_MTDS.obj \
LST_MTDS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
LST_MTDS.obj \
LST_MTDS.eobj: LST_MTDS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
MLT_MTDS.obj \
MLT_MTDS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
MLT_MTDS.obj \
MLT_MTDS.eobj: MLT_MTDS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
RCN_MTDS.obj \
RCN_MTDS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
RCN_MTDS.obj \
RCN_MTDS.eobj: RCN_MTDS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
REG_MTDS.obj \
REG_MTDS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
REG_MTDS.obj \
REG_MTDS.eobj: REG_MTDS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
RPT_MTDS.obj \
RPT_MTDS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
RPT_MTDS.obj \
RPT_MTDS.eobj: RPT_MTDS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
SCH_MTDS.obj \
SCH_MTDS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
SCH_MTDS.obj \
SCH_MTDS.eobj: SCH_MTDS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
TRN_MTDS.obj \
TRN_MTDS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
TRN_MTDS.obj \
TRN_MTDS.eobj: TRN_MTDS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H
TXT_STRS.obj \
TXT_STRS.eobj: 
TXT_STRS.obj \
TXT_STRS.eobj: TXT_STRS.GOC GEOS.H GEODE.H OBJECT.H LMEM.H
XFR_MTDS.obj \
XFR_MTDS.eobj: BNKR30.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH MATH.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                OBJECTS/VLTEXTC.GOH N2TXT.GOH ANSI/STRING.H EXTERNS.GOH
XFR_MTDS.obj \
XFR_MTDS.eobj: XFR_MTDS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H ANSI/STRING.H \
                INITFILE.H MATH.H TOKEN.H

BNKR30EC.geo BNKR30.geo : GEOS.LDF UI.LDF ANSIC.LDF TEXT.LDF SPOOL.LDF MATH.LDF N2TXT.LDF 