BIGCALCMAIN.rdef: GENERIC.UIH ART/MKRBIGCALC.UI ART/MKRBIGCALCTINY.UI \
                BIGCALCMAIN.UIH BIGCALCPCF.UIH BIGCALCEXTRAMAIN.UI \
                ART/MKRCONSUMER.UI ART/MKRRETAIL.UI BIGCALCCALC.UIH \
                BIGCALCCALC.UI ART/MKRMEMPLUS.UI ART/MKRMEMMINUS.UI \
                ART/MKRPLUSMINUS.UI ART/MKRPLUS.UI ART/MKRMINUS.UI \
                ART/MKRTIMES.UI ART/MKRDIVIDE.UI ART/MKRBACKSPACE.UI \
                ART/MKREQUALS.UI BIGCALCMATH.UIH BIGCALCMATH.UI \
                BIGCALCPCF.UI ART/MKRSTATS.UI ART/MKRFINANCE.UI \
                BIGCALCDATA.UI BIGCALCTEMPLATE.UI ART/MKRGETCALC.UI \
                ART/MKRSENDCALC.UI
BIGCALCDCTRL.obj \
BIGCALCDCTRL.eobj: 
BIGCALCMAINCODE.obj \
BIGCALCMAINCODE.eobj: GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF OBJECT.DEF \
                LMEM.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF \
                GSTRING.DEF TEXT.DEF CHAR.DEF WIN.DEF LOCALIZE.DEF \
                SLLANG.DEF INITFILE.DEF VM.DEF DBASE.DEF TIMER.DEF \
                TIMEDATE.DEF SYSTEM.DEF OBJECTS/INPUTC.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF UI.DEF \
                FILE.DEF INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF \
                GCNLIST.DEF OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF MATH.DEF PARSE.DEF \
                BIGCALCMAIN.DEF BIGCALCPROCESS.DEF BIGCALCCALC.DEF \
                BIGCALCMATH.DEF BIGCALCPCF.DEF BIGCALCMAIN.RDEF \
                BIGCALCPROCESS.ASM BIGCALCCALC.ASM BIGCALCMATH.ASM \
                BIGCALCAPPLICATION.ASM BIGCALCFINITESTATE.ASM \
                BIGCALCPCF.ASM BIGCALCHOLDER.ASM BIGCALCMEMORY.ASM \
                BIGCALCUNARYCVT.ASM BIGCALCBUILDPCF.ASM \
                BIGCALCBUILDFIXEDARGSPCF.ASM \
                BIGCALCBUILDVARIABLEARGSPCF.ASM BIGCALCFIXEDARGSPCF.ASM \
                BIGCALCVARIABLEARGSPCF.ASM

BigCalcEC.geo BigCalc.geo : GEOS.LDF UI.LDF MATH.LDF PARSE.LDF 