#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = BigCalc
ASM_TO_OBJS     = bigcalcDCtrl.asm bigcalcMainCode.asm
UI_TO_RDFS      = BIGCALCMAIN.UI
SRCS            = bigcalcApplication.asm bigcalcBuildFixedArgsPCF.asm\
                  bigcalcBuildPCF.asm bigcalcBuildVariableArgsPCF.asm\
                  bigcalcCalc.asm bigcalcDCtrl.asm bigcalcFiniteState.asm\
                  bigcalcFixedArgsPCF.asm bigcalcHolder.asm\
                  bigcalcMainCode.asm bigcalcMath.asm bigcalcMemory.asm\
                  bigcalcPCF.asm bigcalcProcess.asm bigcalcUnaryCvt.asm\
                  bigcalcVariableArgsPCF.asm bigcalcCalc.def\
                  bigcalcMain.def bigcalcMath.def bigcalcPCF.def\
                  bigcalcProcess.def ROADMAP.def bigcalcCalc.ui\
                  bigcalcData.ui bigcalcExtraMain.ui bigcalcMain.ui\
                  bigcalcMath.ui bigcalcPCF.ui bigcalcTemplate.ui
OBJS            = bigcalcDCtrl.obj bigcalcMainCode.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
