#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = TickertapePref
ASM_TO_OBJS     = tickertapepref.asm
UI_TO_RDFS      = TICKERTAPEPREF.UI
SRCS            = tickertapepref.asm tickertapepref.ui
OBJS            = tickertapepref.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
