#!/bin/sh -
# $Id: convgscs,v 1.1.30.1 97/03/29 09:06:47 canavese Exp $
cvtpcx -2 -f -m13 -t -z -x0 -y0 -rMemoryResource -nGetCalc gcsc.pcx
cvtpcx -2 -f -m13 -t -z -x0 -y16 -rMemoryResource -nSendCalc gcsc.pcx
