DOCASM.obj \
DOCASM.eobj: DocAsm/DocAsmMANAGER.ASM \
                STDAPP.DEF GEOS.DEF GEODE.DEF RESOURCE.DEF EC.DEF LMEM.DEF \
                OBJECT.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF \
                GSTRING.DEF TEXT.DEF CHAR.DEF HEAP.DEF UI.DEF FILE.DEF \
                VM.DEF WIN.DEF INPUT.DEF HWR.DEF LOCALIZE.DEF SLLANG.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                GFBUTTON.DEF DOCBUTTN.ASM UIBUTTON.RDEF
DOCGROUP.obj \
DOCGROUP.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GROBJ.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH OBJECTS/FLATFILE/FFFLDPR.GOH FFILE.GOH \
                SSHEET.GOH RULER.GOH MATH.GOH OBJECTS/GVIEWCC.GOH \
                GEOFILE.GOH OBJECTS/FLATFILE/FFDBASEC.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFDBASE.GOH \
                OBJECTS/FLATFILE/FFTCHSTC.GOH
DOCGROUP.obj \
DOCGROUP.eobj: DOCUMENT/DOCGROUP.GOC GEOS.H \
                 \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H \
                OBJECTS/FLATFILE/FFEXBLD.H MATH.H PARSE.H CELL.H \
                IECOMMON.H XLATLIB.H OBJECTS/FLATFILE/FFKBD.H
DOCUMENT.obj \
DOCUMENT.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GROBJ.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH FFILE.GOH SSHEET.GOH RULER.GOH \
                MATH.GOH OBJECTS/FLATFILE/FFDBASEC.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFDBASE.GOH OBJECTS/FLATFILE/FFFLDPR.GOH \
                OBJECTS/FLATFILE/FFFLDPRC.GOH OBJECTS/GVIEWCC.GOH \
                GEOFILE.GOH OBJECTS/FLATFILE/FFTCHSTC.GOH GFBUTTON.GOH
DOCUMENT.obj \
DOCUMENT.eobj: DOCUMENT/DOCUMENT.GOC GEOS.H \
                 \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H MATH.H PARSE.H CELL.H \
                IECOMMON.H XLATLIB.H OBJECTS/FLATFILE/FFKBD.H \
                OBJECTS/FLATFILE/FFEXBLD.H
STRINGS.obj \
STRINGS.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH
STRINGS.obj \
STRINGS.eobj: LOCALIZE/STRINGS.GOC GEOS.H \
                 \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H
MAPPL.obj \
MAPPL.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GEOFILE.GOH \
                OBJECTS/FLATFILE/FFDBASEC.GOH SSHEET.GOH RULER.GOH \
                MATH.GOH FFILE.GOH IMPEX.GOH OBJECTS/FLATFILE/FFDBASE.GOH \
                OBJECTS/FLATFILE/FFTCHSTC.GOH
MAPPL.obj \
MAPPL.eobj: MAIN/MAPPL.GOC GEOS.H  \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STDLIB.H INITFILE.H PARSE.H \
                MATH.H CELL.H IECOMMON.H XLATLIB.H \
                OBJECTS/FLATFILE/FFKBD.H
MFLDORDR.obj \
MFLDORDR.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GROBJ.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH OBJECTS/FLATFILE/FFDBASEC.GOH \
                SSHEET.GOH RULER.GOH MATH.GOH FFILE.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFDBASE.GOH OBJECTS/FLATFILE/FFFLDPR.GOH \
                OBJECTS/FLATFILE/FFFLDPRC.GOH OBJECTS/FLATFILE/FFRECC.GOH \
                OBJECTS/FLATFILE/FFRCPVC.GOH OBJECTS/GVIEWCC.GOH \
                GEOFILE.GOH OBJECTS/FLATFILE/FFTCHSTC.GOH
MFLDORDR.obj \
MFLDORDR.eobj: MAIN/MFLDORDR.GOC GEOS.H  \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H PARSE.H MATH.H CELL.H \
                IECOMMON.H XLATLIB.H OBJECTS/FLATFILE/FFKBD.H \
                OBJECTS/FLATFILE/FFEXBLD.H
MFLDORGZ.obj \
MFLDORGZ.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH OBJECTS/FLATFILE/FFDBASE.GOH FFILE.GOH \
                SSHEET.GOH RULER.GOH MATH.GOH \
                OBJECTS/FLATFILE/FFDBASEC.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFTCHSTC.GOH GEOFILE.GOH
MFLDORGZ.obj \
MFLDORGZ.eobj: MAIN/MFLDORGZ.GOC GEOS.H  \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STDLIB.H MATH.H PARSE.H CELL.H \
                IECOMMON.H XLATLIB.H OBJECTS/FLATFILE/FFKBD.H
MLAYOUTS.obj \
MLAYOUTS.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GROBJ.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH OBJECTS/FLATFILE/FFDBASEC.GOH \
                SSHEET.GOH RULER.GOH MATH.GOH FFILE.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFDBASE.GOH OBJECTS/FLATFILE/FFFLDPR.GOH \
                OBJECTS/FLATFILE/FFFLDPRC.GOH \
                OBJECTS/FLATFILE/FFTCHSTC.GOH OBJECTS/FLATFILE/FFRECC.GOH \
                OBJECTS/FLATFILE/FFRCPVC.GOH GEOFILE.GOH
MLAYOUTS.obj \
MLAYOUTS.eobj: MAIN/MLAYOUTS.GOC GEOS.H  \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H TOKEN.H PARSE.H MATH.H \
                CELL.H IECOMMON.H XLATLIB.H OBJECTS/FLATFILE/FFKBD.H
MMODES.obj \
MMODES.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH OBJECTS/FLATFILE/FFDBASE.GOH FFILE.GOH \
                SSHEET.GOH RULER.GOH MATH.GOH \
                OBJECTS/FLATFILE/FFDBASEC.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFILEC.GOH OBJECTS/FLATFILE/FFUICTRL.GOH \
                OBJECTS/FLATFILE/FFEXBLDC.GOH \
                OBJECTS/FLATFILE/FFFLDPRC.GOH \
                OBJECTS/FLATFILE/FFFLDPR.GOH \
                OBJECTS/FLATFILE/FFTCHSTC.GOH \
                OBJECTS/FLATFILE/FFTEXTC.GOH GROBJ.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH OBJECTS/FLATFILE/FFPAGLRC.GOH \
                OBJECTS/FLATFILE/FFRECC.GOH OBJECTS/FLATFILE/FFRCPVC.GOH \
                GEOFILE.GOH
MMODES.obj \
MMODES.eobj: MAIN/MMODES.GOC GEOS.H  \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STDLIB.H MATH.H PARSE.H CELL.H \
                IECOMMON.H XLATLIB.H OBJECTS/FLATFILE/FFKBD.H \
                OBJECTS/FLATFILE/FFDPASTE.H
MPROCESS.obj \
MPROCESS.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GROBJ.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFDBASEC.GOH SSHEET.GOH RULER.GOH \
                MATH.GOH FFILE.GOH OBJECTS/FLATFILE/FFDBASE.GOH \
                OBJECTS/FLATFILE/FFFLDPR.GOH \
                OBJECTS/FLATFILE/FFFLDPRC.GOH OBJECTS/FLATFILE/FFRECC.GOH \
                OBJECTS/FLATFILE/FFRCPVC.GOH OBJECTS/GVIEWCC.GOH \
                GEOFILE.GOH OBJECTS/FLATFILE/FFTCHSTC.GOH
MPROCESS.obj \
MPROCESS.eobj: MAIN/MPROCESS.GOC GEOS.H  \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H IECOMMON.H XLATLIB.H \
                TOKEN.H PARSE.H MATH.H CELL.H OBJECTS/FLATFILE/FFKBD.H \
                OBJECTS/FLATFILE/FFEXBLD.H
MSORTING.obj \
MSORTING.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GROBJ.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH OBJECTS/FLATFILE/FFDBASEC.GOH \
                SSHEET.GOH RULER.GOH MATH.GOH FFILE.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFDBASE.GOH OBJECTS/FLATFILE/FFFLDPR.GOH \
                OBJECTS/FLATFILE/FFFLDPRC.GOH OBJECTS/FLATFILE/FFRECC.GOH \
                OBJECTS/FLATFILE/FFRCPVC.GOH OBJECTS/GVIEWCC.GOH \
                GEOFILE.GOH OBJECTS/FLATFILE/FFTCHSTC.GOH
MSORTING.obj \
MSORTING.eobj: MAIN/MSORTING.GOC GEOS.H  \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H PARSE.H MATH.H CELL.H \
                IECOMMON.H XLATLIB.H OBJECTS/FLATFILE/FFKBD.H \
                OBJECTS/FLATFILE/FFEXBLD.H
MSUBSETS.obj \
MSUBSETS.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GROBJ.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH OBJECTS/FLATFILE/FFDBASEC.GOH \
                SSHEET.GOH RULER.GOH MATH.GOH FFILE.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFDBASE.GOH OBJECTS/FLATFILE/FFFLDPR.GOH \
                OBJECTS/FLATFILE/FFFLDPRC.GOH OBJECTS/FLATFILE/FFRECC.GOH \
                OBJECTS/FLATFILE/FFRCPVC.GOH OBJECTS/GVIEWCC.GOH \
                GEOFILE.GOH OBJECTS/FLATFILE/FFTCHSTC.GOH
MSUBSETS.obj \
MSUBSETS.eobj: MAIN/MSUBSETS.GOC GEOS.H  \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H GEOMISC.H PARSE.H \
                MATH.H CELL.H IECOMMON.H XLATLIB.H \
                OBJECTS/FLATFILE/FFKBD.H OBJECTS/FLATFILE/FFEXBLD.H
UILAYOUT.obj \
UILAYOUT.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GROBJ.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFEXBLDC.GOH FFILE.GOH SSHEET.GOH \
                RULER.GOH MATH.GOH OBJECTS/FLATFILE/FFFLDPR.GOH \
                OBJECTS/FLATFILE/FFFLDPRC.GOH \
                OBJECTS/FLATFILE/FFDBASE.GOH \
                OBJECTS/FLATFILE/FFTCHSTC.GOH \
                OBJECTS/FLATFILE/FFDBASEC.GOH OBJECTS/FLATFILE/FFRECC.GOH \
                OBJECTS/FLATFILE/FFRCPVC.GOH \
                OBJECTS/FLATFILE/FFGROBJC.GOH OBJECTS/GVIEWCC.GOH \
                OBJECTS/TEXT/TCTRLC.GOH GEOFILE.GOH ART/RNLRSC.GOH \
                ART/RNLRSM.GOH ART/RNLRSCGA.GOH ART/RNTBSC.GOH \
                ART/RNTBSM.GOH ART/RNTBSCGA.GOH ART/FIPSC.GOH \
                ART/FIPSM.GOH ART/FIPSCGA.GOH ART/FDPSC.GOH ART/FDPSM.GOH \
                ART/FDPSCGA.GOH
UILAYOUT.obj \
UILAYOUT.eobj: UI/UILAYOUT.GOC GEOS.H  \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H IECOMMON.H XLATLIB.H \
                OBJECTS/FLATFILE/FFEXBLD.H MATH.H PARSE.H CELL.H \
                OBJECTS/FLATFILE/FFKBD.H
UIMAIN.obj \
UIMAIN.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GROBJ.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH OBJECTS/FLATFILE/FFEXBLDC.GOH \
                FFILE.GOH SSHEET.GOH RULER.GOH MATH.GOH \
                OBJECTS/FLATFILE/FFFLDPR.GOH \
                OBJECTS/FLATFILE/FFFLDPRC.GOH \
                OBJECTS/FLATFILE/FFDBASE.GOH \
                OBJECTS/FLATFILE/FFTCHSTC.GOH \
                OBJECTS/FLATFILE/FFDBASEC.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFRECC.GOH OBJECTS/FLATFILE/FFRCPVC.GOH \
                OBJECTS/FLATFILE/FFGROBJC.GOH OBJECTS/GVIEWCC.GOH \
                OBJECTS/TEXT/TCTRLC.GOH GFBUTTON.GOH GEOFILE.GOH \
                ART/RASC.GOH ART/RASM.GOH ART/RASCGA.GOH ART/LTARSC.GOH \
                ART/LTARSM.GOH ART/LTARSCGA.GOH ART/ASSC.GOH ART/ASSM.GOH \
                ART/ASSCGA.GOH ART/DSSC.GOH ART/DSSM.GOH ART/DSSCGA.GOH \
                ART/DPSC.GOH ART/DPSM.GOH ART/DPSCGA.GOH ART/IPSC.GOH \
                ART/IPSM.GOH ART/IPSCGA.GOH ART/SRTORAR.GOH \
                ART/GEOFILE.GOH ART/GEOFILET.GOH ART/GEOFILED.GOH \
                USRLEVEL.GOH
UIMAIN.obj \
UIMAIN.eobj: UI/UIMAIN.GOC GEOS.H  \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H \
                OBJECTS/FLATFILE/FFEXBLD.H MATH.H PARSE.H CELL.H \
                IECOMMON.H XLATLIB.H OBJECTS/FLATFILE/FFKBD.H
UIMARKED.obj \
UIMARKED.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GROBJ.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH OBJECTS/FLATFILE/FFEXBLDC.GOH \
                FFILE.GOH SSHEET.GOH RULER.GOH MATH.GOH \
                OBJECTS/GVIEWCC.GOH OBJECTS/TEXT/TCTRLC.GOH \
                OBJECTS/FLATFILE/FFFLDEDG.GOH GEOFILE.GOH \
                OBJECTS/FLATFILE/FFDBASEC.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFDBASE.GOH \
                OBJECTS/FLATFILE/FFTCHSTC.GOH
UIMARKED.obj \
UIMARKED.eobj: UI/UIMARKED.GOC GEOS.H  \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H \
                OBJECTS/FLATFILE/FFEXBLD.H MATH.H PARSE.H CELL.H \
                IECOMMON.H XLATLIB.H OBJECTS/FLATFILE/FFKBD.H
UIMODIFY.obj \
UIMODIFY.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GROBJ.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH OBJECTS/SPLINEC.GOH MATH.GOH \
                OBJECTS/GVIEWCC.GOH OBJECTS/TEXT/TCTRLC.GOH RULER.GOH \
                OBJECTS/FLATFILE/FFFLDEDG.GOH FFILE.GOH SSHEET.GOH \
                GEOFILE.GOH OBJECTS/FLATFILE/FFDBASEC.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFDBASE.GOH \
                OBJECTS/FLATFILE/FFTCHSTC.GOH
UIMODIFY.obj \
UIMODIFY.eobj: UI/UIMODIFY.GOC GEOS.H  \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H MATH.H PARSE.H CELL.H \
                IECOMMON.H XLATLIB.H OBJECTS/FLATFILE/FFKBD.H
UITMPLAT.obj \
UITMPLAT.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GROBJ.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH FFILE.GOH SSHEET.GOH RULER.GOH \
                MATH.GOH OBJECTS/FLATFILE/FFDBASE.GOH \
                OBJECTS/FLATFILE/FFDBASEC.GOH IMPEX.GOH \
                OBJECTS/FLATFILE/FFFLDPRC.GOH \
                OBJECTS/FLATFILE/FFFLDPR.GOH \
                OBJECTS/FLATFILE/FFTCHSTC.GOH GEOFILE.GOH
UITMPLAT.obj \
UITMPLAT.eobj: UI/UITMPLAT.GOC GEOWORKS.H GEOS.H \
                 \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H MATH.H PARSE.H CELL.H \
                IECOMMON.H XLATLIB.H OBJECTS/FLATFILE/FFKBD.H
UIBUTTON.rdef: ART/DEMLRSC.UI ART/DEMLRSM.UI ART/DEMLRSCG.UI \
                ART/DMLRSC.UI ART/DMLRSM.UI ART/DMLRSCGA.UI \
                ART/SRLLRSC.UI ART/SRLLRSM.UI ART/SRLLRSCG.UI \
                ART/MRLLRSC.UI ART/MRLLRSM.UI ART/MRLLRSCG.UI

GeoFileEC.geo GeoFile.geo : GEOS.LDF UI.LDF GROBJ.LDF SPOOL.LDF PARSE.LDF CELL.LDF RULER.LDF SPLINE.LDF MATH.LDF SSHEET.LDF TEXT.LDF ANSIC.LDF BITMAP.LDF FFILE.LDF IMPEX.LDF 