#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = WEBBOX
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = BSTRINGS.GOC MEN1STR.GOC MEN2STR.GOC MSGBUTON.GOC\
                  MSGMENU1.GOC MSGMENU2.GOC MSGMENU3.GOC MSGMENU4.GOC\
                  MSGPRIM.GOC MSGPROC.GOC MSGSPTAG.GOC TEXT.GOC UIABOUT.GOC\
                  UIBUTTON.GOC UIMENU1.GOC UIMENU2.GOC UISPTAG.GOC\
                  UISTAT.GOC BBXWEBED.GOH BBXWEBVU.GOH BREADBOX.GOH\
                  BSTRINGS.GOH GLOBAL.GOH MEN1STR.GOH MEN2STR.GOH APP.GOH
OBJS            = BSTRINGS.obj MEN1STR.obj MEN2STR.obj MSGBUTON.obj\
                  MSGMENU1.obj MSGMENU2.obj MSGMENU3.obj MSGMENU4.obj\
                  MSGPRIM.obj MSGPROC.obj MSGSPTAG.obj TEXT.obj UIABOUT.obj\
                  UIBUTTON.obj UIMENU1.obj UIMENU2.obj UISPTAG.obj\
                  UISTAT.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
