#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = IRLAP
ASM_TO_OBJS     = irlapManager.asm
UI_TO_RDFS      = IRLAP.UI IRLAPADDRESSCONTROL.UI IRLAPPREFCONTROL.UI
SRCS            = irlap.asm irlapActions.asm irlapAddressControl.asm\
                  irlapConnect.asm irlapControl.asm irlapDiscovery.asm\
                  irlapEC.asm irlapEvent.asm irlapInitExit.asm\
                  irlapManager.asm irlapPrefControl.asm irlapPXfer.asm\
                  irlapSniff.asm irlapSocket.asm irlapStrings.asm\
                  irlapSXfer.asm irlapTables.asm irlapUtil.asm\
                  irlapXchg.asm irlap.def irlapAddressControl.def\
                  irlapInt.def irlapMacro.def irlap.ui\
                  irlapAddressControl.ui irlapPrefControl.ui
OBJS            = irlapManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
