SLIPSTRINGS.rdef: G:/BBXENSEM/PCGEOS/DRIVER/SOCKET/SLIP/SLIPSTRINGS.UI
SLIPMANAGER.obj \
SLIPMANAGER.eobj: GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF SYSTEM.DEF \
                LOCALIZE.DEF SLLANG.DEF LIBRARY.DEF OBJECT.DEF LMEM.DEF \
                TIMER.DEF TIMEDATE.DEF DRIVER.DEF ASSERT.DEF DISK.DEF \
                FILE.DEF DRIVE.DEF THREAD.DEF INTERNAL/SEMINT.DEF SEM.DEF \
                INTERNAL/HEAPINT.DEF SYSSTATS.DEF INTERNAL/IM.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF CHAR.DEF INITFILE.DEF MEDIUM.DEF UI.DEF \
                VM.DEF TEXT.DEF FONTID.DEF GRAPHICS.DEF FONT.DEF \
                COLOR.DEF WIN.DEF INPUT.DEF HWR.DEF GCNLIST.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                INTERNAL/NETUTILS.DEF INTERNAL/SOCKETINT.DEF \
                INTERNAL/SOCKETDR.DEF SOCKMISC.DEF INTERNAL/SERIALDR.DEF \
                INTERNAL/STREAMDR.DEF SLIP.DEF SLIPSTRINGS.RDEF SLIP.ASM

SLIPEC.geo SLIP.geo : GEOS.LDF NETUTILS.LDF 