#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = SLIP
ASM_TO_OBJS     = slipManager.asm
UI_TO_RDFS      = SLIPSTRINGS.UI
SRCS            = slip.asm slipManager.asm slipTia.asm slip.def\
                  slipStrings.ui
OBJS            = slipManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
