#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = vmfi
ASM_TO_OBJS     = vmfiManager.asm
UI_TO_RDFS      =
SRCS            = vmfiMain.asm vmfiManager.asm vmfiStrategy.asm vmfi.def
OBJS            = vmfiManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
