#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bbxcd
MAIN            = pcode.h timevent.h subcode.h display.h key.h subcode.goc\
                  txt_strs.goc pcode.goc display.goc process.goc\
                  timevent.goc key.goc bbxcd.goc timevent.goh display.goh\
                  pcode.goh process.goh subcode.goh
UI              = uimain.goc uimax.goc uimain.goh uimax.goh define.goh
UI_TO_RDFS      =
OBJS            = subcode.obj txt_strs.obj pcode.obj display.obj\
                  process.obj timevent.obj key.obj bbxcd.obj uimain.obj\
                  uimax.obj
COMMON          = bbxcd.h
MODULES         =
CMODULES        = Main Ui
SRCS            = $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
