#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bbxcd
MAIN            = display.h key.h pcode.h subcode.h timevent.h bbxcd.goc\
                  display.goc key.goc pcode.goc process.goc subcode.goc\
                  timevent.goc txt_strs.goc display.goh pcode.goh\
                  process.goh subcode.goh timevent.goh
UI              = uimain.goc uimax.goc define.goh uimain.goh uimax.goh
UI_TO_RDFS      =
OBJS            = bbxcd.obj display.obj key.obj pcode.obj process.obj\
                  subcode.obj timevent.obj txt_strs.obj uimain.obj\
                  uimax.obj
COMMON          = bbxcd.h
MODULES         =
CMODULES        = Main Ui
SRCS            = $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
