#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = Loopback
ASM_TO_OBJS     = loopbackManager.asm
UI_TO_RDFS      = LOOPBACK.UI
SRCS            = loopback.asm loopbackAddrCtrl.asm loopbackManager.asm\
                  loopbackPrefCtrl.asm loopbackUtil.asm\
                  loopbackAddrCtrl.def loopbackConstant.def\
                  loopbackPrefCtrl.def loopback.ui
OBJS            = loopbackManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
