#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = hangman
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = HANGMAN.GOC process.goc Import.goc BBOXREG.GOH HMICON.GOH\
                  hangman.goh externs.goh
OBJS            = HANGMAN.obj process.obj Import.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
