rem All Rem'd so I don't accidentally regenerate ;-)

rem cvtpcx -2 -w100 -h52 -m1 -G -nQTip1 -oQTip1.goh tip1.pcx
rem cvtpcx -2 -w48 -h30 -m1 -G -nQTip2 -oQTip2.goh tip2.pcx

rem cvtpcx -2 -w100 -h52 -m1 -G -nQTMove -oQTMove.goh hint1.pcx
rem cvtpcx -2 -w79 -h50 -m1 -G -nQTSkill -oQTSkill.goh hint2.pcx
rem cvtpcx -2 -w42 -h42 -m1 -G -nQTStart -oQTStart.goh hint3.pcx

rem cvtpcx -2 -x1 -y1 -w48 -h30 -m1 -G -nAppIcon -oAppIcon.goh pth000-8.pcx
rem cvtpcx -2 -x50 -y1 -w15 -h15 -m1 -G -nTinyIcon -oTiny.goh pth000-8.pcx

rem cvtpcx -2 -x0 -y0 -w19 -h19 -m1 -G -g -nTCClose -oTCClose.goh pth005-8.pcx
rem cvtpcx -2 -x0 -y0 -w19 -h19 -m1 -G -g -nTCOpen -oTCOpen.goh pth006-8.pcx
rem cvtpcx -2 -x0 -y0 -w19 -h19 -m1 -G -g -nHole -oHole.goh pth007-8.pcx

rem cvtpcx -2 -x0 -y0 -w18 -h24 -m1 -G -g -nAUpLeft -oAUpLeft.goh pth011-8.pcx
rem cvtpcx -2 -x0 -y0 -w244 -h67 -m1 -G -g -nAUpMid -oAUpMid.goh pth012-8.pcx
rem cvtpcx -2 -x0 -y0 -w23 -h36 -m1 -G -g -nAUpRight -oAUpRight.goh pth013-8.pcx
rem cvtpcx -2 -x0 -y0 -w32 -h244 -m1 -G -g -nALeft -oALeft.goh pth014-8.pcx
rem cvtpcx -2 -x0 -y0 -w31 -h244 -m1 -G -g -nARight -oARight.goh pth015-8.pcx
rem cvtpcx -2 -x0 -y0 -w25 -h40 -m1 -G -g -nABLeft -oABLeft.goh pth016-8.pcx
rem cvtpcx -2 -x0 -y0 -w244 -h53 -m1 -G -g -nABMid -oABMid.goh pth017-8.pcx
rem cvtpcx -2 -x0 -y0 -w32 -h40 -m1 -G -g -nABRight -oABRight.goh pth018-8.pcx

rem cvtpcx -2 -x0 -y0 -w36 -h33 -m1 -G -g -nBUpLeft -oBUpLeft.goh pth021-8.pcx
rem cvtpcx -2 -x0 -y0 -w244 -h72 -m1 -G -g -nBUpMid -oBUpMid.goh pth022-8.pcx
rem cvtpcx -2 -x0 -y0 -w22 -h41 -m1 -G -g -nBUpRight -oBUpRight.goh pth023-8.pcx
rem cvtpcx -2 -x0 -y0 -w42 -h244 -m1 -G -g -nBLeft -oBLeft.goh pth024-8.pcx
rem cvtpcx -2 -x0 -y0 -w33 -h244 -m1 -G -g -nBRight -oBRight.goh pth025-8.pcx
rem cvtpcx -2 -x0 -y0 -w30 -h42 -m1 -G -g -nBBLeft -oBBLeft.goh pth026-8.pcx
rem cvtpcx -2 -x0 -y0 -w244 -h58 -m1 -G -g -nBBMid -oBBMid.goh pth027-8.pcx
rem cvtpcx -2 -x0 -y0 -w35 -h54 -m1 -G -g -nBBRight -oBBRight.goh pth028-8.pcx
