#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = stub32
ASM_TO_OBJS     = bpt.asm break.asm cbreak.asm com.asm intelbpt.asm\
                  kernel.asm main.asm netware.asm rpc.asm tbreak.asm\
                  timebreak.asm wincom.asm
UI_TO_RDFS      =
SRCS            = bpt.asm break.asm cbreak.asm com.asm intelbpt.asm\
                  kernel.asm main.asm netware.asm rpc.asm tbreak.asm\
                  timebreak.asm wincom.asm com.def netware.def rpc.def\
                  stub.def wincom.def
OBJS            = bpt.obj break.obj cbreak.obj com.obj intelbpt.obj\
                  kernel.obj main.obj netware.obj rpc.obj tbreak.obj\
                  timebreak.obj wincom.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
