#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = GeoCalc
DOCUMENT        = documentChart.asm documentClass.asm documentCtrl.asm\
                  documentGraphic.asm documentHead.asm documentImpex.asm\
                  documentManager.asm documentManip.asm\
                  documentMessages.asm documentMouse.asm documentNew.asm\
                  documentSetup.asm documentSplit.asm
IMPEX           = impex.asm impexManager.asm
MAIN            = mainDocument.asm mainHeader.asm mainInit.asm\
                  mainManager.asm mainProcess.asm
NAME            = nameManager.asm nameUtils.asm
UI              = uiDisplay.asm uiFormat.asm uiGeoCalcApplication.asm\
                  uiGeoCalcChartBody.asm uiGeoCalcContent.asm\
                  uiGeoCalcDisplayGroup.asm uiGeoCalcEditBar.asm\
                  uiGeoCalcSpreadsheet.asm uiGeoCalcView.asm uiList.asm\
                  uiManager.asm uiNotifyGroup.asm uiTarget.asm\
                  uiConstant.def uiAttributes.ui uiCell.ui uiChart.ui\
                  uiContent.ui uiData.ui uiDisplay.ui uiEdit.ui uiFile.ui\
                  uiFormat.ui uiFormula.ui uiGeoCalcDocNote.ui uiGraphic.ui\
                  uiGraphicBody.ui uiLevel.ui uiMain.ui uiName.ui\
                  uiOptions.ui uiPrint.ui uiStrings.ui uiTool.ui uiZoom.ui
UI_TO_RDFS      = UIMAIN.UI
OBJS            =
COMMON          = geocalcApplication.def geocalcChartBody.def\
                  geocalcConstant.def geocalcContent.def geocalcDisplay.def\
                  geocalcDisplayGroup.def geocalcDocCtrl.def\
                  geocalcDocNote.def geocalcDocument.def geocalcEditBar.def\
                  geocalcGeode.def geocalcGrObjHead.def geocalcLevel.def\
                  geocalcMacros.def geocalcProcess.def\
                  geocalcSpreadsheet.def geocalcView.def name.def
MODULES         = Document Impex Main Name UI
CMODULES        =
SRCS            = $(DOCUMENT) $(IMPEX) $(MAIN) $(NAME) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
