#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = TGEN
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = Document.goc strings.goc process.goc Fnctns.goc genr8.goc\
                  Export.goc Import.goc tgen_ui.goc grade.goc talink.goc\
                  tgen.goh externs.goh
OBJS            = Document.obj strings.obj process.obj Fnctns.obj genr8.obj\
                  Export.obj Import.obj tgen_ui.obj grade.obj talink.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
