#!/bin/sh -
# $Id: convert,v 1.4 98/04/28 17:27:19 joon Exp $
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps3.pcx 2 Banner $appArgs
cvtpcx -f -m13 -t -z -nBannerTiny newbanner.tiny.pcx

cvtpcx -f -m13 -t -l -x0 -y0 -nTypeTrigger type.pcc
cvtpcx -f -m13 -t -l -x0 -y0 -nFontsTrigger font.pcc
cvtpcx -f -m13 -t -l -x0 -y0 -nEffectsTrigger effects.pcc
cvtpcx -f -m13 -t -l -x0 -y0 -nPrintTrigger print.pcc
