DISK.obj \
DISK.eobj: GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF DRIVER.DEF \
                LMEM.DEF SEM.DEF SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF \
                FILE.DEF INITFILE.DEF DRIVE.DEF DISK.DEF \
                INTERNAL/HEAPINT.DEF INTERNAL/SEMINT.DEF SYSSTATS.DEF \
                INTERNAL/FSDRIVER.DEF INTERNAL/FSD.DEF \
                INTERNAL/DRIVEINT.DEF INTERNAL/DISKINT.DEF \
                INTERNAL/FILEINT.DEF FILEENUM.DEF INTERNAL/DOS.DEF \
                INTERNAL/DOSFSDR.DEF INTERNAL/INTERRUP.DEF \
                INTERNAL/SWAPDR.DEF INTERNAL/SWAP.DEF

DiskEC.geo Disk.geo : geos.ldf swap.ldf
