#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = Nw
ASM_TO_OBJS     = nw.asm
UI_TO_RDFS      =
SRCS            = nw.asm nwBindery.asm nwDir.asm nwHecb.asm nwInit.asm\
                  nwIpx.asm nwPrint.asm nwResident.asm nwSem.asm\
                  nwSemHigh.asm nwSemLow.asm nwServer.asm nwSimpleSem.asm\
                  nwSocket.asm nwTextMessage.asm nwUserInfo.asm nwUtils.asm\
                  nwConstant.def nwMacros.def
OBJS            = nw.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
