LOOPBACK.rdef: GENERIC.UIH PRODUCT.UIH INTERNAL/PRODFEATURES.UIH \
                CONFIG.UIH OBJECTS/COLORC.UIH
LOOPBACKMANAGER.obj \
LOOPBACKMANAGER.eobj: GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF THREAD.DEF \
                SEM.DEF TIMER.DEF DRIVER.DEF LMEM.DEF SYSTEM.DEF \
                LOCALIZE.DEF SLLANG.DEF MEDIUM.DEF ASSERT.DEF DISK.DEF \
                FILE.DEF DRIVE.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                OBJECT.DEF CHUNKARR.DEF GEOWORKS.DEF \
                INTERNAL/PRODFEATURES.DEF UI.DEF VM.DEF TEXT.DEF \
                FONTID.DEF GRAPHICS.DEF FONT.DEF COLOR.DEF CHAR.DEF \
                WIN.DEF INPUT.DEF HWR.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                CONFIG.DEF OBJECTS/COLORC.DEF SAC.DEF \
                INTERNAL/NETUTILS.DEF INTERNAL/SOCKETINT.DEF \
                INTERNAL/LOOPBACKDR.DEF INTERNAL/SOCKETDR.DEF \
                SOCKMISC.DEF INTERNAL/SEMINT.DEF INTERNAL/LOG.DEF \
                INTERNAL/HEAPINT.DEF SYSSTATS.DEF LOOPBACKCONSTANT.DEF \
                LOOPBACKPREFCTRL.DEF LOOPBACKADDRCTRL.DEF LOOPBACK.RDEF \
                LOOPBACK.ASM LOOPBACKUTIL.ASM LOOPBACKADDRCTRL.ASM \
                LOOPBACKPREFCTRL.ASM

LoopbackEC.geo Loopback.geo : GEOS.LDF UI.LDF NETUTILS.LDF SOCKET.LDF 