'\" Copyright 1989 Regents of the University of California
'\" Permission to use, copy, modify, and distribute this
'\" documentation for any purpose and without fee is hereby
'\" granted, provided that this notice appears in all copies.
'\" The University of California makes no representations about
'\" the suitability of this material for any purpose.  It is
'\" provided "as is" without express or implied warranty.
'\" 
'\" $Header: /sprite/src/lib/tcl/RCS/Tcl_DeleteInterp.man,v 1.2 89/03/24 14:16:06 ouster Exp $ SPRITE (Berkeley)
'\" 
.so \*(]ltmac.sprite
.HS Tcl_DeleteInterp tcl
.BS
.SH NAME
Tcl_DeleteInterp \- destroy a Tcl command interpreter
.SH SYNOPSIS
.nf
\fB#include <tcl.h>\fR
.sp
\fBTcl_DeleteInterp\fR(\fIinterp\fR)
.SH ARGUMENTS
.AS Tcl_Interp *interp
.AP Tcl_Interp *interp in
Token for interpreter to be destroyed.
.BE

.SH DESCRIPTION
.PP
This procedure destroys a command interpreter and releases all of
the resources associated with it, including variables, procedures,
and application-specific command bindings.  After \fBTcl_DeleteInterp\fR
returns the caller should never again use the \fIinterp\fR token.

.SH KEYWORDS
command, delete, interpreter
