#!/usr/public/perl

# $Id: ds,v 1.8 95/07/25 19:29:58 chris Exp $
################################
#	ds
################################

require "newgetopt.pl";

$PP_DIR		= '/usr/games/lib/ds'; 	# where everything is stored
$defaultGame	= "Dink-Squash";
$checkPPScore	= 1;

require "/staff/pcgeos/Tools/scripts/perl/stats";



sub routed {
    local($wscore) = $_[0];
    local($lscore) = $_[1];

    if ($wscore > ($lscore * 2)) {
	return 1;
    } else {
	return 0;
    }
}


################################
#	Formats
################################

format top =
                                        Last      Avg   Power
 Name          W   L Skunk Routs  Pct    10  Stk Margin Rating Class
 ----------  --- --- ----- -----  ---   ---- --- ------ ------ -----
.

format STDOUT =
@@<<<<<<<<< @>>>@>>>@>>/@<@>>/@< @#.###@>>-@<@>@<@###.# @>>>>> @<<<<<<<<<<<<<<<<<<<<
$select,$p,$twins{$p},$tlosses{$p},$tskunks{$p},$tgotskunked{$p},$trouts{$p}, $tgotrouted{$p}, $pct{$p}, $wins, $losses, $streaktype, $streak, $avgmargin, $pwr, $class
.
format MAIL =
@@<<<<<<<<< @>>>@>>>@>>/@<@>>/@< @#.###@>>-@<@>@<@###.# @>>>>> @<<<<<<<<<<<<<<<<<<<<
$select,$p,$twins{$p},$tlosses{$p},$tskunks{$p},$tgotskunked{$p},$trouts{$p}, $tgotrouted{$p}, $pct{$p}, $wins, $losses, $streaktype, $streak, $avgmargin, $pwr, $class
.




