#!/usr/public/perl
# -*- perl -*-
##############################################################################
#
# 	Copyright (c) Geoworks 1996.  All rights reserved.
#       GEOWORKS CONFIDENTIAL
#
# PROJECT:	Tools
# MODULE:	pmake
# FILE: 	pmake-comma
# AUTHOR: 	Jacob A. Gabrielson, Nov 22, 1996
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	jacob	11/22/96   	Initial Revision
#
# DESCRIPTION:
#	This script is intended to support PMake, particularly under
#	NT.  It takes a list of products on the command line and
#	turns them into a form that can be used on the left-hand
#	side of a make rule.  E.g.,
#
#	PRODUCTS = PROD1 PROD2 PROD3
#	_COMMAPRODS != perl \
#		 	$ROOT_DIR/Tools/scripts/perl/pmake-comma $(PRODUCTS)
#	
#	With the result being that _COMMAPRODS now equals:
#
#	{PROD1,PROD2,PROD3}
#
#	All of this could be done with a -e command under NT with perl 4,
#	but with NT perl 5, it doesn't work due to perl 5's seemingly
#	broken handling of quoting on the command-line.
#
#	$Id: pmake-comma,v 1.1 96/11/24 16:55:28 jacob Exp $
#
###############################################################################

$foo = '{' . "@ARGV" . '}';
$foo =~ s/ /,/g;
print $foo, "\n";
exit 0;
