#!/usr/public/perl

# $Id: tarot,v 1.2 97/03/18 13:01:11 andrew Exp $
################################
#	tarot
################################

require "newgetopt.pl";

$PP_DIR		= '/n/yb/tarot';   # where everything is stored
$defaultGame	= "Tarot Fate";
$checkPPScore	= 0;

require "/staff/pcgeos/Tools/scripts/perl/stats";


sub routed {
    local($wscore) = $_[0];
    local($lscore) = $_[1];

    if (!($lscore) || ($wscore > ($lscore + 7)))  {
	return 1;
    } else {
	return 0;
    }
}


################################
#	Formats
################################

format top =
                                 Last                 Avg   Power
 Name         W   L Routs  Pct    10  Stk    Points  Margin Rating Class
 ---------  --- --- -----  ---   ---- ---   -------- ------ ------ ------------
.

format STDOUT =
@@<<<<<<<< @>>>@>>>@>>/@< @#.###@>>-@<@>@<@##.#-@#.#@###.# @>>>>>  @<<<<<<<<<<<<<<
$select,$p,$twins{$p},$tlosses{$p},$trouts{$p}, $tgotrouted{$p}, $pct{$p}, $wins, $losses, $streaktype, $streak, $avgoffense, $avgdefense, $avgmargin, $pwr, $class
.
format MAIL =
@@<<<<<<<< @>>>@>>>@>>/@< @#.###@>>-@<@>@<@##.#-@#.#@###.# @>>>>>  @<<<<<<<<<<<<<<
$select,$p,$twins{$p},$tlosses{$p},$trouts{$p}, $tgotrouted{$p}, $pct{$p}, $wins, $losses, $streaktype, $streak, $avgoffense, $avgdefense, $avgmargin, $pwr, $class
.




