#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = spotlightpref
ASM_TO_OBJS     = spotlightpref.asm
UI_TO_RDFS      = spotlightpref.ui
SRCS            = spotlightpref.asm spotlightpref.ui
OBJS            = spotlightpref.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
