FSM.obj \
FSM.eobj: PPPLOG.GOH
FSM.obj \
FSM.eobj: FSM.GOC PPP.H GEOS.H  \
                 \
                 GEODE.H RESOURCE.H \
                LMEM.H TIMER.H TIMEDATE.H HEAP.H FILE.H EC.H CHAR.H \
                INTERNAL/SOCKETDR.H SOCKMISC.H ANSI/STRING.H ANSI/STDIO.H \
                 PPPLOG.H IP.H \
                SLCOMPRESS.H FSM.H LCP.H LQM.H PAP.H CHAP.H IPCP.H \
                INTERNAL/NETUTILS.H
PPP.obj \
PPP.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH ACCPNT.GOH FOAM.GOH MAILBOX.GOH \
                PPPLOG.GOH
PPP.obj \
PPP.eobj: PPP.GOC GEOS.H  \
                 \
                 HEAP.H GEODE.H \
                RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H \
                FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H \
                ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H SYSTEM.H \
                GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H DRIVE.H \
                INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H PPP.H INTERNAL/SOCKETDR.H SOCKMISC.H \
                ANSI/STRING.H ANSI/STDIO.H \
                 PPPLOG.H IP.H \
                SLCOMPRESS.H FSM.H LCP.H LQM.H PAP.H CHAP.H IPCP.H \
                INTERNAL/NETUTILS.H INITFILE.H MEDIUM.H
PPPLOG.obj \
PPPLOG.eobj: 
PPPLOG.obj \
PPPLOG.eobj: PPPLOG.GOC
CCP.obj \
CCP.eobj: CCP.C
CHAP.obj \
CHAP.eobj: PPP.H GEOS.H  \
                 \
                 GEODE.H RESOURCE.H \
                LMEM.H TIMER.H TIMEDATE.H HEAP.H FILE.H EC.H CHAR.H \
                INTERNAL/SOCKETDR.H SOCKMISC.H ANSI/STRING.H ANSI/STDIO.H \
                 PPPLOG.H IP.H \
                SLCOMPRESS.H FSM.H LCP.H LQM.H PAP.H CHAP.H IPCP.H \
                INTERNAL/NETUTILS.H MD5.H CHAP_MS.H
CHAP_MS.obj \
CHAP_MS.eobj: PPP.H GEOS.H  \
                 \
                 GEODE.H RESOURCE.H \
                LMEM.H TIMER.H TIMEDATE.H HEAP.H FILE.H EC.H CHAR.H \
                INTERNAL/SOCKETDR.H SOCKMISC.H ANSI/STRING.H ANSI/STDIO.H \
                 PPPLOG.H IP.H \
                SLCOMPRESS.H FSM.H LCP.H LQM.H PAP.H CHAP.H IPCP.H \
                INTERNAL/NETUTILS.H CHAP_MS.H MD4.H DES.H
C_MPPC.obj \
C_MPPC.eobj: C_MPPC.C
C_PREDICTOR.obj \
C_PREDICTOR.eobj: C_PREDICTOR.C
C_STAC.obj \
C_STAC.eobj: C_STAC.C
DATA.obj \
DATA.eobj: PPP.H GEOS.H  \
                 \
                 GEODE.H RESOURCE.H \
                LMEM.H TIMER.H TIMEDATE.H HEAP.H FILE.H EC.H CHAR.H \
                INTERNAL/SOCKETDR.H SOCKMISC.H ANSI/STRING.H ANSI/STDIO.H \
                 PPPLOG.H IP.H \
                SLCOMPRESS.H FSM.H LCP.H LQM.H PAP.H CHAP.H IPCP.H \
                INTERNAL/NETUTILS.H
DES.obj \
DES.eobj: DES.H
IP.obj \
IP.eobj: PPP.H GEOS.H  \
                 \
                 GEODE.H RESOURCE.H \
                LMEM.H TIMER.H TIMEDATE.H HEAP.H FILE.H EC.H CHAR.H \
                INTERNAL/SOCKETDR.H SOCKMISC.H ANSI/STRING.H ANSI/STDIO.H \
                 PPPLOG.H IP.H \
                SLCOMPRESS.H FSM.H LCP.H LQM.H PAP.H CHAP.H IPCP.H \
                INTERNAL/NETUTILS.H
IPCP.obj \
IPCP.eobj: PPP.H GEOS.H  \
                 \
                 GEODE.H RESOURCE.H \
                LMEM.H TIMER.H TIMEDATE.H HEAP.H FILE.H EC.H CHAR.H \
                INTERNAL/SOCKETDR.H SOCKMISC.H ANSI/STRING.H ANSI/STDIO.H \
                 PPPLOG.H IP.H \
                SLCOMPRESS.H FSM.H LCP.H LQM.H PAP.H CHAP.H IPCP.H \
                INTERNAL/NETUTILS.H
LCP.obj \
LCP.eobj: PPP.H GEOS.H  \
                 \
                 GEODE.H RESOURCE.H \
                LMEM.H TIMER.H TIMEDATE.H HEAP.H FILE.H EC.H CHAR.H \
                INTERNAL/SOCKETDR.H SOCKMISC.H ANSI/STRING.H ANSI/STDIO.H \
                 PPPLOG.H IP.H \
                SLCOMPRESS.H FSM.H LCP.H LQM.H PAP.H CHAP.H IPCP.H \
                INTERNAL/NETUTILS.H
MD4.obj \
MD4.eobj: GEOS.H  \
                 \
                 ANSI/STRING.H MD4.H
MD5.obj \
MD5.eobj: GEOS.H  \
                 \
                 ANSI/STRING.H MD5.H
PAP.obj \
PAP.eobj: PPP.H GEOS.H  \
                 \
                 GEODE.H RESOURCE.H \
                LMEM.H TIMER.H TIMEDATE.H HEAP.H FILE.H EC.H CHAR.H \
                INTERNAL/SOCKETDR.H SOCKMISC.H ANSI/STRING.H ANSI/STDIO.H \
                 PPPLOG.H IP.H \
                SLCOMPRESS.H FSM.H LCP.H LQM.H PAP.H CHAP.H IPCP.H \
                INTERNAL/NETUTILS.H
SLCOMPRESS.obj \
SLCOMPRESS.eobj: PPP.H GEOS.H  \
                 \
                 GEODE.H RESOURCE.H \
                LMEM.H TIMER.H TIMEDATE.H HEAP.H FILE.H EC.H CHAR.H \
                INTERNAL/SOCKETDR.H SOCKMISC.H ANSI/STRING.H ANSI/STDIO.H \
                 PPPLOG.H IP.H \
                SLCOMPRESS.H FSM.H LCP.H LQM.H PAP.H CHAP.H IPCP.H \
                INTERNAL/NETUTILS.H
PPPSTRINGS.rdef: PPPSTRINGS.UI
PPPADDRCTRL.rdef: GENERIC.UIH PRODUCT.UIH ACCPNT.UIH
PPPMANAGER.obj \
PPPMANAGER.eobj: GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF SYSTEM.DEF \
                LOCALIZE.DEF SLLANG.DEF OBJECT.DEF LMEM.DEF TIMER.DEF \
                TIMEDATE.DEF DRIVER.DEF THREAD.DEF SEM.DEF SYSSTATS.DEF \
                FILE.DEF INITFILE.DEF MEDIUM.DEF GCNLIST.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF EC.DEF ASSERT.DEF DISK.DEF \
                DRIVE.DEF INTERNAL/IM.DEF INTERNAL/SEMINT.DEF \
                OBJECTS/PROCESSC.DEF INTERNAL/HEAPINT.DEF \
                INTERNAL/LOGIN.DEF UI.DEF VM.DEF TEXT.DEF CHAR.DEF \
                WIN.DEF INPUT.DEF HWR.DEF OBJECTS/TEXT/TCOMMON.DEF \
                STYLESH.DEF IACP.DEF OBJECTS/UIINPUTC.DEF \
                OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF \
                INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF SAC.DEF \
                INTERNAL/NETUTILS.DEF INTERNAL/SOCKETINT.DEF ACCPNT.DEF \
                INTERNAL/SOCKETDR.DEF SOCKMISC.DEF INTERNAL/SERIALDR.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/MODEMDR.DEF \
                INTERNAL/STRDRINT.DEF PPP.DEF INTERNAL/PPP.DEF \
                PPPADDRCTRL.DEF PPPGLOBAL.DEF PPPSTRINGS.RDEF \
                PPPADDRCTRL.RDEF PPPMAIN.ASM PPPUTILS.ASM PPPADDRCTRL.ASM

PPPEC.geo PPP.geo : GEOS.LDF NETUTILS.LDF ANSIC.LDF ACCPNT.LDF 