#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = PPP
ASM_TO_OBJS     = pppManager.asm
UI_TO_RDFS      = PPPSTRINGS.UI PPPADDRCTRL.UI
SRCS            = pppAddrCtrl.asm pppMain.asm pppManager.asm pppUtils.asm\
                  ppp.def pppAddrCtrl.def pppGlobal.def pppAddrCtrl.ui\
                  pppStrings.ui ccp.c chap.c chap_ms.c c_mppc.c\
                  c_predictor.c c_stac.c data.c des.c ip.c ipcp.c lcp.c\
                  md4.c md5.c pap.c slcompress.c ccp.h chap.h chap_ms.h\
                  des.h fsm.h ip.h ipcp.h lcp.h lqm.h md4.h md5.h pap.h\
                  ppp.h pppLog.h slcompre.h slcompress.h fsm.goc ppp.goc\
                  pppLog.goc pppLog.goh pppStrings.goh
OBJS            = pppManager.obj ccp.obj chap.obj chap_ms.obj c_mppc.obj\
                  c_predictor.obj c_stac.obj data.obj des.obj ip.obj\
                  ipcp.obj lcp.obj md4.obj md5.obj pap.obj slcompress.obj\
                  fsm.obj ppp.obj pppLog.obj
LOBJS           =

PRODUCTS        = 

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(DBCS/$(DEPFILE))
#include "DBCS/$(DEPFILE)"
#endif
