#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = ppp
ASM_TO_OBJS     = pppManager.asm
UI_TO_RDFS      = pppStrings.ui pppAddrCtrl.ui
SRCS            = pppAddrCtrl.asm pppManager.asm pppMain.asm pppUtils.asm\
                  pppAddrCtrl.def ppp.def pppGlobal.def pppAddrCtrl.ui\
                  pppStrings.ui c_predictor.c c_mppc.c chap.c md4.c\
                  c_stac.c des.c ipcp.c ccp.c ip.c chap_ms.c pap.c data.c\
                  lcp.c md5.c slcompress.c ccp.h md5.h chap.h md4.h ipcp.h\
                  pppLog.h fsm.h ip.h ppp.h pap.h lcp.h chap_ms.h lqm.h\
                  des.h slcompress.h slcompre.h pppLog.goc ppp.goc fsm.goc\
                  pppStrings.goh pppLog.goh
OBJS            = pppManager.obj c_predictor.obj c_mppc.obj chap.obj\
                  md4.obj c_stac.obj des.obj ipcp.obj ccp.obj ip.obj\
                  chap_ms.obj pap.obj data.obj lcp.obj md5.obj\
                  slcompress.obj pppLog.obj ppp.obj fsm.obj
LOBJS           =

PRODUCTS        = DBCS 

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(DBCS/$(DEPFILE))
#include "DBCS/$(DEPFILE)"
#endif
