#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = p1inst
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = INSTALL.GOC RESG.GOC RESB.GOC RESC.GOC RESD.GOC RESE.GOC\
                  RESF.GOC RESA.GOC INSTICO.GOH
OBJS            = INSTALL.obj RESG.obj RESB.obj RESC.obj RESD.obj RESE.obj\
                  RESF.obj RESA.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
