#!/bin/sh -
#
#
# Project:	PC GEOS
# Module:	Solitaire
# File:		convert
#
# Author:	atw
#
#	This file contains the convert information for this application.
#
# 	$Id: convert,v 1.2 98/04/28 17:20:55 joon Exp $
#
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/ggame1.pcx 5 Solitaire $appArgs

cvtpcx -f -m13 -t -z -nSolitaireTiny solitaire.tiny.pcx
