READER.rdef: GENERIC.UIH PRODUCT.UIH CONVIEW.UIH ART/MKRCREADER.UI \
                ART/MKRMREADER.UI ART/MKRCBOOKDOC.UI ART/MKRMBOOKDOC.UI \
                ART/MKRREADERTINY.UI ART/MKRBOOKDOCTINY.UI
READER.obj \
READER.eobj: GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF OBJECT.DEF \
                LMEM.DEF INTERNAL/PRODFEATURES.DEF UI.DEF FILE.DEF VM.DEF \
                TEXT.DEF FONTID.DEF GRAPHICS.DEF FONT.DEF COLOR.DEF \
                CHAR.DEF WIN.DEF INPUT.DEF HWR.DEF LOCALIZE.DEF \
                SLLANG.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                LIBRARY.DEF CONVIEW.DEF OBJECTS/VTEXTC.DEF SPOOL.DEF \
                PRINT.DEF HUGEARR.DEF DBASE.DEF OBJECTS/VLTEXTC.DEF \
                COMPRESS.DEF OBJECTS/INPUTC.DEF TIMER.DEF HELPFILE.DEF \
                GSTRING.DEF READER.DEF READER.RDEF

READEREC.geo READER.geo : GEOS.LDF UI.LDF CONVIEW.LDF 