cvtpcx -G -t -g -w14 -h14 -stiny -anormal -m13 -nOpenedArrow -ooparrow.goh oparrow.pcx
cvtpcx -G -t -g -w14 -h14 -stiny -anormal -m13 -nClosedArrow -oclarrow.goh clarrow.pcx
cvtpcx -G -t -g -w14 -h14 -stiny -anormal -m13 -nAway -oaway.goh away.pcx
cvtpcx -G -t -g -w14 -h14 -stiny -anormal -m13 -nArrived -oarrived.goh arrived.pcx
cvtpcx -G -t -g -w14 -h14 -stiny -anormal -m13 -nDeparted -odeparted.goh departed.pcx
cvtpcx -G -t -g -w19 -h14 -stiny -anormal -m13 -nOpenedFolder -oopfolder.goh opfolder.pcx
cvtpcx -G -t -g -w19 -h14 -stiny -anormal -m13 -nClosedFolder -oclfolder.goh clfolder.pcx
cvtpcx -G -l -u -m13 -x0 -y0 -2 -Stool -nAIMApp -oappicon1.goh appicons.pcx
cvtpcx -G -z -u -m13 -x0 -y50 -2 -Stool -nAIMApp -oappicon2.goh appicons.pcx

