#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = PDFViewer
MAIN            = array.goc catalog.goc dict.goc gfx.goc gfxFont.goc\
                  gfxState.goc lexer.goc obj.goc page.goc parser.goc\
                  stream.goc xref.goc
UI              = pdfvu.goc
UTIL            = gmem.goc gstr.goc
UI_TO_RDFS      =
OBJS            = array.obj catalog.obj dict.obj gfx.obj gfxFont.obj\
                  gfxState.obj lexer.obj obj.obj page.obj parser.obj\
                  stream.obj xref.obj pdfvu.obj gmem.obj gstr.obj
COMMON          = array.goh catalog.goh ccitt.h diction.goh gfx.goh\
                  gfxFont.goh gfxFont2.goh gfxState.goh gmem.goh gstr.goh\
                  gtypes.goh lexer.goh obj.goh page.goh parser.goh\
                  pdfGeode.goh pdfvu.goh stream.goh xref.goh
MODULES         =
CMODULES        = main ui util
SRCS            = $(MAIN) $(UI) $(UTIL) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
