#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = sndwinnt
ASM_TO_OBJS     = sndwinntManager.asm
UI_TO_RDFS      =
SRCS            = pcCode.asm sndwinntManager.asm sndwinntStrategy.asm\
                  sndwinnt.def sndwinntConstant.def sndwinntPCChips.def
OBJS            = sndwinntManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
