#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = TAIDE
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = gty_mtds.goc FNCTNS.GOC Lay_mtds.goc MOD_MTDS.GOC\
                  SEATING.GOC SET_MTDS.GOC SNT_MTDS.GOC STU_MTDS.GOC\
                  TAIDE_UI.GOC TXT_STRS.GOC DOC_MTDS.GOC att_mtds.goc\
                  rpt_mtds.goc Imp_mtds.goc gel_mtds.goc gri_mtds.goc\
                  Exp_mtds.goc SEATING.GOH TAIDE.GOH BBOXREG.GOH\
                  externs.goh tabs.goh Taappico.goh Tadocico.goh
OBJS            = gty_mtds.obj FNCTNS.obj Lay_mtds.obj MOD_MTDS.obj\
                  SEATING.obj SET_MTDS.obj SNT_MTDS.obj STU_MTDS.obj\
                  TAIDE_UI.obj TXT_STRS.obj DOC_MTDS.obj att_mtds.obj\
                  rpt_mtds.obj Imp_mtds.obj gel_mtds.obj gri_mtds.obj\
                  Exp_mtds.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
