#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = cword
ASM_TO_OBJS     = cwordManager.asm
UI_TO_RDFS      = cword.ui
SRCS            = cwordBoard.asm cwordBoardBounds.asm\
                  cwordBoardClueList.asm cwordBoardHWR.asm\
                  cwordBoardKbd.asm cwordBoardOpenClose.asm\
                  cwordClueList.asm cwordEC.asm cwordEngine.asm\
                  cwordEngineFile.asm cwordFile.asm cwordFileSel.asm\
                  cwordGenView.asm cwordHWR.asm cwordManager.asm\
                  cwordObscure.asm cwordVictory.asm cwordVisContent.asm\
                  cword.def cwordBoard.def cwordClueList.def cwordEC.def\
                  cwordEngine.def cwordFile.def cwordGenView.def\
                  cwordHWR.def cwordOther.def cwordVisContent.def cword.ui
OBJS            = cwordManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
