ALARM.obj \
ALARM.eobj: Alarm/AlarmMANAGER.ASM \
                CALENDARGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF SEM.DEF OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF FILE.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF \
                DBASE.DEF ASSERT.DEF DISK.DEF DRIVE.DEF UI.DEF VM.DEF \
                INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF CONFIG.DEF CALENDARCONSTANT.DEF \
                PRODUCT.DEF CALENDAR.DEF CALENDARGLOBAL.DEF \
                CALENDARMACRO.DEF SOUND.DEF DRIVER.DEF \
                INTERNAL/SOUNDFMT.DEF INTERNAL/SEMINT.DEF RTCM.DEF \
                ALARMALARM.ASM ALARMREMINDER.ASM
DAYEVENT.obj \
DAYEVENT.eobj: DayEvent/DayEventMANAGER.ASM \
                CALENDARGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF SEM.DEF OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF FILE.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF \
                DBASE.DEF ASSERT.DEF DISK.DEF DRIVE.DEF UI.DEF VM.DEF \
                INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF CONFIG.DEF CALENDARCONSTANT.DEF \
                PRODUCT.DEF CALENDAR.DEF CALENDARGLOBAL.DEF \
                CALENDARMACRO.DEF DAYEVENTALARM.ASM DAYEVENTDRAW.ASM \
                SYSTEM.DEF DAYEVENTMAIN.ASM DAYEVENTMISC.ASM \
                DAYEVENTSENTTOLIST.ASM
DAYPLAN.obj \
DAYPLAN.eobj: DayPlan/DayPlanMANAGER.ASM \
                CALENDARGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF SEM.DEF OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF FILE.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF \
                DBASE.DEF ASSERT.DEF DISK.DEF DRIVE.DEF UI.DEF VM.DEF \
                INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF CONFIG.DEF CALENDARCONSTANT.DEF \
                PRODUCT.DEF CALENDAR.DEF CALENDARGLOBAL.DEF \
                CALENDARMACRO.DEF INITFILE.DEF DAYPLANINIT.ASM \
                DAYPLANBUFFER.ASM DAYPLANMAIN.ASM FOAM.DEF \
                INTERNAL/RSPCOLOR.DEF DAYPLANRANGE.ASM DAYPLANPRINT.ASM \
                DAYPLANPREFERENCE.ASM DAYPLANMAILBOX.ASM DAYPLANAPI.ASM \
                DAYPLANUTILS.ASM
HOLIDAY.obj \
HOLIDAY.eobj: Holiday/HolidayMANAGER.ASM \
                CALENDARGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF SEM.DEF OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF FILE.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF \
                DBASE.DEF ASSERT.DEF DISK.DEF DRIVE.DEF UI.DEF VM.DEF \
                INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF CONFIG.DEF CALENDARCONSTANT.DEF \
                PRODUCT.DEF CALENDAR.DEF CALENDARGLOBAL.DEF \
                CALENDARMACRO.DEF
MAIN.obj \
MAIN.eobj: Main/MainMANAGER.ASM \
                CALENDARGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF SEM.DEF OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF FILE.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF \
                DBASE.DEF ASSERT.DEF DISK.DEF DRIVE.DEF UI.DEF VM.DEF \
                INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF CONFIG.DEF CALENDARCONSTANT.DEF \
                PRODUCT.DEF CALENDAR.DEF CALENDARGLOBAL.DEF \
                CALENDARMACRO.DEF SYSTEM.DEF ROLODEX.DEF INITFILE.DEF \
                MAINMAILBOX.DEF INTERNAL/GSTATE.DEF INTERNAL/TMATRIX.DEF \
                INTERNAL/FONTDR.DEF DRIVER.DEF MAINAPP.ASM MAINCALC.ASM \
                DATA.DEF MAINCALENDAR.ASM MAINDATABASE.ASM MAINFILE.ASM \
                MAINGEOMETRY.ASM MAINUNDO.ASM MAINUTILS.ASM \
                MAINMAILBOX.ASM MAINVERSITSTRINGS.ASM MAINBOOKEVENT.ASM \
                MAINRECVEVENT.ASM MAINEVENTSCONTENT.ASM \
                MAINCONFIRMDLG.ASM MAINADDRESSCTRL.ASM MAINMENU.ASM \
                MAINAPI.ASM MAINUPDATEEVENT.ASM
MISC.obj \
MISC.eobj: Misc/MiscMANAGER.ASM \
                CALENDARGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF SEM.DEF OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF FILE.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF \
                DBASE.DEF ASSERT.DEF DISK.DEF DRIVE.DEF UI.DEF VM.DEF \
                INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF CONFIG.DEF CALENDARCONSTANT.DEF \
                PRODUCT.DEF CALENDAR.DEF CALENDARGLOBAL.DEF \
                CALENDARMACRO.DEF SYSTEM.DEF INITFILE.DEF \
                MISCCUSTOMSPIN.ASM MISCDATEARROWS.ASM MISCMONTHVALUE.ASM \
                MISCPRINT.ASM MISCSEARCH.ASM
REPEAT.obj \
REPEAT.eobj: Repeat/RepeatMANAGER.ASM \
                CALENDARGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF SEM.DEF OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF FILE.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF \
                DBASE.DEF ASSERT.DEF DISK.DEF DRIVE.DEF UI.DEF VM.DEF \
                INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF CONFIG.DEF CALENDARCONSTANT.DEF \
                PRODUCT.DEF CALENDAR.DEF CALENDARGLOBAL.DEF \
                CALENDARMACRO.DEF REPEATCREATE.ASM REPEATDATABASE.ASM \
                REPEATDYNAMIC.ASM REPEATGENERATE.ASM REPEATTABLE.ASM \
                REPEATUTILS.ASM
UI.obj \
UI.eobj: UI/UIMANAGER.ASM \
                CALENDARGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF SEM.DEF OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF FILE.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF \
                DBASE.DEF ASSERT.DEF DISK.DEF DRIVE.DEF UI.DEF VM.DEF \
                INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF CONFIG.DEF CALENDARCONSTANT.DEF \
                PRODUCT.DEF CALENDAR.DEF CALENDARGLOBAL.DEF \
                CALENDARMACRO.DEF UIMANAGER.RDEF
WEEK.obj \
WEEK.eobj: Week/WeekMANAGER.ASM \
                CALENDARGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF SEM.DEF OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF FILE.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF \
                DBASE.DEF ASSERT.DEF DISK.DEF DRIVE.DEF UI.DEF VM.DEF \
                INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF CONFIG.DEF CALENDARCONSTANT.DEF \
                PRODUCT.DEF CALENDAR.DEF CALENDARGLOBAL.DEF \
                CALENDARMACRO.DEF OBJECTS/INPUTC.DEF \
                WEEKVIEWINTERACTIONCLASS.ASM WEEKDATETEXTCONTENT.ASM \
                WEEKSCHEDULECONTENTCLASS.ASM \
                WEEKEVENTTEXTCONTENTCLASS.ASM
YEAR.obj \
YEAR.eobj: Year/YearMANAGER.ASM \
                CALENDARGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF SEM.DEF OBJECT.DEF LMEM.DEF WIN.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF FILE.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF \
                DBASE.DEF ASSERT.DEF DISK.DEF DRIVE.DEF UI.DEF VM.DEF \
                INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF CONFIG.DEF CALENDARCONSTANT.DEF \
                PRODUCT.DEF CALENDAR.DEF CALENDARGLOBAL.DEF \
                CALENDARMACRO.DEF OBJECTS/INPUTC.DEF YEARMONTH.ASM \
                YEARYEARMAIN.ASM YEARYEARMOUSE.ASM YEARYEARPRINT.ASM
UIMANAGER.rdef: 