#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = Calendar
ALARM           = alarmAlarm.asm alarmManager.asm alarmReminder.asm
DAYEVENT        = dayeventAlarm.asm dayeventDraw.asm dayeventMain.asm\
                  dayeventManager.asm dayeventMisc.asm\
                  dayeventSentToList.asm
DAYPLAN         = dayplanApi.asm dayplanBuffer.asm dayplanInit.asm\
                  dayplanMailbox.asm dayplanMain.asm dayplanManager.asm\
                  dayplanPreference.asm dayplanPrint.asm dayplanRange.asm\
                  dayplanUtils.asm
HOLIDAY         = holidayData.asm holidayFile.asm holidayManager.asm\
                  holidaySetting.asm holidayUtils.asm
MAIN            = mainAddressCtrl.asm mainApi.asm mainApp.asm\
                  mainBookEvent.asm mainCalc.asm mainCalendar.asm\
                  mainConfirmDlg.asm mainDatabase.asm mainEventsContent.asm\
                  mainFile.asm mainGeometry.asm mainMailbox.asm\
                  mainManager.asm mainMenu.asm mainRecvEvent.asm\
                  mainUndo.asm mainUpdateEvent.asm mainUtils.asm\
                  mainVersitStrings.asm mainMailbox.def
MISC            = miscCustomSpin.asm miscDateArrows.asm miscManager.asm\
                  miscMonthValue.asm miscPrint.asm miscSearch.asm
REPEAT          = repeatCreate.asm repeatDatabase.asm repeatDynamic.asm\
                  repeatGenerate.asm repeatManager.asm repeatTable.asm\
                  repeatUtils.asm
UI              = uiManager.asm uiDialog.ui uiMain.ui uiManager.ui\
                  uiMenu.ui uiStrings.ui
WEEK            = weekDateTextContent.asm weekEventTextContentClass.asm\
                  weekManager.asm weekScheduleContentClass.asm\
                  weekViewInteractionClass.asm
YEAR            = yearManager.asm yearMonth.asm yearYearMain.asm\
                  yearYearMouse.asm yearYearPrint.asm
UI_TO_RDFS      = UIMANAGER.UI
OBJS            =
COMMON          = calendarConstant.def calendarGeode.def calendarGlobal.def\
                  calendarMacro.def data.def
MODULES         = Alarm DayEvent DayPlan Holiday Main Misc Repeat UI Week\
                  Year
CMODULES        =
SRCS            = $(ALARM) $(DAYEVENT) $(DAYPLAN) $(HOLIDAY) $(MAIN)\
                  $(MISC) $(REPEAT) $(UI) $(WEEK) $(YEAR) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
