XMS.obj \
XMS.eobj: GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF DRIVER.DEF \
                LMEM.DEF SEM.DEF SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF \
                FILE.DEF INITFILE.DEF DRIVE.DEF DISK.DEF \
                INTERNAL/INTERRUP.DEF INTERNAL/FILEINT.DEF FILEENUM.DEF \
                INTERNAL/DOS.DEF INTERNAL/DRIVEINT.DEF \
                INTERNAL/SEMINT.DEF INTERNAL/XMS.DEF INTERNAL/SWAPDR.DEF \
                INTERNAL/SWAP.DEF

XMSEC.geo XMS.geo : GEOS.LDF SWAP.LDF 