#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = hmbase
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = doc_mtds.goc dta_mtds.goc exp_mtds.goc fld_mtds.goc\
                  gbas_ui.goc imp_mtds.goc nav_mtds.goc rpt_mtds.goc\
                  sch_mtds.goc srt_mtds.goc txt_strs.goc appicons.goh\
                  btns.goh externs.goh findicon.goh gpcbase.goh hbicons.goh\
                  rpticons.goh
OBJS            = doc_mtds.obj dta_mtds.obj exp_mtds.obj fld_mtds.obj\
                  gbas_ui.obj imp_mtds.obj nav_mtds.obj rpt_mtds.obj\
                  sch_mtds.obj srt_mtds.obj txt_strs.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
