#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = hmbase
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = TXT_STRS.goc NAV_MTDS.goc Imp_mtds.goc DTA_MTDS.goc\
                  RPT_MTDS.goc gbas_ui.goc Exp_mtds.goc SRT_MTDS.goc\
                  FLD_MTDS.goc DOC_MTDS.goc Sch_mtds.goc rpticons.goh\
                  gpcbase.goh bbox.goh findicon.goh bbxreg.goh btns.goh\
                  externs.goh appicons.goh hbicons.goh
OBJS            = TXT_STRS.obj NAV_MTDS.obj Imp_mtds.obj DTA_MTDS.obj\
                  RPT_MTDS.obj gbas_ui.obj Exp_mtds.obj SRT_MTDS.obj\
                  FLD_MTDS.obj DOC_MTDS.obj Sch_mtds.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
