#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = gandalf
DEBUG           = debug.goc debugh.goh
EDITASM         = editasmManager.asm manager.asm sllang.def
EDITOR          = complist.goc ecommon.goc editor.goc eventlis.goc\
                  routine.goc editorh.goh
MAIN            = main.h mainagg.goc maincomp.goc mainitrp.goc mainload.goc\
                  mainproc.goc mainsave.goc mainshel.goc maintext.goc\
                  strings.goc mainshlh.goh
UI              = uimain.goc icon.goh uiicon.goh
UI_TO_RDFS      =
OBJS            = debug.obj complist.obj ecommon.obj editor.obj\
                  eventlis.obj routine.obj mainagg.obj maincomp.obj\
                  mainitrp.obj mainload.obj mainproc.obj mainsave.obj\
                  mainshel.obj maintext.obj strings.obj uimain.obj
COMMON          = gandalf.goh
MODULES         = EditAsm
CMODULES        = Debug Editor Main UI
SRCS            = $(DEBUG) $(EDITASM) $(EDITOR) $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
