#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = frcell
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = fcellGm.goc fcellproc.goc fcellui.goc frcell.goh
OBJS            = fcellGm.obj fcellproc.obj fcellui.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
