LOADER.obj \
LOADER.eobj: MAIN.ASM GEOS.DEF CHAR.DEF HEAP.DEF LIBRARY.DEF SYSTEM.DEF \
                LOCALIZE.DEF SLLANG.DEF COLOR.DEF INTERNAL/DOS.DEF \
                FILE.DEF FILEENUM.DEF INTERNAL/DEBUG.DEF \
                INTERNAL/KLOADER.DEF INTERNAL/HEAPINT.DEF \
                INTERNAL/SEMINT.DEF SYSSTATS.DEF INTERNAL/GEODESTR.DEF \
                GEODE.DEF INTERNAL/FILESTR.DEF INTERNAL/GEOSTS.DEF \
                LOADER.DEF LOCATE.ASM STRINGS.ASM INI.ASM LOAD.ASM \
                HEAP.ASM PATH.ASM VIDEODETECT.ASM
