#!/bin/sh -f
#$Id: convert,v 1.1.22.1 97/03/29 09:28:57 canavese Exp $

. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps1.pcx 2 GeoDraw $appArgs
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps1.pcx 3 GeoDrawDoc $docArgs

cvtpcx -f -m2 -t -z -x48 -y0 -nBitmapPtrTool grobj.pcx
