#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = charm
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = PROCESS.goc APPUI.goc MAP.goc TEXT.goc app.goh global.goh
OBJS            = PROCESS.obj APPUI.obj MAP.obj TEXT.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
