#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = flash
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = EDT_MTDS.GOC Flash_ui.goc TXT_STRS.GOC VIS_MTDS.GOC\
                  APP_MTDS.GOC PASSWORD.GOC Flash.goh PASSWORD.GOH\
                  DOCICONS.GOH Appicons.goh PASSWDUI.GOH EXTERNS.GOH\
                  BBOXREG.GOH
OBJS            = EDT_MTDS.obj Flash_ui.obj TXT_STRS.obj VIS_MTDS.obj\
                  APP_MTDS.obj PASSWORD.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
