#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = flash
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = password.goc vis_mtds.goc Flash_ui.goc app_mtds.goc\
                  txt_strs.goc edt_mtds.goc docicons.goh bboxreg.goh\
                  password.goh flash.goh passwdui.goh externs.goh\
                  appicons.goh
OBJS            = password.obj vis_mtds.obj Flash_ui.obj app_mtds.obj\
                  txt_strs.obj edt_mtds.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
