#!/bin/sh -
#
#
# Project:	PC GEOS
# Module:	Amateur Night
# File:		convert
#
# Author:	atw
#
#	This file contains the convert information for this application.
#
# 	$Id: convert,v 1.1.20.1 97/03/29 10:00:28 canavese Exp $
#
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/ggame1.pcx 2 Amateur -dYC -dYM -dTM -dTCGA $appArgs


