#!/bin/sh -
#
#
# Project:	PC GEOS
# Module:	Text Editor
# File:		convert
#
# Author:	brianc
#
#	This file contains the convert information for this application.
#
# 	$Id: convert,v 1.1.20.1 97/03/29 10:04:17 canavese Exp $
#
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/ggame1.pcx 1 Pyramid $appArgs

