/*
GEOS.H
STDDEF.H _DEFS.H
_NULL.H HEAP.H
GEODE.H RESOURCE.H
EC.H OBJECT.H
LMEM.H GRAPHICS.H
FONTID.H FONT.H
COLOR.H TIMER.H
VM.H DBASE.H
LOCALIZE.H TIMEDATE.H
FILE.H SLLANG.H
SYSTEM.H GEOWORKS.H
CHUNKARR.H DISK.H
DRIVE.H INPUT.H
CHAR.H HWR.H
UDIALOG.H WIN.H
OBJECTS\TEXT\TCOMMON.H
STYLESH.H FILEENUM.H
*/

/*
 * The RCS tag needs to follow the stuff above
 *
 * $Id: stdapp.h,v 1.1 97/04/04 15:59:25 newdeal Exp $
 *
 */
