#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = vmtree
ASM_TO_OBJS     = vmtreeManager.asm
UI_TO_RDFS      =
SRCS            = vmtreeCode.asm vmtreeUtils.asm vmtreeRead.asm\
                  vmtreeStack.asm vmtreeEntry.asm vmtreeWrite.asm\
                  vmtreeManager.asm vmtreeVariable.def vmtreeConstant.def
OBJS            = vmtreeManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
