#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = VMTree
ASM_TO_OBJS     = vmtreeManager.asm
UI_TO_RDFS      =
SRCS            = vmtreeCode.asm vmtreeEntry.asm vmtreeManager.asm\
                  vmtreeRead.asm vmtreeStack.asm vmtreeUtils.asm\
                  vmtreeWrite.asm vmtreeConstant.def vmtreeVariable.def
OBJS            = vmtreeManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
