#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = att6300
ASM_TO_OBJS     = att6300Manager.asm
UI_TO_RDFS      =
SRCS            = att6300Admin.asm att6300EscTab.asm att6300Manager.asm\
                  att6300StringTab.asm att6300Tables.asm DUMBCOMDEVINFO.ASM\
                  VIDCOMTABLES.ASM DUMBCOMTABLES.ASM VIDCOMENTRY.ASM\
                  VIDCOMOUTPUT.ASM VIDCOMCHARS.ASM DUMBCOMGENCHAR.ASM\
                  VIDCOMFONT.ASM VIDCOMUNDER.ASM VIDCOMUTILS.ASM\
                  VIDCOMREGION.ASM VIDCOMXOR.ASM VIDCOMINFO.ASM\
                  VIDCOMESCAPE.ASM VIDCOMPALETTE.ASM DUMBCOMOUTPUT.ASM\
                  DUMBCOMUTILS.ASM DUMBCOMCHARS.ASM DUMBCOMPOINTER.ASM\
                  DUMBCOMPALETTE.ASM VIDCOMPOLYGON.ASM VIDCOMLINE.ASM\
                  VIDCOMPUTLINE.ASM VIDCOMRASTER.ASM VIDCOMEXCLBOUNDS.ASM\
                  DUMBCOMRASTER.ASM att6300Constant.def att6300Macro.def\
                  att6300NTMacro.def att6300Variable.def
OBJS            = att6300Manager.obj
LOBJS           =

PRODUCTS        = WIN32
PROTOCONST	= VIDEO
LIBNAME		= video
SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
