#!/bin/sh -
# $Id: convtool,v 1.1.30.1 97/03/29 09:06:48 canavese Exp $
cvtpcx -f -m13 -t -l -x0 -y0 -rMode -nFinance -dLM -dLC -dLCGA grid.pcx
cvtpcx -f -m13 -t -l -x0 -y41 -rMode -nRetail -dLM -dLC -dLCGA grid.pcx
cvtpcx -f -m13 -t -l -x0 -y82 -rMode -nStats -dLM -dLC -dLCGA grid.pcx
cvtpcx -f -m13 -t -l -x0 -y123 -rMode -nConsumer -dLM -dLC -dLCGA grid.pcx
