#!/bin/sh -
#
#
# Project:	PC GEOS
# Module:	Big Calc
# File:		convert
#
# Author:	brianc
#
#	This file contains the convert information for this application.
#
#     $Id: convert,v 1.11 98/04/28 17:37:04 joon Exp $
#
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon

if [ $# -eq 0 ]; then

.

elif [ $1 = "PENELOPE" ]; then
  
  #
  # Calculator Icons (Penelope Only)
  #
  cvtpcx -2 -f -t -m11 -w25 -h20 -stiny -nBigCalcPeneTiny bcal.pcx
  cvtpcx -2 -f -t -m11 -x6 -y8 -w28 -h28 -nPenePaperTape picons3.pcx
  cvtpcx -2 -f -t -m11 -x7 -y10 -w28 -h28 -nPeneConversions picons1.pcx
  cvtpcx -2 -f -t -m11 -x41 -y10 -w28 -h28 -nPeneExchange picons1.pcx
  cvtpcx -2 -f -t -m11 -x73 -y10 -w28 -h28 -nPeneErase picons1.pcx
  cvtpcx -2 -f -t -m11 -x107 -y10 -w28 -h28 -nPeneOptions picons1.pcx
  cvtpcx -2 -f -t -m11 -x225 -y30 -w25 -h17 -nPeneArrow picons2.pcx
  cvtpcx -2 -f -t -m11 -x305 -y108 -w61 -h13 -nPeneInvert picons2.pcx
fi

cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps3.pcx 1 BigCalc $appArgs
cvtpcx -f -m13 -t -z -nBigCalcTiny bigcalc.tiny.pcx

cvtpcx -2 -f -m13 -t -b -anormal -x0 -y0 -w14 -h34 -nBackspace clcbut01.pcx

#
# Calculator Application Icon (Responder Only)
#
cvtpcx -N -2 -f -t -x0 -y0 -w64 -h50 -nResponderCalculator calapp.pcx
cvtpcx -N -2 -f -t -x0 -y0 -w115 -h75 -nResponderMainScreen CALCU.PCX


