GEODECK.obj \
GEODECK.eobj: GEOS.DEF GEODE.DEF PRODUCT.DEF EC.DEF LIBRARY.DEF \
                RESOURCE.DEF OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF \
                OBJECTS/WINC.DEF WIN.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF HEAP.DEF VM.DEF VMDEF.DEF DBASE.DEF \
                HUGEARR.DEF OBJECTS/INPUTC.DEF DECKMAP.DEF LCJOKER.ASM \
                LCWIN.ASM LCGEOBACK.ASM LCNEFERTITE.ASM LCGRAPES.ASM \
                LCCLASSIC.ASM LCPYRAMID.ASM LCEAGLE.ASM LCHINGE.ASM \
                LCBUBBLES.ASM LCMASKS.ASM LCFLOWERS.ASM LCCHEESE.ASM \
                LCFRACTAL1.ASM LCFRACTAL2.ASM LCCLUBJ.ASM LCCLUBK.ASM \
                LCCLUBQ.ASM LCDIAMONDJ.ASM LCDIAMONDK.ASM LCDIAMONDQ.ASM \
                LCHEARTJ.ASM LCHEARTK.ASM LCHEARTQ.ASM LCSPADEJ.ASM \
                LCSPADEK.ASM LCSPADEQ.ASM LCDIAMOND2.ASM LCDIAMOND3.ASM \
                LCDIAMOND4.ASM LCDIAMOND5.ASM LCDIAMOND6.ASM \
                LCDIAMOND7.ASM LCDIAMOND8.ASM LCDIAMOND9.ASM \
                LCDIAMONDA.ASM LCDIAMONDT.ASM LCHEART2.ASM LCHEART3.ASM \
                LCHEART4.ASM LCHEART5.ASM LCHEART6.ASM LCHEART7.ASM \
                LCHEART8.ASM LCHEART9.ASM LCHEARTA.ASM LCHEARTT.ASM \
                LCCLUB2.ASM LCCLUB3.ASM LCCLUB4.ASM LCCLUB5.ASM \
                LCCLUB6.ASM LCCLUB7.ASM LCCLUB8.ASM LCCLUB9.ASM \
                LCCLUBA.ASM LCCLUBT.ASM LCSPADE2.ASM LCSPADE3.ASM \
                LCSPADE4.ASM LCSPADE5.ASM LCSPADE6.ASM LCSPADE7.ASM \
                LCSPADE8.ASM LCSPADE9.ASM LCSPADEA.ASM LCSPADET.ASM \
                LMJOKER.ASM LMWIN.ASM LMGEOBACK.ASM LMNEFERTITE.ASM \
                LMGRAPES.ASM LMCLASSIC.ASM LMPYRAMID.ASM LMEAGLE.ASM \
                LMHINGE.ASM LMBUBBLES.ASM LMMASKS.ASM LMFLOWERS.ASM \
                LMCHEESE.ASM LMFRACTAL1.ASM LMFRACTAL2.ASM LMCLUBJ.ASM \
                LMCLUBK.ASM LMCLUBQ.ASM LMDIAMONDJ.ASM LMDIAMONDK.ASM \
                LMDIAMONDQ.ASM LMHEARTJ.ASM LMHEARTK.ASM LMHEARTQ.ASM \
                LMSPADEJ.ASM LMSPADEK.ASM LMSPADEQ.ASM LMDIAMOND2.ASM \
                LMDIAMOND3.ASM LMDIAMOND4.ASM LMDIAMOND5.ASM \
                LMDIAMOND6.ASM LMDIAMOND7.ASM LMDIAMOND8.ASM \
                LMDIAMOND9.ASM LMDIAMONDA.ASM LMDIAMONDT.ASM LMCLUB2.ASM \
                LMCLUB3.ASM LMCLUB4.ASM LMCLUB5.ASM LMCLUB6.ASM \
                LMCLUB7.ASM LMCLUB8.ASM LMCLUB9.ASM LMCLUBA.ASM \
                LMCLUBT.ASM LMSPADE2.ASM LMSPADE3.ASM LMSPADE4.ASM \
                LMSPADE5.ASM LMSPADE6.ASM LMSPADE7.ASM LMSPADE8.ASM \
                LMSPADE9.ASM LMSPADEA.ASM LMSPADET.ASM LMHEART2.ASM \
                LMHEART3.ASM LMHEART4.ASM LMHEART5.ASM LMHEART6.ASM \
                LMHEART7.ASM LMHEART8.ASM LMHEART9.ASM LMHEARTA.ASM \
                LMHEARTT.ASM CGAJOKER.ASM CGAWIN.ASM CGAGEOBACK.ASM \
                CGANEFERTITE.ASM CGAGRAPES.ASM CGACLASSIC.ASM \
                CGAPYRAMID.ASM CGAEAGLE.ASM CGAHINGE.ASM CGABUBBLES.ASM \
                CGAMASKS.ASM CGAFLOWERS.ASM CGACHEESE.ASM CGAFRACTAL1.ASM \
                CGAFRACTAL2.ASM CGACLUBJ.ASM CGACLUBK.ASM CGACLUBQ.ASM \
                CGADIAMONDJ.ASM CGADIAMONDK.ASM CGADIAMONDQ.ASM \
                CGAHEARTJ.ASM CGAHEARTK.ASM CGAHEARTQ.ASM CGASPADEJ.ASM \
                CGASPADEK.ASM CGASPADEQ.ASM CGADIAMOND2.ASM \
                CGADIAMOND3.ASM CGADIAMOND4.ASM CGADIAMOND5.ASM \
                CGADIAMOND6.ASM CGADIAMOND7.ASM CGADIAMOND8.ASM \
                CGADIAMOND9.ASM CGADIAMONDA.ASM CGADIAMONDT.ASM \
                CGACLUB2.ASM CGACLUB3.ASM CGACLUB4.ASM CGACLUB5.ASM \
                CGACLUB6.ASM CGACLUB7.ASM CGACLUB8.ASM CGACLUB9.ASM \
                CGACLUBA.ASM CGACLUBT.ASM CGASPADE2.ASM CGASPADE3.ASM \
                CGASPADE4.ASM CGASPADE5.ASM CGASPADE6.ASM CGASPADE7.ASM \
                CGASPADE8.ASM CGASPADE9.ASM CGASPADEA.ASM CGASPADET.ASM \
                CGAHEART2.ASM CGAHEART3.ASM CGAHEART4.ASM CGAHEART5.ASM \
                CGAHEART6.ASM CGAHEART7.ASM CGAHEART8.ASM CGAHEART9.ASM \
                CGAHEARTA.ASM CGAHEARTT.ASM
