#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = geodeck
ASM_TO_OBJS     = geodeck.asm
UI_TO_RDFS      =
SRCS            = LMWin.asm CGADiamondQ.asm LCWin.asm LMDiamond6.asm\
                  LMClubQ.asm LMSpade5.asm geodeck.asm LMHinge.asm\
                  LMDiamondQ.asm LMClub5.asm LMEagle.asm LCEagle.asm\
                  CGAHeartQ.asm CGASpade3.asm LMSpade6.asm LCDiamond7.asm\
                  LCSpade9.asm CGAClubQ.asm LCHeartT.asm CGAHeart3.asm\
                  LCSpade8.asm LCDiamondJ.asm LCHeart7.asm CGAHeart5.asm\
                  LMDiamond9.asm CGAClub9.asm LCDiamond5.asm LCHeart5.asm\
                  LMSpade7.asm LMClub3.asm LCDiamondA.asm CGADiamond2.asm\
                  LMHeartK.asm LCSpadeJ.asm LCSpade7.asm LMFractal2.asm\
                  LMClub4.asm LCClub5.asm CGADiamond4.asm CGAWin.asm\
                  CGASpade2.asm CGAGrapes.asm CGAClubK.asm LMSpadeT.asm\
                  LMClubJ.asm CGAHeart8.asm CGABubbles.asm LMJoker.asm\
                  LCPyramid.asm LMMasks.asm LCSpade6.asm LMHeartJ.asm\
                  LMClub7.asm CGASpadeT.asm CGAHeart7.asm CGADiamond8.asm\
                  CGASpade7.asm CGAClub5.asm CGASpadeK.asm CGASpade9.asm\
                  LMDiamond7.asm LCJoker.asm LCHeart4.asm LCClub8.asm\
                  LMDiamond5.asm LCBubbles.asm LCNefertite.asm\
                  CGADiamondT.asm LMSpadeK.asm CGAFlowers.asm LMSpadeQ.asm\
                  CGAJoker.asm LMClub6.asm LCFractal1.asm LMClubK.asm\
                  LMHeart2.asm CGADiamond9.asm LCSpadeK.asm LMSpadeA.asm\
                  CGAHeart9.asm LMClubA.asm LMHeart7.asm LCClubJ.asm\
                  LMSpade9.asm LMSpade8.asm LCClubT.asm LCDiamond3.asm\
                  CGAEagle.asm LCSpade2.asm LMPyramid.asm LMGrapes.asm\
                  LCSpadeA.asm LMHeartA.asm LCHeartA.asm CGAClubT.asm\
                  CGADiamond5.asm LCClubA.asm LCHeart2.asm LCMasks.asm\
                  LMHeart6.asm LMDiamondJ.asm LMDiamond3.asm LMBubbles.asm\
                  LCDiamondK.asm LCFlowers.asm LMCheese.asm LMSpadeJ.asm\
                  CGAClub2.asm LCSpadeT.asm LMFlowers.asm LMGeoback.asm\
                  LMFractal1.asm LCSpadeQ.asm CGADiamond7.asm\
                  LCDiamondQ.asm CGAHeartA.asm CGAHeartK.asm LMSpade2.asm\
                  LCDiamond4.asm LMHeartT.asm LCClubQ.asm LCSpade5.asm\
                  LMSpade4.asm LCCheese.asm CGASpadeA.asm LMNefertite.asm\
                  LMHeart5.asm CGAHeart6.asm LMSpade3.asm LMClub9.asm\
                  CGAHeart4.asm LMDiamond4.asm CGAHeart2.asm LCGrapes.asm\
                  CGADiamondA.asm LCDiamond6.asm CGAPyramid.asm\
                  LCGeoback.asm LMDiamond2.asm CGASpade5.asm LCHeartK.asm\
                  LMClub2.asm LCClubK.asm LMDiamond8.asm LCDiamond9.asm\
                  LCFractal2.asm CGAClub3.asm CGADiamondK.asm\
                  LMDiamondK.asm CGAGeoback.asm LCDiamond2.asm LMClub8.asm\
                  CGASpade4.asm LCHeart6.asm CGADiamond6.asm CGAHinge.asm\
                  CGAHeartT.asm LCClub7.asm CGADiamondJ.asm LMClassic.asm\
                  CGASpade8.asm LCSpade4.asm LCSpade3.asm LMHeart4.asm\
                  CGAFractal2.asm LCClub3.asm LCClub2.asm LMDiamondT.asm\
                  CGASpadeQ.asm CGACheese.asm CGADiamond3.asm CGAClub8.asm\
                  LMDiamondA.asm CGAFractal1.asm LMHeart8.asm LMHeart3.asm\
                  LMHeart9.asm CGAMasks.asm CGAClubA.asm CGASpadeJ.asm\
                  LCHeart3.asm CGAClub4.asm LCClub9.asm LCClassic.asm\
                  CGAClub6.asm CGAClubJ.asm LCDiamond8.asm LCHeart8.asm\
                  LCHinge.asm LCHeartJ.asm LCClub6.asm CGASpade6.asm\
                  LMClubT.asm LMHeartQ.asm LCClub4.asm CGANefertite.asm\
                  CGAClassic.asm LCDiamondT.asm LCHeart9.asm CGAClub7.asm\
                  LCHeartQ.asm CGAHeartJ.asm
OBJS            = geodeck.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
