#!/bin/sh -
#########################################################################
#
#				convert
#
# Description:	Convert script for the Zoomer File Manager
# Created:	Don Reeves, on December 17, 1992
# 
# $Id: convert,v 1.10.9.1 97/03/29 09:05:28 canavese Exp $
#
#########################################################################

##############################################################################
#
# taken from CommonGM/CArt/convert to make YM-only art for ZMGR - brianc 6/9/93
#
##############################################################################

#
# Convert a pcx file to a moniker, dealing with locating the installed or
# uninstalled version of the file (doesn't deal with branches, I'm afraid)
#
# Usage: cvt <file> <cvtpcx-args>
#
cvt() {
    name=""
    for a do
	case $a in
	    -n*)	name=`expr x$a : 'x-n\(.*\)$'` ;;
	esac
    done
    if [ ! "$name" ]; then
	echo $0: missing -n arg for cvt
	exit 1
    fi
    file=$1
    shift
    if [ ! -f $file ]; then
	file=`otherdir`/$file
    fi
    cvtpcx -f "$@" $file
    mv mkr$name.ui cmkr$name.ui
}

#
# Similar to the above, but the pcx file is cvted to a bitmap, rather
# than a gstring moniker. Must be given a -n<name> argument to pass to cvtpcx,
# and result is left in cbm<name>.ui, instead of cmkr<name>.ui
#
cvtbm() {
    name=""
    for a do
	case $a in
	    -n*)	name=`expr x$a : 'x-n\(.*\)$'` ;;
	esac
    done
    if [ ! "$name" ]; then
	echo $0: missing -n arg for cvtbm
	exit 1
    fi
    cvt "$@" -g
    sed -e 's/Moniker =/Bitmap =/' cmkr$name.ui > cbm$name.ui
}


#########################################################################
# Application Icons 	(APPICON.PCX)					#
#########################################################################

#------------------------ File Manager Icon  ---------------------------#
cvt PCX/appicon.pcx -m13 -t -L -x0 -y0   -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nFileMgr

#-----------------------  File Cabinet Icon  ---------------------------#
cvt PCX/appicon.pcx -m13 -t -L -x0 -y41  -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nFileCabinet

#-----------------------  Generic GEOS App Icon  -----------------------#
cvt PCX/appicon.pcx -m13 -t -L -x0 -y82  -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nGenAppl

#-----------------------  Generic GEOS Doc Icon  -----------------------#
cvt PCX/appicon.pcx -m13 -t -L -x0 -y123 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nGenDoc

#-----------------------  Generic DOS App Icon  ------------------------#
cvt PCX/appicon.pcx -m13 -t -L -x0 -y164 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nDosAppl

#-----------------------  Generic DOS Doc Icon  ------------------------#
cvt PCX/appicon.pcx -m13 -t -L -x0 -y205 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nDosData

#-----------------------  Template Icon  -------------------------------#
cvt PCX/appicon.pcx -m13 -t -L -x0 -y246 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nTemplate

#########################################################################
# Desktop Icons		(DESKICON.PCX)					#
#########################################################################

#-----------------------  Messy Waste Can Icon  ------------------------#
###	This bitmap must be done first or the non-bitmap will be overwritten
cvtbm PCX/deskicon.pcx -rAppIconArea -u -m13 -t -L -x0 -y0   -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nMessyWasteCan
###	Non-bitmap
cvt   PCX/deskicon.pcx -rAppIconArea    -m13 -t -L -x0 -y0   -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nMessyWasteCan

#-----------------------  MonoFolder Icon  -----------------------------#
cvt   PCX/deskicon.pcx -rAppIconArea    -m13 -t -L -x0 -y41  -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nMonoFolder
sed -e '/cachedSize/s/30/31/' cmkrMonoFolder.ui > q
rm cmkrMonoFolder.ui
mv q cmkrMonoFolder.ui

#-----------------------  MultiFolder Icon  ----------------------------#
cvt   PCX/deskicon.pcx -rAppIconArea    -m13 -t -L -x0 -y82  -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nMultiFolder
sed -e '/cachedSize/s/30/31/' cmkrMultiFolder.ui > q
rm cmkrMultiFolder.ui
mv q cmkrMultiFolder.ui

#-----------------------  World Directory Icon  ------------------------#
cvt   PCX/deskicon.pcx -rAppIconArea -u -m13 -t -L -x0 -y123 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nWorldDirButton

#-----------------------  Document Directory Icon  ---------------------#
###	This bitmap must be done first or the non-bitmap will be overwritten
cvt   PCX/deskicon.pcx -rAppIconArea -g -u -m13 -t -L -x0 -y164 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nDocDirButton
sed -e '/cachedSize/s/48/32/' -e 's/Moniker =/Bitmap =/' cmkrDocDirButton.ui > cbmDocDirButton.ui
rm cmkrDocDirButton.ui
###	Non-bitmap
cvt   PCX/deskicon.pcx -rAppIconArea    -m13 -t -L -x0 -y164 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nDocDirButton

#-----------------------  Connect Icon  --------------------------------#
cvt   PCX/deskicon.pcx -rAppIconArea -u -m13 -t -L -x0 -y205 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nConnectButton

#-----------------------  Disconnect Icon  -----------------------------#
cvt   PCX/deskicon.pcx -rAppIconArea -u -m13 -t -L -x0 -y246 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nDisconnectButton

#--------------------------  Folder Icon  ------------------------------#
cvt   PCX/deskicon.pcx                  -m13 -t -L -x0 -y287 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nFileFolder


#########################################################################
#			Disk Drive Icons				#
#########################################################################

#-------------------  Three Inch Disk Icon  ----------------------------#
cvtbm PCX/drivicon.pcx -u -rAppDrives -m13 -t -L -x0 -y0   -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nThreeInchDisk
cvt   PCX/drivicon.pcx                -m13 -t -L -x0 -y0   -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nThreeInchDisk

#---------------------  Five Inch Disk Icon  ----------------------------#
cvtbm PCX/drivicon.pcx -u -rAppDrives -m13 -t -L -x0 -y41  -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nFiveInchDisk
cvt   PCX/drivicon.pcx                -m13 -t -L -x0 -y41  -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nFiveInchDisk

#-----------------------  Hard Disk Icon  ------------------------------#
cvtbm PCX/drivicon.pcx -u -rAppDrives -m13 -t -L -x0 -y82  -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nHardDisk
cvt   PCX/drivicon.pcx                -m13 -t -L -x0 -y82  -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nHardDisk

#-------------------------  Ram Disk Icon  -----------------------------#
cvtbm PCX/drivicon.pcx -u -rAppDrives -m13 -t -L -x0 -y123 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nRamDisk
cvt   PCX/drivicon.pcx                -m13 -t -L -x0 -y123 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nRamDisk

#-------------------------  Net Disk Icon  -----------------------------#
cvtbm PCX/drivicon.pcx -u -rAppDrives -m13 -t -L -x0 -y164 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nNetDisk
cvt   PCX/drivicon.pcx                -m13 -t -L -x0 -y164 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nNetDisk

#--------------------------  CD Rom Icon  ------------------------------#
cvtbm PCX/drivicon.pcx -u -rAppDrives -m2  -t -L -x0 -y205 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nCDRom
cvt   PCX/drivicon.pcx                -m2  -t -L -x0 -y205 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nCDRom

#--------------------------  PCMCIA Icon  ------------------------------#
cvtbm PCX/drivicon.pcx -u -rAppDrives -m2  -t -L -x0 -y246 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nPCMCIA
cvt   PCX/drivicon.pcx                -m2  -t -L -x0 -y246 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dYC -dTM -dTCGA -nPCMCIA


#########################################################################
# Zoomer-Specific	(ZOOMICON.PCX)					#
#########################################################################

cvtpcx -rAppIconArea -u -f -m13 -t -L -x0 -y0   -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dTM -dTCGA -dYC -nZoomerDrives PCX/zoomicon.pcx

cvtpcx -rAppIconArea -u -f -m13 -t -L -x0 -y164 -dLC -dLM -dSC -dSM -dLCGA -dSCGA -dTM -dTCGA -dYC -nConnectNotifyButton PCX/zoomicon.pcx

