DOCUMENT.obj \
DOCUMENT.eobj: Document/DocumentMANAGER.ASM \
                ICONGEODE.DEF STDAPP.DEF GEOS.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF LMEM.DEF OBJECT.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF HEAP.DEF \
                UI.DEF FILE.DEF VM.DEF WIN.DEF INPUT.DEF HWR.DEF \
                LOCALIZE.DEF SLLANG.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF \
                TIMEDATE.DEF OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF \
                IACP.DEF OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF \
                OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF \
                OBJECTS/GENC.DEF DISK.DEF DRIVE.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                INITFILE.DEF OBJECTS/WINC.DEF OBJECTS/INPUTC.DEF \
                ASSERT.DEF OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                BITMAP.DEF IMPEX.DEF IECOMMON.DEF INTERNAL/VIDEODR.DEF \
                DRIVER.DEF GROBJ.DEF OBJECTS/SPLINE.DEF \
                OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF ICONCONSTANT.DEF \
                ICONGLOBAL.DEF ICONFILE.DEF ICONDOCUMENT.DEF \
                ICONFORMAT.DEF ICONVIEWER.DEF DOCUMENTCONSTANT.DEF \
                DOCUMENTDOCUMENT.ASM DOCUMENTAPPLICATION.ASM \
                DOCUMENTADDICON.ASM DOCUMENTSAVEICON.ASM DOCUMENTICON.ASM \
                DOCUMENTVISBITMAP.ASM DOCUMENTUTILS.ASM \
                DOCUMENTOPTIONS.ASM DOCUMENTDATABASE.ASM \
                DOCUMENTIMPEX.ASM DOCUMENTTOKEN.ASM DOCUMENTTRANSFER.ASM \
                DOCUMENTUI.ASM
FORMAT.obj \
FORMAT.eobj: Format/FormatMANAGER.ASM \
                ICONGEODE.DEF STDAPP.DEF GEOS.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF LMEM.DEF OBJECT.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF HEAP.DEF \
                UI.DEF FILE.DEF VM.DEF WIN.DEF INPUT.DEF HWR.DEF \
                LOCALIZE.DEF SLLANG.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF \
                TIMEDATE.DEF OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF \
                IACP.DEF OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF \
                OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF \
                OBJECTS/GENC.DEF DISK.DEF DRIVE.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                INITFILE.DEF OBJECTS/WINC.DEF OBJECTS/INPUTC.DEF \
                ASSERT.DEF OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                BITMAP.DEF IMPEX.DEF IECOMMON.DEF INTERNAL/VIDEODR.DEF \
                DRIVER.DEF GROBJ.DEF OBJECTS/SPLINE.DEF \
                OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF ICONCONSTANT.DEF \
                ICONGLOBAL.DEF ICONFILE.DEF ICONDOCUMENT.DEF \
                ICONFORMAT.DEF ICONVIEWER.DEF FORMATCONSTANT.DEF \
                FORMATFORMAT.ASM FORMATTRANSFORM.ASM FORMATUI.ASM \
                FORMATFLIP.ASM FORMATVMFILE.ASM
PREVIEW.obj \
PREVIEW.eobj: Preview/PreviewMANAGER.ASM \
                ICONGEODE.DEF STDAPP.DEF GEOS.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF LMEM.DEF OBJECT.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF HEAP.DEF \
                UI.DEF FILE.DEF VM.DEF WIN.DEF INPUT.DEF HWR.DEF \
                LOCALIZE.DEF SLLANG.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF \
                TIMEDATE.DEF OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF \
                IACP.DEF OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF \
                OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF \
                OBJECTS/GENC.DEF DISK.DEF DRIVE.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                INITFILE.DEF OBJECTS/WINC.DEF OBJECTS/INPUTC.DEF \
                ASSERT.DEF OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                BITMAP.DEF IMPEX.DEF IECOMMON.DEF INTERNAL/VIDEODR.DEF \
                DRIVER.DEF GROBJ.DEF OBJECTS/SPLINE.DEF \
                OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF ICONCONSTANT.DEF \
                ICONGLOBAL.DEF ICONFILE.DEF ICONDOCUMENT.DEF \
                ICONFORMAT.DEF ICONVIEWER.DEF PREVIEWPREVIEW.ASM
SOURCE.obj \
SOURCE.eobj: Source/SourceMANAGER.ASM \
                ICONGEODE.DEF STDAPP.DEF GEOS.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF LMEM.DEF OBJECT.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF HEAP.DEF \
                UI.DEF FILE.DEF VM.DEF WIN.DEF INPUT.DEF HWR.DEF \
                LOCALIZE.DEF SLLANG.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF \
                TIMEDATE.DEF OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF \
                IACP.DEF OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF \
                OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF \
                OBJECTS/GENC.DEF DISK.DEF DRIVE.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                INITFILE.DEF OBJECTS/WINC.DEF OBJECTS/INPUTC.DEF \
                ASSERT.DEF OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                BITMAP.DEF IMPEX.DEF IECOMMON.DEF INTERNAL/VIDEODR.DEF \
                DRIVER.DEF GROBJ.DEF OBJECTS/SPLINE.DEF \
                OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF ICONCONSTANT.DEF \
                ICONGLOBAL.DEF ICONFILE.DEF ICONDOCUMENT.DEF \
                ICONFORMAT.DEF ICONVIEWER.DEF SYSTEM.DEF \
                INTERNAL/HARRINT.DEF SOURCECONSTANT.DEF \
                SOURCESTRINGS.RDEF SOURCESOURCE.ASM SOURCEUTILS.ASM \
                SOURCEPOINTER.ASM SOURCELARGE.ASM
UI.obj \
UI.eobj: UI/UIMANAGER.ASM \
                ICONGEODE.DEF STDAPP.DEF GEOS.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF LMEM.DEF OBJECT.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF HEAP.DEF \
                UI.DEF FILE.DEF VM.DEF WIN.DEF INPUT.DEF HWR.DEF \
                LOCALIZE.DEF SLLANG.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF \
                TIMEDATE.DEF OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF \
                IACP.DEF OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF \
                OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF \
                OBJECTS/GENC.DEF DISK.DEF DRIVE.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                INITFILE.DEF OBJECTS/WINC.DEF OBJECTS/INPUTC.DEF \
                ASSERT.DEF OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                BITMAP.DEF IMPEX.DEF IECOMMON.DEF INTERNAL/VIDEODR.DEF \
                DRIVER.DEF GROBJ.DEF OBJECTS/SPLINE.DEF \
                OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF ICONCONSTANT.DEF \
                ICONGLOBAL.DEF ICONFILE.DEF ICONDOCUMENT.DEF \
                ICONFORMAT.DEF ICONVIEWER.DEF UICONSTANT.DEF \
                UIMANAGER.RDEF UICOLOR.ASM UINEWCLASSES.ASM
VIEWER.obj \
VIEWER.eobj: Viewer/ViewerMANAGER.ASM \
                ICONGEODE.DEF STDAPP.DEF GEOS.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF LMEM.DEF OBJECT.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF HEAP.DEF \
                UI.DEF FILE.DEF VM.DEF WIN.DEF INPUT.DEF HWR.DEF \
                LOCALIZE.DEF SLLANG.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF \
                TIMEDATE.DEF OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF \
                IACP.DEF OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF \
                OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF \
                OBJECTS/GENC.DEF DISK.DEF DRIVE.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                INITFILE.DEF OBJECTS/WINC.DEF OBJECTS/INPUTC.DEF \
                ASSERT.DEF OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                BITMAP.DEF IMPEX.DEF IECOMMON.DEF INTERNAL/VIDEODR.DEF \
                DRIVER.DEF GROBJ.DEF OBJECTS/SPLINE.DEF \
                OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF ICONCONSTANT.DEF \
                ICONGLOBAL.DEF ICONFILE.DEF ICONDOCUMENT.DEF \
                ICONFORMAT.DEF ICONVIEWER.DEF VIEWERCONSTANT.DEF \
                VIEWERVISICON.ASM VIEWERMAIN.ASM VIEWERKBD.ASM \
                VIEWERUI.ASM
