#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = icon
DOCUMENT        = documentAddIcon.asm documentApplication.asm\
                  documentDatabase.asm documentDocument.asm\
                  documentIcon.asm documentImpex.asm documentManager.asm\
                  documentOptions.asm documentSaveIcon.asm\
                  documentToken.asm documentTransfer.asm documentUI.asm\
                  documentUtils.asm documentVisBitmap.asm\
                  documentConstant.def
FORMAT          = formatFlip.asm formatFormat.asm formatManager.asm\
                  formatTransform.asm formatUI.asm formatVMFile.asm\
                  formatConstant.def
PREVIEW         = previewManager.asm previewPreview.asm
SOURCE          = sourceLarge.asm sourceManager.asm sourcePointer.asm\
                  sourceSource.asm sourceUtils.asm sourceConstant.def\
                  sourceStrings.ui
UI              = uiColor.asm uiManager.asm uiNewClasses.asm uiConstant.def\
                  uiAddIcon.ui uiDocument.ui uiFormatMenu.ui uiGraphics.ui\
                  uiIconMenu.ui uiMain.ui uiManager.ui uiOptions.ui\
                  uiPreview.ui uiStrings.ui uiTokenDB.ui uiTransform.ui\
                  uiWriteSource.ui
VIEWER          = viewerKbd.asm viewerMain.asm viewerManager.asm\
                  viewerUI.asm viewerVisIcon.asm viewerConstant.def
UI_TO_RDFS      = sourceStrings.ui uiManager.ui
OBJS            =
COMMON          = iconConstant.def iconDocument.def iconFile.def\
                  iconFormat.def iconGeode.def iconGlobal.def\
                  iconViewer.def
MODULES         = Document Format Preview Source UI Viewer
CMODULES        =
SRCS            = $(DOCUMENT) $(FORMAT) $(PREVIEW) $(SOURCE) $(UI)\
                  $(VIEWER) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
