#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = BSD8ST
ASM_TO_OBJS     = manager.asm
UI_TO_RDFS      =
SRCS            = bsdac.asm bsdelay.asm bserror.asm bsinit.asm bsint.asm\
                  bsmixer.asm bsnwav.asm bsrecord.asm bsregs.asm\
                  bsstrate.asm bsstream.asm bstimer.asm bsvoice.asm\
                  bswav.asm manager.asm bsconst.def bserror.def
OBJS            = manager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
