DBCS/TCPIP.obj \
DBCS/TCPIP.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH ACCPNT.GOH
DBCS/TCPIP.obj \
DBCS/TCPIP.eobj: TCPIP.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H OBJECT.H \
                LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H GSTRING.H \
                TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H TIMEDATE.H \
                FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H SEM.H INITFILE.H INTERNAL/SOCKETDR.H \
                SOCKMISC.H IP.H TCP.H UDP.H RAWIP.H TCPIP.H TCPIPLOG.H \
                ANSI/STRING.H
DBCS/ICMP.obj \
DBCS/ICMP.eobj: GEOS.H ANSI/STRING.H TIMER.H LMEM.H TIMEDATE.H EC.H \
                INTERNAL/SOCKETDR.H SOCKMISC.H IP.H TCP.H ICMP.H UDP.H \
                RAWIP.H TCPIP.H TCPIPLOG.H
DBCS/IPINPUT.obj \
DBCS/IPINPUT.eobj: GEOS.H RESOURCE.H GEODE.H ANSI/STRING.H TIMER.H HEAP.H \
                LMEM.H EC.H INTERNAL/SOCKETDR.H SOCKMISC.H IP.H TCP.H \
                ICMP.H UDP.H RAWIP.H TCPIP.H TCPIPLOG.H
DBCS/IPOUTPUT.obj \
DBCS/IPOUTPUT.eobj: GEOS.H RESOURCE.H ANSI/STRING.H TIMER.H LMEM.H EC.H \
                INTERNAL/SOCKETDR.H SOCKMISC.H IP.H TCP.H ICMP.H TCPIP.H \
                TCPIPLOG.H
DBCS/RAWIP.obj \
DBCS/RAWIP.eobj: GEOS.H RESOURCE.H ANSI/STRING.H LMEM.H EC.H \
                INTERNAL/SOCKETDR.H SOCKMISC.H IP.H RAWIP.H ICMP.H \
                TCPIP.H TIMER.H
DBCS/TCPINPUT.obj \
DBCS/TCPINPUT.eobj: GEOS.H RESOURCE.H ANSI/STRING.H LMEM.H TIMER.H TIMEDATE.H \
                EC.H INTERNAL/SOCKETDR.H SOCKMISC.H IP.H TCP.H TCPIP.H \
                TCPIPLOG.H
DBCS/TCPIPLOG.obj \
DBCS/TCPIPLOG.eobj: GEOS.H RESOURCE.H GEODE.H ANSI/STRING.H ANSI/STDIO.H \
                FILE.H EC.H INTERNAL/SOCKETDR.H SOCKMISC.H IP.H TCP.H \
                ICMP.H UDP.H TCPIP.H TIMER.H TCPIPLOG.H ANSI/SBCS.H tcpipLog.c
DBCS/TCPOUTPUT.obj \
DBCS/TCPOUTPUT.eobj: GEOS.H RESOURCE.H ANSI/STRING.H LMEM.H TIMER.H TIMEDATE.H \
                EC.H INTERNAL/SOCKETDR.H SOCKMISC.H IP.H TCP.H TCPIP.H \
                TCPIPLOG.H
DBCS/TCPUTILS.obj \
DBCS/TCPUTILS.eobj: GEOS.H RESOURCE.H GEODE.H ANSI/STRING.H LMEM.H TIMER.H \
                TIMEDATE.H EC.H INTERNAL/SOCKETDR.H SOCKMISC.H IP.H TCP.H \
                ICMP.H TCPIP.H TCPIPLOG.H
DBCS/UDP.obj \
DBCS/UDP.eobj: GEOS.H RESOURCE.H ANSI/STRING.H LMEM.H INITFILE.H EC.H \
                INTERNAL/SOCKETDR.H SOCKMISC.H IP.H UDP.H ICMP.H TCPIP.H \
                TIMER.H TCPIPLOG.H
DBCS/TCPIPSTRINGS.rdef: 
DBCS/TCPIPADDRCTRL.rdef: GENERIC.UIH PRODUCT.UIH
DBCS/TCPIPMANAGER.obj \
DBCS/TCPIPMANAGER.eobj: GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF SYSTEM.DEF \
                LOCALIZE.DEF SLLANG.DEF LIBRARY.DEF OBJECT.DEF LMEM.DEF \
                TIMER.DEF TIMEDATE.DEF DRIVER.DEF THREAD.DEF \
                INTERNAL/SEMINT.DEF SEM.DEF INTERNAL/HEAPINT.DEF \
                SYSSTATS.DEF INTERNAL/IM.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF \
                INTERNAL/THREADIN.DEF FILE.DEF INITFILE.DEF ASSERT.DEF \
                DISK.DEF DRIVE.DEF MEDIUM.DEF UI.DEF VM.DEF TEXT.DEF \
                FONTID.DEF GRAPHICS.DEF FONT.DEF COLOR.DEF CHAR.DEF \
                UNICODE.DEF WIN.DEF INPUT.DEF HWR.DEF GCNLIST.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                SOCKET.DEF SAC.DEF INTERNAL/NETUTILS.DEF \
                INTERNAL/SOCKETINT.DEF RESOLVER.DEF INTERNAL/IP.DEF \
                INTERNAL/SOCKETDR.DEF SOCKMISC.DEF TCPIP.DEF \
                TCPIPGLOBAL.DEF TCPIPADDRCTRL.DEF DHCPCONSTANT.DEF \
                DBCS/TCPIPSTRINGS.RDEF DBCS/TCPIPADDRCTRL.RDEF TCPIPENTRY.ASM \
                TCPIPSOCKET.ASM TCPIPLINK.ASM TCPIPUTILS.ASM \
                TCPIPADDRCTRL.ASM TCPIPDHCP.ASM

DBCS/TCPIPEC.geo DBCS/TCPIP.geo : GEOS.LDF NETUTILS.LDF SOCKET.LDF ANSIC.LDF ACCPNT.LDF RESOLVER.LDF RESOLVER.LDF 