SERIALHIGHSPEED.obj \
SERIALHIGHSPEED.eobj: SERIAL.DEF GEOS.DEF GEODE.DEF RESOURCE.DEF EC.DEF \
                SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF DRIVER.DEF \
                LMEM.DEF HEAP.DEF MEDIUM.DEF ASSERT.DEF DISK.DEF FILE.DEF \
                DRIVE.DEF INTERNAL/SEMINT.DEF INTERNAL/INTERRUP.DEF \
                INTERNAL/DOS.DEF FILEENUM.DEF INTERNAL/SERIALDR.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/STRDRINT.DEF \
                INTERNAL/POWERDR.DEF INTERNAL/SERIALIO.DEF
SERIALINIT.obj \
SERIALINIT.eobj: SERIAL.DEF GEOS.DEF GEODE.DEF RESOURCE.DEF EC.DEF \
                SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF DRIVER.DEF \
                LMEM.DEF HEAP.DEF MEDIUM.DEF ASSERT.DEF DISK.DEF FILE.DEF \
                DRIVE.DEF INTERNAL/SEMINT.DEF INTERNAL/INTERRUP.DEF \
                INTERNAL/DOS.DEF FILEENUM.DEF INTERNAL/SERIALDR.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/STRDRINT.DEF \
                INTERNAL/POWERDR.DEF INTERNAL/SERIALIO.DEF INITFILE.DEF
SERIALINT.obj \
SERIALINT.eobj: SERIAL.DEF GEOS.DEF GEODE.DEF RESOURCE.DEF EC.DEF \
                SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF DRIVER.DEF \
                LMEM.DEF HEAP.DEF MEDIUM.DEF ASSERT.DEF DISK.DEF FILE.DEF \
                DRIVE.DEF INTERNAL/SEMINT.DEF INTERNAL/INTERRUP.DEF \
                INTERNAL/DOS.DEF FILEENUM.DEF INTERNAL/SERIALDR.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/STRDRINT.DEF \
                INTERNAL/POWERDR.DEF INTERNAL/SERIALIO.DEF
SERIALMAIN.obj \
SERIALMAIN.eobj: SERIAL.DEF GEOS.DEF GEODE.DEF RESOURCE.DEF EC.DEF \
                SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF TIMER.DEF DRIVER.DEF \
                LMEM.DEF HEAP.DEF MEDIUM.DEF ASSERT.DEF DISK.DEF FILE.DEF \
                DRIVE.DEF INTERNAL/SEMINT.DEF INTERNAL/INTERRUP.DEF \
                INTERNAL/DOS.DEF FILEENUM.DEF INTERNAL/SERIALDR.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/STRDRINT.DEF \
                INTERNAL/POWERDR.DEF INTERNAL/SERIALIO.DEF INITFILE.DEF

SerialEC.geo Serial.geo : GEOS.LDF STREAM.LDF
