PROTO.rdef: GENERIC.UIH PRODUCT.UIH
PROTOMANAGER.obj \
PROTOMANAGER.eobj: GEOS.DEF GEODE.DEF RESOURCE.DEF EC.DEF OBJECT.DEF LMEM.DEF \
                SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF HEAP.DEF DISK.DEF \
                FILE.DEF DRIVE.DEF FILEENUM.DEF INTERNAL/FILESTR.DEF \
                INTERNAL/FILEINT.DEF INTERNAL/DOS.DEF \
                INTERNAL/DRIVEINT.DEF INTERNAL/SEMINT.DEF \
                INTERNAL/GEODESTR.DEF UI.DEF VM.DEF TEXT.DEF FONTID.DEF \
                GRAPHICS.DEF FONT.DEF COLOR.DEF CHAR.DEF WIN.DEF \
                INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF \
                PROTOCONSTANT.DEF PROTOMACRO.DEF PROTOVARIABLE.DEF \
                PROTO.RDEF PROTOMAIN.ASM

protoEC.geo proto.geo : GEOS.LDF UI.LDF 