#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = protobiffer
ASM_TO_OBJS     = protoManager.asm
UI_TO_RDFS      = proto.ui
SRCS            = protoManager.asm protoMain.asm protoVariable.def\
                  protoConstant.def protoMacro.def proto.ui
OBJS            = protoManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
