#!/bin/sh -
#########################################################################
#				convert					#
# Convert script for Startup 						#
# Run this to create the mkrXXX.ui files for Startup.			#
# 									#
# $Id: convert,v 1.6.8.1 97/03/29 10:20:07 canavese Exp $			#
#########################################################################
#
# Convert a pcx file to a moniker, dealing with locating the installed or
# uninstalled version of the file (doesn't deal with branches, I'm afraid)
#
# Usage: cvt <file> <cvtpcx-args>
#
cvt() {
    file=$1
    shift
    if [ ! -f $file ]; then
	file=`otherdir`/$file
    fi
    cvtpcx -f "$@" $file
}



#########################################################################
#			Room Button Monikers				#
#########################################################################

#--------------------------  Color  ------------------------------#
cvt PCX/biggrid.pcx -g -m13 -w144 -h114 -x1 -y231 -anormal -nProRoomColor

#---------------------------  BW  --------------------------------#
cvt PCX/biggrid.pcx -g -m13 -w144 -h114 -x146 -y231 -anormal -b -nProRoomBW

#---------------------------  CGA  -------------------------------#
cvt PCX/biggrid.pcx -g -m13 -w144 -h62 -x291 -y231 -averySquished -b -nProRoomCGA


#########################################################################
#		ICLAS monikers						#
#########################################################################
cvtflags="PCX/ws-lev.pcx -g -w144"
y=1
cvt $cvtflags -m3  -h114 -x1   -y$y -anormal -nCPrimary
cvt $cvtflags -m3  -h114 -x146 -y$y -anormal -b -nBWPrimary
cvt $cvtflags -m3  -h62  -x291 -y$y -averySquished -b -nCGAPrimary

y=116
cvt $cvtflags -m13  -h114 -x1   -y$y -anormal -nCAssisted
cvt $cvtflags -m13  -h114 -x146 -y$y -anormal -b -nBWAssisted
cvt $cvtflags -m13  -h62  -x291 -y$y -averySquished -b -nCGAAssisted

y=231
cvt $cvtflags -m13  -h114 -x1   -y$y -anormal -nCSelfGuided
cvt $cvtflags -m13  -h114 -x146 -y$y -anormal -b -nBWSelfGuided
cvt $cvtflags -m13  -h62  -x291 -y$y -averySquished -b -nCGASelfGuided

cvt PCX/gmouse.pcx -m13 -rOverviewRoom -t -l -x0 -y0 -dSC -dSM -dSCGA -dYC -dYM -dTC -dTM -dTCGA -nMouseTutIcon

#
# 3/26 EDS: removed "-dYCLA" typo, because I don't think that "-dLCGA"
# was intended.
#
