#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = ProtoBiffer
ASM_TO_OBJS     = protoManager.asm
UI_TO_RDFS      = PROTO.UI
SRCS            = protoMain.asm protoManager.asm protoConstant.def\
                  protoMacro.def protoVariable.def proto.ui
OBJS            = protoManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
