#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = EtherODI
ASM_TO_OBJS     = ethodiManager.asm
UI_TO_RDFS      =
SRCS            = ethodiArp.asm ethodiInit.asm ethodiManager.asm\
                  ethodiProtocol.asm ethodiTransceive.asm\
                  ../EtherCom/ETHERCOMUTIL.ASM\
                  ../EtherCom/ETHERCOMSTRATEGY.ASM\
                  ../EtherCom/ETHERCOMGETINFO.ASM\
                  ../EtherCom/ETHERCOMTRANSCEIVE.ASM\
                  ../EtherCom/ETHERCOMLINK.ASM\
                  ../EtherCom/ETHERCOMCLIENT.ASM\
                  ../EtherCom/ETHERCOMOPTION.ASM\
                  ../EtherCom/ETHERCOMMEDIUM.ASM\
                  ../EtherCom/ETHERCOMPROCESS.ASM arp.def\
                  ethodiConstant.def ethodiVariable.def
OBJS            = ethodiManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
