#!/bin/sh -
#
#
# Project:	PC GEOS
# Module:	ScrapBook
# File:		convert
#
# Author:	brianc
#
#	This file contains the user Interface description for this
# appilication.
#
# 	$Id: convert,v 1.2 98/05/14 01:52:58 joon Exp $
#
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps2.pcx 0 ScrapBook -dTM -dTCGA $appArgs
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps2.pcx 1 ScrapBookDoc $docArgs
cvtpcx -f -m13 -t -z -nScrapBookTiny scrapbook.tiny.pcx
