#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = GPCBase
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = DOC_MTDS.GOC DTA_MTDS.GOC Exp_mtds.goc FLD_MTDS.GOC\
                  gbas_ui.goc Imp_mtds.goc NAV_MTDS.GOC RPT_MTDS.GOC\
                  Sch_mtds.goc SRT_MTDS.GOC TXT_STRS.GOC appicons.goh\
                  BBOX.GOH BTNS.GOH externs.goh FINDICON.GOH gpcbase.goh\
                  rpticons.goh
OBJS            = DOC_MTDS.obj DTA_MTDS.obj Exp_mtds.obj FLD_MTDS.obj\
                  gbas_ui.obj Imp_mtds.obj NAV_MTDS.obj RPT_MTDS.obj\
                  Sch_mtds.obj SRT_MTDS.obj TXT_STRS.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
