#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = HOME
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = X10CODES.H BOOLEAN.GOC DOCUMENT.GOC HOME.GOC ICON.GOC\
                  ITEM.GOC PROCESS.GOC ROOM.GOC UNIT.GOC VALUE.GOC HOME.GOH\
                  HOMEAPP.GOH HOMEICON.GOH BBOXREG.GOH
OBJS            = BOOLEAN.obj DOCUMENT.obj HOME.obj ICON.obj ITEM.obj\
                  PROCESS.obj ROOM.obj UNIT.obj VALUE.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
