#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = GeoWrite
ARTICLE         = articleArticle.asm articleManager.asm
DOCUMENT        = documentArticle.asm documentAttrMgr.asm documentBody.asm\
                  documentContent.asm documentConvert.asm documentData.asm\
                  documentDisplay.asm documentDocument.asm documentDraw.asm\
                  documentFlow.asm documentFrame.asm documentHdrFtr.asm\
                  documentHead.asm documentHelp.asm documentImpex.asm\
                  documentManager.asm documentManip.asm\
                  documentMasterPage.asm documentMerge.asm\
                  documentMergeScrap.asm documentMisc.asm\
                  documentNotify.asm documentOpenClose.asm documentPage.asm\
                  documentPageSetup.asm documentPrint.asm\
                  documentRegion.asm documentScroll.asm\
                  documentSearchSp.asm documentSection.asm\
                  documentUserSection.asm documentUtils.asm\
                  documentVariable.asm documentData.ui documentManager.ui
MAIN            = mainAbbrev.asm mainApp.asm mainAppUI.asm mainManager.asm\
                  mainProcess.asm
UI              = uiFixed.asm uiGifImage.asm uiManager.asm uiPrint.asm\
                  uiRowColumn.asm uiSuperIC.asm uiTemplate.asm\
                  uiWriteDC.asm uiGifImage.def uiAbbrev.ui uiAppMoniker.ui\
                  uiDisplay.ui uiDocMoniker.ui uiDocument.ui uiEdit.ui\
                  uiFixed.ui uiGraphics.ui uiHelpEdit.ui uiLayout.ui\
                  uiMain.ui uiManager.ui uiOptions.ui uiPageSetup.ui\
                  uiPrint.ui uiRowColumn.ui uiTemplate.ui uiText.ui\
                  uiView.ui
UI_TO_RDFS      = DOCUMENTMANAGER.UI UIMANAGER.UI
OBJS            =
COMMON          = flowRegion.def writeApplication.def writeArticle.def\
                  writeBatchExport.def writeConstant.def writeControls.def\
                  writeDisplay.def writeDocument.def writeGeode.def\
                  writeGrObjBody.def writeGrObjHead.def writeHdrFtr.def\
                  writeProcess.def writeSuperImpex.def
MODULES         = Article Document Main UI
CMODULES        =
SRCS            = $(ARTICLE) $(DOCUMENT) $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
