#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = ftpc
CLASSES         = FTPPROC.goc
UI              = EXPIRE.goc FTPUI.goc ftpui.goh
UI_TO_RDFS      =
OBJS            = FTPPROC.obj EXPIRE.obj FTPUI.obj
COMMON          = expire.goh expireui.goh itextlim.goh ctextlim.goh\
                  options.goh internal.goh resource.goh
MODULES         =
CMODULES        = Classes UI
SRCS            = $(CLASSES) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
