#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = ftpc
CLASSES         = FTPPROC.GOC ftplist.goh
UI              = EXPIRE.GOC FTPUI.GOC ftpui.goh
UI_TO_RDFS      =
OBJS            = FTPPROC.obj EXPIRE.obj FTPUI.obj
COMMON          = CTEXTLIM.GOH EXPIRE.GOH EXPIREUI.GOH INTERNAL.GOH\
                  ITEXTLIM.GOH OPTIONS.GOH resource.goh
MODULES         =
CMODULES        = Classes UI
SRCS            = $(CLASSES) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
