#!/bin/sh -
#
#
# Project:	PC GEOS
# Module:	BJack
# File:		convert
#
# Author:	srs
#
#	This file contains the convert information for this application.
#
# 	$Id: convert,v 1.1.5.1 97/03/29 10:01:59 canavese Exp $
#
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/gshuf1.pcx 0 BJack -dLC,LM,SC,SM,LCGA,SCGA,YC,TC,TM,TCGA $appArgs


