#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = SafBuild
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = safbuildApp.goc safbuildDoc.goc safbuildGame.goc\
                  safbuildQuestion.goc safbuildQuiz.goc safbuildUI.goc\
                  safbuildUtils.goc safbuildVerify.goc global.goh\
                  safbuild.goh
OBJS            = safbuildApp.obj safbuildDoc.obj safbuildGame.obj\
                  safbuildQuestion.obj safbuildQuiz.obj safbuildUI.obj\
                  safbuildUtils.obj safbuildVerify.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
