BKRT.obj \
BKRT.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH BKRT.GOH BCKRST.GOH ART/MKRAPP.GOH \
                ART/MKRAPPTINY.GOH ART/MKRFILE.GOH ART/MKRDOC.GOH
BKRT.obj \
BKRT.eobj: BKRT.GOC GEOS.H C:/BC45/INCLUDE/STDDEF.H \
                C:/BC45/INCLUDE/_DEFS.H C:/BC45/INCLUDE/_NULL.H HEAP.H \
                GEODE.H RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H \
                FONTID.H FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H \
                LOCALIZE.H ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H \
                SYSTEM.H GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H \
                DRIVE.H INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H \
                OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H STYLESH.H \
                DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H \
                PARALLDR.H HUGEARR.H FILEENUM.H
BRPROC.obj \
BRPROC.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH GEOMISC.H BKRT.GOH BCKRST.GOH
BRPROC.obj \
BRPROC.eobj: BRPROC.GOC GEOS.H C:/BC45/INCLUDE/STDDEF.H \
                C:/BC45/INCLUDE/_DEFS.H C:/BC45/INCLUDE/_NULL.H HEAP.H \
                GEODE.H RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H \
                FONTID.H FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H \
                LOCALIZE.H ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H \
                SYSTEM.H GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H \
                DRIVE.H INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H \
                OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H STYLESH.H \
                DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H \
                PARALLDR.H HUGEARR.H FILEENUM.H GEOMISC.H ANSI/STRING.H \
                INITFILE.H

BKRTEC.geo BKRT.geo : GEOS.LDF UI.LDF ANSIC.LDF BCKRST.LDF 