DOCUMENT.obj \
DOCUMENT.eobj: Document/DocumentMANAGER.ASM \
                GEOCALCGEODE.DEF GEOS.DEF STDAPP.DEF GEODE.DEF \
                RESOURCE.DEF EC.DEF LMEM.DEF OBJECT.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF HEAP.DEF UI.DEF FILE.DEF VM.DEF WIN.DEF \
                INPUT.DEF HWR.DEF LOCALIZE.DEF SLLANG.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                LIBRARY.DEF TIMER.DEF SYSTEM.DEF DBASE.DEF ASSERT.DEF \
                INTERNAL/PRODFEATURES.DEF OBJECTS/WINC.DEF SPOOL.DEF \
                PRINT.DEF CELL.DEF MATH.DEF PARSE.DEF RULER.DEF \
                SSHEET.DEF OBJECTS/VTEXTC.DEF HUGEARR.DEF GROBJ.DEF \
                OBJECTS/SPLINE.DEF OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF \
                BITMAP.DEF CHART.DEF IMPEX.DEF IECOMMON.DEF \
                GEOCALCCONSTANT.DEF GEOCALCPROCESS.DEF GEOCALCMACROS.DEF \
                GEOCALCLEVEL.DEF GEOCALCCONTENT.DEF INITFILE.DEF \
                OBJECTS/SSHEET/SCTRLC.DEF GEOCALCDOCUMENT.DEF \
                GEOCALCDOCCTRL.DEF GEOCALCVIEW.DEF GEOCALCDISPLAY.DEF \
                GEOCALCSPREADSHEET.DEF GEOCALCGROBJHEAD.DEF \
                GEOCALCAPPLICATION.DEF GEOCALCDISPLAYGROUP.DEF \
                GEOCALCDOCNOTE.DEF GEOCALCCHARTBODY.DEF DOCUMENTCLASS.ASM \
                DOCUMENTNEW.ASM DOCUMENTMANIP.ASM DOCUMENTMESSAGES.ASM \
                DOCUMENTGRAPHIC.ASM DOCUMENTCHART.ASM DOCUMENTHEAD.ASM \
                DOCUMENTSETUP.ASM DOCUMENTIMPEX.ASM DOCUMENTMOUSE.ASM \
                DOCUMENTCTRL.ASM FILEENUM.DEF DOCUMENTSPLIT.ASM
IMPEX.obj \
IMPEX.eobj: Impex/ImpexMANAGER.ASM \
                GEOCALCGEODE.DEF GEOS.DEF STDAPP.DEF GEODE.DEF \
                RESOURCE.DEF EC.DEF LMEM.DEF OBJECT.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF HEAP.DEF UI.DEF FILE.DEF VM.DEF WIN.DEF \
                INPUT.DEF HWR.DEF LOCALIZE.DEF SLLANG.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                LIBRARY.DEF TIMER.DEF SYSTEM.DEF DBASE.DEF ASSERT.DEF \
                INTERNAL/PRODFEATURES.DEF OBJECTS/WINC.DEF SPOOL.DEF \
                PRINT.DEF CELL.DEF MATH.DEF PARSE.DEF RULER.DEF \
                SSHEET.DEF OBJECTS/VTEXTC.DEF HUGEARR.DEF GROBJ.DEF \
                OBJECTS/SPLINE.DEF OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF \
                BITMAP.DEF CHART.DEF IMPEX.DEF IECOMMON.DEF \
                GEOCALCCONSTANT.DEF GEOCALCPROCESS.DEF GEOCALCMACROS.DEF \
                GEOCALCLEVEL.DEF GEOCALCCONTENT.DEF IMPEX.ASM
MAIN.obj \
MAIN.eobj: Main/MainMANAGER.ASM \
                GEOCALCGEODE.DEF GEOS.DEF STDAPP.DEF GEODE.DEF \
                RESOURCE.DEF EC.DEF LMEM.DEF OBJECT.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF HEAP.DEF UI.DEF FILE.DEF VM.DEF WIN.DEF \
                INPUT.DEF HWR.DEF LOCALIZE.DEF SLLANG.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                LIBRARY.DEF TIMER.DEF SYSTEM.DEF DBASE.DEF ASSERT.DEF \
                INTERNAL/PRODFEATURES.DEF OBJECTS/WINC.DEF SPOOL.DEF \
                PRINT.DEF CELL.DEF MATH.DEF PARSE.DEF RULER.DEF \
                SSHEET.DEF OBJECTS/VTEXTC.DEF HUGEARR.DEF GROBJ.DEF \
                OBJECTS/SPLINE.DEF OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF \
                BITMAP.DEF CHART.DEF IMPEX.DEF IECOMMON.DEF \
                GEOCALCCONSTANT.DEF GEOCALCPROCESS.DEF GEOCALCMACROS.DEF \
                GEOCALCLEVEL.DEF GEOCALCCONTENT.DEF GEOCALCDOCNOTE.DEF \
                MAININIT.ASM MAINPROCESS.ASM
NAME.obj \
NAME.eobj: Name/NameMANAGER.ASM \
                GEOCALCGEODE.DEF GEOS.DEF STDAPP.DEF GEODE.DEF \
                RESOURCE.DEF EC.DEF LMEM.DEF OBJECT.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF HEAP.DEF UI.DEF FILE.DEF VM.DEF WIN.DEF \
                INPUT.DEF HWR.DEF LOCALIZE.DEF SLLANG.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                LIBRARY.DEF TIMER.DEF SYSTEM.DEF DBASE.DEF ASSERT.DEF \
                INTERNAL/PRODFEATURES.DEF OBJECTS/WINC.DEF SPOOL.DEF \
                PRINT.DEF CELL.DEF MATH.DEF PARSE.DEF RULER.DEF \
                SSHEET.DEF OBJECTS/VTEXTC.DEF HUGEARR.DEF GROBJ.DEF \
                OBJECTS/SPLINE.DEF OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF \
                BITMAP.DEF CHART.DEF IMPEX.DEF IECOMMON.DEF \
                GEOCALCCONSTANT.DEF GEOCALCPROCESS.DEF GEOCALCMACROS.DEF \
                GEOCALCLEVEL.DEF GEOCALCCONTENT.DEF NAMEUTILS.ASM
UI.obj \
UI.eobj: UI/UIMANAGER.ASM \
                GEOCALCGEODE.DEF GEOS.DEF STDAPP.DEF GEODE.DEF \
                RESOURCE.DEF EC.DEF LMEM.DEF OBJECT.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF \
                CHAR.DEF HEAP.DEF UI.DEF FILE.DEF VM.DEF WIN.DEF \
                INPUT.DEF HWR.DEF LOCALIZE.DEF SLLANG.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                LIBRARY.DEF TIMER.DEF SYSTEM.DEF DBASE.DEF ASSERT.DEF \
                INTERNAL/PRODFEATURES.DEF OBJECTS/WINC.DEF SPOOL.DEF \
                PRINT.DEF CELL.DEF MATH.DEF PARSE.DEF RULER.DEF \
                SSHEET.DEF OBJECTS/VTEXTC.DEF HUGEARR.DEF GROBJ.DEF \
                OBJECTS/SPLINE.DEF OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF \
                BITMAP.DEF CHART.DEF IMPEX.DEF IECOMMON.DEF \
                GEOCALCCONSTANT.DEF GEOCALCPROCESS.DEF GEOCALCMACROS.DEF \
                GEOCALCLEVEL.DEF GEOCALCCONTENT.DEF INITFILE.DEF \
                INTERNAL/VIDEODR.DEF DRIVER.DEF INTERNAL/HEAPINT.DEF \
                INTERNAL/SEMINT.DEF SYSSTATS.DEF OBJECTS/INPUTC.DEF \
                OBJECTS/TEXT/TCTRLC.DEF OBJECTS/SSHEET/SCTRLC.DEF \
                GEOCALCAPPLICATION.DEF GEOCALCDOCUMENT.DEF \
                GEOCALCDOCCTRL.DEF GEOCALCDISPLAY.DEF \
                GEOCALCSPREADSHEET.DEF GEOCALCVIEW.DEF \
                GEOCALCGROBJHEAD.DEF GEOCALCEDITBAR.DEF \
                GEOCALCDISPLAYGROUP.DEF GEOCALCDOCNOTE.DEF \
                GEOCALCCHARTBODY.DEF UIMAIN.RDEF UITARGET.ASM \
                UIDISPLAY.ASM UIGEOCALCEDITBAR.ASM \
                UIGEOCALCSPREADSHEET.ASM UIGEOCALCCONTENT.ASM \
                UIGEOCALCVIEW.ASM UIGEOCALCAPPLICATION.ASM \
                UIGEOCALCDISPLAYGROUP.ASM UIGEOCALCCHARTBODY.ASM
UIMAIN.rdef: 