#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = geocalc
UI              = uiGeoCalcContent.asm uiGeoCalcView.asm uiTarget.asm\
                  uiGeoCalcSpreadsheet.asm uiGeoCalcApplication.asm\
                  uiGeoCalcDisplayGroup.asm uiDisplay.asm uiNotifyGroup.asm\
                  uiGeoCalcEditBar.asm uiFormat.asm uiManager.asm\
                  uiGeoCalcChartBody.asm uiList.asm uiConstant.def\
                  uiChart.ui uiGeoCalcDocNote.ui uiStrings.ui uiContent.ui\
                  uiZoom.ui uiName.ui uiGraphic.ui uiFile.ui uiTool.ui\
                  uiEdit.ui uiLevel.ui uiPrint.ui uiDisplay.ui\
                  uiGraphicBody.ui uiFormula.ui uiData.ui uiCell.ui\
                  uiAttributes.ui uiMain.ui uiOptions.ui uiFormat.ui
DOCUMENT        = documentChart.asm documentGraphic.asm documentManager.asm\
                  documentSplit.asm documentManip.asm documentCtrl.asm\
                  documentClass.asm documentNew.asm documentMouse.asm\
                  documentHead.asm documentImpex.asm documentSetup.asm\
                  documentMessages.asm
MAIN            = mainManager.asm mainHeader.asm mainProcess.asm\
                  mainDocument.asm mainInit.asm
IMPEX           = impexManager.asm impex.asm
NAME            = nameManager.asm nameUtils.asm
UI_TO_RDFS      = uiMain.ui
OBJS            =
COMMON          = geocalcEditBar.def geocalcDocNote.def geocalcMacros.def\
                  geocalcGeode.def geocalcDocument.def name.def\
                  geocalcDisplay.def geocalcConstant.def geocalcDocCtrl.def\
                  geocalcApplication.def geocalcSpreadsheet.def\
                  geocalcProcess.def geocalcView.def geocalcGrObjHead.def\
                  geocalcContent.def geocalcChartBody.def geocalcLevel.def\
                  geocalcDisplayGroup.def
MODULES         = UI Document Main Impex Name
CMODULES        =
SRCS            = $(UI) $(DOCUMENT) $(MAIN) $(IMPEX) $(NAME) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
