#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = uki
ASM_TO_OBJS     = ukiCommon.asm
UI_TO_RDFS      =
SRCS            = ukiCommon.asm uki.asm ukiKbd.asm ukiMouse.asm\
                  ukiCommon.def uki.def ukihelp.ui uki.ui
OBJS            = ukiCommon.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
