#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = UKI
ASM_TO_OBJS     = ukiCommon.asm
UI_TO_RDFS      =
SRCS            = uki.asm ukiCommon.asm ukiKbd.asm ukiMouse.asm uki.def\
                  ukiCommon.def uki.ui ukihelp.ui
OBJS            = ukiCommon.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
