#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = PYRAMID
ASM_TO_OBJS     = pyramid.asm
UI_TO_RDFS      = PYRAMID.UI
SRCS            = pyramid.asm pyramidDeck.asm pyramidGame.asm myMacros.def\
                  pyramid.def sizes.def pyramid.ui
OBJS            = pyramid.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
