#!/bin/awk -f
BEGIN {
	type="tcl"
	printf "%-30s %5s %5s %6s\n", "File", "Orig", "Comp", "Diff"
}
type == "tcl" {
	orig=$4
	type="tlc"
	file=$8
	next
}
type == "tlc" {
	diff=(orig-$4+0.0)/orig*100
	printf "%-30s %5d %5d %5.2f%%\n", file, orig, $4, diff
	type="tcl"
}
