#!/bin/sh -f
#$Id: convert,v 1.3 98/05/14 00:38:32 joon Exp $

. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps1.pcx 2 GeoDraw -dTM -dTCGA $appArgs
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps1.pcx 3 GeoDrawDoc $docArgs

cvtpcx -f -m13 -t -z -nGeoDrawTiny newdraw.tiny.pcx
cvtpcx -f -m2 -t -z -x48 -y0 -nBitmapPtrTool grobj.pcx
