#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = ms7
ASM_TO_OBJS     = ms7Manager.asm
UI_TO_RDFS      =
SRCS            = ms7Manager.asm ms7Path.asm ms7Strings.asm ms7Utils.asm\
                  DOSSTRINGS.ASM DOSENTRY.ASM Common/DOS7DISK.ASM\
                  DOSDRIVE.ASM MSDRIVE.ASM Common/DOS7PATH.ASM\
                  Common/DOS7ENUM.ASM DOSFORMAT.ASM DOSFORMATINIT.ASM\
                  DOSDISKCOPY.ASM Common/DOS7IO.ASM DOSPRIMARY.ASM\
                  DOSINITEXIT.ASM Common/DOS7INITEXIT.ASM DOSCRITICAL.ASM\
                  Common/DOS7UTILS.ASM Common/DOS7VIRTUAL.ASM\
                  DOSWAITPOST.ASM MSSFT.ASM DOSSUSPEND.ASM\
                  Common/DOS7LINK.ASM DOSIDLE.ASM Common/DOS7FILECHANGE.ASM\
                  DOSCONVERT.ASM DOSCMAPUS.ASM DOSCMAPMULTI.ASM\
                  DOSCONVERTSJIS.ASM DOSCMAPSJIS.ASM DOSCONVERTJIS.ASM\
                  DOSCONVERTEUC.ASM ms7Interface.def
OBJS            = ms7Manager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
