#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = instc
FTOOL           = ftool.goc ftoolui.goc seldofc.goc ftool.goh ftoolui.goh
INIF            = inif.goc inifui.goc inif.goh inifui.goh
MAIN            = iconedi.goc instc.goc instc2.goc list.goc list2.goc\
                  tools.goc iconedi.goh
UI              = appui.goc appui.goh
UI_TO_RDFS      =
OBJS            = ftool.obj ftoolui.obj seldofc.obj inif.obj inifui.obj\
                  iconedi.obj instc.obj instc2.obj list.obj list2.obj\
                  tools.obj appui.obj
COMMON          = instc.goh process.goh
MODULES         =
CMODULES        = ftool inif main ui
SRCS            = $(FTOOL) $(INIF) $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
