#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = taipei
ASM_TO_OBJS     = taipeiManager.asm
UI_TO_RDFS      = taipei.ui
SRCS            = taipei.asm taipeiContent.asm taipeiInit.asm\
                  taipeiManager.asm util.asm taipei.def taipei.ui\
                  taipeiBitmap.ui taipeiConfig.ui taipeiJBitmap.ui
OBJS            = taipeiManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
