SLIDES.rdef: GENERIC.UIH PRODUCT.UIH IMPEX.UIH OBJECTS/TEXT/TCTRL.UIH \
                RULER.UIH OBJECTS/COLORC.UIH OBJECTS/STYLES.UIH \
                ART/MKRSLIDES.UI ART/MKRTINYAPP.UI ART/MKRSLIDESDOC.UI \
                ART/MKRTINYDOC.UI ART/MKRPREV.UI ART/MKRNEXT.UI
SLIDES.obj \
SLIDES.eobj: GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF VM.DEF \
                OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF \
                COLOR.DEF WIN.DEF TIMER.DEF FILE.DEF CHAR.DEF \
                LOCALIZE.DEF SLLANG.DEF GSTRING.DEF TEXT.DEF \
                OBJECTS/WINC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF INITFILE.DEF LIBRARY.DEF OBJECTS/INPUTC.DEF \
                UI.DEF INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF GCNLIST.DEF \
                TIMEDATE.DEF OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF \
                IACP.DEF OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF \
                OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF \
                OBJECTS/GENC.DEF DISK.DEF DRIVE.DEF UDIALOG.DEF \
                OBJECTS/GINTERC.DEF TOKEN.DEF OBJECTS/CLIPBRD.DEF \
                OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF ALB.DEF \
                OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF DBASE.DEF IMPEX.DEF \
                IECOMMON.DEF INTERNAL/CONVERT.DEF SAVER.DEF \
                OBJECTS/COLORC.DEF INTERNAL/IM.DEF INTERNAL/SEMINT.DEF \
                SLIDES.RDEF

SlidesEC.geo Slides.geo : GEOS.LDF UI.LDF TEXT.LDF IMPEX.LDF CONVERT.LDF SAVER.LDF COLOR.LDF 