DBCS/ASMTOOLS.obj \
DBCS/ASMTOOLS.eobj: ASMTOOLS/ASMTOOLSMANAGER.ASM \
                STDAPP.DEF GEOS.DEF GEODE.DEF RESOURCE.DEF EC.DEF LMEM.DEF \
                OBJECT.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF \
                GSTRING.DEF TEXT.DEF CHAR.DEF UNICODE.DEF HEAP.DEF UI.DEF \
                FILE.DEF VM.DEF WIN.DEF INPUT.DEF HWR.DEF LOCALIZE.DEF \
                SLLANG.DEF OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF \
                CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                PRODUCT.DEF INTERNAL/SEMINT.DEF THREAD.DEF \
                INTERNAL/HEAPINT.DEF SYSSTATS.DEF INTERNAL/INTERRUP.DEF \
                DRIVER.DEF INTERNAL/VIDEODR.DEF HUGEARR.DEF SOCKET.DEF \
                SOCKMISC.DEF SEM.DEF
DBCS/BROWSER.obj \
DBCS/BROWSER.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH HTMLVIEW.GOH PRODUCT.GOH \
                OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH \
                OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH STATTEXT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH
DBCS/BROWSER.obj \
DBCS/BROWSER.eobj: JS/BROWSER.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STDLIB.H ANSI/STRING.H \
                PRODUCT.H HTMLFSTR.H AWATCHER.H HTMLOPT.H HTMLDRV.H \
                MATH.H FIXES.H HTMLPROG.H HWLIB.H MEDIUM.H SOCKMISC.H \
                JAVASCR.H INTERNAL/NETUTILS.H COOKIES.H INITFILE.H
DBCS/SEBROWSE.obj \
DBCS/SEBROWSE.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH HTMLVIEW.GOH PRODUCT.GOH \
                OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH \
                OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH STATTEXT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH
DBCS/SEBROWSE.obj \
DBCS/SEBROWSE.eobj: JS/SEBROWSE.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STDLIB.H ANSI/ASSERT.H \
                PRODUCT.H HTMLFSTR.H AWATCHER.H HTMLOPT.H HTMLDRV.H \
                MATH.H FIXES.H HTMLPROG.H HWLIB.H MEDIUM.H SOCKMISC.H \
                JAVASCR.H
DBCS/AWATCHER.obj \
DBCS/AWATCHER.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH
DBCS/AWATCHER.obj \
DBCS/AWATCHER.eobj: HTMLVIEW/AWATCHER.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H AWATCHER.H
DBCS/GLBANIM.obj \
DBCS/GLBANIM.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH OPTIONS.GOH PRODUCT.GOH PRODGPC.GOH
DBCS/GLBANIM.obj \
DBCS/GLBANIM.eobj: HTMLVIEW/GLBANIM.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H PRODUCT.H
DBCS/HTMLVIEW.obj \
DBCS/HTMLVIEW.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH OBJECTS/TEXT/TCTRLC.GOH RULER.GOH \
                OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH FIXES.GOH \
                HTMLVIEW.GOH PRODUCT.GOH OBJECTS/GVIEWCC.GOH OPTIONS.GOH \
                PRODGPC.GOH HTML4PAR.GOH OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH \
                STATTEXT.GOH URLFETCH.GOH MAILHUB.GOH SOCKET.GOH \
                SOCKMISC.H PARENTC.GOH FAVORITE.GOH IMPORTG.GOH \
                EXPIRE.GOH HTMLV_UI.GOH OBJECTS/IDIALCC.GOH \
                ART/APPICON.GOH FAVORUI.GOH FAVORCLS.GOH ART/LOCK.GOH \
                ART/UNLOCK.GOH ART/GREEN.GOH ART/RED.GOH ART/YELLOW.GOH \
                ICONS/ICONS.GOH ART/GI001-8.GOH ART/GI002-8.GOH \
                ART/GI003-8.GOH ART/GI004-8.GOH ART/GI005-8.GOH \
                ART/A111-8.GOH ART/A113-8.GOH ART/A114-8.GOH \
                ART/GI009-8.GOH ART/GI010-8.GOH ART/GI011-8.GOH \
                ART/GI012-8.GOH ART/GI013-8.GOH ART/GI014-8.GOH \
                INIT/EXPIREUI.GOH ART/RED2.GOH ART/GREEN2.GOH \
                ART/TOOLICON.GOH BREADBOX.GOH
DBCS/HTMLVIEW.obj \
DBCS/HTMLVIEW.eobj: HTMLVIEW/HTMLVIEW.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H INITFILE.H SYSSTATS.H SEM.H \
                ANSI/STRING.H ANSI/STDIO.H ANSI/STDLIB.H GEOMISC.H \
                FIXES.H PRODUCT.H HTMLFSTR.H AWATCHER.H HTMLOPT.H \
                HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H MEDIUM.H SOCKMISC.H \
                JAVASCR.H
DBCS/IMPORTG.obj \
DBCS/IMPORTG.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH ANSI/STRING.H HTMLVIEW.GOH PRODUCT.GOH \
                OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH \
                OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH STATTEXT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH IMPORTG.GOH
DBCS/IMPORTG.obj \
DBCS/IMPORTG.eobj: HTMLVIEW/IMPORTG.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H LIBRARY.H PRODUCT.H \
                HTMLFSTR.H AWATCHER.H HTMLOPT.H HTMLDRV.H MATH.H FIXES.H \
                HTMLPROG.H HWLIB.H MEDIUM.H SOCKMISC.H ANSI/STDIO.H SEM.H
DBCS/LOADURL.obj \
DBCS/LOADURL.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FIXES.GOH HTMLVIEW.GOH PRODUCT.GOH \
                OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH \
                OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH STATTEXT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH DIALOGT.GOH GLBANIM.GOH \
                SEM.H
DBCS/LOADURL.obj \
DBCS/LOADURL.eobj: HTMLVIEW/LOADURL.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H LIBRARY.H ANSI/STRING.H ANSI/STDIO.H \
                ANSI/STDLIB.H GEOMISC.H FIXES.H PRODUCT.H HTMLFSTR.H \
                AWATCHER.H HTMLOPT.H HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H \
                MEDIUM.H SOCKMISC.H SEM.H INITFILE.H
DBCS/OPENCLOS.obj \
DBCS/OPENCLOS.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH OBJECTS/TEXT/TCTRLC.GOH RULER.GOH \
                OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH FIXES.GOH \
                HTMLVIEW.GOH PRODUCT.GOH OBJECTS/GVIEWCC.GOH OPTIONS.GOH \
                PRODGPC.GOH HTML4PAR.GOH OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH \
                STATTEXT.GOH URLFETCH.GOH MAILHUB.GOH SOCKET.GOH \
                SOCKMISC.H PARENTC.GOH FAVORITE.GOH IMPORTG.GOH \
                EXPIRE.GOH IAPP.H OBJECTS/GSYSC.GOH
DBCS/OPENCLOS.obj \
DBCS/OPENCLOS.eobj: HTMLVIEW/OPENCLOS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H INITFILE.H SYSSTATS.H SEM.H \
                ANSI/STRING.H ANSI/STDIO.H ANSI/STDLIB.H GEOMISC.H \
                FIXES.H PRODUCT.H HTMLFSTR.H AWATCHER.H HTMLOPT.H \
                HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H MEDIUM.H SOCKMISC.H \
                IAPP.H
DBCS/SCRAPBK.obj \
DBCS/SCRAPBK.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH OBJECTS/TEXT/TCTRLC.GOH RULER.GOH \
                OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH FIXES.GOH \
                HTMLVIEW.GOH PRODUCT.GOH OBJECTS/GVIEWCC.GOH OPTIONS.GOH \
                PRODGPC.GOH HTML4PAR.GOH OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH \
                STATTEXT.GOH URLFETCH.GOH MAILHUB.GOH SOCKET.GOH \
                SOCKMISC.H PARENTC.GOH FAVORITE.GOH IMPORTG.GOH \
                EXPIRE.GOH
DBCS/SCRAPBK.obj \
DBCS/SCRAPBK.eobj: HTMLVIEW/SCRAPBK.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H INITFILE.H SYSSTATS.H SEM.H \
                ANSI/STRING.H ANSI/STDIO.H ANSI/STDLIB.H GEOMISC.H \
                FIXES.H PRODUCT.H HTMLFSTR.H AWATCHER.H HTMLOPT.H \
                HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H MEDIUM.H SOCKMISC.H
DBCS/STATTEXT.obj \
DBCS/STATTEXT.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH ANSI/STRING.H STATTEXT.GOH \
                HTMLVIEW.GOH PRODUCT.GOH OBJECTS/GVIEWCC.GOH OPTIONS.GOH \
                PRODGPC.GOH HTML4PAR.GOH OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH
DBCS/STATTEXT.obj \
DBCS/STATTEXT.eobj: HTMLVIEW/STATTEXT.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H PRODUCT.H HTMLFSTR.H \
                AWATCHER.H HTMLOPT.H HTMLDRV.H MATH.H FIXES.H HTMLPROG.H \
                HWLIB.H MEDIUM.H SOCKMISC.H
DBCS/UIACTION.obj \
DBCS/UIACTION.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH OBJECTS/TEXT/TCTRLC.GOH RULER.GOH \
                OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH FIXES.GOH \
                HTMLVIEW.GOH PRODUCT.GOH OBJECTS/GVIEWCC.GOH OPTIONS.GOH \
                PRODGPC.GOH HTML4PAR.GOH OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH \
                STATTEXT.GOH URLFETCH.GOH MAILHUB.GOH SOCKET.GOH \
                SOCKMISC.H PARENTC.GOH FAVORITE.GOH IMPORTG.GOH \
                EXPIRE.GOH
DBCS/UIACTION.obj \
DBCS/UIACTION.eobj: HTMLVIEW/UIACTION.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H INITFILE.H SYSSTATS.H SEM.H \
                ANSI/STRING.H ANSI/STDIO.H ANSI/STDLIB.H GEOMISC.H \
                FIXES.H PRODUCT.H HTMLFSTR.H AWATCHER.H HTMLOPT.H \
                HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H MEDIUM.H SOCKMISC.H
DBCS/UIOFTEN.obj \
DBCS/UIOFTEN.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH OBJECTS/TEXT/TCTRLC.GOH RULER.GOH \
                OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH FIXES.GOH \
                HTMLVIEW.GOH PRODUCT.GOH OBJECTS/GVIEWCC.GOH OPTIONS.GOH \
                PRODGPC.GOH HTML4PAR.GOH OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH \
                STATTEXT.GOH URLFETCH.GOH MAILHUB.GOH SOCKET.GOH \
                SOCKMISC.H PARENTC.GOH FAVORITE.GOH IMPORTG.GOH \
                EXPIRE.GOH OBJECTS/GSYSC.GOH
DBCS/UIOFTEN.obj \
DBCS/UIOFTEN.eobj: HTMLVIEW/UIOFTEN.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H INITFILE.H SYSSTATS.H SEM.H \
                ANSI/STRING.H ANSI/STDIO.H ANSI/STDLIB.H GEOMISC.H \
                FIXES.H PRODUCT.H HTMLFSTR.H AWATCHER.H HTMLOPT.H \
                HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H MEDIUM.H SOCKMISC.H
DBCS/UIRARE.obj \
DBCS/UIRARE.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH OBJECTS/TEXT/TCTRLC.GOH RULER.GOH \
                OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH FIXES.GOH \
                HTMLVIEW.GOH PRODUCT.GOH OBJECTS/GVIEWCC.GOH OPTIONS.GOH \
                PRODGPC.GOH HTML4PAR.GOH OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH \
                STATTEXT.GOH URLFETCH.GOH MAILHUB.GOH SOCKET.GOH \
                SOCKMISC.H PARENTC.GOH FAVORITE.GOH IMPORTG.GOH \
                EXPIRE.GOH OBJECTS/GSYSC.GOH
DBCS/UIRARE.obj \
DBCS/UIRARE.eobj: HTMLVIEW/UIRARE.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H INITFILE.H SYSSTATS.H SEM.H \
                ANSI/STRING.H ANSI/STDIO.H ANSI/STDLIB.H GEOMISC.H \
                FIXES.H PRODUCT.H HTMLFSTR.H AWATCHER.H HTMLOPT.H \
                HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H MEDIUM.H SOCKMISC.H
DBCS/EXPIRE.obj \
DBCS/EXPIRE.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH EXPIRE.GOH OPTIONS.GOH PRODUCT.GOH \
                PRODGPC.GOH
DBCS/EXPIRE.obj \
DBCS/EXPIRE.eobj: INIT/EXPIRE.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H PRODUCT.H
DBCS/INIT.obj \
DBCS/INIT.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH SEM.H FIXES.GOH HTMLVIEW.GOH \
                PRODUCT.GOH OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH \
                HTML4PAR.GOH OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH \
                STATTEXT.GOH URLFETCH.GOH MAILHUB.GOH SOCKET.GOH \
                SOCKMISC.H OBJECTS/TEXT/TCTRLC.GOH RULER.GOH \
                OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH PARENTC.GOH
DBCS/INIT.obj \
DBCS/INIT.eobj: INIT/INIT.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H SEM.H LIBRARY.H INITFILE.H \
                ANSI/STRING.H ANSI/STDIO.H ANSI/STDLIB.H FIXES.H \
                PRODUCT.H HTMLFSTR.H AWATCHER.H HTMLOPT.H HTMLDRV.H \
                MATH.H HTMLPROG.H HWLIB.H MEDIUM.H SOCKMISC.H JAVASCR.H
DBCS/BOOKCLAS.obj \
DBCS/BOOKCLAS.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH OPTIONS.GOH PRODUCT.GOH PRODGPC.GOH
DBCS/BOOKCLAS.obj \
DBCS/BOOKCLAS.eobj: NAVIGATE/BOOKCLAS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H PRODUCT.H
DBCS/BOOKMARK.obj \
DBCS/BOOKMARK.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH ANSI/STRING.H OPTIONS.GOH PRODUCT.GOH \
                PRODGPC.GOH
DBCS/BOOKMARK.obj \
DBCS/BOOKMARK.eobj: NAVIGATE/BOOKMARK.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H PRODUCT.H
DBCS/FAVORCLS.obj \
DBCS/FAVORCLS.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH ANSI/STRING.H OPTIONS.GOH PRODUCT.GOH \
                PRODGPC.GOH FAVORCLS.GOH FAVORITE.GOH HTMLVIEW.GOH \
                OBJECTS/GVIEWCC.GOH HTML4PAR.GOH OBJECTS/VLTEXTC.GOH \
                HTMLSTAT.GOH STATTEXT.GOH URLFETCH.GOH MAILHUB.GOH \
                SOCKET.GOH SOCKMISC.H OBJECTS/TEXT/TCTRLC.GOH RULER.GOH \
                OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH PARENTC.GOH
DBCS/FAVORCLS.obj \
DBCS/FAVORCLS.eobj: NAVIGATE/FAVORCLS.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H PRODUCT.H HTMLFSTR.H \
                AWATCHER.H HTMLOPT.H HTMLDRV.H MATH.H FIXES.H HTMLPROG.H \
                HWLIB.H MEDIUM.H SOCKMISC.H
DBCS/FAVORITE.obj \
DBCS/FAVORITE.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH ANSI/STRING.H INITFILE.H OPTIONS.GOH \
                PRODUCT.GOH PRODGPC.GOH FAVORITE.GOH IBTREE.GOH IBDLL.GOH \
                IBMS.GOH
DBCS/FAVORITE.obj \
DBCS/FAVORITE.eobj: NAVIGATE/FAVORITE.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H INITFILE.H PRODUCT.H
DBCS/NAVCACHE.obj \
DBCS/NAVCACHE.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FIXES.GOH HTMLVIEW.GOH PRODUCT.GOH \
                OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH \
                OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH STATTEXT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH DIALOGT.GOH GLBANIM.GOH \
                SEM.H
DBCS/NAVCACHE.obj \
DBCS/NAVCACHE.eobj: NAVIGATE/NAVCACHE.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H LIBRARY.H ANSI/STRING.H ANSI/STDIO.H \
                ANSI/STDLIB.H GEOMISC.H INITFILE.H FIXES.H PRODUCT.H \
                HTMLFSTR.H AWATCHER.H HTMLOPT.H HTMLDRV.H MATH.H \
                HTMLPROG.H HWLIB.H MEDIUM.H SOCKMISC.H SEM.H SYSSTATS.H
DBCS/NAVIGATE.obj \
DBCS/NAVIGATE.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FIXES.GOH HTMLVIEW.GOH PRODUCT.GOH \
                OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH \
                OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH STATTEXT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH DIALOGT.GOH GLBANIM.GOH \
                SEM.H
DBCS/NAVIGATE.obj \
DBCS/NAVIGATE.eobj: NAVIGATE/NAVIGATE.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H LIBRARY.H ANSI/STRING.H ANSI/STDIO.H \
                ANSI/STDLIB.H GEOMISC.H FIXES.H PRODUCT.H HTMLFSTR.H \
                AWATCHER.H HTMLOPT.H HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H \
                MEDIUM.H SOCKMISC.H SEM.H INITFILE.H
DBCS/LOCALPAG.obj \
DBCS/LOCALPAG.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FIXES.GOH HTMLVIEW.GOH PRODUCT.GOH \
                OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH \
                OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH STATTEXT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH
DBCS/LOCALPAG.obj \
DBCS/LOCALPAG.eobj: URLDOC/LOCALPAG.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H ANSI/STRING.H ANSI/STDIO.H \
                ANSI/STDLIB.H FIXES.H PRODUCT.H HTMLFSTR.H AWATCHER.H \
                HTMLOPT.H HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H MEDIUM.H \
                SOCKMISC.H
DBCS/URLDOC.obj \
DBCS/URLDOC.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FIXES.GOH HTMLVIEW.GOH PRODUCT.GOH \
                OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH \
                OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH STATTEXT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH FAVORITE.GOH
DBCS/URLDOC.obj \
DBCS/URLDOC.eobj: URLDOC/URLDOC.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H GEOMISC.H INITFILE.H ANSI/STRING.H \
                ANSI/STDIO.H ANSI/STDLIB.H FIXES.H PRODUCT.H HTMLFSTR.H \
                AWATCHER.H HTMLOPT.H HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H \
                MEDIUM.H SOCKMISC.H
DBCS/URLDOCCT.obj \
DBCS/URLDOCCT.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FIXES.GOH HTMLVIEW.GOH PRODUCT.GOH \
                OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH \
                OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH STATTEXT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH
DBCS/URLDOCCT.obj \
DBCS/URLDOCCT.eobj: URLDOCCT/URLDOCCT.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H GEOMISC.H INITFILE.H ANSI/STRING.H \
                ANSI/STDIO.H ANSI/STDLIB.H FIXES.H PRODUCT.H HTMLFSTR.H \
                AWATCHER.H HTMLOPT.H HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H \
                MEDIUM.H SOCKMISC.H
DBCS/URLFETCH.obj \
DBCS/URLFETCH.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH ANSI/STRING.H SEM.H THREAD.H \
                INITFILE.H HTMLVIEW.GOH PRODUCT.GOH OBJECTS/GVIEWCC.GOH \
                OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH OBJECTS/VLTEXTC.GOH \
                HTMLSTAT.GOH STATTEXT.GOH URLFETCH.GOH MAILHUB.GOH \
                SOCKET.GOH SOCKMISC.H OBJECTS/TEXT/TCTRLC.GOH RULER.GOH \
                OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH PARENTC.GOH
DBCS/URLFETCH.obj \
DBCS/URLFETCH.eobj: URLFETCH/URLFETCH.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H PRODUCT.H ANSI/STRING.H LIBRARY.H \
                SEM.H INITFILE.H ANSI/STDIO.H HTMLFSTR.H AWATCHER.H \
                HTMLOPT.H HTMLDRV.H MATH.H FIXES.H HTMLPROG.H HWLIB.H \
                MEDIUM.H SOCKMISC.H
DBCS/FRFETCH.obj \
DBCS/FRFETCH.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FIXES.GOH HTMLVIEW.GOH PRODUCT.GOH \
                OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH \
                OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH STATTEXT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH WAV.GOH
DBCS/FRFETCH.obj \
DBCS/FRFETCH.eobj: URLFRAME/FRFETCH.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H GEOMISC.H INITFILE.H ANSI/STRING.H \
                ANSI/STDIO.H ANSI/STDLIB.H FIXES.H PRODUCT.H HTMLFSTR.H \
                AWATCHER.H HTMLOPT.H HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H \
                MEDIUM.H SOCKMISC.H JAVASCR.H COOKIES.H
DBCS/URLFRAME.obj \
DBCS/URLFRAME.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FIXES.GOH HTMLVIEW.GOH PRODUCT.GOH \
                OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH \
                OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH STATTEXT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH
DBCS/URLFRAME.obj \
DBCS/URLFRAME.eobj: URLFRAME/URLFRAME.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H \
                EC.H OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H GEOMISC.H INITFILE.H ANSI/STRING.H \
                ANSI/STDIO.H ANSI/STDLIB.H FIXES.H PRODUCT.H HTMLFSTR.H \
                AWATCHER.H HTMLOPT.H HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H \
                MEDIUM.H SOCKMISC.H JAVASCR.H
DBCS/URLTEXT.obj \
DBCS/URLTEXT.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FIXES.GOH HTMLVIEW.GOH PRODUCT.GOH \
                OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH \
                OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH STATTEXT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH IMPORTG.GOH
DBCS/URLTEXT.obj \
DBCS/URLTEXT.eobj: URLTEXT/URLTEXT.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H GEOMISC.H ANSI/STRING.H ANSI/STDIO.H \
                ANSI/STDLIB.H FIXES.H PRODUCT.H HTMLFSTR.H AWATCHER.H \
                HTMLOPT.H HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H MEDIUM.H \
                SOCKMISC.H SEM.H
DBCS/URLTEXT2.obj \
DBCS/URLTEXT2.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH FIXES.GOH HTMLVIEW.GOH PRODUCT.GOH \
                OBJECTS/GVIEWCC.GOH OPTIONS.GOH PRODGPC.GOH HTML4PAR.GOH \
                OBJECTS/VLTEXTC.GOH HTMLSTAT.GOH STATTEXT.GOH \
                URLFETCH.GOH MAILHUB.GOH SOCKET.GOH SOCKMISC.H \
                OBJECTS/TEXT/TCTRLC.GOH RULER.GOH OBJECTS/COLORC.GOH \
                OBJECTS/STYLES.GOH PARENTC.GOH
DBCS/URLTEXT2.obj \
DBCS/URLTEXT2.eobj: URLTEXT/URLTEXT2.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H \
                OBJECT.H LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H \
                GSTRING.H TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H \
                TIMEDATE.H FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H UNICODE.H \
                HWR.H WIN.H UDIALOG.H OBJECTS/GINTERC.H \
                OBJECTS/TEXT/TCOMMON.H STYLESH.H DRIVER.H THREAD.H \
                PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H PARALLDR.H \
                HUGEARR.H FILEENUM.H GEOMISC.H ANSI/STRING.H ANSI/STDIO.H \
                ANSI/STDLIB.H FIXES.H PRODUCT.H HTMLFSTR.H AWATCHER.H \
                HTMLOPT.H HTMLDRV.H MATH.H HTMLPROG.H HWLIB.H MEDIUM.H \
                SOCKMISC.H

DBCS/GPCBrowEC.geo DBCS/GPCBrow.geo : GEOS.LDF UI.LDF ANSIC.LDF TEXT.LDF SPOOL.LDF HTML4PAR.LDF IBMS.LDF NETUTILS.LDF COOKIES.LDF JS.LDF PARENTC.LDF IDIALC.LDF WAV.LDF MAILHUB.LDF SOCKET.LDF
