#!/bin/sh -
#########################################################################
#				convert					#
# Convert script for Desktop and File Cabinet				#
# Run this to create the mkrXXX.ui files for desktop and file cabinet.	#
# 									#
# $Id: convert,v 1.9 98/08/20 06:27:57 joon Exp $			#
#########################################################################
#
# global variables
#
cvtArgs="-t -L -dLC -dLM -dLCGA -dYC -dYM"
cvtfileArgs="-m13 $cvtArgs"


if [ -f driveicon.sed ]; then
    di_sed=driveicon.sed
else
    di_sed=`otherdir`/driveicon.sed
fi


#
# Convert a pcx file to a moniker, dealing with locating the installed or
# uninstalled version of the file (doesn't deal with branches, I'm afraid)
#
# Usage: cvt <file> <cvtpcx-args>
#
cvt() {
    file=$1
    shift
    if [ ! -f $file ]; then
	file=`otherdir`/$file
    fi
    cvtpcx -f "$@" $file
    mv -f mkr$name.ui cmkr$name.ui
}


#
# Creates the proper .ui files for all icons in the given pcx file.
#
# usage:  cvtfile <filename> <resource> <list of icons> <other args>
cvtfile() {
	echo $3
	filename=$1
	resource=$2
	icons=$3
	shift 3
	x=0 y=0
	for name in $icons; do
		cvt $filename -x$x -y$y -r$resource -n$name $*
		echo $filename -x$x -y$y -r$resource -n$name $*
		y=`expr $y + 41`
	done
}


#
# MASKS: (for use with -m flag)
#	0 = black	5 = violet	10 = light green	15 = white
#	1 = blue	6 = brown	11 = light cyan
#	2 = green	7 = light_gray	12 = light red
#	3 = cyan	8 = dark gray	13 = light purple
#	4 = red		9 = light blue	14 = yellow
#

#########################################################################
#		nd.pcx - Folder Contents Icons				#
#########################################################################
#
# All icons in this file use mask color 13.
#
ndIcons="NDHelp NDWasteBasket NDFileFolder NDDosAppl NDDosData NDPrinter NDCDRom NDThreeInchDisk NDFiveInchDisk NDTemplate NDFullWasteBasket"
cvtfile PCX/nd.pcx NDStandard "$ndIcons" $cvtfileArgs


#########################################################################
#		nd4.pcx - More Drive Icons				#
#########################################################################
#
# All icons in this file use mask color 13.
#
nd4Icons="NDHardDrive NDRamDisk NDNetDrive NDRemovableDisk NDZipDisk"
cvtfile PCX/nd4.pcx NDStandard "$nd4Icons" $cvtfileArgs


#########################################################################
# NewDesk Icons	(NEWDESK.PCX)						#
######################################################################### 
#
# All icons in this file use mask color 13.
#

cvtpcx -f -m13 -t -l -x0 -y0   -dLC -dLM -dLCGA -nNDMyComputer PCX/newdesk.pcx
cvtpcx -f -m13 -t -l -x0 -y41  -dLC -dLM -dLCGA -nNDWorld PCX/newdesk.pcx
cvtpcx -f -m13 -t -l -x0 -y82  -dLC -dLM -dLCGA -nNDDocument PCX/newdesk.pcx


#########################################################################
# NewDesk Tiny Icons (NEWDESK.TINY.PCX)					#
######################################################################### 
#
# All icons in this file use mask color 13.
#

cvtpcx -f -m13 -t -z -x0 -y0   -nNDFileFolderTiny PCX/newdesk.tiny.pcx
cvtpcx -f -m13 -t -z -x0 -y16  -nNDThreeInchDiskTiny PCX/newdesk.tiny.pcx
cvtpcx -f -m13 -t -z -x0 -y32  -nNDFiveInchDiskTiny PCX/newdesk.tiny.pcx
cvtpcx -f -m13 -t -z -x0 -y48  -nNDHardDriveTiny PCX/newdesk.tiny.pcx
cvtpcx -f -m13 -t -z -x0 -y64  -nNDNetDriveTiny PCX/newdesk.tiny.pcx
cvtpcx -f -m13 -t -z -x0 -y80  -nNDCDRomTiny PCX/newdesk.tiny.pcx
cvtpcx -f -m13 -t -z -x0 -y96  -nNDRemovableDiskTiny PCX/newdesk.tiny.pcx
cvtpcx -f -m13 -t -z -x0 -y112 -nNDZipDiskTiny PCX/newdesk.tiny.pcx
