#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = babase
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = sch_mtds.goc txt_strs.goc babase.goc doc_mtds.goc\
                  dta_mtds.goc nav_mtds.goc hbicons.goh hbase.goh\
                  bblogo.goh
OBJS            = sch_mtds.obj txt_strs.obj babase.obj doc_mtds.obj\
                  dta_mtds.obj nav_mtds.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
