#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = babase
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = babase.goc DOC_MTDS.GOC DTA_MTDS.GOC NAV_MTDS.GOC\
                  SCH_MTDS.GOC TXT_STRS.GOC BBLOGO.GOH HBASE.GOH\
                  HBICONS.GOH
OBJS            = babase.obj DOC_MTDS.obj DTA_MTDS.obj NAV_MTDS.obj\
                  SCH_MTDS.obj TXT_STRS.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
