#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = Stub
ASM_TO_OBJS     = atron.asm bpt.asm break.asm bsw.asm cbreak.asm com.asm\
                  intelbpt.asm kernel.asm main.asm netware.asm rpc.asm\
                  tbreak.asm timebreak.asm wincom.asm
UI_TO_RDFS      =
SRCS            = atron.asm bpt.asm break.asm bsw.asm cbreak.asm com.asm\
                  intelbpt.asm kernel.asm main.asm netware.asm rpc.asm\
                  tbreak.asm timebreak.asm wincom.asm atron.def bsw.def\
                  com.def gulliver.def netware.def pcmcia.def penelope.def\
                  pscope.def resp.def respcom.def rpc.def stub.def\
                  use32.def wincom.def zoomer.def
OBJS            = atron.obj bpt.obj break.obj bsw.obj cbreak.obj com.obj\
                  intelbpt.obj kernel.obj main.obj netware.obj rpc.obj\
                  tbreak.obj timebreak.obj wincom.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
