#!/bin/sh -f
#
# $Id: convert,v 1.1 98/04/28 19:43:52 joon Exp $
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon

CArgs="-f -u -t -L -dLC -dLM -dSM -dLCGA -dSCGA -dYM -dTC -dTM -dTCGA"
MArgs="-f -u -t -L -dLC -dLM -dSC -dLCGA -dYC -dTC -dTM -dTCGA"
maskColor="3"

cvtfile file2gr.pcx 6 CBookDoc $CArgs
cvtfile file2gr.pcx 7 MBookDoc $MArgs
cvtfile file2gr.pcx 8 CReader $CArgs
cvtfile file2gr.pcx 9 MReader $MArgs

cvtpcx -f -m13 -t -z -nReaderTiny reader.tiny.pcx
cvtpcx -f -m13 -t -z -nBookDocTiny bookdoc.tiny.pcx
