#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = tcpip
ASM_TO_OBJS     = tcpipManager.asm
UI_TO_RDFS      = tcpipStrings.ui tcpipAddrCtrl.ui
SRCS            = tcpipUtils.asm tcpipLink.asm tcpipSocket.asm\
                  tcpipEntry.asm tcpipManager.asm tcpipDhcp.asm\
                  tcpipAddrCtrl.asm tcpipLog.asm dhcpConstant.def\
                  tcpipAddrCtrl.def tcpip.def tcpipGlobal.def\
                  tcpipAddrCtrl.ui tcpipStrings.ui tcpInput.c ipOutput.c\
                  tcpOutput.c icmp.c ipInput.c tcpUtils.c rawIp.c udp.c\
                  tcpipLog.c udp.h tcp.h ip.h icmp.h rawIp.h tcpip.h\
                  tcpipLog.h tcpip.goc
OBJS            = tcpipManager.obj tcpInput.obj ipOutput.obj tcpOutput.obj\
                  icmp.obj ipInput.obj tcpUtils.obj rawIp.obj udp.obj\
                  tcpipLog.obj tcpip.obj
LOBJS           =

PRODUCTS        = DBCS 

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(DBCS/$(DEPFILE))
#include "DBCS/$(DEPFILE)"
#endif
