#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = tcpip
ASM_TO_OBJS     = tcpipManager.asm
UI_TO_RDFS      = tcpipStrings.ui tcpipAddrCtrl.ui
SRCS            = tcpipAddrCtrl.asm tcpipDhcp.asm tcpipEntry.asm\
                  tcpipLink.asm tcpipLog.asm tcpipManager.asm\
                  tcpipSocket.asm tcpipUtils.asm dhcpConstant.def tcpip.def\
                  tcpipAddrCtrl.def tcpipGlobal.def tcpipAddrCtrl.ui\
                  tcpipStrings.ui icmp.c ipInput.c ipOutput.c rawIp.c\
                  tcpInput.c tcpipLog.c tcpOutput.c tcpUtils.c udp.c icmp.h\
                  ip.h rawIp.h tcp.h tcpip.h tcpipLog.h udp.h tcpip.goc
OBJS            = tcpipManager.obj icmp.obj ipInput.obj ipOutput.obj\
                  rawIp.obj tcpInput.obj tcpipLog.obj tcpOutput.obj\
                  tcpUtils.obj udp.obj tcpip.obj
LOBJS           =

PRODUCTS        = DBCS 

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(DBCS/$(DEPFILE))
#include "DBCS/$(DEPFILE)"
#endif
