#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = Munch
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = BGEGNER.GOC GRAFDATA.GOC MUNCH.GOC SPRITES.GOC TOPTEN.GOC\
                  BGEGNER.GOH MAX.GOH MONIKERS.GOH PALETTE.GOH SPRITES.GOH\
                  TOOLARGE.GOH TOPTEN.GOH
OBJS            = BGEGNER.obj GRAFDATA.obj MUNCH.obj SPRITES.obj TOPTEN.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
