#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = munch
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = bGegner.goc sprites.goc topten.goc munch.goc grafData.goc\
                  monikers.goh topten.goh sprites.goh max.goh bGegner.goh\
                  palette.goh toolarge.goh
OBJS            = bGegner.obj sprites.obj topten.obj munch.obj grafData.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
