#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = hearts
ASM_TO_OBJS     = hearts.asm
UI_TO_RDFS      = hearts.ui
SRCS            = heartsDeck.asm heartsGame.asm hearts.asm heartsHand.asm\
                  heartsSound.asm heartsGame.def heartsDeck.def\
                  heartsHand.def myMacros.def hearts.ui
OBJS            = hearts.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
