#!/bin/sh
###############################################################################
#
#       Copyright (c) GeoWorks 1993 -- All Rights Reserved
#
#       PROJECT:        PC/GEOS
#       FILE:           mkart
#
#       AUTHOR:         Jeremy Dashe, 4/17/93
#
#       REVISION HISTORY:
#               Name    Date            Description
#               ----    ----            -----------
#               jdashe  4/17/93	        Initial version
#
#       $Id: mkart,v 1.3.13.1 97/03/29 03:29:47 canavese Exp $
#
# DESCRIPTION:
#       This is shell script creates the hardcoded image display code
#	used in loader.exe for this specific video driver.
#
hcpic videoCGAImageLogo.asm ../Art/ens20_cga.pcx -aLogo -x0 -y0 -vc
