#!/bin/sh -
#
#	$Id: convert,v 1.1 98/04/28 11:33:21 joon Exp $
#
artDir=/staff/pcgeos/Appl/Art/Art.20
. $artDir/cvtcommon
cvtfile $artDir/g20apps2.pcx 2 GeoDex $appArgs
cvtfile $artDir/g20apps2.pcx 3 GeoDexDoc $docArgs

cvtpcx -f -m13 -t -z -nGeoDexTiny newdex.tiny.pcx
