#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = fontmgck
CHARSET         = charset.goc
DRAWFONT        = drawfont.goc
FONTDRVR        = fontdrvrManager.asm
FONTM           = fontm.goc font_ui.goh
NONLIN          = nonlin.goc
UI_TO_RDFS      =
OBJS            = charset.obj drawfont.obj fontm.obj nonlin.obj
COMMON          = charset.goh gsol.h fontmagi.h
MODULES         = FONTDRVR
CMODULES        = CHARSET DRAWFONT FONTM NONLIN
SRCS            = $(CHARSET) $(DRAWFONT) $(FONTDRVR) $(FONTM) $(NONLIN)\
                  $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
