#!/bin/sh -
#
# $Id: convert,v 1.2.2.1 97/03/29 08:08:50 canavese Exp $

#
# Convert a pcx file to a moniker, dealing with locating the installed or
# uninstalled version of the file (doesn't deal with branches, I'm afraid)
#
# Usage: cvt <file> <cvtpcx-args>
#
cvt() {
    name=""
    for a do
	case $a in
	    -n*)	name=`expr x$a : 'x-n\(.*\)$'` ;;
	esac
    done
    file=$1
    shift
    if [ ! -f $file ]; then
	file=`otherdir`/$file
    fi
    cvtpcx -f -2 "$@" $file
}

cvt printin.pcx -nPrinting -w90 -h90 -g -N
cvt printsheet.pcx -nPrintSheet -w200 -h140 -g -N
cvt scan.pcx -nScanning -w90 -h90 -g -N
