GWPOKER.rdef: GENERIC.UIH PRODUCT.UIH CARDS.UIH GAME.UIH ART/MKPOKER.UI
GWPOKER.obj \
GWPOKER.eobj: GEOS.DEF GEODE.DEF EC.DEF MYMACROS.DEF LIBRARY.DEF \
                RESOURCE.DEF OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF \
                OBJECTS/WINC.DEF WIN.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF HEAP.DEF TIMER.DEF TIMEDATE.DEF SYSTEM.DEF \
                LOCALIZE.DEF SLLANG.DEF FILE.DEF FILEENUM.DEF VM.DEF \
                HUGEARR.DEF OBJECTS/INPUTC.DEF INITFILE.DEF DBASE.DEF \
                UI.DEF INPUT.DEF HWR.DEF OBJECTS/PROCESSC.DEF GCNLIST.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SOUND.DEF DRIVER.DEF INTERNAL/SOUNDFMT.DEF \
                INTERNAL/SEMINT.DEF GAME.DEF CARDS.DEF WAV.DEF \
                POKERGAME.ASM OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF PAYOFFDISPLAY.ASM \
                POKERSOUND.ASM SIZES.DEF GWPOKER.RDEF

GWPOKEREC.geo GWPOKER.geo : GEOS.LDF UI.LDF GAME.LDF SOUND.LDF WAV.LDF CARDS.LDF 