DSCGAMANAGER.obj \
DSCGAMANAGER.eobj: VIDCOMGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF DRIVER.DEF LMEM.DEF INTERNAL/SEMINT.DEF \
                GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF WIN.DEF \
                CHAR.DEF LOCALIZE.DEF SLLANG.DEF SYSTEM.DEF \
                INTERNAL/HEAPINT.DEF SYSSTATS.DEF INTERNAL/GSTATE.DEF \
                INTERNAL/TMATRIX.DEF INTERNAL/FONTDR.DEF FILE.DEF \
                INTERNAL/WINDOW.DEF INTERNAL/INTERRUP.DEF \
                INTERNAL/THREADIN.DEF INTERNAL/VIDEODR.DEF HUGEARR.DEF \
                DSCGACONSTANT.DEF DUMBCOMCONSTANT.DEF VIDCOMCONSTANT.DEF \
                DSCGAMACRO.DEF DUMBCOMMACRO.DEF VIDCOMMACRO.DEF \
                DUMBCOMDEVINFO.ASM VIDCOMTABLES.ASM DSCGATABLES.ASM \
                DUMBCOMTABLES.ASM VIDCOMVARIABLE.DEF DUMBCOMVARIABLE.DEF \
                DSCGAVARIABLE.DEF DSCGASTRINGTAB.ASM VIDCOMENTRY.ASM \
                VIDCOMOUTPUT.ASM VIDCOMCHARS.ASM DUMBCOMGENCHAR.ASM \
                VIDCOMFONT.ASM VIDCOMUNDER.ASM VIDCOMUTILS.ASM \
                VIDCOMREGION.ASM VIDCOMXOR.ASM VIDCOMINFO.ASM \
                VIDCOMESCAPE.ASM VIDCOMPALETTE.ASM DUMBCOMOUTPUT.ASM \
                DUMBCOMUTILS.ASM DUMBCOMCHARS.ASM DUMBCOMPOINTER.ASM \
                DUMBCOMPALETTE.ASM DSCGAESCTAB.ASM VIDCOMPOLYGON.ASM \
                VIDCOMLINE.ASM VIDCOMPUTLINE.ASM VIDCOMRASTER.ASM \
                VIDCOMEXCLBOUNDS.ASM DUMBCOMRASTER.ASM DSCGAADMIN.ASM

DSCGAEC.geo DSCGA.geo : GEOS.LDF 