# GOCFLAGS += -DPRODUCT_NDO2000 -DINTERIM_NEWDEAL_16_COLOR_ART
# LINKFLAGS += -DPRODUCT_NDO2000 -DINTERIM_NEWDEAL_16_COLOR_ART

#if $(PRODUCT) == "NDO2000"
GOCFLAGS += -DPRODUCT_NDO2000
LINKFLAGS += -DPRODUCT_NDO2000
#else
GOCFLAGS += -DEFAX_SUPPORT
LINKFLAGS += -DEFAX_SUPPORT
#endif

GEODE           = email

#include <$(SYSMAKEFILE)>
