#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = radio
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = radio.goc onoff.goh bbreg24.goh bbxreg.goh fmnote.goh\
                  icon.goh
OBJS            = radio.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
