/*-
 * parse.c --
 *	Functions to parse a makefile.
 *
 *	One function, Parse_Init, must be called before any functions
 *	in this module are used. After that, the function Parse_File is the
 *	main entry point and controls most of the other functions in this
 *	module.
 *
 *	Most important structures are kept in Lsts. Directories for
 *	the #include "..." function are kept in the 'parseIncPath' Lst, while
 *	those for the #include <...> are kept in the 'sysIncPath' Lst. The
 *	targets currently being defined are kept in the 'targets' Lst.
 *
 *	The variables 'fname' and 'lineno' are used to track the name
 *	of the current file and the line number in that file so that error
 *	messages can be more meaningful.
 *
 * Copyright (c) 1988, 1989 by the Regents of the University of California
 * Copyright (c) 1988, 1989 by Adam de Boor
 * Copyright (c) 1989 by Berkeley Softworks
 *
 * Permission to use, copy, modify, and distribute this
 * software and its documentation for any non-commercial purpose
 * and without fee is hereby granted, provided that the above copyright
 * notice appears in all copies.  The University of California,
 * Berkeley Softworks and Adam de Boor make no representations about
 * the suitability of this software for any purpose.  It is provided
 * "as is" without express or implied warranty.
 *
 * Interface:
 *	Parse_Init	    	    Initialization function which must be
 *	    	  	    	    called before anything else in this module
 *	    	  	    	    is used.
 *
 *	Parse_File	    	    Function used to parse a makefile. It must
 *	    	  	    	    be given the name of the file, which should
 *	    	  	    	    already have been opened, and a function
 *	    	  	    	    to call to read a character from the file.
 *
 *	Parse_IsVar	    	    Returns TRUE if the given line is a
 *	    	  	    	    variable assignment. Used by MainParseArgs
 *	    	  	    	    to determine if an argument is a target
 *	    	  	    	    or a variable assignment. Used internally
 *	    	  	    	    for pretty much the same thing...
 *
 *	Parse_Error	    	    Function called when an error occurs in
 *	    	  	    	    parsing. Used by the variable and
 *	    	  	    	    conditional modules.
 *	Parse_MainName	    	    Returns a Lst of the main target to create.
 */
#include <config.h>

#ifndef lint
static char     *rcsid = "$Id: parse.c,v 1.15 96/06/24 15:06:29 tbradley Exp $ SPRITE (Berkeley)";
#endif lint

#include <compat/file.h>

#include    <stdio.h>
#include    <ctype.h>
#if defined(__HIGHC__)
#include    <malloc.h>
#	include <sys/stat.h>
#define malloc hc_malloc
#define calloc hc_calloc
#define free hc_free
#define realloc hc_realloc
#undef malloc
#undef calloc
#undef free
#undef realloc
#	include <process.h>
#elif defined(__BORLANDC__) && !defined(_MSC_VER)
#	include <malloc.h>
#	include <sys/stat.h>
#       include <process.h>
#	include "t:\src\xspawn.h"
#endif


#include    <stdlib.h>
#include    <compat/string.h>

#include    "make.h"
#include    "buf.h"

#if defined (unix)
#      include    "rmt.h"
#      include    "arch.h"
#elif defined(_LINUX)
#       include <process.h>
#elif defined(_WIN32)
#      include    <windows.h>
#endif /* unix */

/*
 * These values are returned by ParseEOF to tell Parse_File whether to
 * CONTINUE parsing, i.e. it had only reached the end of an include file,
 * or if it's DONE.
 */
#define	CONTINUE	1
#define	DONE		0
static int 	    ParseEOF         (void);

static Lst     	    targets;	/* targets we're working on */
static Boolean	    inLine;	/* true if currently in a dependency
				 * line or its commands */

static char    	    *fname;	/* name of current file (for errors) */
static int          lineno;	/* line number in current file */
static FILE   	    *curFILE; 	/* current makefile */

static int	    fatals = 0;

static GNode	    *mainNode;	/* The main target to create. This is the
				 * first target on the first dependency
				 * line in the first makefile */
/*
 * Definitions for handling #include specifications
 */
typedef struct IFile {
    char           *fname;	    /* name of previous file */
    int             lineno;	    /* saved line number */
    FILE *       F;		    /* the open stream */
}              	  IFile;

static Lst      includes;  	/* stack of IFiles generated by
				 * #includes */
Lst         	parseIncPath;	/* list of directories for "..." includes */
Lst         	sysIncPath;	/* list of directories for <...> includes */

/*-
 * anyExport is used to trace if any target will need exportation. If none
 * does, then any .EXPORT target can be ignored and the process needn't
 * be slowed down by trying to connect to some load-balancing system.
 */
static Boolean anyExport = FALSE;

/*-
 * specType contains the SPECial TYPE of the current target. It is
 * Not if the target is unspecial. If it *is* special, however, the children
 * are linked as children of the parent but not vice versa. This variable is
 * set in ParseDoDependency
 */
typedef enum {
    Begin,  	    /* .BEGIN */
    Default,	    /* .DEFAULT */
    End,    	    /* .END */
    Export, 	    /* .EXPORT */
    Ignore,	    /* .IGNORE */
    Includes,	    /* .INCLUDES */
    Interrupt,	    /* .INTERRUPT */
    Libs,	    /* .LIBS */
    MFlags,	    /* .MFLAGS or .MAKEFLAGS */
    Main,	    /* .MAIN and we don't have anything user-specified to
		     * make */
    NoExport,	    /* .NOEXPORT */
    Not,	    /* Not special */
    NotParallel,    /* .NOTPARALELL */
    Null,   	    /* .NULL */
    Order,  	    /* .ORDER */
    _Path,	    /* .PATH */
    Precious,	    /* .PRECIOUS */
    Shell,	    /* .SHELL */
    Silent,	    /* .SILENT */
    SingleShell,    /* .SINGLESHELL */
    Suffixes,	    /* .SUFFIXES */
    Attribute,	    /* Generic attribute */
} ParseSpecial;

ParseSpecial specType;

/*
 * Predecessor node for handling .ORDER. Initialized to NILGNODE when .ORDER
 * seen, then set to each successive source on the line.
 */
static GNode	*predecessor;

/*********************prototypes for static routines******************/
static int	ParseFindKeyword(char *str);
static int	ParseLinkSrc(GNode *pgn, GNode *cgn);
static int	ParseDoOp(GNode *gn, int op);
static void	ParseDoSrc(int tOp, char *src);
static int	ParseFindMain(GNode *gn);
static int	ParseClearPath(Lst path);
static void	ParseDoDependency(char *line);
static int	ParseAddCmd(GNode *gn, char *cmd);
static int	ParseHasCommands(GNode *gn);
static void	ParseDoInclude(char *file);
static char	*ParseReadLine(void);
static void	ParseFinishLine(void);

/*
 * The parseKeywords table is searched using binary search when deciding
 * if a target or source is special. The 'spec' field is the ParseSpecial
 * type of the keyword ("Not" if the keyword isn't special as a target) while
 * the 'op' field is the operator to apply to the list of targets if the
 * keyword is used as a source ("0" if the keyword isn't special as a source)
 */
static struct {
    char    	  *name;    	/* Name of keyword */
    ParseSpecial  spec;	    	/* Type when used as a target */
    int	    	  op;	    	/* Operator when used as a source */
} parseKeywords[] = {
{ ".BEGIN", 	  Begin,    	0 },
{ ".DEFAULT",	  Default,  	0 },
{ ".DONTCARE",	  Attribute,   	OP_DONTCARE },
{ ".END",   	  End,	    	0 },
{ ".EXEC",	  Attribute,   	OP_EXEC },
{ ".EXPORT",	  Export,   	OP_EXPORT },
{ ".EXPORTSAME",  Attribute,	OP_EXPORTSAME },
{ ".IGNORE",	  Ignore,   	OP_IGNORE },
{ ".INCLUDES",	  Includes, 	0 },
{ ".INTERRUPT",	  Interrupt,	0 },
{ ".INVISIBLE",	  Attribute,   	OP_INVISIBLE },
{ ".JOIN",  	  Attribute,   	OP_JOIN },
{ ".LIBS",  	  Libs,	    	0 },
{ ".M68020",	  Attribute,	OP_M68020 },
{ ".MAIN",	  Main,		0 },
{ ".MAKE",  	  Attribute,   	OP_MAKE },
{ ".MAKEFLAGS",	  MFlags,   	0 },
{ ".MFLAGS",	  MFlags,   	0 },
{ ".NOEXPORT",	  NoExport,   	OP_NOEXPORT },
{ ".NOTMAIN",	  Attribute,   	OP_NOTMAIN },
{ ".NOTPARALLEL", NotParallel,	0 },
{ ".NULL",  	  Null,	    	0 },
{ ".ORDER", 	  Order,    	0 },
{ ".PATH",	  _Path,	0 },
{ ".PRECIOUS",	  Precious, 	OP_PRECIOUS },
{ ".RECURSIVE",	  Attribute,	OP_MAKE },
{ ".SHELL", 	  Shell,    	0 },
{ ".SILENT",	  Silent,   	OP_SILENT },
{ ".SINGLESHELL", SingleShell,	0 },
{ ".SUFFIXES",	  Suffixes, 	0 },
{ ".USE",   	  Attribute,   	OP_USE },
};

/*-
 *----------------------------------------------------------------------
 * ParseFindKeyword --
 *	Look in the table of keywords for one matching the given string.
 *
 * Results:
 *	The index of the keyword, or -1 if it isn't there.
 *
 * Arguments:
 *      char *str : String to find
 *
 * Side Effects:
 *	None
 *----------------------------------------------------------------------
 */
static int
ParseFindKeyword (char *str)
{
    register int    start,
		    end,
		    cur;
    register int    diff;

    start = 0;
    end = (sizeof(parseKeywords)/sizeof(parseKeywords[0])) - 1;

    do {
	cur = start + ((end - start) / 2);
	diff = strcmp (str, parseKeywords[cur].name);

	if (diff == 0) {
	    return (cur);
	} else if (diff < 0) {
	    end = cur - 1;
	} else {
	    start = cur + 1;
	}
    } while (start <= end);
    return (-1);
}

/*-
 *---------------------------------------------------------------------
 * Parse_Error  --
 *	Error message abort function for parsing. Prints out the context
 *	of the error (line number and file) as well as the message with
 *	two optional arguments.
 *
 * Results:
 *	None
 *
 * Arguments:
 *      int            type : Error type -- PARSE_WARNING if just a warning,
 *                            PARSE_FATAL if can't continue (after parsing)
 *      char          *fmt  : printf format string
 *      unsigned long  arg1 : First optional argument for the fmt string
 *      unsigned long  arg2 : Second optional argument for the fmt string
 *
 * Side Effects:
 *	"fatals" is incremented if the level is PARSE_FATAL.
 *---------------------------------------------------------------------
 */
/* VARARGS1 */
void
Parse_Error (int type, char *fmt, ...)
{
    va_list ap;

    va_start(ap,fmt);

    if ((type != PARSE_WARNING) || !noWarnings) {
	fprintf (stderr, "\"%s\", line %d: ", fname, lineno);
	if (type == PARSE_WARNING) {
	    fprintf (stderr, "Warning: ");
	}
	vfprintf (stderr, fmt, ap);
	putc ('\n', stderr);

	if (type == PARSE_FATAL) {
	    fatals += 1;
	}
    }

    va_end(ap);
}

/*-
 *-----------------------------------------------------------------------
 * Parse_AnyExport --
 *	Return TRUE if any target was labeled for exportation.
 *
 * Results:
 *	TRUE or FALSE...
 *
 * Side Effects:
 *	None.
 *
 *-----------------------------------------------------------------------
 */
Boolean
Parse_AnyExport(void)
{
    return (anyExport);
}

/*-
 *---------------------------------------------------------------------
 * ParseLinkSrc  --
 *	Link the parent node to its new child. Used in a Lst_ForEach by
 *	ParseDoDependency. If the specType isn't 'Not', the parent
 *	isn't linked as a parent of the child.
 *
 * Results:
 *	Always = 0
 *
 * Arguments:
 *      GNode *pgn : The parent node
 *      GNode *cgn : The child node
 *
 * Side Effects:
 *	New elements are added to the parents list of cgn and the
 *	children list of cgn. the unmade field of pgn is updated
 *	to reflect the additional child.
 *---------------------------------------------------------------------
 */
static int
ParseLinkSrc (GNode *pgn, GNode *cgn)
{
    if (Lst_Member (pgn->children, (ClientData)cgn) == NILLNODE) {
	(void)Lst_AtEnd (pgn->children, (ClientData)cgn);
	if (specType == Not) {
	    (void)Lst_AtEnd (cgn->parents, (ClientData)pgn);
	}
	pgn->unmade += 1;
    }
    return (0);
}

/*-
 *---------------------------------------------------------------------
 * ParseDoOp  --
 *	Apply the parsed operator to the given target node. Used in a
 *	Lst_ForEach call by ParseDoDependency once all targets have
 *	been found and their operator parsed. If the previous and new
 *	operators are incompatible, a major error is taken.
 *
 * Results:
 *	Always 0
 *
 * Arguments:
 *      GNode *gn : The node to which the operator is to be applied
 *      int    op : The operator to apply
 *
 * Side Effects:
 *	The type field of the node is altered to reflect any new bits in
 *	the op.
 *---------------------------------------------------------------------
 */
static int
ParseDoOp (GNode *gn, int op)
{
    /*
     * If the dependency mask of the operator and the node don't match and
     * the node has actually had an operator applied to it before, and
     * the operator actually has some dependency information in it, complain.
     */
    if (((op & OP_OPMASK) != (gn->type & OP_OPMASK)) &&
	!OP_NOP(gn->type) && !OP_NOP(op))
    {
	Parse_Error (PARSE_FATAL, "Inconsistent operator for %s", (unsigned long)gn->name, 0);
	return (1);
    }

    if ((op == OP_DOUBLEDEP) && ((gn->type & OP_OPMASK) == OP_DOUBLEDEP)) {
	/*
	 * If the node was the object of a :: operator, we need to create a
	 * new instance of it for the children and commands on this dependency
	 * line. The new instance is placed on the 'cohorts' list of the
	 * initial one (note the initial one is not on its own cohorts list)
	 * and the new instance is linked to all parents of the initial
	 * instance.
	 */
	register GNode	*cohort;
	LstNode	    	ln;

	cohort = Targ_NewGN(gn->name);
	/*
	 * Duplicate links to parents so graph traversal is simple. Perhaps
	 * some type bits should be duplicated?
	 *
	 * Make the cohort invisible as well to avoid duplicating it into
	 * other variables. True, parents of this target won't tend to do
	 * anything with their local variables, but better safe than
	 * sorry.
	 */
	Lst_ForEach(gn->parents, ParseLinkSrc, (ClientData)cohort);
	cohort->type = OP_DOUBLEDEP|OP_INVISIBLE;
	(void)Lst_AtEnd(gn->cohorts, (ClientData)cohort);

	/*
	 * Replace the node in the targets list with the new copy
	 */
	ln = Lst_Member(targets, (ClientData)gn);
	Lst_Replace(ln, (ClientData)cohort);
	gn = cohort;
    }
    /*
     * We don't want to nuke any previous flags (whatever they were) so we
     * just OR the new operator into the old
     */
    gn->type |= op;

    return (0);
}

/*-
 *---------------------------------------------------------------------
 * ParseDoSrc  --
 *	Given the name of a source, figure out if it is an attribute
 *	and apply it to the targets if it is. Else decide if there is
 *	some attribute which should be applied *to* the source because
 *	of some special target and apply it if so. Otherwise, make the
 *	source be a child of the targets in the list 'targets'
 *
 * Results:
 *	None
 *
 * Arguments:
 *      int   tOp : Operator (if any) from special targets
 *      char *src : Name of the source to handle
 *
 * Side Effects:
 *	Operator bits may be added to the list of targets or to the source.
 *	The targets may have a new source added to their lists of children.
 *---------------------------------------------------------------------
 */
static void
ParseDoSrc (int tOp, char *src)
{
    int		op;	/* operator (if any) from special source */
    GNode	*gn;

    op = 0;
    if (*src == '.' && isupper (src[1])) {
	int keywd = ParseFindKeyword(src);
	if (keywd != -1) {
	    op = parseKeywords[keywd].op;
	}
    }
    if (op != 0) {
	Lst_ForEach (targets, ParseDoOp, (ClientData)op);
	if (op == OP_EXPORT) {
	    anyExport = TRUE;
	}
    } else if (specType == Main) {
	/*
	 * If we have noted the existence of a .MAIN, it means we need
	 * to add the sources of said target to the list of things
	 * to create. The string 'src' is likely to be free, so we
	 * must make a new copy of it. Note that this will only be
	 * invoked if the user didn't specify a target on the command
	 * line. This is to allow #ifmake's to succeed, or something...
	 */
	(void) Lst_AtEnd (create, (ClientData)Str_New(src));
	/*
	 * Add the name to the .TARGETS variable as well, so the user can
	 * employ that, if desired.
	 */
	Var_Append(".TARGETS", src, VAR_GLOBAL);
    } else if (specType == Order) {
	/*
	 * Create proper predecessor/successor links between the previous
	 * source and the current one.
	 */
	gn = Targ_FindNode(src, TARG_CREATE);
	if (predecessor != NILGNODE) {
	    (void)Lst_AtEnd(predecessor->successors, (ClientData)gn);
	    (void)Lst_AtEnd(gn->preds, (ClientData)predecessor);
	}
	/*
	 * The current source now becomes the predecessor for the next one.
	 */
	predecessor = gn;
    } else {
	/*
	 * If the source is not an attribute, we need to find/create
	 * a node for it. After that we can apply any operator to it
	 * from a special target or link it to its parents, as
	 * appropriate.
	 *
	 * In the case of a source that was the object of a :: operator,
	 * the attribute is applied to all of its instances (as kept in
	 * the 'cohorts' list of the node) or all the cohorts are linked
	 * to all the targets.
	 */
	gn = Targ_FindNode (src, TARG_CREATE);
	if (tOp) {
	    gn->type |= tOp;
	} else {
	    Lst_ForEach (targets, ParseLinkSrc, (ClientData)gn);
	}
	if ((gn->type & OP_OPMASK) == OP_DOUBLEDEP) {
	    register GNode  	*cohort;
	    register LstNode	ln;

	    for (ln=Lst_First(gn->cohorts); ln != NILLNODE; ln = Lst_Succ(ln)){
		cohort = (GNode *)Lst_Datum(ln);
		if (tOp) {
		    cohort->type |= tOp;
		} else {
		    Lst_ForEach(targets, ParseLinkSrc, (ClientData)cohort);
		}
	    }
	}
    }
}

/*-
 *-----------------------------------------------------------------------
 * ParseFindMain --
 *	Find a real target in the list and set it to be the main one.
 *	Called by ParseDoDependency when a main target hasn't been found
 *	yet.
 *
 * Results:
 *	0 if main not found yet, 1 if it is.
 *
 * Arguments:
 *      GNode *gn : Node to examine
 *
 * Side Effects:
 *	mainNode is changed and Targ_SetMain is called.
 *
 *-----------------------------------------------------------------------
 */
static int
ParseFindMain(GNode *gn)
{
    if (((gn->type & (OP_NOTMAIN|OP_USE|OP_EXEC|OP_TRANSFORM)) == 0) &&
	(gn->name[0] != '.' || strchr(gn->name, '/') != 0))
    {
	mainNode = gn;
	Targ_SetMain(gn);
	return (1);
    } else {
	return (0);
    }
}

/*-
 *-----------------------------------------------------------------------
 * ParseAddDir --
 *	Front-end for Dir_AddDir to make sure Lst_ForEach keeps going
 *
 * Results:
 *	=== 0
 *
 * Side Effects:
 *	See Dir_AddDir.
 *
 *-----------------------------------------------------------------------
 */
static int
ParseAddDir(Lst path, char *name)
{
    Dir_AddDir(path, name);
    return(0);
}

/*-
 *-----------------------------------------------------------------------
 * ParseClearPath --
 *	Front-end for Dir_ClearPath to make sure Lst_ForEach keeps going
 *
 * Results:
 *	=== 0
 *
 * Side Effects:
 *	See Dir_ClearPath
 *
 *-----------------------------------------------------------------------
 */
static int
ParseClearPath(Lst path)
{
    Dir_ClearPath(path);
    return(0);
}

/*-
 *---------------------------------------------------------------------
 * ParseDoDependency  --
 *	Parse the dependency line in line.
 *
 * Results:
 *	None
 *
 * Side Effects:
 *	The nodes of the sources are linked as children to the nodes of the
 *	targets. Some nodes may be created.
 *
 *	We parse a dependency line by first extracting words from the line and
 * finding nodes in the list of all targets with that name. This is done
 * until a character is encountered which is an operator character. Currently
 * these are only ! and :. At this point the operator is parsed and the
 * pointer into the line advanced until the first source is encountered.
 * 	The parsed operator is applied to each node in the 'targets' list,
 * which is where the nodes found for the targets are kept, by means of
 * the ParseDoOp function.
 *	The sources are read in much the same way as the targets were except
 * that now they are expanded using the wildcarding scheme of the C-Shell
 * and all instances of the resulting words in the list of all targets
 * are found. Each of the resulting nodes is then linked to each of the
 * targets as one of its children.
 *	Certain targets are handled specially. These are the ones detailed
 * by the specType variable.
 *	The storing of transformation rules is also taken care of here.
 * A target is recognized as a transformation rule by calling
 * Suff_IsTransform. If it is a transformation rule, its node is gotten
 * from the suffix module via Suff_AddTransform rather than the standard
 * Targ_FindNode in the target module.
 *---------------------------------------------------------------------
 */
static void
ParseDoDependency (char *line)
{
    register char  *cp;		/* our current position */
    register GNode *gn;		/* a general purpose temporary node */
    register int    op;		/* the operator on the line */
    char            savec;	/* a place to save a character */
    Lst    	    paths;   	/* List of search paths to alter when parsing
				 * a list of .PATH targets */
    int	    	    tOp;    	/* operator from special target */
    Lst	    	    sources;	/* list of source names after expansion */
    Lst 	    curTargs;	/* list of target names to be found and added
				 * to the targets list */

    tOp = 0;

    specType = Not;
    paths = (Lst)NULL;

    curTargs = Lst_Init(FALSE);

    do {
	for (cp = line;
	     *cp && !isspace (*cp) &&
	     (*cp != '!') && (*cp != ':') && (*cp != '(');
	     cp++)
	{
	    if (*cp == '$') {
		/*
		 * Must be a dynamic source (would have been expanded
		 * otherwise), so call the Var module to parse the puppy
		 * so we can safely advance beyond it...There should be
		 * no errors in this, as they would have been discovered
		 * in the initial Var_Subst and we wouldn't be here.
		 */
		int 	length;
		Boolean	freeIt;
		char	*result;

		result=Var_Parse(cp, VAR_CMD, TRUE, &length, &freeIt);

		if (freeIt) {
		    free(result);
		}
		cp += length-1;
	    }
#if !defined(unix)
	    /* allow for the escaping of ':' in DOS as file names might
	     * have a colon in them to specifiy the drive
	     */
	    if (*cp == '\\' && *(cp+1) == ':')
	    {
		memmove(cp, cp+1, strlen(cp+1)+1);
	    }
#endif
	    continue;
	}
	if (*cp == '(') {
	    /*
	     * Archives must be handled specially to make sure the OP_ARCHV
	     * flag is set in their 'type' field, for one thing, and because
	     * things like "archive(file1.o file2.o file3.o)" are permissible.
	     * Arch_ParseArchive will set 'line' to be the first non-blank
	     * after the archive-spec. It creates/finds nodes for the members
	     * and places them on the given list, returning SUCCESS if all
	     * went well and FAILURE if there was an error in the
	     * specification. On error, line should remain untouched.
	     */
#ifdef unix
	    if (Arch_ParseArchive (&line, targets, VAR_CMD) != SUCCESS) {
		Parse_Error (PARSE_FATAL,
			     "Error in archive specification: \"%s\"",
			       (unsigned long)line,0);
		return;
	    } else {
		continue;
	    }
#endif
	}
	savec = *cp;

	if (!*cp) {
	    /*
	     * Ending a dependency line without an operator is a Bozo
	     * no-no
	     */
	    Parse_Error (PARSE_FATAL, "Need an operator", 0, 0);
	    return;
	}
	*cp = '\0';
	/*
	 * Have a word in line. See if it's a special target and set
	 * specType to match it.
	 */
	if (*line == '.' && isupper (line[1])) {
	    /*
	     * See if the target is a special target that must have it
	     * or its sources handled specially.
	     */
	    int keywd = ParseFindKeyword(line);
	    if (keywd != -1) {
		if (specType == _Path && parseKeywords[keywd].spec != _Path) {
		    Parse_Error(PARSE_FATAL, "Mismatched special targets", 0, 0);
		    return;
		}

		specType = parseKeywords[keywd].spec;
		tOp = parseKeywords[keywd].op;

		/*
		 * Certain special targets have special semantics:
		 *	.PATH		Have to set the dirSearchPath
		 *			variable too
		 *	.EXPORT		Doesn't really apply the
		 *			.EXPORT operator to its
		 *			sources, so we reset tOp.
		 *	.MAIN		Its sources are only used if
		 *			nothing has been specified to
		 *			create.
		 *	.DEFAULT    	Need to create a node to hang
		 *			commands on, but we don't want
		 *			it in the graph, nor do we want
		 *			it to be the Main Target, so we
		 *			create it, set OP_NOTMAIN and
		 *			add it to the list, setting
		 *			DEFAULT to the new node for
		 *			later use. We claim the node is
		 *	    	    	A transformation rule to make
		 *	    	    	life easier later, when we'll
		 *	    	    	use Make_HandleUse to actually
		 *	    	    	apply the .DEFAULT commands.
		 *	.BEGIN
		 *	.END
		 *	.INTERRUPT  	Are not to be considered the
		 *			main target.
		 *  	.NOTPARALLEL	Make only one target at a time.
		 *  	.SINGLESHELL	Create a shell for each command.
		 *  	.ORDER	    	Must set initial predecessor to NIL
		 */
		switch (specType) {
		    case _Path:
			if (paths == NULL) {
			    paths = Lst_Init(FALSE);
			}
			(void)Lst_AtEnd(paths, (ClientData)dirSearchPath);
			break;
		    case Export:
			tOp = 0;
			break;
		    case Main:
			if (!Lst_IsEmpty(create)) {
			    specType = Not;
			}
			break;
		    case Begin:
		    case End:
		    case Interrupt:
			gn = Targ_FindNode(line, TARG_CREATE);
			gn->type |= OP_NOTMAIN;
			(void)Lst_AtEnd(targets, (ClientData)gn);
			break;
		    case Default:
			gn = Targ_NewGN(".DEFAULT");
			gn->type |= (OP_NOTMAIN|OP_TRANSFORM);
			(void)Lst_AtEnd(targets, (ClientData)gn);
			DEFAULT = gn;
			break;
#ifdef unix
		    case NotParallel:
		    {
			extern int  maxJobs;

			maxJobs = 1;
			break;
		    }
#endif
		    case SingleShell:
			backwards = 1;
			break;
		    case Order:
			predecessor = NILGNODE;
			break;
		    default:
			break;
		}
	    } else if (strncmp (line, ".PATH", 5) == 0) {
		/*
		 * .PATH<suffix> has to be handled specially.
		 * Call on the suffix module to give us a path to
		 * modify.
		 */
		Lst 	path;

		specType = _Path;
		path = Suff_GetPath (&line[5]);
		if (path == NILLST) {
		    Parse_Error (PARSE_FATAL,
				 "Suffix '%s' not defined (yet)",
				 (unsigned long)&line[5], 0);
		    return;
		} else {
		    if (paths == (Lst)NULL) {
			paths = Lst_Init(FALSE);
		    }
		    (void)Lst_AtEnd(paths, (ClientData)path);
		}
	    }
	}

	/*
	 * Have word in line. Get or create its node and stick it at
	 * the end of the targets list
	 */
	if ((specType == Not) && (*line != '\0')) {
	    if (Dir_HasWildcards(line)) {
		/*
		 * Targets are to be sought only in the current directory,
		 * so create an empty path for the thing. Note we need to
		 * use Dir_Destroy in the destruction of the path as the
		 * Dir module could have added a directory to the path...
		 */
		Lst	    emptyPath = Lst_Init(FALSE);

		Dir_Expand(line, emptyPath, curTargs);

		Lst_Destroy(emptyPath, Dir_Destroy);
	    } else {
		/*
		 * No wildcards, but we want to avoid code duplication,
		 * so create a list with the word on it.
		 */
		(void)Lst_AtEnd(curTargs, (ClientData)line);
	    }

	    while(!Lst_IsEmpty(curTargs)) {
		char	*targName = (char *)Lst_DeQueue(curTargs);

		if (!Suff_IsTransform (targName)) {
		    gn = Targ_FindNode (targName, TARG_CREATE);
		} else {
		    gn = Suff_AddTransform (targName);
		}

		(void)Lst_AtEnd (targets, (ClientData)gn);
	    }
	} else if (specType == _Path && *line != '.' && *line != '\0') {
	    Parse_Error(PARSE_WARNING, "Extra target (%s) ignored", (unsigned long)line, 0);
	}

	*cp = savec;
	/*
	 * If it is a special type and not .PATH, it's the only target we
	 * allow on this line...
	 */
	if (specType != Not && specType != _Path) {
	    Boolean warn = FALSE;

	    while ((*cp != '!') && (*cp != ':') && *cp) {
		if (*cp != ' ' && *cp != '\t') {
		    warn = TRUE;
		}
		cp++;
	    }
	    if (warn) {
		Parse_Error(PARSE_WARNING, "Extra target ignored", 0, 0);
	    }
	} else {
	    while (*cp && isspace (*cp)) {
		cp++;
	    }
	}
	line = cp;
    } while ((*line != '!') && (*line != ':') && *line);

    /*
     * Don't need the list of target names anymore...
     */
    Lst_Destroy(curTargs, NOFREE);

    if (!Lst_IsEmpty(targets)) {
	switch(specType) {
	    default:
		Parse_Error(PARSE_WARNING, "Special and mundane targets don't mix. Mundane ones ignored", 0, 0);
		break;
	    case Default:
	    case Begin:
	    case End:
	    case Interrupt:
		/*
		 * These four create nodes on which to hang commands, so
		 * targets shouldn't be empty...
		 */
	    case Not:
		/*
		 * Nothing special here -- targets can be empty if it wants.
		 */
		break;
	}
    }

    /*
     * Have now parsed all the target names. Must parse the operator next. The
     * result is left in  op .
     */
    if (*cp == '!') {
	op = OP_FORCE;
    } else if (*cp == ':') {
	if (cp[1] == ':') {
	    op = OP_DOUBLEDEP;
	    cp++;
	} else {
	    op = OP_DEPENDS;
	}
    } else {
	Parse_Error (PARSE_FATAL, "Missing dependency operator", 0, 0);
	return;
    }

    cp++;			/* Advance beyond operator */

    Lst_ForEach (targets, ParseDoOp, (ClientData)op);

    /*
     * Get to the first source
     */
    while (*cp && isspace (*cp)) {
	cp++;
    }
    line = cp;

    /*
     * Several special targets take different actions if present with no
     * sources:
     *	a .SUFFIXES line with no sources clears out all old suffixes
     *	a .PRECIOUS line makes all targets precious
     *	a .IGNORE line ignores errors for all targets
     *	a .SILENT line creates silence when making all targets
     *	a .PATH removes all directories from the search path(s).
     *	a .NOEXPORT turns off exportation for all jobs.
     */
    if (!*line) {
	switch (specType) {
	    case Suffixes:
		Suff_ClearSuffixes ();
		break;
	    case Precious:
		allPrecious = TRUE;
		break;
	    case Ignore:
		ignoreErrors = TRUE;
		break;
	    case Silent:
		beSilent = TRUE;
		break;
	    case _Path:
		Lst_ForEach(paths, ParseClearPath, (ClientData)NULL);
		break;
	    case NoExport:
		noExport = TRUE;
		break;
	    default:
		break;
	}
    } else if (specType == MFlags) {
	/*
	 * Call on functions in main.c to deal with these arguments and
	 * set the initial character to a null-character so the loop to
	 * get sources won't get anything
	 */
	Main_ParseArgLine (line);
	*line = '\0';
    }
#ifdef unix
    else if (specType == Shell) {
	if (Job_ParseShell (line) != SUCCESS) {
	    Parse_Error (PARSE_FATAL, "improper shell specification", 0, 0);
	    return;
	}
	*line = '\0';
    } else if ((specType == NotParallel) || (specType == SingleShell)) {
	*line = '\0';
    }
#endif /* def unix */
    /*
     * NOW GO FOR THE SOURCES
     */
    if ((specType == Suffixes) || (specType == _Path) ||
	(specType == Includes) || (specType == Libs) ||
	(specType == Export)   || (specType == Null))
    {
	while (*line) {
	    /*
	     * If the target was one that doesn't take files as its sources
	     * but takes something like suffixes, we take each
	     * space-separated word on the line as a something and deal
	     * with it accordingly.
	     *
	     * If the target was .SUFFIXES, we take each source as a
	     * suffix and add it to the list of suffixes maintained by the
	     * Suff module.
	     *
	     * If the target was a .PATH, we add the source as a directory
	     * to search on the search path.
	     *
	     * If it was .INCLUDES, the source is taken to be the suffix of
	     * files which will be #included and whose search path should
	     * be present in the .INCLUDES variable.
	     *
	     * If it was .LIBS, the source is taken to be the suffix of
	     * files which are considered libraries and whose search path
	     * should be present in the .LIBS variable.
	     *
	     * If it was .EXPORT, the source is the location of the export
	     * server and is passed to the Rmt module as such.
	     *
	     * If it was .NULL, the source is the suffix to use when a file
	     * has no valid suffix.
	     */
	    char  savec;
	    while (*cp && !isspace (*cp)) {
		cp++;
	    }
	    savec = *cp;
	    *cp = '\0';
	    switch (specType) {
		case Suffixes:
		    Suff_AddSuffix (line);
		    break;
		case _Path:
		    Lst_ForEach(paths, ParseAddDir, (ClientData)line);
		    break;
		case Includes:
		    Suff_AddInclude (line);
		    break;
		case Libs:
		    Suff_AddLib (line);
		    break;
#ifdef unix
		case Export:
		    Rmt_AddServer (line);
		    break;
#endif /* ifdef unix */
		case Null:
		    Suff_SetNull (line);
		    break;
		default:
		    break;
	    }
	    *cp = savec;
	    if (savec != '\0') {
		cp++;
	    }
	    while (*cp && isspace (*cp)) {
		cp++;
	    }
	    line = cp;
	}
	if (paths) {
	    Lst_Destroy(paths, NOFREE);
	}
    } else {
	while (*line) {
	    /*
	     * The targets take real sources, so we must beware of archive
	     * specifications (i.e. things with left parentheses in them)
	     * and handle them accordingly.
	     */
	    while (*cp && !isspace (*cp)) {
		if ((*cp == '(') && (cp > line) && (cp[-1] != '$')) {
		    /*
		     * Only stop for a left parenthesis if it isn't at the
		     * start of a word (that'll be for variable changes
		     * later) and isn't preceded by a dollar sign (a dynamic
		     * source).
		     */
		    break;
		} else {
		    cp++;
		}
	    }

	    if (*cp == '(') {
		GNode	  *gn;

		sources = Lst_Init (FALSE);
#ifdef unix
		if (Arch_ParseArchive (&line, sources, VAR_CMD) != SUCCESS) {
		    Parse_Error (PARSE_FATAL,
				 "Error in source archive spec \"%s\"",
				   (unsigned long)line, 0);
		    return;
		}
#endif /* def unix */
		while (!Lst_IsEmpty (sources)) {
		    gn = (GNode *) Lst_DeQueue (sources);
		    ParseDoSrc (tOp, gn->name);
		}
		Lst_Destroy (sources, NOFREE);
		cp = line;
	    } else {
		if (*cp) {
		    *cp = '\0';
		    cp += 1;
		}

		ParseDoSrc (tOp, line);
	    }
	    while (*cp && isspace (*cp)) {
		cp++;
	    }
	    line = cp;
	}
    }

    if (mainNode == NILGNODE) {
	/*
	 * If we have yet to decide on a main target to make, in the
	 * absence of any user input, we want the first target on
	 * the first dependency line that is actually a real target
	 * (i.e. isn't a .USE or .EXEC rule) to be made.
	 * For compatibility with other makes we also don't use
	 * targets that start with a dot as default main targets.
	 */
	Lst_ForEach (targets, ParseFindMain, (ClientData)0);
    }

}

/*-
 *---------------------------------------------------------------------
 * Parse_IsVar  --
 *	Return TRUE if the passed line is a variable assignment. A variable
 *	assignment consists of a single word followed by optional whitespace
 *	followed by either a += or an = operator.
 *	This function is used both by the Parse_File function and main when
 *	parsing the command-line arguments.
 *
 * Results:
 *	TRUE if it is. FALSE if it ain't
 *
 * Side Effects:
 *	none
 *---------------------------------------------------------------------
 */
Boolean
Parse_IsVar (register char *line)
{
    register Boolean wasSpace = FALSE;	/* set TRUE if found a space */
    register Boolean haveName = FALSE;	/* Set TRUE if have a variable name */

    /*
     * Skip to variable name
     */
    while ((*line == ' ') || (*line == '\t')) {
	line++;
    }

    while (*line != '=') {
	if (*line == '\0') {
	    /*
	     * end-of-line -- can't be a variable assignment.
	     */
	    return (FALSE);
	} else if ((*line == ' ') || (*line == '\t')) {
	    /*
	     * there can be as much white space as desired so long as there is
	     * only one word before the operator
	     */
	    wasSpace = TRUE;
	} else if (wasSpace && haveName) {
	    /*
	     * Stop when an = operator is found.
	     */
	    if ((*line == '+') || (*line == ':') || (*line == '?') ||
		(*line == '!')) {
		break;
	    }

	    /*
	     * This is the start of another word, so not assignment.
	     */
	    return (FALSE);
	} else {
	    haveName = TRUE;
	    wasSpace = FALSE;
	}
	line++;
    }

    /*
     * A final check: if we stopped on a +, ?, ! or :, the next character must
     * be an = or it ain't a valid assignment
     */
    if (((*line == '+') ||
	 (*line == '?') ||
	 (*line == ':') ||
	 (*line == '!')) &&
	(line[1] != '='))
    {
	return (FALSE);
    } else {
	return (haveName);
    }
}

/*-
 *---------------------------------------------------------------------
 * Parse_DoVar  --
 *	Take the variable assignment in the passed line and do it in the
 *	global context.
 *
 *      line is guaranteed to be a variable assignment.  This reduces error
 *      checks
 *
 *      ctxt is the context in which to do the assignment
 *
 *	Note: There is a lexical ambiguity with assignment modifier characters
 *	in variable names. This routine interprets the character before the =
 *	as a modifier. Therefore, an assignment like
 *	    C++=/usr/bin/CC
 *	is interpreted as "C+ +=" instead of "C++ =".
 *
 * Results:
 *	none
 *
 * Side Effects:
 *	the variable structure of the given variable name is altered in the
 *	global context.
 *---------------------------------------------------------------------
 */
void
Parse_DoVar (char* line0, GNode *ctxt)
{
    char   *line = line0; /* to avoid warning about use of var after vfork() */
    char   *cp;	/* pointer into line */
    enum {
	VAR_SUBST, VAR_APPEND, VAR_SHELL, VAR_NORMAL
    }	    	    type;   	/* Type of assignment */
    char            *opc;	/* ptr to operator character to
				 * null-terminate the variable name */

    /*
     * Skip to variable name
     */
    while ((*line == ' ') || (*line == '\t')) {
	line++;
    }

    /*
     * Skip to operator character, nulling out whitespace as we go
     */
    for (cp = line + 1; *cp != '='; cp++) {
	if (isspace (*cp)) {
	    *cp = '\0';
	}
    }
    opc = cp-1;		/* operator is the previous character */
    *cp++ = '\0';	/* nuke the = */

    /*
     * Check operator type
     */
    switch (*opc) {
	case '+':
	    type = VAR_APPEND;
	    *opc = '\0';
	    break;

	case '?':
	    /*
	     * If the variable already has a value, we don't do anything.
	     */
	    *opc = '\0';
	    if (Var_Exists(line, ctxt)) {
		return;
	    } else {
		type = VAR_NORMAL;
	    }
	    break;

	case ':':
	    type = VAR_SUBST;
	    *opc = '\0';
	    break;

	case '!':
	    type = VAR_SHELL;
	    *opc = '\0';
	    break;

	default:
	    type = VAR_NORMAL;
	    break;
    }

    while (isspace (*cp)) {
	cp++;
    }

    if (type == VAR_APPEND) {
	Var_Append (line, cp, ctxt);
    } else if (type == VAR_SUBST) {
	/*
	 * Allow variables in the old value to be undefined, but leave their
	 * invocation alone -- this is done by forcing oldVars to be false.
	 * XXX: This can cause recursive variables, but that's not hard to do,
	 * and this allows someone to do something like
	 *
	 *  CFLAGS = $(.INCLUDES)
	 *  CFLAGS := -I.. $(CFLAGS)
	 *
	 * And not get an error.
	 */
	Boolean	  oldOldVars = oldVars;

	oldVars = FALSE;
	cp = Var_Subst(cp, ctxt, FALSE);
	oldVars = oldOldVars;

	Var_Set(line, cp, ctxt);
	free(cp);
    } else if (type == VAR_SHELL) {

#if defined(unix) || defined(_LINUX)
	char	result[BUFSIZ];	/* Result of command */
	char	*args[4];   	/* Args for invoking the shell */
	Boolean	freeCmd;    	/* TRUE if the command needs to be freed, i.e.
				 * if any variable expansion was performed */
	int 	fds[2];	    	/* Pipe streams */
	int 	cpid;	    	/* Child PID */
	int 	pid;	    	/* PID from wait() */

	/*
	 * Set up arguments for shell
	 */
	args[0] = "sh";
	args[1] = "-c";
	if (strchr(cp, '$') != (char *)NULL) {
	    /*
	     * There's a dollar sign in the command, so perform variable
	     * expansion on the whole thing. The resulting string will need
	     * freeing when we're done, so set freeCmd to TRUE.
	     */
	    args[2] = Var_Subst(cp, VAR_CMD, TRUE);
	    freeCmd = TRUE;
	} else {
	    args[2] = cp;
	    freeCmd = FALSE;
	}
	args[3] = (char *)NULL;
	/*
	 * Open a pipe for fetching its output
	 */
	pipe(fds);

	/*
	 * Fork
	 */
	cpid = vfork();
	if (cpid == 0) {
	    /*
	     * Close input side of pipe
	     */
	    close(fds[0]);

	    /*
	     * Duplicate the output stream to the shell's output, then
	     * shut the extra thing down. Note we don't fetch the error
	     * stream...why not? Why?
	     */
	    dup2(fds[1], 1);
	    close(fds[1]);

	    execv("/bin/sh", args);
	    _exit(1);
	} else if (cpid < 0) {
	    /*
	     * Couldn't fork -- tell the user and make the variable null
	     */
	    Parse_Error(PARSE_WARNING, "Couldn't exec \"%s\"",
			    	    	(unsigned long)cp, 0);
	    Var_Set(line, "", ctxt);
	} else {
	    int	status;
	    int cc;

	    /*
	     * No need for the writing half
	     */
	    close(fds[1]);

	    /*
	     * Wait for the process to exit.
	     *
	     * XXX: If the child writes more than a pipe's worth, we will
	     * deadlock.
	     */
	    while(((pid = wait(&status)) != cpid) && (pid >= 0)) {
		;
	    }

	    /*
	     * Read all the characters the child wrote.
	     */
	    cc = read(fds[0], result, sizeof(result));

	    if (cc < 0) {
		/*
		 * Couldn't read the child's output -- tell the user and
		 * set the variable to null
		 */
		Parse_Error(PARSE_WARNING, "Couldn't read shell's output",0,0);
		cc = 0;
	    }

	    if (status) {
		/*
		 * Child returned an error -- tell the user but still use
		 * the result.
		 */
		Parse_Error(PARSE_WARNING, "\"%s\" returned non-zero",
			    	    	    (unsigned long)cp, 0);
	    }
	    /*
	     * Null-terminate the result, convert newlines to spaces and
	     * install it in the variable.
	     */
	    result[cc] = '\0';
	    cp = &result[cc] - 1;

	    if (*cp == '\n') {
		/*
		 * A final newline is just stripped
		 */
		*cp-- = '\0';
	    }
	    while (cp >= result) {
		if (*cp == '\n') {
		    *cp = ' ';
		}
		cp--;
	    }
	    Var_Set(line, result, ctxt);

	    /*
	     * Close the input side of the pipe.
	     */
	    close(fds[0]);
	}
	if (freeCmd) {
	    free(args[2]);
	}
#elif defined(_WIN32)
	    char               *cmdLine;
	    STARTUPINFO         startupInfo = {0};
	    PROCESS_INFORMATION procInfo;
	    unsigned long       nToRead;
	    HANDLE              cmdRead, cmdWrite;
	    SECURITY_ATTRIBUTES sAttr =
	                             {sizeof(SECURITY_ATTRIBUTES), NULL, TRUE};

	    if (strchr(cp, '$') != NULL) {
		char *tmpPtr;
	    /*
	     * There's a dollar sign in the command, so perform variable
	     * expansion on the whole thing. The resulting string will need
	     * freeing when we're done, so set freeCmd to TRUE.
	     */
		tmpPtr  = Var_Subst(cp, VAR_CMD, TRUE);
		cmdLine = (char *) malloc(strlen("cmd /c %s") +
					  strlen(tmpPtr));

		/* print the command shell evocation and resulting command
		 * and variable substitution to a cmdLine useable by
		 * CreateProcess.  Note that for compatibility with DOS pmake
		 * which sometimes required a '`' before shell commands, we
		 * ignore the '`' if it's present (we also do this if there
		 * was no variable substitution -- ie, in the "else" clause */

		sprintf(cmdLine, "cmd /c %s",
			(tmpPtr[0] == '`') ? tmpPtr + 1 : tmpPtr);
		free(tmpPtr);
	    } else {
		cmdLine = (char *) malloc(20 + strlen(cp));
		sprintf(cmdLine, "cmd /c %s", (cp[0] == '`') ? cp + 1 : cp);
	    }

	    if (noExecute) {
		char *ptr = strchr(cmdLine, '/');
		ptr += 2;

		printf("VARIABLE \"%s\" != %s\n", line, ptr);
	    }

	    if (!CreatePipe(&cmdRead, &cmdWrite, &sAttr, 0)) {
		ErrorMessage("pmake");
		ExitProcess(1);
	    }

	    startupInfo.cb          = sizeof(STARTUPINFO);
	    startupInfo.lpReserved  = NULL;
	    startupInfo.lpDesktop   = NULL;
	    startupInfo.lpTitle     = NULL;
	    startupInfo.dwFlags     = STARTF_USESTDHANDLES;
	    startupInfo.cbReserved2 = 0;
	    startupInfo.lpReserved2 = 0;
	    startupInfo.hStdInput   = GetStdHandle(STD_INPUT_HANDLE);
	    startupInfo.hStdOutput  = cmdWrite;
	    startupInfo.hStdError   = cmdWrite;

	    if (!CreateProcess(NULL, cmdLine, NULL, NULL, TRUE,
			       NORMAL_PRIORITY_CLASS, NULL, NULL, &startupInfo,
			       &procInfo)) {
		ErrorMessage("pmake: Failed to spawn shell");
		ExitProcess(1);
	    }

	    (void) CloseHandle(cmdWrite); /* VERY important.  else ReadFile on
					   * input buffer could block forever*/

	    switch(WaitForSingleObject(procInfo.hProcess, INFINITE)) {
	        case WAIT_FAILED :
		    ErrorMessage("pmake: Failed to wait for shell");
		    (void) CloseHandle(procInfo.hProcess);
		    (void) CloseHandle(procInfo.hThread);
		    ExitProcess(1);

	        case WAIT_TIMEOUT :
		    ErrorMessage("pmake: Process wait timed out");
		    (void) CloseHandle(procInfo.hProcess);
		    (void) CloseHandle(procInfo.hThread);
		    ExitProcess(1);

	        case WAIT_OBJECT_0 :
		    (void) CloseHandle(procInfo.hProcess);
		    (void) CloseHandle(procInfo.hThread);

		    /* figure out how many bytes were written */
		    if (!PeekNamedPipe(cmdRead, NULL, 0, NULL, &nToRead,
				       NULL)) {
			ErrorMessage("pmake");

			/*
			 * if the pipe was ended before we read anything, don't
			 * die
			 */
			if (GetLastError() != ERROR_BROKEN_PIPE) {
			    ExitProcess(1);
			}
		    } else {
			char          *buf;
			unsigned long nRead;

			buf = (char *) malloc(nToRead + 1);

			if (!ReadFile(cmdRead, buf, nToRead, &nRead, NULL)) {
			    ErrorMessage("pmake");
			    ExitProcess(1);
			}

			if ((nRead < nToRead) && DEBUG(JOB)) {
			    printf("nToRead was %u.  nRead was only %u\n",
				   nToRead, nRead);
			}

			/*
			 * Null-terminate the result, convert newlines to
			 * spaces and install it in the variable.
			 */

			buf[nRead] = '\0';
			cp = &buf[nRead] - 1;

			if (*cp == '\n') {
                            /*
			     * A final newline is just stripped
			     */
			    *cp-- = '\0';
			    if (*cp == '\r') {
				*cp-- = '\0';
			    }
			}
			while (cp >= buf) {
			    if (*cp == '\n') {
				*cp = ' ';
			    }
			    cp--;
			}
			Var_Set(line, buf, ctxt);

			(void) CloseHandle(cmdRead);
			free(cmdLine);
		    }
	    }

#else /* _MSDOS */

#    define STDOUT 1

#    if defined(__HIGHC__)
       char *filename;
#    else
       char filename[13] = "TMPXXXXXX";
#    endif /* defined(__HIGHC__) */

       char *cmd;
       Boolean	freeCmd;    	/* TRUE if the command needs to be freed, i.e.
				 * if any variable expansion was performed */

       int cpid;
       int  fptr, oldstdout;
       /*
	* Set up arguments for shell
	*/
	if (strchr(cp, '$') != (char *)NULL)
	{
	    /*
	     * There's a dollar sign in the command, so perform variable
	     * expansion on the whole thing. The resulting string will need
	     * freeing when we're done, so set freeCmd to TRUE.
	     */
	    cmd = Var_Subst(cp, VAR_CMD, TRUE);
	    freeCmd = TRUE;
	}
	else
	{
	    cmd = cp;
	    freeCmd = FALSE;
	}

       /* this charater tells us that we must goes through the
	* command interpreter, so use the system call and hope it works
	*/
       	if (cp[0] == '`')
	{
	    char    *cmd2;
#    if defined(__HIGHC__)
	    char    tmpname[13];

	    strcpy(tmpname, "TMXXXXXX");
	    filename = mktemp(tmpname);
#    else
	    mktemp(filename);
#    endif /* defined(__HIGHC__) */

	    cmd++;  /* skip the back qute */
	    MallocCheck(cmd2, strlen(cmd)+15);
	    strcpy(cmd2, cmd);
	    cp = cmd2;
	    while(*cp++);
	    --cp;
	    strcpy(cp, " >");
	    cp += 2;
	    strcpy(cp, filename);
	    /*
	     * system allows us to do DOS commands and redirection
	     * of stdout
	     */
	    cpid = system(cmd2);
	    free(cmd2);
	} else {
	    /*
	     * spawn a process to execute the next command and wait for it to
	     * finish before continuing
	     */
#    if defined(__HIGHC__)
	    char tempname[13] = "";

	    strcpy(tempname, "TMXXXXXX");
	    filename = mktemp(tempname);
#    else
	    mktemp(filename);
#    endif /* defined(__HIGHC__) */

	    fptr = open(filename, O_CREAT | O_RDWR, S_IREAD | S_IWRITE);
	    if (!fptr) {
		Fatal("File Open Error", 0, 0);
    	    }
	    oldstdout = dup(STDOUT);	/* save old STDOUT descriptor */
	    dup2(fptr, STDOUT);	        /* redirect STDOUT to our file */
	    close(fptr);

	    cp = cmd;
	    while(*cp && !isspace(*cp++));
	    /* if the command has arguments, then to get just the command
	     * overwrite the space with a null '\0'
	     */
	    if (*cp) {
		--cp;
		*cp++ = '\0';
    	    }
	    cpid = spawnlp(P_WAIT, cmd, cmd, *cp ? cp : "", NULL);

	    dup2(oldstdout, STDOUT);
	    close(oldstdout);
	    /*
	     * i need to redirect the output of the process to a file so that
	     * i can get at the information of the spawned process, when was
	     * DOS ever going to get those pipes...sigh, just a pipe dream...
	     */
	}
        if (cpid != 0) {
	    Fatal("Child Process Failed: %d", cpid, 0);
    	}
        Var_SetFromFile(line, filename, ctxt);
        unlink(filename);


    	if (freeCmd) {
	    free(cmd);
    	}
#endif /* defined(unix) */

    } else {
	/*
	 * Normal assignment -- just do it.
	 */
	Var_Set (line, cp, ctxt);
    }
}

#if defined(_WIN32)

/***********************************************************************
 *				ParseRunCommand
 ***********************************************************************
 *
 * SYNOPSIS:	     Runs command and stores its output in commandOutput
 * CALLED BY:	     ParseDoBackTick
 * RETURN:	     TRUE if the command returns 0, FALSE otherwise
 * SIDE EFFECTS:     mallocs memory for commandOutput and spawns a
 *                   process
 *
 * STRATEGY:	     Spawn the command using CreateProcess and catch its
 *                   output using a pipe.
 *
 * REVISION HISTORY:
 *	Name	        Date		Description
 *	----	        ----		-----------
 *	tbradley	10/21/96   	Initial Revision
 *
 ***********************************************************************/
static Boolean
ParseRunCommand (char *command, char **commandOutput)
{
    SECURITY_ATTRIBUTES secAttrs  = {sizeof(SECURITY_ATTRIBUTES), NULL, TRUE};
    HANDLE              outHandle, inHandle;
    DWORD               exitCode;

    if (!CreatePipe(&inHandle, &outHandle, &secAttrs, 0)) {
	ErrorMessage("pmake");
	return FALSE;
    } else {
	STARTUPINFO         startInfo = {0};
	PROCESS_INFORMATION procInfo  = {INVALID_HANDLE_VALUE};
	DWORD               nToRead;

	startInfo.cb         = sizeof(startInfo);
	startInfo.dwFlags    = STARTF_USESTDHANDLES;
	startInfo.hStdInput  = GetStdHandle(STD_INPUT_HANDLE);
	startInfo.hStdOutput = outHandle;
	startInfo.hStdError  = outHandle;

	if (!CreateProcess(NULL, command, NULL, NULL, TRUE, 0, NULL, NULL,
			   &startInfo, &procInfo)) {
	    ErrorMessage("pmake");
	    return FALSE;
	}
	CloseHandle(outHandle);

	switch(WaitForSingleObject(procInfo.hProcess, INFINITE)) {
	case WAIT_FAILED:
	    ErrorMessage("pmake: Failed to wait for shell");
	    (void) CloseHandle(procInfo.hProcess);
	    (void) CloseHandle(procInfo.hThread);
	    return FALSE;

	case WAIT_TIMEOUT :
	    ErrorMessage("pmake: Process wait timed out");
	    (void) CloseHandle(procInfo.hProcess);
	    (void) CloseHandle(procInfo.hThread);
	    return FALSE;

	case WAIT_OBJECT_0 :
	    if (!GetExitCodeProcess(procInfo.hProcess, &exitCode)) {
		ErrorMessage("pmake");
		exitCode = 1;
	    }
	    (void) CloseHandle(procInfo.hProcess);
	    (void) CloseHandle(procInfo.hThread);
	}

	/* figure out how many bytes were written */
	if (!PeekNamedPipe(inHandle, NULL, 3, NULL, &nToRead, NULL)) {
	    ErrorMessage("pmake");
	    return FALSE;
	} else {
	    DWORD  nRead;
	    char  *cp;

	    *commandOutput = (char *) malloc(nToRead + 1);

	    if (!ReadFile(inHandle, *commandOutput, nToRead, &nRead, NULL)) {
		ErrorMessage("pmake");
		free(commandOutput);

		return FALSE;
	    }
	    (void)CloseHandle(inHandle);

	    /*
	     * Null-terminate the result and convert newlines to spaces.
	     */

	    (*commandOutput)[nRead] = '\0';
	    cp = &(*commandOutput)[nRead] - 1;

	    if (*cp == '\n') {
		/*
		 * A final newline is just stripped
		 */
		*cp-- = '\0';
		if (*cp == '\r') {
		    *cp-- = '\0';
		}
	    }
	    while (cp >= *commandOutput) {
		if (*cp == '\n' || *cp == '\r') {
		    *cp = ' ';
		}
		cp--;
	    }
	}
    }

    return (exitCode == 0) ? TRUE : FALSE;
}	/* End of ParseRunCommand.	*/


/***********************************************************************
 *				ParseDoBackTick
 ***********************************************************************
 *
 * SYNOPSIS:	      If there's a ` in cmd then execute the command in
 *                    between the `` and replace the command with
 *                    the string it returns.
 * CALLED BY:	      JobPrintCommand
 * RETURN:	      TRUE if successfully parsed the string and there were
 *                    backticks.
 * SIDE EFFECTS:      reallocs cmd
 *
 * STRATEGY:	      Look through the string and see if there's any `.
 *                    If there is, then parse the string up to the 2nd
 *                    ` and grab execute the command contained therein.
 *                    If there are no ``, then simply return TRUE.
 *
 * REVISION HISTORY:
 *	Name	        Date		Description
 *	----	        ----		-----------
 *	tbradley	10/18/96   	Initial Revision
 *
 ***********************************************************************/
Boolean
Parse_DoBackTick (char **cmd)
{
    char  *command       = *cmd;
    int    commandLength = 0;
    char  *commandOutput, *tempStr;
    /*
     * first find the beginning of the command.
     */
    while ((*command != '\0') && (*command != '`')) { command++; }

    /*
     * next find out how long the command is.
     */
    if (*command != '\0') {
	/*
	 * there was a backtick.
	 */
	commandLength++;
	while(*(command + commandLength) != '\0') {
	    if (*(command + commandLength) == '`') {
		break;
	    }
	    commandLength++;
	}
    } else {
	/*
	 * there were no backticks.
	 */
	return FALSE;
    }

    /*
     * If we got a first backtick but not a second one...
     */
    if (*command == '`' && *(command + commandLength) == '\0') {
	Parse_Error(PARSE_FATAL, "Unmatched `");
	return FALSE;
    }
    *(command + commandLength) = '\0';
    if (DEBUG(PARSE)) {
	printf("Backticked command == %s\n", command + 1);
    }

    if (!ParseRunCommand(command + 1, &commandOutput)) {
	fprintf(stderr, "pmake: Execution of %s` failed. Stop.\n", command);
	return FALSE;
    }
    if (DEBUG(PARSE)) {
	printf("%s` yielded \"%s\"\n", command, commandOutput);
    }
    *(command + commandLength) = '`';

    tempStr = (char *) malloc(strlen(commandOutput) + strlen(*cmd));
    if (tempStr == NULL) {
	fprintf(stderr, "pmake: Out of memory\n");
	ExitProcess(1);
    } else {
	int i = 0;
	int j = 0;

	/*
	 * Now replace the `command` in the string with the command's
	 * output.
	 */

	/*
	 * Copy the chars from cmd to tempStr until we see the first `.
	 */
	while((*cmd)[i] != '`') {
	    tempStr[i] = (*cmd)[i];
	    i++;
	}

	/*
	 * Now copy over the chars from the commandOutput.
	 */
	while((unsigned) j < strlen(commandOutput)) {
	    tempStr[i] = commandOutput[j];
	    i++;
	    j++;
	}

	/*
	 * Finally, copy everything left at the end of the string to
	 * tempStr;
	 */
	while((*cmd)[i - j + commandLength + 1] != '\0') {
	    tempStr[i] = (*cmd)[i - j + commandLength + 1];
	    i++;
	}

	tempStr[i] = '\0';
	/*
	 * Now set cmd = tempStr
	 */
	*cmd = tempStr;
	if (DEBUG(PARSE)) {
	    printf("Command line after parsing `s is %s\n", *cmd);
	}
    }

    return TRUE;
}	/* End of ParseDoBackTick.	*/
#endif /* defined(_WIN32) */

/*-
 *---------------------------------------------------------------------
 * ParseAddCmd  --
 *	Lst_ForEach function to add a command line to all targets
 *
 * Results:
 *	Always 0
 *
 * Arguments:
 *      GNode *gn  : The node to which the command is to be added
 *      char  *cmd : The command to add -- NULL is just disable transforms
 *
 * Side Effects:
 *	A new element is added to the commands list of the node.
 *---------------------------------------------------------------------
 */
static int
ParseAddCmd (GNode *gn, char *cmd)
{
    if (gn->type & OP_HAS_COMMANDS) {
	Parse_Error(PARSE_WARNING, "Extra command line for \"%s\" ignored",
		    (unsigned long)gn->name, 0);
    } else if (cmd != NULL) {
	(void)Lst_AtEnd (gn->commands, (ClientData)cmd);
    } else {
	gn->type |= OP_EMPTY_CMD;
    }

    return (0);
}

/*-
 *-----------------------------------------------------------------------
 * ParseHasCommands --
 *	Callback procedure for Parse_File when destroying the list of
 *	targets on the last dependency line. Marks a target as already
 *	having commands if it does, to keep from having shell commands
 *	on multiple dependency lines.
 *
 * Results:
 *	Always 0.
 *
 * Side Effects:
 *	OP_HAS_COMMANDS may be set for the target.
 *
 *-----------------------------------------------------------------------
 */
static int
ParseHasCommands(GNode *gn)
{
    if (!OP_NO_CMDS(gn)) {
	gn->type |= OP_HAS_COMMANDS;
    }
    return(0);
}

/*-
 *-----------------------------------------------------------------------
 * Parse_AddIncludeDir --
 *	Add a directory to the path searched for included makefiles
 *	bracketed by double-quotes. Used by functions in main.c
 *
 * Results:
 *	None.
 *
 * Arguments:
 *      char *dir : The name of the directory to add
 *
 * Side Effects:
 *	The directory is appended to the list.
 *
 *-----------------------------------------------------------------------
 */
void
Parse_AddIncludeDir (char *dir)
{
    Dir_AddDir (parseIncPath, dir);
}


#if defined(_WIN32) || defined(_LINUX)
/***********************************************************************
 *		ParsePrintList
 ***********************************************************************
 *
 * SYNOPSIS:	       prints out each datum of each list element of a
 *                     Lst
 * CALLED BY:	       only by ParseDoInclude via Lst_ForEach
 * RETURN:	       0 so that Lst_ForEach keeps going
 *
 * STRATEGY:	       just print the datum passed in by Lst_ForEach
 *
 * REVISION HISTORY:
 *	Name		Date		Description
 *	----		----		-----------
 *	tbradley	3/14/97   	Initial Revision
 *
 ***********************************************************************/
static int
ParsePrintList (Path *path, void *unused)
{
    printf("\t\t%s\n", path->name);
    return 0;
}	/* End of ParsePrintList.	*/
#endif /* defined(_WIN32) */

/*-
 *---------------------------------------------------------------------
 * ParseDoInclude  --
 *	Push to another file.
 *
 *	The input is the line minus the #include. A file spec is a string
 *	enclosed in <> or "". The former is looked for only in sysIncPath.
 *	The latter in . and the directories specified by -I command line
 *	options
 *
 * Results:
 *	None
 *
 * Side Effects:
 *	A structure is added to the includes Lst and readProc, lineno,
 *	fname and curFILE are altered for the new file
 *---------------------------------------------------------------------
 */
static void
ParseDoInclude (char *file)
{
    char          *fullname;	/* full pathname of file */
    IFile         *oldFile;	/* state associated with current file */
    /*Lst           path;*/    	/* the path to use to find the file */
    char          endc;	    	/* the character which ends the file spec */
    char          *cp;		/* current position in file spec */
    Boolean 	  isSystem; 	/* TRUE if makefile is a system makefile */

    /*
     * Skip to delimiter character so we know where to look
     */
    while ((*file == ' ') || (*file == '\t')) {
	file++;
    }

    if ((*file != '"') && (*file != '<')) {
	/*
	 * XXX: Should give some sort of error message, I suppose, but because
	 * # is used for both comments and directives, we can't be sure if
	 * the thing might not just be a comment, so we just return...
	 */
	return;
    }

    /*
     * Set the search path on which to find the include file based on the
     * characters which bracket its name. Angle-brackets imply it's
     * a system Makefile while double-quotes imply it's a user makefile
     */
    if (*file == '<') {
	isSystem = TRUE;
	endc = '>';
    } else {
	isSystem = FALSE;
	endc = '"';
    }

    /*
     * Skip to matching delimiter
     */
    for (cp = ++file; *cp && *cp != endc; cp++) {
	continue;
    }

    if (*cp != endc) {
	Parse_Error (PARSE_FATAL,
		     "Unclosed %cinclude filename. '%c' expected",
		     SPECIAL_CHAR, endc);
	return;
    }
    *cp = '\0';

    /*
     * Substitute for any variables in the file name before trying to
     * find the thing.
     */
    file = Var_Subst (file, VAR_CMD, FALSE);

    /*
     * I'm going to consider this debug output to be part of the make
     * module since it's the one that actually calls this function.
     */
    if (DEBUG(MAKE)) {
	char delim1 = isSystem ? '<' : '"';
	char delim2 = isSystem ? '>' : '"';

	printf("%s: include %c%s%c\n", fname, delim1, file, delim2);
    }

    /*
     * Now we know the file's name and its search path, we attempt to
     * find the durn thing. A return of NULL indicates the file don't
     * exist.
     */

#if defined(_WIN32)
    /*
     * if the path is fully qualified, then just include the damn thing
     */
    if (file[1] == ':' || IS_PATHSEP(file[0])) {
	fullname = Str_New(file);
	/*
	 * XXX see if the file exists?
	 */
    } else
#endif /* defined (_WIN32) */

    if (!isSystem) {
	/*
	 * Include files contained in double-quotes are first searched for
	 * relative to the including file's location. We don't want to
	 * cd there, of course, so we just tack on the old file's
	 * leading path components and call Dir_FindFile to see if
	 * we can locate the beast.
	 */
	char	  *prefEnd;

	prefEnd = Var_LastPathSep (fname);
	if (prefEnd != NULL) {
	    char  	*newName;
	    /*
	     * Just for safety, put back the same type of slash
	     * that we're about to mess with.  Under Unix, of course,
	     * this is kind of silly, but it won't hurt.
	     */
	    char	originalSlash = *prefEnd;

	    *prefEnd = '\0';
	    newName = Str_Concat (fname, file, STR_ADDSLASH);

	    if (DEBUG(MAKE) && !Lst_IsEmpty(parseIncPath)) {
		printf("\tSearching in -I search Paths:\n");
		Lst_ForEach(parseIncPath, ParsePrintList, NULL);
	    }
	    fullname = Dir_FindFile (newName, parseIncPath);

	    if (fullname == NULL) {
		if (DEBUG(MAKE) && !Lst_IsEmpty(dirSearchPath)) {
		    printf("\tSearching in .Path's:\n");
		    Lst_ForEach(dirSearchPath, ParsePrintList, NULL);
		}
		fullname = Dir_FindFile(newName, dirSearchPath);
	    }

	    free (newName);
	    *prefEnd = originalSlash;
	} else {
	    fullname = NULL;
	}
    } else {
	fullname = NULL;
    }

    if (fullname == NULL) {
	/*
	 * It's a System makefile or it wasn't found in same directory as
	 * including makefile. Search for it first on the -I search path,
	 * then on the .PATH search path, if not found in a -I directory.
	 * XXX: Suffix specific?
	 */
	if (DEBUG(MAKE) && !Lst_IsEmpty(parseIncPath)) {
	    printf("\tSearching in -I search paths:\n");
	    Lst_ForEach(parseIncPath, ParsePrintList, NULL);
	}
	fullname = Dir_FindFile (file, parseIncPath);

	if (fullname == NULL) {
	    if (DEBUG(MAKE) && !Lst_IsEmpty(dirSearchPath)) {
		printf("\tSearching in .PATH's:\n");
		Lst_ForEach(dirSearchPath, ParsePrintList, NULL);
	    }
	    fullname = Dir_FindFile(file, dirSearchPath);
	}
    }

    if (fullname == NULL) {
	/*
	 * Still haven't found the makefile. Look for it on the system
	 * path as a last resort.
	 */
	if (DEBUG(MAKE) && !Lst_IsEmpty(sysIncPath)) {
	    printf("\tSearching in System Include Paths:\n");
	    Lst_ForEach(sysIncPath, ParsePrintList, NULL);
	}
	fullname = Dir_FindFile(file, sysIncPath);
    }

    if (fullname == NULL) {
	*cp = endc;
	Parse_Error (PARSE_FATAL, "Could not find %s", (unsigned long)file, 0);
	return;
    }

    if (DEBUG(MAKE)) {
	printf("\tFound %s as\n"
	       "\t      %s\n\n", file, fullname);
    }

    /*
     * Once we find the absolute path to the file, we get to save all the
     * state from the current file before we can start reading this
     * include file. The state is stored in an IFile structure which
     * is placed on a list with other IFile structures. The list makes
     * a very nice stack to track how we got here...
     */
    MallocCheck (oldFile, sizeof (IFile));
    oldFile->fname = fname;

    oldFile->F = curFILE;
    oldFile->lineno = lineno;

    (void) Lst_AtFront (includes, (ClientData)oldFile);

    /*
     * Once the previous state has been saved, we can get down to reading
     * the new file. We set up the name of the file to be the absolute
     * name of the include file so error messages refer to the right
     * place. Naturally enough, we start reading at line number 0.
     */
    fname = fullname;
    lineno = 0;

    curFILE = fopen (fullname, "r");
    if (curFILE == NULL) {
	Parse_Error (PARSE_FATAL, "Cannot open %s", fullname);
	/*
	 * Pop to previous file
	 */
	(void) ParseEOF();
    }
}

/*-
 *---------------------------------------------------------------------
 * ParseEOF  --
 *	Called when EOF is reached in the current file. If we were reading
 *	an include file, the includes stack is popped and things set up
 *	to go back to reading the previous file at the previous location.
 *
 * Results:
 *	CONTINUE if there's more to do. DONE if not.
 *
 * Side Effects:
 *	The old curFILE, is closed. The includes list is shortened.
 *	lineno, curFILE, and fname are changed if CONTINUE is returned.
 *---------------------------------------------------------------------
 */
static int
ParseEOF (void)
{
    IFile     *ifile;	/* the state on the top of the includes stack */

    if (Lst_IsEmpty (includes)) {
	return (DONE);
    }

    ifile = (IFile *) Lst_DeQueue (includes);
    free (fname);
    fname = ifile->fname;
    lineno = ifile->lineno;
#if defined(_WIN32)
    if (curFILE != NULL) {
	fclose (curFILE);
    }
#else
    fclose(curFILE);
#endif
    curFILE = ifile->F;
    free ((Address)ifile);
    return (CONTINUE);
}

/***********************************************************************
 *				Parse_UpCaseString
 ***********************************************************************
 *
 * SYNOPSIS:	    upcases its argument
 * CALLED BY:	    (UTILITY)
 * RETURN:	    the upcased version of the string
 * SIDE EFFECTS:    DESTRUCTIVE!  alters the string in-place!
 *
 * STRATEGY:	    call toupper on each element of str
 *
 * REVISION HISTORY:
 *	Name	Date		Description
 *	----	----		-----------
 *	tbradley 9/16/96   	Initial Revision
 *
 ***********************************************************************/
void
Parse_UpCaseString (char *str)
{
    if (str != NULL) {
	while (*str != '\0') {
	    *str = (char) toupper(*str);
	    str++;
	}
    }
}	/* End of ParseUpCaseString.	*/


/*-
 *---------------------------------------------------------------------
 * ParseReadc  --
 *	Read a character from the current file and update the line number
 *	counter as necessary
 *
 * Results:
 *	The character that was read
 *
 * Side Effects:
 *	The lineno counter is incremented if the character is a newline
 *---------------------------------------------------------------------
 */
#ifdef notdef
static int parseReadChar;

#define ParseReadc() (((parseReadChar = getc(curFILE)) == '\n') ? \
		      (lineno++, '\n') : parseReadChar)
#elif defined(_LINUX)

char ParseReadc() {

  static int parseLastChar = 0;
  int next;

  if( parseLastChar != 0) {
    int retValue = parseLastChar;
    parseLastChar = 0;
    return retValue;
  }
  next = getc(curFILE);
  if(next == '\r') {

    next = getc(curFILE);
    if(next == '\n') {
      return next;
    }
    parseLastChar = next;
    return '\r';
  }
  return next;
}

#else
#define ParseReadc() (getc(curFILE))
#endif /* notdef */


/*-
 *---------------------------------------------------------------------
 * ParseReadLine --
 *	Read an entire line from the input file. Called only by Parse_File.
 *	To facilitate escaped newlines and what have you, a character is
 *	buffered in 'lastc', which is '\0' when no characters have been
 *	read. When we break out of the loop, c holds the terminating
 *	character and lastc holds a character that should be added to
 *	the line (unless we don't read anything but a terminator).
 *
 * Results:
 *	A line w/o its newline
 *
 * Side Effects:
 *	Only those associated with reading a character
 *---------------------------------------------------------------------
 */
static char *
ParseReadLine (void)
{
    Buffer  	  buf;	    	/* Buffer for current line */
    register int  c;	      	/* the current character */
    register int  lastc;    	/* The most-recent character */
    Boolean	  semiNL;     	/* treat semi-colons as newlines */
    Boolean	  ignDepOp;   	/* TRUE if should ignore dependency operators
				 * for the purposes of setting semiNL */
    Boolean 	  ignComment;	/* TRUE if should ignore comments (in a
				 * shell command */
    char    	  *line;    	/* Result */
    int	    	  lineLength;	/* Length of result */

    semiNL = FALSE;
    ignDepOp = FALSE;
    ignComment = FALSE;

    /*
     * Handle special-characters at the beginning of the line. Either a
     * leading tab (shell command) or pound-sign (possible conditional)
     * forces us to ignore comments and dependency operators and treat
     * semi-colons as semi-colons (by leaving semiNL FALSE). This also
     * discards completely blank lines.
     */
    while(1) {
	c = ParseReadc();

	if ((c == '\t') || (c == SPECIAL_CHAR)) {
	    ignComment = ignDepOp = TRUE;
	    break;
	} else if (c == '\n') {
	    lineno++;
	} else {
	    /*
	     * Anything else breaks out without doing anything
	     */
	    break;
	}
    }

    if ((char)c != (char)EOF) {
	lastc = c;
	buf = Buf_Init(BSIZE);

	while (((c = ParseReadc ()) != '\n' || (lastc == '\\')) &&
	       ((char)c != (char)EOF))
	{
test_char:
	    switch(c) {
	    case '\n':
		/*
		 * Escaped newline: read characters until a non-space or an
		 * unescaped newline and replace them all by a single space.
		 * This is done by storing the space over the backslash and
		 * dropping through with the next nonspace. If it is a
		 * semi-colon and semiNL is TRUE, it will be recognized as a
		 * newline in the code below this...
		 */
		lineno++;
		lastc = ' ';
		while ((c = ParseReadc ()) == ' ' || c == '\t') {
		    continue;
		}
		if ((char)c == (char)EOF || c == '\n') {
		    goto line_read;
		} else {
		    /*
		     * Check for comments, semiNL's, etc. -- easier than
		     * ungetc(c, curFILE); continue;
		     */
		    goto test_char;
		}
	    case ';':
		/*
		 * Semi-colon: Need to see if it should be interpreted as a
		 * newline
		 */
		if (semiNL) {
		    /*
		     * To make sure the command that may be following this
		     * semi-colon begins with a tab, we push one back into the
		     * input stream. This will overwrite the semi-colon in the
		     * buffer. If there is no command following, this does no
		     * harm, since the newline remains in the buffer and the
		     * whole line is ignored.
		     */
		    ungetc('\t', curFILE);
		    goto line_read;
		}
		break;
	    case '=':
		if (!semiNL) {
		    /*
		     * Haven't seen a dependency operator before this, so this
		     * must be a variable assignment -- don't pay attention to
		     * dependency operators after this.
		     */
		    ignDepOp = TRUE;
		} else if (lastc == ':' || lastc == '!') {
		    /*
		     * Well, we've seen a dependency operator already, but it
		     * was the previous character, so this is really just an
		     * expanded variable assignment. Revert semi-colons to
		     * being just semi-colons again and ignore any more
		     * dependency operators.
		     *
		     * XXX: Note that a line like "foo : a:=b" will blow up,
		     * but who'd write a line like that anyway?
		     */
		    ignDepOp = TRUE; semiNL = FALSE;
		}
		break;
	    case '#':
		if (!ignComment) {
		    if (backwards || (lastc != '\\')) {
			/*
			 * If the character is a hash mark and it isn't escaped
			 * (or we're being compatible), the thing is a comment.
			 * Skip to the end of the line.
			 */
			do {
			    c = ParseReadc();
			} while ((c != '\n') && ((char)c != (char)EOF));
			goto line_read;
		    } else {
			/*
			 * Don't add the backslash. Just let the # get copied
			 * over.
			 */
			lastc = c;
			continue;
		    }
		}
		break;
	    case ':':
	    case '!':
		if (!ignDepOp && (c == ':' || c == '!')) {
		    /*
		     * A semi-colon is recognized as a newline only on
		     * dependency lines. Dependency lines are lines with a
		     * colon or an exclamation point. Ergo...
		     */
		    semiNL = TRUE;
		}
		break;
	    }
	    /*
	     * Copy in the previous character and save this one in lastc.
	     */
	    Buf_AddByte (buf, (Byte)lastc);
	    lastc = c;

	}
    line_read:
	lineno++;

	if (lastc != '\0') {
	    Buf_AddByte (buf, (Byte)lastc);
	}
	Buf_AddByte (buf, (Byte)'\0');
	line = (char *)Buf_GetAll (buf, &lineLength);
	Buf_Destroy (buf, FALSE);

	if (line[0] == SPECIAL_CHAR) {
	    /*
	     * The line might be a conditional. Ask the conditional module
	     * about it and act accordingly
	     */
	    switch (Cond_Eval (line)) {
	    case COND_SKIP:
		do {
		    /*
		     * Skip to next conditional that evaluates to COND_PARSE.
		     */
		    free (line);
		    c = ParseReadc();
		    /*
		     * Skip lines until get to one that begins with a
		     * special char.
		     */
		    while ((c != SPECIAL_CHAR) && ((char)c != (char)EOF)) {
			while (((c != '\n') || (lastc == '\\')) &&
			       ((char)c != (char)EOF))
			{
			    /*
			     * Advance to next unescaped newline
			     */
			    if ((lastc = c) == '\n') {
				lineno++;
			    }
			    c = ParseReadc();
			}
			lineno++;

			lastc = c;
			c = ParseReadc ();
		    }

		    if ((char)c == (char)EOF) {
			Parse_Error (PARSE_FATAL, "Unclosed conditional", 0, 0);
			return ((char *)NULL);
		    }

		    /*
		     * Read the entire line into buf
		     */
		    buf = Buf_Init (BSIZE);
		    do {
			Buf_AddByte (buf, (Byte)c);
			c = ParseReadc();
		    } while ((c != '\n') && ((char)c != (char)EOF));
		    lineno++;

		    Buf_AddByte (buf, (Byte)'\0');
		    line = (char *)Buf_GetAll (buf, &lineLength);
		    Buf_Destroy (buf, FALSE);
		} while (Cond_Eval(line) != COND_PARSE);
		/*FALLTHRU*/
	    case COND_PARSE:
		free (line);
		line = (char *)ParseReadLine();
		break;
	    }
	}

	return (line);
    } else {
	/*
	 * Hit end-of-file, so return a NULL line to indicate this.
	 */
	return((char *)NULL);
    }
}

/*-
 *-----------------------------------------------------------------------
 * ParseFinishLine --
 *	Handle the end of a dependency group.
 *
 * Results:
 *	Nothing.
 *
 * Side Effects:
 *	inLine set FALSE. 'targets' list destroyed.
 *
 *-----------------------------------------------------------------------
 */
static void
ParseFinishLine(void)
{
    extern int Suff_EndTransform();

    if (inLine) {
	Lst_ForEach(targets, Suff_EndTransform, (ClientData)NULL);
	Lst_Destroy (targets, (void (*)())ParseHasCommands);
	inLine = FALSE;
    }
}


/*-
 *---------------------------------------------------------------------
 * Parse_File --
 *	Parse a file into its component parts, incorporating it into the
 *	current dependency graph. This is the main function and controls
 *	almost every other function in this module
 *
 * Results:
 *	None
 *
 * Arguments:
 *      char *name   : The name of the file being read
 *      FILE *stream : Stream open to makefile to parse
 *
 * Side Effects:
 *	Loads. Nodes are added to the list of all targets, nodes and links
 *	are added to the dependency graph. etc. etc. etc.
 *---------------------------------------------------------------------
 */
void
Parse_File(char *name, FILE *stream)
{
    register char *cp,		/* pointer into the line */
                  *line;	/* the line we're working on */

    inLine = FALSE;
    fname = name;
    curFILE = stream;
    lineno = 0;
    fatals = 0;

    do {
	while ((line = (char *)ParseReadLine ()) != NULL) {
	    if (*line == SPECIAL_CHAR) {
		/*
		 * Lines that begin with the special character are either
		 * include or undef directives.
		 */
		for (cp = line + 1; isspace (*cp); cp++) {
		    continue;
		}
		if (strncmp (cp, "include", 7) == 0) {
		    ParseDoInclude (cp + 7);
		    goto nextLine;
		} else if (strncmp(cp, "undef", 5) == 0) {
		    char *cp2;
		    for (cp += 5; isspace(*cp); cp++) {
			continue;
		    }

		    for (cp2 = cp; !isspace(*cp2) && (*cp2 != '\0'); cp2++) {
			continue;
		    }

		    *cp2 = '\0';

		    Var_Delete(cp, VAR_GLOBAL);
		    goto nextLine;
		}
	    }
	    if (*line == '#') {
		/*
		 * If we're this far, the line must be a comment, even if
		 * SPECIAL_CHAR is '#'
		 */
		goto nextLine;
	    }

	    if (*line == '\t'
#ifdef POSIX
		       || *line == ' '
#endif
		       )
	    {
		/*
		 * If a line starts with a tab (or space in POSIX-land), it
		 * can only hope to be a creation command.
		 */
	    shellCommand:
		for (cp = line + 1; isspace (*cp); cp++) {
		    continue;
		}
		if (*cp) {
		    if (inLine) {
			/*
			 * So long as it's not a blank line and we're actually
			 * in a dependency spec, add the command to the list of
			 * commands of all targets in the dependency spec
			 */
			Lst_ForEach (targets, ParseAddCmd, (ClientData)cp);
			continue;
		    } else {
			Parse_Error (PARSE_FATAL,
				     "Unassociated shell command \"%.20s\"",
				     (unsigned long)cp, 0);
		    }
		} else {
		    if (inLine) {
			/*
			 * The target has an empty command -- this shouldn't
			 * cause anything to be executed, but still prevents
			 * transformations from being applied.
			 */
			Lst_ForEach(targets, ParseAddCmd, (ClientData)NULL);
			continue;
		    }
		}
	    } else if (Parse_IsVar (line)) {
		ParseFinishLine();
		Parse_DoVar (line, VAR_GLOBAL);
	    } else {
		/*
		 * We now know it's a dependency line so it needs to have all
		 * variables expanded before being parsed. Tell the variable
		 * module to complain if some variable is undefined...
		 * To make life easier on novices, if the line is indented we
		 * first make sure the line has a dependency operator in it.
		 * If it doesn't have an operator and we're in a dependency
		 * line's script, we assume it's actually a shell command
		 * and add it to the current list of targets.
		 *
		 * Note that POSIX declares all lines that start with
		 * whitespace are shell commands, so there's no need to check
		 * here...
		 */
		Boolean	nonSpace = FALSE;

		cp = line;
#ifndef POSIX
		if (line[0] == ' ') {
		    while ((*cp != ':') && (*cp != '!') && (*cp != '\0')) {
			if (!isspace(*cp)) {
			    nonSpace = TRUE;
			}
			cp++;
		    }
		}

		if (*cp == '\0') {
		    if (inLine) {
			Parse_Error (PARSE_WARNING,
				     "Shell command needs a leading tab", 0, 0);
			goto shellCommand;
		    } else if (nonSpace) {
			Parse_Error (PARSE_FATAL, "Missing operator", 0, 0);
		    }
		} else {
#endif
		    ParseFinishLine();

		    cp = Var_Subst (line, VAR_CMD, TRUE);
		    free (line);
		    line = cp;

		    /*
		     * Need a non-circular list for the target nodes
		     */
		    targets = Lst_Init (FALSE);
		    inLine = TRUE;

		    ParseDoDependency (line);
#ifndef POSIX
		}
#endif
	    }

	    nextLine:

	    free (line);
	}
	/*
	 * Reached EOF, but it may be just EOF of an include file...
	 */
    } while (ParseEOF() == CONTINUE);

    /*
     * Make sure conditionals are clean
     */
    Cond_End();

    if (fatals) {
	fprintf (stderr, "Fatal errors encountered -- cannot continue\n");
	exit (1);
    }
}


/*-
 *---------------------------------------------------------------------
 * Parse_Init --
 *	initialize the parsing module
 *
 * Results:
 *	none
 *
 * Side Effects:
 *	the parseIncPath list is initialized...
 *---------------------------------------------------------------------
 */
void
Parse_Init (void)
{
    char    	*cp;
    char    	*start;
#ifdef unix
    static char syspath[] = DEFSYSPATH;	/* Avoid faults on read-only string
					 * constant... */
#else
    char        *rootdir;
    char    	*syspath = NULL;
#endif

#ifdef unix
#	define DEFSYSPATH_DELIMETER  ':'
#	define QUOTED_DELIMETER	     ":"
#else
#	define DEFSYSPATH_DELIMETER  ';'
#	define QUOTED_DELIMETER      ";"
#endif

#ifndef unix
#if defined(_WIN32) || defined(_LINUX)
/*
 * Under NT, look in Include/Win32 before Include; this is so that
 * we can integrate unobtrusively into the existing Unix environment.
 */
#define DEFSYSPATH_APPEND1	"/Include/Win32"
#define DEFSYSPATH_APPEND2	"/Include"
#else  /* _MSDOS */
#define DEFSYSPATH_APPEND1	QUOTED_SLASH "Include"
#endif /* _WIN32 */
    /*
     * In DOS world, we will look for an environment variable called
     * ROOT_DIR, if it exists, then it will be our default path for
     * looking for system makefiles.
     *
     * Under Win32, we make the path look like:
     *
     *	$ROOT_DIR/Win32/Include;$ROOT_DIR/Include
     */
    rootdir = getenv("ROOT_DIR");
    if (rootdir != NULL) {
	MallocCheck(syspath, ((strlen(rootdir) * 2)
			      + sizeof(DEFSYSPATH_APPEND1)
			      + sizeof(DEFSYSPATH_APPEND2)
			      + 2)); /* null term and a ';' */
	strcpy(syspath, rootdir);
	strcat(syspath, DEFSYSPATH_APPEND1);
#if defined(_WIN32) || defined(_LINUX)
	strcat(syspath, QUOTED_DELIMETER);
	strcat(syspath, rootdir);
	strcat(syspath, DEFSYSPATH_APPEND2);
#endif /* _WIN32 */
    }
    rootdir = getenv("SYSMK");
    if (rootdir != NULL) {
	if (syspath == NULL) {
	    MallocCheck(syspath, strlen(rootdir) + 1);
	    strcpy(syspath, rootdir);
	} else {
	    /*
	     * Append ";$SYSMK" to include path.
	     */
	    syspath = realloc((void *)syspath, (strlen(syspath)
						+ strlen(rootdir) + 2));
	    strcat(syspath, QUOTED_DELIMETER);
	    strcat(syspath, rootdir);
	}
    }
#endif /* !unix */

    mainNode = NILGNODE;
    parseIncPath = Lst_Init (FALSE);
    sysIncPath = Lst_Init (FALSE);
    includes = Lst_Init (FALSE);

    if (syspath == NULL) {
	return;
    }
    /*
     * Add the directories from the DEFSYSPATH (more than one may be given
     * as dir1:...:dirn) to the system include path. (in the DOS world it will
     * be semi-colons rather than colons, just for fun :)
     */
    for (start = syspath; *start != '\0'; start = cp)
    {
	for (cp = start; *cp != '\0' && *cp != DEFSYSPATH_DELIMETER; cp++)
	{
	    ;
	}
	if (*cp == '\0')
	{
	    Dir_AddDir(sysIncPath, start);
	} else
	{
	    *cp++ = '\0';
	    Dir_AddDir(sysIncPath, start);
	}
    }
#ifndef unix
    if (syspath != NULL) {
	free(syspath);
    }
#endif
}

/*-
 *-----------------------------------------------------------------------
 * Parse_MainName --
 *	Return a Lst of the main target to create for main()'s sake. If
 *	no such target exists, we Punt with an obnoxious error message.
 * 	(not so obnoxious anymore, sorry adam :)
 * Results:
 *	A Lst of the single node to create.
 *
 * Side Effects:
 *	None.
 *
 *-----------------------------------------------------------------------
 */
Lst
Parse_MainName(void)
{
    Lst           main;	/* result list */

    main = Lst_Init (FALSE);

    if (mainNode == NILGNODE) {
	Punt ("I don't know what to make! Check your makefile. \n",0,0);
    	/*NOTREACHED*/
    } else if (mainNode->type & OP_DOUBLEDEP) {
	Lst_Concat(main, mainNode->cohorts, LST_CONCNEW);
    }
    (void) Lst_AtEnd (main, (ClientData)mainNode);
    return (main);
}
