#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = hminst
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = INSTALL.GOC RESD.GOC RESB.GOC RESC.GOC RESA.GOC\
                  INSTICO.GOH
OBJS            = INSTALL.obj RESD.obj RESB.obj RESC.obj RESA.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
