TEDIT.rdef: GENERIC.UIH PRODUCT.UIH SPOOL.UIH OBJECTS/TEXT/TCTRL.UIH \
                RULER.UIH OBJECTS/COLORC.UIH OBJECTS/STYLES.UIH SPELL.UIH \
                ART/MKRTEXTEDITOR.UI ART/MKRTEXTEDITORTINY.UI \
                INTERNAL/PRODFEATURES.UIH
TEDIT.obj \
TEDIT.eobj: GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF EC.DEF ASSERT.DEF \
                DISK.DEF FILE.DEF DRIVE.DEF VM.DEF OBJECT.DEF LMEM.DEF \
                GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF GSTRING.DEF \
                TEXT.DEF CHAR.DEF UI.DEF WIN.DEF INPUT.DEF HWR.DEF \
                LOCALIZE.DEF SLLANG.DEF OBJECTS/PROCESSC.DEF \
                OBJECTS/METAC.DEF CHUNKARR.DEF GEOWORKS.DEF GCNLIST.DEF \
                TIMEDATE.DEF OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF \
                IACP.DEF OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF \
                OBJECTS/VCOMPC.DEF OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF \
                OBJECTS/GENC.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SPOOL.DEF PRINT.DEF INTERNAL/PRODFEATURES.DEF \
                OBJECTS/VTEXTC.DEF HUGEARR.DEF DBASE.DEF \
                OBJECTS/VLTEXTC.DEF OBJECTS/TEXT/TCTRLC.DEF RULER.DEF \
                OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF SPELL.DEF \
                TEDIT.RDEF

TEDITEC.geo TEDIT.geo : GEOS.LDF UI.LDF MAILBOX.LDF 