#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bjack
ASM_TO_OBJS     = bjack.asm
UI_TO_RDFS      = bjack.ui
SRCS            = bjackGame.asm bjack.asm bjackSound.asm sizes.def\
                  myMacros.def bjack.ui
OBJS            = bjack.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
