#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = BJACK
ASM_TO_OBJS     = bjack.asm
UI_TO_RDFS      = BJACK.UI
SRCS            = bjack.asm bjackGame.asm bjackSound.asm myMacros.def\
                  sizes.def bjack.ui
OBJS            = bjack.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
