#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = filedd
ASM_TO_OBJS     = fileddManager.asm
UI_TO_RDFS      =
SRCS            = fileddRead.asm filedd.asm fileddCode.asm fileddBody.asm\
                  fileddWrite.asm fileddUtils.asm fileddManager.asm\
                  fileddEntry.asm fileddVariable.def fileddConstant.def
OBJS            = fileddManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
