#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = Simp2or4
ASM_TO_OBJS     = simp2or4Manager.asm
UI_TO_RDFS      =
SRCS            = simp2or4DevInfo.asm simp2or4Entry.asm simp2or4Manager.asm\
                  simp2or4Switch.asm simp2or4Constant.def
OBJS            = simp2or4Manager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
