#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = mouse
ASM_TO_OBJS     = mouseCommon.asm mouseSerCommon.asm
UI_TO_RDFS      =
SRCS            = mouseCommon.asm mouseSerCommon.asm
OBJS            = mouseCommon.obj mouseSerCommon.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
