#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = dosreal
ASM_TO_OBJS     = dosrealManager.asm
UI_TO_RDFS      =
SRCS            = dosrealDMA.asm dosrealManager.asm dosrealStrategy.asm\
                  DMAError.def dosrealConstants.def
OBJS            = dosrealManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
