#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = canonbjc
ASM_TO_OBJS     = canonBJCManager.asm
UI_TO_RDFS      = canonBJC.ui
SRCS            = canonBJCDriverInfo.asm canonBJCmonoInfo.asm\
                  canonBJCDialog.asm canonBJCManager.asm\
                  canonBJCcmyInfo.asm canonBJCcmykInfo.asm\
                  canonBJCControlCodes.asm UI/uiGetNoMain.asm\
                  UI/uiGetOptions.asm UI/uiEval.asm UI/uiEvalDummyASF.asm\
                  printcomEntry.asm printcomInfo.asm printcomAdmin.asm\
                  printcomTables.asm printcomNoEscapes.asm\
                  printcomCanonBJCJob.asm printcomASFOnlyPage.asm\
                  printcomCanonBJCCursor.asm printcomStream.asm\
                  printcomCanonBJCColor.asm printcomCanonBJCGraphics.asm\
                  printcomNoStyles.asm printcomNoText.asm\
                  Buffer/bufferCreate.asm Buffer/bufferDestroy.asm\
                  canonBJCConstant.def canonBJC.ui
OBJS            = canonBJCManager.obj
LOBJS           =
LIBNAME         = print
PROTOCONST      = PRINT

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
