#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = hangman
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = process.goc Import.goc hangman.goc hmicon.goh bboxreg.goh\
                  externs.goh hangman.goh
OBJS            = process.obj Import.obj hangman.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
