#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = hangman
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = hangman.goc Import.goc process.goc externs.goh\
                  hangman.goh hmicon.goh
OBJS            = hangman.obj Import.obj process.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
