PROCESS.obj \
PROCESS.eobj: MAGIC.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH EXTERNS.GOH
PROCESS.obj \
PROCESS.eobj: PROCESS.GOC GEOS.H C:/BC45/INCLUDE/STDDEF.H \
                C:/BC45/INCLUDE/_DEFS.H C:/BC45/INCLUDE/_NULL.H HEAP.H \
                GEODE.H RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H \
                FONTID.H FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H \
                LOCALIZE.H ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H \
                SYSTEM.H GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H \
                DRIVE.H INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H \
                OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H STYLESH.H \
                DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H \
                PARALLDR.H HUGEARR.H FILEENUM.H
MAIN.obj \
MAIN.eobj: MAGIC.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH ICON.GOH
MAIN.obj \
MAIN.eobj: MAIN.GOC GEOS.H C:/BC45/INCLUDE/STDDEF.H \
                C:/BC45/INCLUDE/_DEFS.H C:/BC45/INCLUDE/_NULL.H HEAP.H \
                GEODE.H RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H \
                FONTID.H FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H \
                LOCALIZE.H ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H \
                SYSTEM.H GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H \
                DRIVE.H INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H \
                OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H STYLESH.H \
                DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H \
                PARALLDR.H HUGEARR.H FILEENUM.H
DIALOG.obj \
DIALOG.eobj: MAGIC.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH
DIALOG.obj \
DIALOG.eobj: DIALOG.GOC GEOS.H C:/BC45/INCLUDE/STDDEF.H \
                C:/BC45/INCLUDE/_DEFS.H C:/BC45/INCLUDE/_NULL.H HEAP.H \
                GEODE.H RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H \
                FONTID.H FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H \
                LOCALIZE.H ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H \
                SYSTEM.H GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H \
                DRIVE.H INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H \
                OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H STYLESH.H \
                DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H \
                PARALLDR.H HUGEARR.H FILEENUM.H
PIECE.obj \
PIECE.eobj: MAGIC.GOH STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH EXTERNS.GOH
PIECE.obj \
PIECE.eobj: PIECE.GOC GEOS.H C:/BC45/INCLUDE/STDDEF.H \
                C:/BC45/INCLUDE/_DEFS.H C:/BC45/INCLUDE/_NULL.H HEAP.H \
                GEODE.H RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H \
                FONTID.H FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H \
                LOCALIZE.H ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H \
                SYSTEM.H GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H \
                DRIVE.H INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H \
                OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H STYLESH.H \
                DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H \
                PARALLDR.H HUGEARR.H FILEENUM.H
CONTENT.obj \
CONTENT.eobj: MATH.GOH MAGIC.GOH STDAPP.GOH OBJECT.GOH UI.GOH \
                OBJECTS/METAC.GOH OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH EXTERNS.GOH
CONTENT.obj \
CONTENT.eobj: CONTENT.GOC GEOS.H C:/BC45/INCLUDE/STDDEF.H \
                C:/BC45/INCLUDE/_DEFS.H C:/BC45/INCLUDE/_NULL.H MATH.H \
                HEAP.H GEODE.H RESOURCE.H EC.H OBJECT.H LMEM.H GRAPHICS.H \
                FONTID.H FONT.H COLOR.H GSTRING.H TIMER.H VM.H DBASE.H \
                LOCALIZE.H ANSI/CTYPE.H TIMEDATE.H FILE.H SLLANG.H \
                SYSTEM.H GEOWORKS.H CHUNKARR.H OBJECTS/HELPCC.H DISK.H \
                DRIVE.H INPUT.H CHAR.H HWR.H WIN.H UDIALOG.H \
                OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H STYLESH.H \
                DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H SERIALDR.H \
                PARALLDR.H HUGEARR.H FILEENUM.H

MAGICEC.geo MAGIC.geo : GEOS.LDF UI.LDF ANSIC.LDF MATH.LDF 