#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = GeoPoint
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = functs.goc proc.goc show.goc ui.goc GeoPoint.goh
OBJS            = functs.obj proc.obj show.obj ui.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
