#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = geopoint
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = proc.goc ui.goc show.goc functs.goc geopoint.goh
OBJS            = proc.obj ui.obj show.obj functs.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
