#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = imps2
ASM_TO_OBJS     = imps2.asm
UI_TO_RDFS      =
SRCS            = imps2.asm ../mouseCommon.asm
OBJS            = imps2.obj
LOBJS           =

PRODUCTS        = GEOS2X 

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(GEOS2X/$(DEPFILE))
#include "GEOS2X/$(DEPFILE)"
#endif
