GDIPOINTER.obj \
GDIPOINTER.eobj: GEOS.DEF HEAP.DEF LMEM.DEF GEODE.DEF RESOURCE.DEF EC.DEF \
                DRIVER.DEF INITFILE.DEF CHAR.DEF TIMER.DEF INPUT.DEF \
                GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF HWR.DEF \
                TIMEDATE.DEF SEM.DEF ASSERT.DEF DISK.DEF FILE.DEF \
                DRIVE.DEF INTERNAL/IM.DEF INTERNAL/SEMINT.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF OBJECT.DEF \
                CHUNKARR.DEF GEOWORKS.DEF INTERNAL/HEAPINT.DEF \
                SYSSTATS.DEF INTERNAL/INTERRUP.DEF INTERNAL/KBDMAP.DEF \
                OBJECTS/UIINPUTC.DEF LOCALIZE.DEF SLLANG.DEF \
                INTERNAL/KBDDR.DEF INTERNAL/MOUSEDR.DEF GDIPOINTER.DEF \
                GDI.DEF

GDIPointerEC.geo GDIPointer.geo : geos.ldf gdi.ldf 
