rem All Rem'd so I don't accidentally regenerate ;-)

rem cvtpcx -2 -w48 -h30 -m1 -G -nQTip1 -oQTip1.goh tip1.pcx
rem cvtpcx -2 -w66 -h24 -m1 -G -nQTip2 -oQTip2.goh tip2.pcx
rem cvtpcx -2 -w100 -h81 -m1 -G -nQTip3 -oQTip3.goh tip3.pcx

rem cvtpcx -2 -w47 -h30 -m1 -G -nQTTip1 -oQTTip1.goh hint1.pcx
rem cvtpcx -2 -w66 -h24 -m1 -G -nQTTip2 -oQTTip2.goh hint2.pcx
rem cvtpcx -2 -w157 -h50 -m1 -G -nQTTip3 -oQTTip3.goh hint3.pcx

