#!/bin/sh -
# $Id: convert,v 1.2 98/04/28 19:15:11 joon Exp $

${cvtpcx-cvtpcx} -2 -m13 -t -l -x0 -y41 -dLCGA -dLC -dLM -nClock clock.pcx
${cvtpcx-cvtpcx} -f -m13 -t -z -nClockTiny clock.tiny.pcx
#
# Location List: Small Color
#
# Motif adds 1 to the width and height of each of these when laying the list
# out.
#
${cvtpcx-cvtpcx} -2 -m7  -x94  -y9  -w18 -h15 -nSCClockNW locate.pcx
${cvtpcx-cvtpcx} -2 -m7  -x114 -y9  -w18 -h15 -nSCClockN locate.pcx
${cvtpcx-cvtpcx} -2 -m7  -x134 -y9  -w18 -h15 -nSCClockNE locate.pcx
${cvtpcx-cvtpcx} -2 -m7  -x94  -y26 -w18 -h15 -nSCClockW locate.pcx
${cvtpcx-cvtpcx} -2 -m7  -x114 -y26 -w18 -h15 -nSCClockC locate.pcx
${cvtpcx-cvtpcx} -2 -m7  -x134 -y26 -w18 -h15 -nSCClockE locate.pcx
${cvtpcx-cvtpcx} -2 -m7  -x94  -y43 -w18 -h15 -nSCClockSW locate.pcx
${cvtpcx-cvtpcx} -2 -m7  -x114 -y43 -w18 -h15 -nSCClockS locate.pcx
${cvtpcx-cvtpcx} -2 -m7  -x134 -y43 -w18 -h15 -nSCClockSE locate.pcx
#
# Location List: Small Mono
#
# Motif adds 3 to the width and height of each of these when laying the list
# out.
#
${cvtpcx-cvtpcx} -2 -b -f -x100 -y2  -w16 -h13 -nSMClockNW locatebw.pcx
${cvtpcx-cvtpcx} -2 -b -f -x119 -y2  -w16 -h13 -nSMClockN locatebw.pcx
${cvtpcx-cvtpcx} -2 -b -f -x138 -y2  -w16 -h13 -nSMClockNE locatebw.pcx
${cvtpcx-cvtpcx} -2 -b -f -x100 -y18 -w16 -h13 -nSMClockW locatebw.pcx
${cvtpcx-cvtpcx} -2 -b -f -x119 -y18 -w16 -h13 -nSMClockC locatebw.pcx
${cvtpcx-cvtpcx} -2 -b -f -x138 -y18 -w16 -h13 -nSMClockE locatebw.pcx
${cvtpcx-cvtpcx} -2 -b -f -x100 -y34 -w16 -h13 -nSMClockSW locatebw.pcx
${cvtpcx-cvtpcx} -2 -b -f -x119 -y34 -w16 -h13 -nSMClockS locatebw.pcx
${cvtpcx-cvtpcx} -2 -b -f -x138 -y34 -w16 -h13 -nSMClockSE locatebw.pcx
#
# Location List: Small CGA
#
# Motif adds 3 to the width and height of each of these when laying the list
# out.
#
${cvtpcx-cvtpcx} -2 -b -f -x125 -y1  -w18 -h7  -nSCGAClockNW -averySquished locatecga.pcx
${cvtpcx-cvtpcx} -2 -b -f -x144 -y1  -w18 -h7  -nSCGAClockN -averySquished locatecga.pcx
${cvtpcx-cvtpcx} -2 -b -f -x163 -y1  -w18 -h7  -nSCGAClockNE -averySquished locatecga.pcx
${cvtpcx-cvtpcx} -2 -b -f -x125 -y9  -w18 -h7  -nSCGAClockW -averySquished locatecga.pcx
${cvtpcx-cvtpcx} -2 -b -f -x144 -y9  -w18 -h7  -nSCGAClockC -averySquished locatecga.pcx
${cvtpcx-cvtpcx} -2 -b -f -x163 -y9  -w18 -h7  -nSCGAClockE -averySquished locatecga.pcx
${cvtpcx-cvtpcx} -2 -b -f -x125 -y17 -w18 -h7  -nSCGAClockSW -averySquished locatecga.pcx
${cvtpcx-cvtpcx} -2 -b -f -x144 -y17 -w18 -h7  -nSCGAClockS -averySquished locatecga.pcx
${cvtpcx-cvtpcx} -2 -b -f -x163 -y17 -w18 -h7  -nSCGAClockSE -averySquished locatecga.pcx
