#!/bin/sh -
#########################################################################
#				convert					#
# Convert script for Desktop and File Cabinet				#
# Run this to create the mkrXXX.ui files for desktop and file cabinet.	#
#									#
# CommonGM/convert							#
# 									#
# $Id: convert,v 1.10.9.1 97/03/29 09:02:45 canavese Exp $
#########################################################################
if [ -f driveicon.sed ]; then
    di_sed=driveicon.sed
else
    di_sed=`otherdir`/driveicon.sed
fi
#
# Convert a pcx file to a moniker, dealing with locating the installed or
# uninstalled version of the file (doesn't deal with branches, I'm afraid)
#
# Usage: cvt <file> <cvtpcx-args>
#
cvt() {
    name=""
    for a do
	case $a in
	    -n*)	name=`expr x$a : 'x-n\(.*\)$'` ;;
	esac
    done
    if [ ! "$name" ]; then
	echo $0: missing -n arg for cvt
	exit 1
    fi
    file=$1
    shift
    if [ ! -f $file ]; then
	file=`otherdir`/$file
    fi
    cvtpcx -f "$@" $file
    mv mkr$name.ui cmkr$name.ui
}

#
# Similar to the above, but the pcx file is cvted to a bitmap, rather
# than a gstring moniker. Must be given a -n<name> argument to pass to cvtpcx,
# and result is left in cbm<name>.ui, instead of cmkr<name>.ui
#
cvtbm() {
    name=""
    for a do
	case $a in
	    -n*)	name=`expr x$a : 'x-n\(.*\)$'` ;;
	esac
    done
    if [ ! "$name" ]; then
	echo $0: missing -n arg for cvtbm
	exit 1
    fi
    cvt "$@" -g
    sed -e 's/Moniker =/Bitmap =/' cmkr$name.ui > cbm$name.ui
}


#########################################################################
#			Application Icons				#
#########################################################################

#----------------------  GeoManager Icon  ------------------------------#
cvt /staff/pcgeos/Appl/Art/Art.20/g20apps3.pcx -m13 -t -L -x0 -y123 -dLCGA -nFileMgr

#----------------------  File Cabinet Icon  ----------------------------#
cvt PCX/filecab.pcx -m13 -t -l -x0 -y0 -dLC -dLM -dLCGA -nFileCabinet


#########################################################################
#			Disk Drive Icons				#
#########################################################################

#-------------------  Three Inch Disk Icon  ----------------------------#
cvtbm PCX/gdesk07.pcx -u -rAppDrives -m13 -t -L -x0 -y0 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nThreeInchDisk
cvt PCX/gdesk07.pcx -m13 -t -L -x0 -y0 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nThreeInchDisk

#---------------------  Five Inch Disk Icon  ----------------------------#
cvtbm PCX/gdesk07.pcx -u -rAppDrives -m13 -t -L -x0 -y41 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nFiveInchDisk
cvt PCX/gdesk07.pcx -m13 -t -L -x0 -y41 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nFiveInchDisk

#-----------------------  Hard Disk Icon  ------------------------------#
cvtbm PCX/gdesk07.pcx -u -rAppDrives -m13 -t -L -x0 -y82 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nHardDisk
cvt PCX/gdesk07.pcx -m13 -t -L -x0 -y82 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nHardDisk

#-------------------------  Ram Disk Icon  -----------------------------#
cvtbm PCX/gdesk07.pcx -u -rAppDrives -m13 -t -L -x0 -y123 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nRamDisk
cvt PCX/gdesk07.pcx -m13 -t -L -x0 -y123 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nRamDisk

#-------------------------  Net Disk Icon  -----------------------------#
cvtbm PCX/gdesk07.pcx -u -rAppDrives -m13 -t -L -x0 -y164 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nNetDisk
cvt PCX/gdesk07.pcx -m13 -t -L -x0 -y164 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nNetDisk

#--------------------------  CD Rom Icon  ------------------------------#
cvtbm PCX/gdesk08.pcx -u -rAppDrives -m2 -t -L -x0 -y0 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nCDRom
cvt PCX/gdesk08.pcx -m13 -t -L -x0 -y205 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nCDRom


#--------------------------  PCMCIA Icon  ------------------------------#
# ONLY FOR ZMGR as of 5/18/93 - brianc #
# now for all filemgrs 10/5/93 -- ardeb
cvtbm PCX/gdesk07.pcx -u -rAppDrives -m13 -t -L -x0 -y205 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nPCMCIA
cvt PCX/gdesk07.pcx -m13 -t -L -x0 -y205 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nPCMCIA



#########################################################################
#			General Desktop Icons				#
#########################################################################

#----------------------  Messy Waste Can Icon  -------------------------#
###	This bitmap must be done first or the non-bitmap will be overwritten
cvtbm PCX/gdesk06.pcx -rAppIconArea -u -m13 -t -L -x0 -y0 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nMessyWasteCan
###	Non-bitmap
cvt PCX/gdesk06.pcx -rAppIconArea -m13 -t -L -x0 -y0 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nMessyWasteCan

#-------------------------  MonoFolder Icon  ---------------------------#
cvt PCX/gdesk06.pcx -rAppIconArea -m13 -t -L -x0 -y41 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nMonoFolder
sed -e '/cachedSize/s/30/31/' cmkrMonoFolder.ui > q
rm cmkrMonoFolder.ui
mv q cmkrMonoFolder.ui


#------------------------  MultiFolder Icon  ---------------------------#
cvt PCX/gdesk06.pcx -rAppIconArea -m13 -t -L -x0 -y82 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nMultiFolder
sed -e '/cachedSize/s/30/31/' cmkrMultiFolder.ui > q
rm cmkrMultiFolder.ui
mv q cmkrMultiFolder.ui


#-----------------------  World Directory Icon  ------------------------#
cvt PCX/gdesk06.pcx -rAppIconArea -u -m13 -t -L -x0 -y123 -dLM -dLC -dLCGA -dTM -dTCGA -dYC -nWorldDirButton

#---------------------  Document Directory Icon  -----------------------#
###	This bitmap must be done first or the non-bitmap will be overwritten
cvt PCX/gdesk06.pcx -rAppIconArea -g -u -m13 -t -L -x0 -y164 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nDocDirButton
sed -e '/cachedSize/s/48/32/' -e 's/Moniker =/Bitmap =/' cmkrDocDirButton.ui > cbmDocDirButton.ui
rm cmkrDocDirButton.ui

###	Non-bitmap
cvt PCX/gdesk06.pcx -rAppIconArea -m13 -t -L -x0 -y164 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nDocDirButton


#########################################################################
#			Folder Contents Icons				#
#########################################################################

#--------------------------  Folder Icon  ------------------------------#
cvt PCX/gdesk04.pcx -m13 -t -L -x0 -y246 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nFileFolder

#-----------------------  Generic GEOS App Icon  -----------------------#
cvt PCX/ggeos.pcx -m13 -t -L -x0 -y0 -dLC -dLM -dLCGA -dTM -dTCGA -nGenAppl

#-----------------------  Generic GEOS Doc Icon  -----------------------#
cvt PCX/ggeos.pcx -m13 -t -L -x0 -y41 -dLC -dLM -dLCGA -dTM -dTCGA -nGenDoc

#-----------------------  Generic DOS App Icon  ------------------------#
cvt PCX/gdesk03.pcx -m13 -t -L -x0 -y164 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nDosAppl

#-----------------------  Generic DOS Doc Icon  ------------------------#
cvt PCX/gdesk03.pcx -m13 -t -L -x0 -y205 -dLC -dLM -dLCGA -dTM -dTCGA -dYC -nDosData

#-------------------------  Template Icon  -----------------------------#
cvt PCX/folder.pcx -m13 -t -l -x0 -y205 -dLC -dLM -dLCGA -nTemplate


#########################################################################
#			File Cabinet Icons				#
#########################################################################

#---------------------------   Open Icon  ------------------------------#
cvtbm PCX/cab1icon.pcx -rAppIconArea -u -m13 -t -l -x0 -y0   -dLC -dLM -dLCGA -nOpenFile


#-------------------------   Get Info Icon  ----------------------------#
cvtbm PCX/cab1icon.pcx -rAppIconArea -u -m13 -t -l -x0 -y41  -dLC -dLM -dLCGA -nGetInfo


#-------------------------   Move File Icon  ---------------------------#
cvtbm PCX/cab1icon.pcx -rAppIconArea -u -m13 -t -l -x0 -y82  -dLC -dLM -dLCGA -nMoveFile


#-------------------------   Copy File Icon  ---------------------------#
cvtbm PCX/cab1icon.pcx -rAppIconArea -u -m13 -t -l -x0 -y123 -dLC -dLM -dLCGA -nCopyFile


#----------------------   Duplicate File Icon  -------------------------#
cvtbm PCX/cab1icon.pcx -rAppIconArea -u -m13 -t -l -x0 -y164 -dLC -dLM -dLCGA -nDupFile


#------------------------   Rename File Icon  --------------------------#
cvtbm PCX/cab1icon.pcx -rAppIconArea -u -m13 -t -l -x0 -y205 -dLC -dLM -dLCGA -nRenameFile


#------------------------   Format Disk Icon  --------------------------#
cvtbm PCX/cab2icon.pcx -rAppIconArea -u -m13 -t -l -x0 -y0  -dLC -dLM -dLCGA -nFormat 


#-----------------------   Close Directory Icon  -----------------------#
cvtbm PCX/cab2icon.pcx -rAppIconArea -u -m13 -t -l -x0 -y41 -dLC -dLM -dLCGA -nCloseDir


#------------------------   Open Directory Icon  -----------------------#
cvtbm PCX/cab2icon.pcx -rAppIconArea -u -m13 -t -l -x0 -y82 -dLC -dLM -dLCGA -nOpenDir


#----------------------   Create Directory Icon  -----------------------#
cvtbm PCX/cab2icon.pcx -rAppIconArea -u -m13 -t -l -x0 -y123 -dLC -dLM -dLCGA -nCreateDir


#----------------------------   Exit Icon  -----------------------------#
cvtbm PCX/cab2icon.pcx -rAppIconArea -u -m2 -t -l -x0 -y164   -dLC -dLM -dLCGA -nExit


#----------------------------   Help Icon  -----------------------------#
cvtbm PCX/cab2icon.pcx -rAppIconArea -u -m2 -t -l -x0 -y205  -dLC -dLM -dLCGA -nHelp

#----------------------------   Preferences Icon  -----------------------------#

. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps3.pcx 4 PrefMgrButton -dYC -dYM -dLC -dLM -dTM -dTCGA $appArgs -rAppIconArea 





