#!/bin/sh -
#
# Project:	PC GEOS
# Module:	GeoComm
# File:		convert
#
# Author:	brianc
#
#	This file contains the user Interface description for this
# appzlication.
#
# 	$Id: convert,v 1.2 98/04/28 18:59:26 joon Exp $
#
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps2.pcx 6 GeoComm $appArgs -dTM -dTCGA
cvtfile /staff/pcgeos/Appl/Art/Art.20/g20apps2.pcx 7 GeoCommDoc $docArgs
cvtpcx -f -m13 -t -z -nGeoCommTiny geocomm.tiny.pcx

#############################################################################
#
#			New icons for Responder
#
#############################################################################

#
# Responder Terminal appl icon
#
cvtpcx -N -2 -f -t -x0 -y0 -w64 -h50 -nTerminalBitmap termapp.pcx
cvtpcx -N -2 -f -t -x0 -y0 -w64 -h50 -nTelnetBitmap telnapp.pcx

#
# Special Key dialog bitmap
#
# Note, the -g puts the bitmaps in chunks, not in gstring visMonikers.
#
cvtpcx -N -2 -f -g -t -x0 -y0 -w32 -h20 -nSpecialKeyBitmap speckti.pcx
