#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bobbin
ASM_TO_OBJS     = bobbin.asm
UI_TO_RDFS      = bobbin.ui
SRCS            = bobbin.asm bobbin.def bobbinHelp.ui bobbin.ui
OBJS            = bobbin.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
