#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = NoodlePref
ASM_TO_OBJS     = noodlepref.asm
UI_TO_RDFS      = NOODLEPREF.UI
SRCS            = noodlepref.asm noodlepref.ui
OBJS            = noodlepref.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
