#!/bin/sh -
#
# $Id: convert,v 1.1.18.1 97/03/29 10:28:44 canavese Exp $
#
cvtpcx -j -x1 -y12 -w48 -h37 -nDude1 bobbin.pcx
cvtpcx -j -x1 -y60 -w48 -h37 -nDude2 bobbin.pcx
cvtpcx -j -x1 -y108 -w48 -h37 -nDude3 bobbin.pcx
cvtpcx -j -x1 -y178 -w60 -h37 -nWalkDude1 bobbin.pcx
cvtpcx -j -x1 -y226 -w60 -h37 -nWalkDude2 bobbin.pcx
cvtpcx -j -x1 -y274 -w60 -h37 -nWalkDude3 bobbin.pcx

cvtpcx -j -b -x105 -y12 -w48 -h37 -nBWDude1 bobbin.pcx
cvtpcx -j -b -x105 -y60 -w48 -h37 -nBWDude2 bobbin.pcx
cvtpcx -j -b -x105 -y108 -w48 -h37 -nBWDude3 bobbin.pcx
cvtpcx -j -b -x105 -y178 -w60 -h37 -nBWWalkDude1 bobbin.pcx
cvtpcx -j -b -x105 -y226 -w60 -h37 -nBWWalkDude2 bobbin.pcx
cvtpcx -j -b -x105 -y274 -w60 -h37 -nBWWalkDude3 bobbin.pcx
