COMMENT @%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

	Copyright (c) GeoWorks 1993 -- All Rights Reserved

PROJECT:	PC GEOS
MODULE:		
FILE:		dosCMapUS.asm

AUTHOR:		Gene Anderson, May 24, 1993

ROUTINES:
	Name			Description
	----			-----------

REVISION HISTORY:
	Name	Date		Description
	----	----		-----------
	Gene	5/24/93		Initial revision


DESCRIPTION:
	

	$Id: dosCMapUS.asm,v 1.1 97/04/10 11:55:07 newdeal Exp $

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@

Resident	segment	resource

codePageUS	Chars \
	C_LATIN_CAPITAL_LETTER_C_CEDILLA,		;0x80
	C_LATIN_SMALL_LETTER_U_DIAERESIS,		;0x81
	C_LATIN_SMALL_LETTER_E_ACUTE,			;0x82
	C_LATIN_SMALL_LETTER_A_CIRCUMFLEX,		;0x83
	C_LATIN_SMALL_LETTER_A_DIAERESIS,		;0x84
	C_LATIN_SMALL_LETTER_A_GRAVE,			;0x85
	C_LATIN_SMALL_LETTER_A_RING,			;0x86
	C_LATIN_SMALL_LETTER_C_CEDILLA,			;0x87
	C_LATIN_SMALL_LETTER_E_CIRCUMFLEX,		;0x88
	C_LATIN_SMALL_LETTER_E_DIAERESIS,		;0x89
	C_LATIN_SMALL_LETTER_E_GRAVE,			;0x8a
	C_LATIN_SMALL_LETTER_I_DIAERESIS,		;0x8b
	C_LATIN_SMALL_LETTER_I_CIRCUMFLEX,		;0x8c
	C_LATIN_SMALL_LETTER_I_GRAVE,			;0x8d
	C_LATIN_CAPITAL_LETTER_A_DIAERESIS,		;0x8e
	C_LATIN_CAPITAL_LETTER_A_RING,			;0x8f
	C_LATIN_CAPITAL_LETTER_E_ACUTE,			;0x90
	C_LATIN_SMALL_LETTER_A_E,			;0x91
	C_LATIN_CAPITAL_LETTER_A_E,			;0x92
	C_LATIN_SMALL_LETTER_O_CIRCUMFLEX,		;0x93
	C_LATIN_SMALL_LETTER_O_DIAERESIS,		;0x94
	C_LATIN_SMALL_LETTER_O_GRAVE,			;0x95
	C_LATIN_SMALL_LETTER_U_CIRCUMFLEX,		;0x96
	C_LATIN_SMALL_LETTER_U_GRAVE,			;0x97
	C_LATIN_SMALL_LETTER_Y_DIAERESIS,		;0x98
	C_LATIN_CAPITAL_LETTER_O_DIAERESIS,		;0x99
	C_LATIN_CAPITAL_LETTER_U_DIAERESIS,		;0x9a
	C_CENT_SIGN,					;0x9b
	C_POUND_SIGN,					;0x9c
	C_YEN_SIGN,					;0x9d
	C_PESETA_SIGN,					;0x9e
	C_LATIN_SMALL_LETTER_SCRIPT_F,			;0x9f
	C_LATIN_SMALL_LETTER_A_ACUTE,			;0xa0
	C_LATIN_SMALL_LETTER_I_ACUTE,			;0xa1
	C_LATIN_SMALL_LETTER_O_ACUTE,			;0xa2
	C_LATIN_SMALL_LETTER_U_ACUTE,			;0xa3
	C_LATIN_SMALL_LETTER_N_TILDE,			;0xa4
	C_LATIN_CAPITAL_LETTER_N_TILDE,			;0xa5
	C_FEMININE_ORDINAL_INDICATOR,			;0xa6
	C_MASCULINE_ORDINAL_INDICATOR,			;0xa7
	C_INVERTED_QUESTION_MARK,			;0xa8
	C_REVERSED_NOT_SIGN,				;0xa9
	C_NOT_SIGN,					;0xaa
	C_FRACTION_ONE_HALF,				;0xab
	C_FRACTION_ONE_QUARTER,				;0xac
	C_INVERTED_EXCLAMATION_MARK,			;0xad
	C_LEFT_POINTING_GUILLEMET,			;0xae
	C_RIGHT_POINTING_GUILLEMET,			;0xaf

	C_LIGHT_SHADE,					;0xb0	graphics chars
	C_MEDIUM_SHADE,					;0xb1
	C_DARK_SHADE,					;0xb2
	C_FORMS_LIGHT_VERTICAL,				;0xb3
	C_FORMS_LIGHT_VERTICAL_AND_LEFT,		;0xb4
	C_FORMS_VERTICAL_SINGLE_AND_LEFT_DOUBLE,	;0xb5
	C_FORMS_VERTICAL_DOUBLE_AND_LEFT_SINGLE,	;0xb6
	C_FORMS_DOWN_DOUBLE_AND_LEFT_SINGLE,		;0xb7
	C_FORMS_DOWN_SINGLE_AND_LEFT_DOUBLE,		;0xb8
	C_FORMS_DOUBLE_VERTICAL_AND_LEFT,		;0xb9
	C_FORMS_DOUBLE_VERTICAL,			;0xba
	C_FORMS_DOUBLE_DOWN_AND_LEFT,			;0xbb
	C_FORMS_DOUBLE_UP_AND_LEFT,			;0xbc
	C_FORMS_UP_DOUBLE_AND_LEFT_SINGLE,		;0xbd
	C_FORMS_UP_SINGLE_AND_LEFT_DOUBLE,		;0xbe
	C_FORMS_LIGHT_DOWN_AND_LEFT,			;0xbf
	C_FORMS_LIGHT_UP_AND_RIGHT,			;0xc0
	C_FORMS_LIGHT_UP_AND_HORIZONTAL,		;0xc1
	C_FORMS_LIGHT_DOWN_AND_HORIZONTAL,		;0xc2
	C_FORMS_LIGHT_VERTICAL_AND_RIGHT,		;0xc3
	C_FORMS_LIGHT_HORIZONTAL,			;0xc4
	C_FORMS_LIGHT_VERTICAL_AND_HORIZONTAL,		;0xc5
	C_FORMS_VERTICAL_SINGLE_AND_RIGHT_DOUBLE,	;0xc6
	C_FORMS_VERTICAL_DOUBLE_AND_RIGHT_SINGLE,	;0xc7
	C_FORMS_DOUBLE_UP_AND_RIGHT,			;0xc8
	C_FORMS_DOUBLE_DOWN_AND_RIGHT,			;0xc9
	C_FORMS_DOUBLE_UP_AND_HORIZONTAL,		;0xca
	C_FORMS_DOUBLE_DOWN_AND_HORIZONTAL,		;0xcb
	C_FORMS_DOUBLE_VERTICAL_AND_RIGHT,		;0xcc
	C_FORMS_DOUBLE_HORIZONTAL,			;0xcd
	C_FORMS_DOUBLE_VERTICAL_AND_HORIZONTAL,		;0xce
	C_FORMS_UP_SINGLE_AND_HORIZONTAL_DOUBLE,	;0xcf
	C_FORMS_UP_DOUBLE_AND_HORIZONTAL_SINGLE,	;0xd0
	C_FORMS_DOWN_SINGLE_AND_HORIZONTAL_DOUBLE,	;0xd1
	C_FORMS_DOWN_DOUBLE_AND_HORIZONTAL_SINGLE,	;0xd2
	C_FORMS_UP_DOUBLE_AND_RIGHT_SINGLE,		;0xd3
	C_FORMS_UP_SINGLE_AND_RIGHT_DOUBLE,		;0xd4
	C_FORMS_DOWN_SINGLE_AND_RIGHT_DOUBLE,		;0xd5
	C_FORMS_DOWN_DOUBLE_AND_RIGHT_SINGLE,		;0xd6
	C_FORMS_VERTICAL_DOUBLE_AND_HORIZONTAL_SINGLE,	;0xd7
	C_FORMS_VERTICAL_SINGLE_AND_HORIZONTAL_DOUBLE,	;0xd8
	C_FORMS_LIGHT_UP_AND_LEFT,			;0xd9
	C_FORMS_LIGHT_DOWN_AND_RIGHT,			;0xda
	C_FULL_BLOCK,					;0xdb
	C_LOWER_HALF_BLOCK,				;0xdc
	C_LEFT_HALF_BLOCK,				;0xdd
	C_RIGHT_HALF_BLOCK,				;0xde
	C_UPPER_HALF_BLOCK,				;0xdf	graphics chars

	C_GREEK_SMALL_LETTER_ALPHA,			;0xe0
	C_LATIN_SMALL_LETTER_SHARP_S,			;0xe1
	C_GREEK_CAPITAL_LETTER_GAMMA,			;0xe2
	C_GREEK_SMALL_LETTER_PI,			;0xe3
	C_GREEK_CAPITAL_LETTER_SIGMA,			;0xe4
	C_GREEK_SMALL_LETTER_SIGMA,			;0xe5
	C_MICRO_SIGN,					;0xe6
	C_GREEK_SMALL_LETTER_TAU,			;0xe7
	C_GREEK_CAPITAL_LETTER_PHI,			;0xe8
	C_GREEK_CAPITAL_LETTER_THETA,			;0xe9
	C_GREEK_CAPITAL_LETTER_OMEGA,			;0xea
	C_GREEK_SMALL_LETTER_DELTA,			;0xeb
	C_INFINITY,					;0xec
	C_GREEK_SMALL_LETTER_PHI,			;0xed
	C_GREEK_SMALL_LETTER_EPSILON,			;0xee
	C_INTERSECTION,					;0xef
	C_IDENTICAL_TO,					;0xf0
	C_PLUS_OR_MINUS_SIGN,				;0xf1
	C_GREATER_THAN_OR_EQUAL_TO,			;0xf2
	C_LESS_THAN_OR_EQUAL_TO,			;0xf3
	C_TOP_HALF_INTEGRAL,				;0xf4
	C_BOTTOM_HALF_INTEGRAL,				;0xf5
	C_DIVISION_SIGN,				;0xf6
	C_ALMOST_EQUAL_TO,				;0xf7
	C_DEGREE_SIGN,					;0xf8
	C_BULLET_OPERATOR,				;0xf9
	C_MIDDLE_DOT,					;0xfa
	C_SQUARE_ROOT,					;0xfb
	C_SUPERSCRIPT_LATIN_SMALL_LETTER_N,		;0xfc
	C_SUPERSCRIPT_DIGIT_TWO,			;0xfd
	C_BLACK_SQUARE,					;0xfe
	C_NON_BREAKING_SPACE				;0xff
.assert ($-codePageUS) eq 256

	ForceRef	codePageUS

Resident	ends
