COMMENT @%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

	Copyright (c) GeoWorks 1994 -- All Rights Reserved

PROJECT:	PC GEOS
MODULE:		
FILE:		dosCMapMulti.asm

AUTHOR:		Gene Anderson, May 4, 1994

ROUTINES:
	Name			Description
	----			-----------

REVISION HISTORY:
	Name	Date		Description
	----	----		-----------
	Gene	5/4/94		Initial revision


DESCRIPTION:
	mapping table for Unicode <-> multilingual code page 850.

	$Id: dosCMapMulti.asm,v 1.1 97/04/10 11:55:11 newdeal Exp $

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%@

Resident	segment	resource

codePageMulti	Chars \
	C_LATIN_CAPITAL_LETTER_C_CEDILLA,		;0x80
	C_LATIN_SMALL_LETTER_U_DIAERESIS,		;0x81
	C_LATIN_SMALL_LETTER_E_ACUTE,			;0x82
	C_LATIN_SMALL_LETTER_A_CIRCUMFLEX,		;0x83
	C_LATIN_SMALL_LETTER_A_DIAERESIS,		;0x84
	C_LATIN_SMALL_LETTER_A_GRAVE,			;0x85
	C_LATIN_SMALL_LETTER_A_RING,			;0x86
	C_LATIN_SMALL_LETTER_C_CEDILLA,			;0x87
	C_LATIN_SMALL_LETTER_E_CIRCUMFLEX,		;0x88
	C_LATIN_SMALL_LETTER_E_DIAERESIS,		;0x89
	C_LATIN_SMALL_LETTER_E_GRAVE,			;0x8a
	C_LATIN_SMALL_LETTER_I_DIAERESIS,		;0x8b
	C_LATIN_SMALL_LETTER_I_CIRCUMFLEX,		;0x8c
	C_LATIN_SMALL_LETTER_I_GRAVE,			;0x8d
	C_LATIN_CAPITAL_LETTER_A_DIAERESIS,		;0x8e
	C_LATIN_CAPITAL_LETTER_A_RING,			;0x8f
	C_LATIN_CAPITAL_LETTER_E_ACUTE,			;0x90
	C_LATIN_SMALL_LETTER_A_E,			;0x91
	C_LATIN_CAPITAL_LETTER_A_E,			;0x92
	C_LATIN_SMALL_LETTER_O_CIRCUMFLEX,		;0x93
	C_LATIN_SMALL_LETTER_O_DIAERESIS,		;0x94
	C_LATIN_SMALL_LETTER_O_GRAVE,			;0x95
	C_LATIN_SMALL_LETTER_U_CIRCUMFLEX,		;0x96
	C_LATIN_SMALL_LETTER_U_GRAVE,			;0x97
	C_LATIN_SMALL_LETTER_Y_DIAERESIS,		;0x98
	C_LATIN_CAPITAL_LETTER_O_DIAERESIS,		;0x99
	C_LATIN_CAPITAL_LETTER_U_DIAERESIS,		;0x9a
	C_LATIN_SMALL_LETTER_O_SLASH,			;0x9b
	C_POUND_SIGN,					;0x9c
	C_LATIN_CAPITAL_LETTER_O_SLASH,			;0x9d
	C_MULTIPLICATION_SIGN,				;0x9e
	C_LATIN_SMALL_LETTER_SCRIPT_F,			;0x9f
	C_LATIN_SMALL_LETTER_A_ACUTE,			;0xa0
	C_LATIN_SMALL_LETTER_I_ACUTE,			;0xa1
	C_LATIN_SMALL_LETTER_O_ACUTE,			;0xa2
	C_LATIN_SMALL_LETTER_U_ACUTE,			;0xa3
	C_LATIN_SMALL_LETTER_N_TILDE,			;0xa4
	C_LATIN_CAPITAL_LETTER_N_TILDE,			;0xa5
	C_FEMININE_ORDINAL_INDICATOR,			;0xa6
	C_MASCULINE_ORDINAL_INDICATOR,			;0xa7
	C_INVERTED_QUESTION_MARK,			;0xa8
	C_REGISTERED_TRADE_MARK_SIGN,			;0xa9
	C_NOT_SIGN,					;0xaa
	C_FRACTION_ONE_HALF,				;0xab
	C_FRACTION_ONE_QUARTER,				;0xac
	C_INVERTED_EXCLAMATION_MARK,			;0xad
	C_LEFT_POINTING_GUILLEMET,			;0xae
	C_RIGHT_POINTING_GUILLEMET,			;0xaf

	C_LIGHT_SHADE,					;0xb0	graphics chars
	C_MEDIUM_SHADE,					;0xb1
	C_DARK_SHADE,					;0xb2
	C_FORMS_LIGHT_VERTICAL,				;0xb3
	C_FORMS_LIGHT_VERTICAL_AND_LEFT,		;0xb4
	C_LATIN_CAPITAL_LETTER_A_ACUTE,			;0xb5
	C_LATIN_CAPITAL_LETTER_A_CIRCUMFLEX,		;0xb6
	C_LATIN_CAPITAL_LETTER_A_GRAVE,			;0xb7
	C_COPYRIGHT_SIGN,				;0xb8
	C_FORMS_DOUBLE_VERTICAL_AND_LEFT,		;0xb9
	C_FORMS_DOUBLE_VERTICAL,			;0xba
	C_FORMS_DOUBLE_DOWN_AND_LEFT,			;0xbb
	C_FORMS_DOUBLE_UP_AND_LEFT,			;0xbc
	C_CENT_SIGN,					;0xbd
	C_YEN_SIGN,					;0xbe
	C_FORMS_LIGHT_DOWN_AND_LEFT,			;0xbf
	C_FORMS_LIGHT_UP_AND_RIGHT,			;0xc0
	C_FORMS_LIGHT_UP_AND_HORIZONTAL,		;0xc1
	C_FORMS_LIGHT_DOWN_AND_HORIZONTAL,		;0xc2
	C_FORMS_LIGHT_VERTICAL_AND_RIGHT,		;0xc3
	C_FORMS_LIGHT_HORIZONTAL,			;0xc4
	C_FORMS_LIGHT_VERTICAL_AND_HORIZONTAL,		;0xc5
	C_LATIN_SMALL_LETTER_A_TILDE,			;0xc6
	C_LATIN_CAPITAL_LETTER_A_TILDE,			;0xc7
	C_FORMS_DOUBLE_UP_AND_RIGHT,			;0xc8
	C_FORMS_DOUBLE_DOWN_AND_RIGHT,			;0xc9
	C_FORMS_DOUBLE_UP_AND_HORIZONTAL,		;0xca
	C_FORMS_DOUBLE_DOWN_AND_HORIZONTAL,		;0xcb
	C_FORMS_DOUBLE_VERTICAL_AND_RIGHT,		;0xcc
	C_FORMS_DOUBLE_HORIZONTAL,			;0xcd
	C_FORMS_DOUBLE_VERTICAL_AND_HORIZONTAL,		;0xce
	C_CURRENCY_SIGN,				;0xcf
	C_LATIN_SMALL_LETTER_ETH,			;0xd0
	C_LATIN_CAPITAL_LETTER_ETH,			;0xd1
	C_LATIN_CAPITAL_LETTER_E_CIRCUMFLEX,		;0xd2
	C_LATIN_CAPITAL_LETTER_E_DIAERESIS,		;0xd3
	C_LATIN_CAPITAL_LETTER_E_GRAVE,			;0xd4
	C_LATIN_SMALL_LETTER_DOTLESS_I,			;0xd5
	C_LATIN_CAPITAL_LETTER_I_ACUTE,			;0xd6
	C_LATIN_CAPITAL_LETTER_I_CIRCUMFLEX,		;0xd7
	C_LATIN_CAPITAL_LETTER_I_DIAERESIS,		;0xd8
	C_FORMS_LIGHT_UP_AND_LEFT,			;0xd9
	C_FORMS_LIGHT_DOWN_AND_RIGHT,			;0xda
	C_FULL_BLOCK,					;0xdb
	C_LOWER_HALF_BLOCK,				;0xdc
	C_BROKEN_VERTICAL_BAR,				;0xdd
	C_LATIN_CAPITAL_LETTER_I_GRAVE,			;0xde
	C_UPPER_HALF_BLOCK,				;0xdf	graphics chars

	C_LATIN_CAPITAL_LETTER_O_ACUTE,			;0xe0
	C_LATIN_SMALL_LETTER_SHARP_S,			;0xe1
	C_LATIN_CAPITAL_LETTER_O_CIRCUMFLEX,		;0xe2
	C_LATIN_CAPITAL_LETTER_O_GRAVE,			;0xe3
	C_LATIN_SMALL_LETTER_O_TILDE,			;0xe4
	C_LATIN_CAPITAL_LETTER_O_TILDE,			;0xe5
	C_MICRO_SIGN,					;0xe6
	C_LATIN_SMALL_LETTER_THORN,			;0xe7
	C_LATIN_CAPITAL_LETTER_THORN,			;0xe8
	C_LATIN_CAPITAL_LETTER_U_ACUTE,			;0xe9
	C_LATIN_CAPITAL_LETTER_U_CIRCUMFLEX,		;0xea
	C_LATIN_CAPITAL_LETTER_U_GRAVE,			;0xeb
	C_LATIN_SMALL_LETTER_Y_ACUTE,			;0xec
	C_LATIN_CAPITAL_LETTER_Y_ACUTE,			;0xed
	C_SPACING_MACRON,				;0xee
	C_SPACING_ACUTE,				;0xef
	C_SOFT_HYPHEN,					;0xf0
	C_PLUS_OR_MINUS_SIGN,				;0xf1
	C_SPACING_DOUBLE_UNDERSCORE,			;0xf2
	C_FRACTION_THREE_QUARTERS,			;0xf3
	C_PARAGRAPH_SIGN,				;0xf4
	C_SECTION_SIGN,					;0xf5
	C_DIVISION_SIGN,				;0xf6
	C_SPACING_CEDILLA,				;0xf7
	C_DEGREE_SIGN,					;0xf8
	C_SPACING_DIAERESIS,				;0xf9
	C_MIDDLE_DOT,					;0xfa
	C_SUPERSCRIPT_DIGIT_ONE,			;0xfb
	C_SUPERSCRIPT_DIGIT_THREE,			;0xfc
	C_SUPERSCRIPT_DIGIT_TWO,			;0xfd
	C_BLACK_SQUARE,					;0xfe
	C_NON_BREAKING_SPACE				;0xff
.assert ($-codePageMulti) eq 256

	ForceRef	codePageMulti

Resident	ends
