#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = pdfviewer
UI              = pdfvu.goc
MAIN            = catalog.goc stream.goc gfxState.goc page.goc xref.goc\
                  array.goc gfxFont.goc lexer.goc dict.goc gfx.goc\
                  parser.goc obj.goc
UTIL            = gmem.goc gstr.goc
UI_TO_RDFS      =
OBJS            = pdfvu.obj catalog.obj stream.obj gfxState.obj page.obj\
                  xref.obj array.obj gfxFont.obj lexer.obj dict.obj gfx.obj\
                  parser.obj obj.obj gmem.obj gstr.obj
COMMON          = obj.goh ccitt.h pdfvu.goh stream.goh gfxFont2.goh\
                  gfxFont.goh pdfGeode.goh catalog.goh gtypes.goh gstr.goh\
                  gmem.goh lexer.goh xref.goh page.goh array.goh parser.goh\
                  gfxState.goh diction.goh gfx.goh
MODULES         =
CMODULES        = ui main util
SRCS            = $(UI) $(MAIN) $(UTIL) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
