#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = CDex
DB              = dbUtils.goc Display.goc Record.goc Update.goc
DIAL            = dUtils.goc Phone.goc
FILE            = Document.goc
IMPEX           = Export.goc Import.goc
MAIN            = Edit.goc Exit.goc GeoDex.goc Init.goc mUtils.goc
MISC            = Ltrs.goc LtrsDrw.goc LtrTbInv.goc Search.goc View.goc\
                  Consts.goh Variable.goh
UI              = Strings.goc uiMain.goc
UI_TO_RDFS      =
OBJS            = dbUtils.obj Display.obj Record.obj Update.obj dUtils.obj\
                  Phone.obj Document.obj Export.obj Import.obj Edit.obj\
                  Exit.obj GeoDex.obj Init.obj mUtils.obj Ltrs.obj\
                  LtrsDrw.obj LtrTbInv.obj Search.obj View.obj Strings.obj\
                  uiMain.obj
COMMON          = cdex.goh
MODULES         =
CMODULES        = DB Dial File Impex Main Misc UI
SRCS            = $(DB) $(DIAL) $(FILE) $(IMPEX) $(MAIN) $(MISC) $(UI)\
                  $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
