#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = taskmax
ASM_TO_OBJS     = taskmaxManager.asm
UI_TO_RDFS      = taskmax.ui
SRCS            = taskmaxApplication.asm taskmaxClipboard.asm\
                  taskmaxDriver.asm taskmaxInitExit.asm taskmaxItem.asm\
                  taskmaxMain.asm taskmaxStrings.asm taskmaxSummons.asm\
                  taskmaxUtils.asm taskmaxManager.asm taskStrings.asm\
                  taskInit.asm taskSwitch.asm taskApplication.asm\
                  taskDriver.asm taskTrigger.asm taskItem.asm taskUtils.asm\
                  taskClipboard.asm taskmaxConstant.def taskmaxVariable.def\
                  taskmax.ui
OBJS            = taskmaxManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
