#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = sblaster
ASM_TO_OBJS     = soundblasterManager.asm
UI_TO_RDFS      =
SRCS            = soundblasterDAC.asm soundblasterError.asm\
                  soundblasterInit.asm soundblasterInt.asm\
                  soundblasterManager.asm soundblasterRegister.asm\
                  soundblasterStrategy.asm soundblasterStream.asm\
                  soundblasterTimeDelay.asm soundblasterVoice.asm\
                  soundblasterConstant.def soundblasterError.def\
                  soundblasterPCTimer.def
OBJS            = soundblasterManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
