#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = wccrtl
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = wcc_test_function.c wcc_test_function.h wccrtl.goc
OBJS            = wcc_test_function.obj wccrtl.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
