#!/bin/sh -
##############################################################################
#
#       Copyright (c) Geoworks 1995 -- All Rights Reserved
#
# PROJECT:      Productivity, hopefully.
# MODULE:       Tools
# FILE:         filterKey, a SH script
# AUTHOR:       Paul Canavese, November 30, 1995
#
# REVISION HISTORY:
#       Name     Date            Description
#       ----     ----            -----------
#       canavese 11/30/95        Initial Revision
#
# DESCRIPTION:
#	Takes standard input and includes text that matches the passed
#	key, and deletes text that does not match the inverse of the
#	key.  How's that?  Let's try an example.
#
#	Text file:
#		; This is an example file: foo.txt
#		KEY(I want this included)
#		NOT-KEY(I do not want this included)
#
#	Example:
#		% cat foo.txt | filterKey KEY
#		; This is an example file: foo.txt
#		I want this included
#		% cat foo.txt | filterKey NOT-KEY
#		; This is an example file: foo.txt
#		I do not want this included
#

if [ $# -eq 0 ]; then

   echo "Usage"
   echo "   filterKey [key]+"
   exit 0

fi

while [ $# -gt 0 ]; do

   case $1 in

	NOT-*)	base=`expr $1 : 'NOT-\(.*\)'`
		sed -e '/'$1'([^)]*)/s/'$1'(\([^)]*\))/\1/' \
		    -e '/'$base'([^)]*)/d';;
	*)	sed -e '/NOT-'$1'([^)]*)/d' \
		    -e '/'$1'([^)]*)/s/'$1'(\([^)]*\))/\1/';;
   esac
   shift

done


