#!/bin/sh -
##############################################################################
#
#       Copyright (c) Geoworks 1995 -- All Rights Reserved
#
# PROJECT:      Productivity, hopefully.
# MODULE:       Tools
# FILE:         makeIni, a SH script
# AUTHOR:       Paul Canavese, November 30, 1995
#
# REVISION HISTORY:
#       Name     Date            Description
#       ----     ----            -----------
#       canavese 11/30/95        Initial Revision
#
# DESCRIPTION:
#	Translates a template file into a usable .ini file for a particular
#	version of a product.
#
#	This script uses the geos.temp and/or net.temp files in the passed
#	directory as template files.  Based on the passed flags, the .ini
#	file is modified.
#
# SPECIAL STRINGS:
#	The makeIni script will specially handle the following strings in
#	the template files:
#
#	Comments:
#
# 		For comments only in the template file, start line with !
#
#	EC-related:
#					EC			NON-EC
#
#		EC-ext(fname)  		fname.ec		fname
#  		EC-net(fname)		fname.ec		fname.net
#  		EC-long(long name)	EC long name		long name
#  		EC-dos(fname,ext)	fnameec.ext		fname.ext
#					^^ truncated to 8 characters!
#  		EC-NEC(string1,string2)	string1			string2
#
#       $Id$
#
###############################################################################

set -xv
echo Hiya

usage() {
    echo "usage:"
    echo "makeIni [<country>] [ec] [diskset|server|rom|ram|gfs] \"
    echo "        [net|geos|both] <directory>"
    echo
    echo "   defaults: us, non-ec, diskset, both"
    echo "   <directory> should specify the product directory in"
    echo "     ProductFiles."
    echo
    echo "Example:  
    echo "   makeIni ec server /staff/pcgeos/Installed/ProductFiles/Gulliver"
    echo
    exit 1
}

#
# Defaults: us, non-ec, diskset
#
ec=
nec=1
country=us
media=diskset
dir=
keys=
bases=

while [ $# -gt 0 ]; do

   case $1 in

	# Country.

	german)		country=german;;
	dutch)		country=dutch;;
	uk)		country=uk;;
	us)		country=us;;

	# EC/non-EC.

	ec)		ec=ec
			nec="";;

	# Media.	

	disk*)		media=diskset;;
	serv*)		media=server;;
	rom)		media=rom;;
	ram)		media=ram;;
	gfs)		media=gfs;;

	# Base .ini file names.

	geos)		bases="$bases geos";;
	net)		bases="$bases net";;
	both)		bases="geos net";;

	# Directory.

	/*)		dir=$1;;

   esac
   shift

done

if [ "$bases" = "" ]; then
   bases="geos net"
fi

#
# Set up filter keys.
#

case $country in
   german) 	keys="$keys GERMAN NOT-DUTCH NOT-UK NOT-US";;
   dutch) 	keys="$keys NOT-GERMAN DUTCH NOT-UK NOT-US";;
   uk) 		keys="$keys NOT-GERMAN NOT-DUTCH UK NOT-US";;
   us)	 	keys="$keys NOT-GERMAN NOT-DUTCH NOT-UK US";;
esac

case $media in

   # PC Demo targets

   diskset) 	keys="$keys DISKSET NOT-SERVER NOT-ROM NOT-RAM NOT-GFS"
		keys="$keys NOT-PROTOTYPE PCDEMO";;
   server) 	keys="$keys NOT-DISKSET SERVER NOT-ROM NOT-RAM NOT-GFS"
		keys="$keys NOT-PROTOTYPE PCDEMO";;

   # Prototype targets

   rom) 	keys="$keys NOT-DISKSET NOT-SERVER ROM NOT-RAM NOT-GFS"
		keys="$keys PROTOTYPE NOT-PCDEMO";;
   ram) 	keys="$keys NOT-DISKSET NOT-SERVER NOT-ROM RAM NOT-GFS"
		keys="$keys PROTOTYPE NOT-PCDEMO";;
   gfs) 	keys="$keys NOT-DISKSET NOT-SERVER NOT-ROM NOT-RAM GFS"
		keys="$keys PROTOTYPE NOT-PCDEMO";;
esac

if [ "$ec" = "ec" ]; then
   keys="$keys EC"
else
   keys="$keys NOT-EC"
fi

#
# Handle each .ini file.
#

for base in $bases
do

   #
   # Determine and test for template file.
   #

   if [ ! -f $dir/$base.temp ]; then
	echo "$dir/$base.temp does not exist."
	exit 1
   fi

   #
   # Print out header, filter with keys, and delete comments
   #

   echo "Opening $base.temp..." 

   (echo "; This file generated automatically by makeIni."; \
    echo "; Generated on `date +'%D, %T, %a`"; \
    echo "; Country="$country" Media="$media" "$ec; \
    echo ""; \
    cat $dir/$base.temp) | \
   filterKey $keys |
   sed -e '/^!/d' \
	> /tmp/makeIni$$.1

   #
   # Do special EC handling.
   #

   if [ "$ec" = "ec" ]; then

	cat /tmp/makeIni$$.1 | \
	sed -e '/EC-EXT([^)]*)/s/EC-EXT(\([^)]*\))/\1.ec/' \
	    -e '/EC-NET([^)]*)/s/EC-NET(\([^)]*\))/\1.ec/' \
	    -e '/EC-LONG([^)]*)/s/EC-LONG(\([^)]*\))/EC \1/' \
	    -e '/EC-NEC([^)]*)/s/EC-NEC(\([^),]*\),\([^)]*\))/\1/' \
	    -e '/EC-DOS([^),]*,[^)]*)z/s/EC-DOS(\([^),]*\),\([^)]*\))/@S@\1ec@E@.\2/' \
	    -e '/@S@.*@E@/s/@S@\([^.]\{1,8\}\)[^.]*@E@/\1/' \
		> /tmp/makeIni$$.2

   else

	cat /tmp/makeIni$$.2 | \
	sed -e '/EC-EXT([^)]*)/s/EC-EXT(\([^)]*\))/\1/' \
	    -e '/EC-NET([^)]*)/s/EC-NET(\([^)]*\))/\1.net/' \
	    -e '/EC-LONG([^)]*)/s/EC-LONG(\([^)]*\))/\1/' \
	    -e '/EC-NEC([^)]*)/s/EC-NEC(\([^),]*\),\([^)]*\))/\2/' \
	    -e '/EC-DOS([^),]*,[^)]*)/s/EC-DOS(\([^),]*\),\([^)]*\))/\1.\2/' \
		> /tmp/makeIni$$.2
   fi

   #
   # Copy file to the right place.
   #

   cp /tmp/makeIni$$.2 $dir/$country/$media/$base$ec.ini
   echo "$dir/$country/$media/$base$ec.ini created."

   #
   # Remove temporary files.
   #

   echo "Removing temporary files..."
   rm -f /tmp/makeIni$$.*

done

