MSLFMANAGER.obj \
MSLFMANAGER.eobj: DOSGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF RESOURCE.DEF \
                EC.DEF LMEM.DEF SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF \
                DRIVE.DEF DISK.DEF FILE.DEF DRIVER.DEF TIMEDATE.DEF \
                SEM.DEF TIMER.DEF INITFILE.DEF GCNLIST.DEF \
                OBJECTS/METAC.DEF OBJECT.DEF CHUNKARR.DEF GEOWORKS.DEF \
                GRAPHICS.DEF FONTID.DEF FONT.DEF COLOR.DEF \
                INTERNAL/SEMINT.DEF INTERNAL/INTERRUP.DEF \
                INTERNAL/DOS.DEF FILEENUM.DEF INTERNAL/FILEINT.DEF \
                INTERNAL/DRIVEINT.DEF INTERNAL/DISKINT.DEF \
                INTERNAL/FSD.DEF INTERNAL/LOG.DEF INTERNAL/HEAPINT.DEF \
                SYSSTATS.DEF INTERNAL/GEODESTR.DEF INTERNAL/FILESTR.DEF \
                INTERNAL/LOCALINT.DEF CHAR.DEF INTERNAL/FSDRIVER.DEF \
                INTERNAL/DOSFSDR.DEF INTERNAL/PRODFEATURES.DEF ASSERT.DEF \
                MSLFINTERFACE.DEF DOSCONSTANT.DEF DOSMACRO.DEF \
                DOSSTRINGS.ASM DOSVARIABLE.DEF MSLFSTRINGS.ASM \
                MSVARIABLE.DEF DOSENTRY.ASM DOSDISK.ASM DOSDRIVE.ASM \
                MSDRIVE.ASM DOSPATH.ASM DOSENUM.ASM DOSFORMAT.ASM \
                DOSFORMATINIT.ASM DOSDISKCOPY.ASM DOSIO.ASM \
                DOSPRIMARY.ASM DOSINITEXIT.ASM MSINITEXIT.ASM \
                DOSCRITICAL.ASM DOSUTILS.ASM DOSVIRTUAL.ASM \
                DOSWAITPOST.ASM THREAD.DEF MSSFT.ASM DOSSUSPEND.ASM \
                DOSLINK.ASM DOSIDLE.ASM DOSFILECHANGE.ASM

MSLFEC.geo MSLF.geo : GEOS.LDF 