#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = CHARM
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = APPUI.GOC MAP.GOC PROCESS.GOC TEXT.GOC APP.GOH GLOBAL.GOH
OBJS            = APPUI.obj MAP.obj PROCESS.obj TEXT.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
