rem All Rem'd so I don't accidentally regenerate ;-)

rem cvtpcx -2 -w90 -h60 -m1 -G -nQTip1 -oQTip1.goh tip1.pcx
rem cvtpcx -2 -w90 -h60 -m1 -G -nQTip2a -oQTip2a.goh tip2a.pcx
rem cvtpcx -2 -w90 -h60 -m1 -G -nQTip2b -oQTip2b.goh tip2b.pcx

rem cvtpcx -2 -w72 -h42 -m1 -G -nQTCheat -oQTCheat.goh hint1.pcx
rem cvtpcx -2 -w78 -h52 -m1 -G -nQTMove -oQTMove.goh hint2a.pcx
rem cvtpcx -2 -w50 -h52 -m1 -G -nQTSize -oQTSize.goh hint2b.pcx

