#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = Safari2
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = safari2App.goc safari2File.goc safari2Game.goc\
                  safari2Quiz.goc safari2Timer.goc safari2UI.goc global.goh\
                  safari2.goh
OBJS            = safari2App.obj safari2File.obj safari2Game.obj\
                  safari2Quiz.obj safari2Timer.obj safari2UI.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
