#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = FREECELL
ASM_TO_OBJS     = freecellManager.asm
UI_TO_RDFS      = FREECELL.UI
SRCS            = freecellSound.asm freecellGame.asm freecellManager.asm\
                  freecell.asm freecell.def freecellMacros.def freecell.ui
OBJS            = freecellManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
