#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = modem
LIBNAME         = modem
PROTOCONST      = MODEM
ASM_TO_OBJS     = modemManager.asm
UI_TO_RDFS      =
SRCS            = modemAdmin.asm modemEC.asm modemManager.asm\
                  modemParse.asm modemSend.asm modemStrategy.asm modem.def
OBJS            = modemManager.obj
LOBJS           =

PRODUCTS        = DBCS

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(DBCS/$(DEPFILE))
#include "DBCS/$(DEPFILE)"
#endif
