#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = xwm
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = EXPORT.GOC PROCESS.GOC XWMUI.GOC Import.goc BBOXREG.GOH\
                  EXTERNS.GOH DOCICON.GOH XWM.GOH APPICON.GOH DOC.GOH\
                  APP.GOH
OBJS            = EXPORT.obj PROCESS.obj XWMUI.obj Import.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
