#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = ttoolins
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = RES1A.GOC RES1B.GOC RES1C.GOC RES1D.GOC RES1E.GOC\
                  RESA.GOC RESAA.GOC RESAB.GOC RESAC.GOC RESB.GOC RESC.GOC\
                  RESD.GOC RESE.GOC RESF.GOC RESG.GOC RESH.GOC RESI.GOC\
                  RESJ.GOC RESK.GOC RESL.GOC RESM.GOC RESN.GOC RESO.GOC\
                  RESP.GOC RESQ.GOC RESR.GOC RESS.GOC REST.GOC RESU.GOC\
                  RESV.GOC RESW.GOC RESX.GOC RESY.GOC RESZ.GOC ttoolins.goc\
                  TTI_ICON.GOH
OBJS            = RES1A.obj RES1B.obj RES1C.obj RES1D.obj RES1E.obj\
                  RESA.obj RESAA.obj RESAB.obj RESAC.obj RESB.obj RESC.obj\
                  RESD.obj RESE.obj RESF.obj RESG.obj RESH.obj RESI.obj\
                  RESJ.obj RESK.obj RESL.obj RESM.obj RESN.obj RESO.obj\
                  RESP.obj RESQ.obj RESR.obj RESS.obj REST.obj RESU.obj\
                  RESV.obj RESW.obj RESX.obj RESY.obj RESZ.obj ttoolins.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
