#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = numbers
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = Main.goc Process.goc Content.goc SCREEN.goc sounds.goc\
                  PASSWORD.goc Vis.goc Peditor.goc DOCUMENT.goc hlapp.goh\
                  bboxreg.goh password.goh passwdui.goh numbers.goh
OBJS            = Main.obj Process.obj Content.obj SCREEN.obj sounds.obj\
                  PASSWORD.obj Vis.obj Peditor.obj DOCUMENT.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
