#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = numbers
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = Content.goc Main.goc Peditor.goc Process.goc DOCUMENT.GOC\
                  SCREEN.GOC Vis.goc PASSWORD.GOC sounds.goc Hlapp.goh\
                  Numbers.goh PASSWDUI.GOH PASSWORD.GOH BBOXREG.GOH
OBJS            = Content.obj Main.obj Peditor.obj Process.obj DOCUMENT.obj\
                  SCREEN.obj Vis.obj PASSWORD.obj sounds.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
