#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = SwarmPref
ASM_TO_OBJS     = swarmpref.asm
UI_TO_RDFS      = SWARMPREF.UI
SRCS            = swarmpref.asm swarmpref.ui
OBJS            = swarmpref.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
