ARTICLE.obj \
ARTICLE.eobj: Article/ArticleMANAGER.ASM \
                WRITEGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF EC.DEF \
                OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF \
                COLOR.DEF CHUNKARR.DEF FILE.DEF VM.DEF DBASE.DEF CHAR.DEF \
                INPUT.DEF HWR.DEF THREAD.DEF PRODUCT.DEF \
                INTERNAL/THREADIN.DEF OBJECTS/WINC.DEF WIN.DEF \
                OBJECTS/METAC.DEF GEOWORKS.DEF OBJECTS/INPUTC.DEF \
                RESOURCE.DEF UI.DEF TEXT.DEF LOCALIZE.DEF SLLANG.DEF \
                OBJECTS/PROCESSC.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF OBJECTS/VLTEXTC.DEF \
                IMPEX.DEF IECOMMON.DEF RULER.DEF GROBJ.DEF \
                OBJECTS/SPLINE.DEF OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF \
                BITMAP.DEF SSMETA.DEF WRITECONSTANT.DEF WRITEDOCUMENT.DEF \
                SYSTEM.DEF INITFILE.DEF USERINFO.DEF \
                OBJECTS/TEXT/TCTRLC.DEF SPELL.DEF WRITEARTICLE.DEF \
                ARTICLEARTICLE.ASM
DOCUMENT.obj \
DOCUMENT.eobj: Document/DocumentMANAGER.ASM \
                WRITEGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF EC.DEF \
                OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF \
                COLOR.DEF CHUNKARR.DEF FILE.DEF VM.DEF DBASE.DEF CHAR.DEF \
                INPUT.DEF HWR.DEF THREAD.DEF PRODUCT.DEF \
                INTERNAL/THREADIN.DEF OBJECTS/WINC.DEF WIN.DEF \
                OBJECTS/METAC.DEF GEOWORKS.DEF OBJECTS/INPUTC.DEF \
                RESOURCE.DEF UI.DEF TEXT.DEF LOCALIZE.DEF SLLANG.DEF \
                OBJECTS/PROCESSC.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF OBJECTS/VLTEXTC.DEF \
                IMPEX.DEF IECOMMON.DEF RULER.DEF GROBJ.DEF \
                OBJECTS/SPLINE.DEF OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF \
                BITMAP.DEF SSMETA.DEF WRITECONSTANT.DEF WRITEDOCUMENT.DEF \
                SYSTEM.DEF INITFILE.DEF USERINFO.DEF \
                OBJECTS/TEXT/TCTRLC.DEF SPELL.DEF WRITEAPPLICATION.DEF \
                WRITEDISPLAY.DEF GSTRING.DEF LIBRARY.DEF \
                INTERNAL/GRWININT.DEF INTERNAL/CONVERT.DEF COMPRESS.DEF \
                HELPFILE.DEF MATH.DEF CELL.DEF PARSE.DEF SSHEET.DEF \
                WRITEARTICLE.DEF WRITEGROBJHEAD.DEF WRITEGROBJBODY.DEF \
                WRITEHDRFTR.DEF FLOWREGION.DEF PAGEINFO.DEF ASSERT.DEF \
                DOCUMENTMANAGER.RDEF DOCUMENTDATA.ASM \
                DOCUMENTDOCUMENT.ASM DOCUMENTOPENCLOSE.ASM TIMER.DEF \
                DOCUMENTCONTENT.ASM DOCUMENTARTICLE.ASM \
                DOCUMENTSECTION.ASM DOCUMENTPAGE.ASM DOCUMENTDRAW.ASM \
                DOCUMENTMANIP.ASM DOCUMENTUTILS.ASM DOCUMENTFLOW.ASM \
                DOCUMENTFRAME.ASM DOCUMENTNOTIFY.ASM DOCUMENTMISC.ASM \
                DOCUMENTPRINT.ASM DOCUMENTMERGE.ASM \
                DOCUMENTMERGESCRAP.ASM DOCUMENTHEAD.ASM \
                DOCUMENTATTRMGR.ASM DOCUMENTBODY.ASM DOCUMENTHDRFTR.ASM \
                DOCUMENTUSERSECTION.ASM DOCUMENTPAGESETUP.ASM \
                DOCUMENTREGION.ASM DOCUMENTMASTERPAGE.ASM \
                DOCUMENTDISPLAY.ASM DOCUMENTSCROLL.ASM DOCUMENTIMPEX.ASM \
                DOCUMENTVARIABLE.ASM DOCUMENTCONVERT.ASM DOCUMENTHELP.ASM \
                DOCUMENTSEARCHSP.ASM
MAIN.obj \
MAIN.eobj: Main/MainMANAGER.ASM \
                WRITEGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF EC.DEF \
                OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF \
                COLOR.DEF CHUNKARR.DEF FILE.DEF VM.DEF DBASE.DEF CHAR.DEF \
                INPUT.DEF HWR.DEF THREAD.DEF PRODUCT.DEF \
                INTERNAL/THREADIN.DEF OBJECTS/WINC.DEF WIN.DEF \
                OBJECTS/METAC.DEF GEOWORKS.DEF OBJECTS/INPUTC.DEF \
                RESOURCE.DEF UI.DEF TEXT.DEF LOCALIZE.DEF SLLANG.DEF \
                OBJECTS/PROCESSC.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF OBJECTS/VLTEXTC.DEF \
                IMPEX.DEF IECOMMON.DEF RULER.DEF GROBJ.DEF \
                OBJECTS/SPLINE.DEF OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF \
                BITMAP.DEF SSMETA.DEF WRITECONSTANT.DEF WRITEPROCESS.DEF \
                WRITEDOCUMENT.DEF SYSTEM.DEF INITFILE.DEF USERINFO.DEF \
                OBJECTS/TEXT/TCTRLC.DEF SPELL.DEF WRITEAPPLICATION.DEF \
                WRITEARTICLE.DEF FLOWREGION.DEF MAINPROCESS.ASM \
                FILEENUM.DEF LIBRARY.DEF INTERNAL/XLATLIB.DEF MAINAPP.ASM \
                MAINAPPUI.ASM
UI.obj \
UI.eobj: UI/UIMANAGER.ASM \
                WRITEGEODE.DEF GEOS.DEF HEAP.DEF GEODE.DEF EC.DEF \
                OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF FONT.DEF \
                COLOR.DEF CHUNKARR.DEF FILE.DEF VM.DEF DBASE.DEF CHAR.DEF \
                INPUT.DEF HWR.DEF THREAD.DEF PRODUCT.DEF \
                INTERNAL/THREADIN.DEF OBJECTS/WINC.DEF WIN.DEF \
                OBJECTS/METAC.DEF GEOWORKS.DEF OBJECTS/INPUTC.DEF \
                RESOURCE.DEF UI.DEF TEXT.DEF LOCALIZE.DEF SLLANG.DEF \
                OBJECTS/PROCESSC.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                DISK.DEF DRIVE.DEF UDIALOG.DEF OBJECTS/GINTERC.DEF \
                TOKEN.DEF OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF \
                OBJECTS/GPROCC.DEF ALB.DEF OBJECTS/GFIELDC.DEF \
                OBJECTS/GSCREENC.DEF OBJECTS/GFSELC.DEF \
                OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF OBJECTS/GCTRLC.DEF \
                OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                OBJECTS/VTEXTC.DEF SPOOL.DEF PRINT.DEF \
                INTERNAL/PRODFEATURES.DEF HUGEARR.DEF OBJECTS/VLTEXTC.DEF \
                IMPEX.DEF IECOMMON.DEF RULER.DEF GROBJ.DEF \
                OBJECTS/SPLINE.DEF OBJECTS/COLORC.DEF OBJECTS/STYLES.DEF \
                BITMAP.DEF SSMETA.DEF SPELL.DEF WRITECONSTANT.DEF \
                WRITEDOCUMENT.DEF SYSTEM.DEF INITFILE.DEF USERINFO.DEF \
                OBJECTS/TEXT/TCTRLC.DEF WRITEAPPLICATION.DEF \
                WRITEPROCESS.DEF WRITEDISPLAY.DEF WRITESUPERIMPEX.DEF \
                GSTRING.DEF WRITEGROBJHEAD.DEF PAGEINFO.DEF \
                UIMANAGER.RDEF UISUPERIC.ASM UIWRITEDC.ASM FILEENUM.DEF \
                UITEMPLATE.ASM UIGIFIMAGE.ASM UIGIFIMAGE.DEF
DOCUMENTMANAGER.rdef: GENERIC.UIH PRODUCT.UIH GROBJ.UIH OBJECTS/COLORC.UIH \
                OBJECTS/STYLES.UIH BITMAP.UIH OBJECTS/TEXT/TCTRL.UIH \
                RULER.UIH DOCUMENT/DOCUMENTDATA.UI
UIMANAGER.rdef: GENERIC.UIH PRODUCT.UIH IMPEX.UIH SPOOL.UIH GROBJ.UIH \
                OBJECTS/COLORC.UIH OBJECTS/STYLES.UIH BITMAP.UIH \
                OBJECTS/TEXT/TCTRL.UIH RULER.UIH SPELL.UIH \
                OBJECTS/SPLINE.UIH INTERNAL/PRODFEATURES.UIH \
                UI/UIWRITE.UIH UI/UIMAIN.UI ART/MKREDITTEXTTOOL.UI \
                ART/MKRBITMAPPTRTOOL.UI ART/MKRGEOWRITE.UI \
                ART/MKRGEOWRITETINY.UI UI/UIPRINT.UI UI/UIPAGESETUP.UI \
                UI/UIEDIT.UI UI/UIVIEW.UI UI/UIOPTIONS.UI USRLEVEL.UIH \
                UI/UILAYOUT.UI UI/UIGRAPHICS.UI UI/UITEXT.UI \
                UI/UIHELPEDIT.UI UI/UIDOCUMENT.UI UI/UIDISPLAY.UI \
                UI/UIDOCMONIKER.UI ART/MKRGEOWRITEDOC.UI UI/UITEMPLATE.UI \
                ART/WIZARDHEADER.UI ART/MKRWIZARDPREV.UI \
                ART/MKRWIZARDNEXT.UI

writeEC.geo write.geo : GEOS.LDF UI.LDF TEXT.LDF GROBJ.LDF RULER.LDF BITMAP.LDF SPOOL.LDF IMPEX.LDF SPELL.LDF STYLES.LDF SPLINE.LDF COLOR.LDF SSMETA.LDF CONVERT.LDF COMPRESS.LDF MAILBOX.LDF 