#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = oliner
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = ui.goc strings.goc pprev.goc doc.goc move.goc find.goc\
                  proc.goc functs.goc ecall.goc oliner.goh
OBJS            = ui.obj strings.obj pprev.obj doc.obj move.obj find.obj\
                  proc.obj functs.obj ecall.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
