#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = oliner
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = doc.goc ecall.goc find.goc functs.goc move.goc pprev.goc\
                  proc.goc strings.goc ui.goc oliner.goh
OBJS            = doc.obj ecall.obj find.obj functs.obj move.obj pprev.obj\
                  proc.obj strings.obj ui.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
