#!/usr/bin/sh
#
##############################################################################
#
# 	Copyright (c) GeoWorks 1992 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Shell scripts
# FILE: 	makeJediIntlIni
# AUTHOR: 	Chris Boyke, Aug  13, 1993
#		Andrew Wilson, ???, 1994	- XIP for Bullet
#		Todd Stumpf, Aug 22, 1994	- XIP for Jedi
#		clee, Aug 14th, 1995.		- XIP for Intl. Jedi
#
# DESCRIPTION:
#
#   This script merges the English net.ini with international version-
#   specific changes, to create the international net.ini file
#
#
#
# USAGE:
# 	Current directory must be /s/p/Jedi<language>/ProductFiles/Jedi
#
# 	$Id: makeJediIntlIni,v 1.1 95/09/20 17:07:22 cthomas Exp $
#
#

baseIni=/staff/pcgeos/ReleaseJedi/Installed/ProductFiles/Jedi/net.ini
diffIni=diff.ini
destIni=net.ini

# backup original

mv -f $destIni $destIni.bak

#
#
# Merge in changes, AND
#
# make sure the ini file is dosified.  First, un-dosify it, so we're sure
# there are no CR/LF combos to start with (unix2dos doesn't care if
# a line already has one before it adds another)
#

mergeini $baseIni $diffIni | dos2unix | unix2dos > $destIni

