#! /bin/sh 

#
# This script is to ship the XIP geodes download to novell network. We only
# want to do that when we want to make those geodes to be translated.
#
# Syntax:
#	shipXIP (PC | PC_EC | PC_XIP | PC_XIP_EC | JEDI_XIP) [language]
#
#
# Example:
#	shipXIP JEDI_XIP French
#

#
# IMPORTANT: When you use this script as the template to create another 
#	     international version of the product, there are some places
#	     you need to change:
#		1) destDir
#		2) fileList
#		3) srcDir
#		4) pcOnlyList
#
# $Id: shipXIP,v 1.7 95/09/27 18:03:18 cthomas Exp $
#

# set -x

#
# Check for the valid input parameters.
#
case $# in
0)	echo "usage: $0 (PC | PC_EC | PC_XIP | PC_XIP_EC | JEDI_XIP) [language]"
	exit 1;;
1 | 2)	# Version argument will be checked by the jediGeodes script
	;;
*)	echo "$0 -- Too many arguments."
	exit 1;;
esac

version=$1
language=$2


#
# determine Ec-ness of version
#
case $version in
*_EC)
	ec="ec"
	branchec=".ec"
	nonec=
	;;
*)
	ec=
	branchec=
	nonec="-n"
	;;
esac

#
# Determine whre geodes go
#

case $version in
PC_XIP*)
	destBranch=pcxip
	;;
PC*)
	destBranch=pc
	;;
JEDI_XIP)
	destBranch=jedixip
	;;
esac

if [ "$language" ] ; then
	case "$language" in 
	[Ff][Rr]*)
		shortLang=fr
		;;
	[Gg][EeRr]*)
		shortLang=gr
		;;
	[Ii][Tt]*)
		shortLang=it
		;;
	[Pp][Oo]*)
		shortLang=po
		;;
	[Ss][Pp]*)
		shortLang=sp
		;;
	*)
		echo "$0: Invalid language"
		exit 1
		;;
	esac
fi

srcDir="/staff/pcgeos/ReleaseJedi/Installed"

if [ "$shortLang" ] ; then
	destBaseDir="/n/company/jedi/src/$shortLang"
else
	destBaseDir="/n/company/jedi/src/common"
fi

destDir=$destBaseDir/${destBranch}${branchec}
send="pcs -u -v $nonec -d${destDir}"

fileList=`/staff/pcgeos/Tools/scripts/products/jedi/intl/jediGeodes $version ${language}`

if [ $? -ne 0 ] ; then
	exit 1
fi

curDir=`pwd`

echo "Go to $srcDir ..."
cd $srcDir
PWD=$srcDir
export PWD

if [ -d $destDir ]; then
	if [ -d ${destDir}b ] ; then
		rm -rf ${destDir}b
	fi
	mv -f $destDir ${destDir}b
	mkdir -p $destDir
fi

for i in $fileList
do
#	echo "Sending $i down to $destDir"
	filePath=`echo "$i" | sed 's/\/[^/][^/]*\.geo//`
	$send $filePath
done

echo "Download done."
cd $curDir
exit 0
