#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = HB10
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = DOC_MTDS.GOC DTA_MTDS.GOC EXP_MTDS.GOC FLD_MTDS.GOC\
                  HBASE.GOC IMP_MTDS.GOC NAV_MTDS.GOC RPT_MTDS.GOC\
                  SCH_MTDS.GOC TXT_STRS.GOC BBLOGO.GOH BTNS.GOH HBASE.GOH\
                  HBICONS.GOH
OBJS            = DOC_MTDS.obj DTA_MTDS.obj EXP_MTDS.obj FLD_MTDS.obj\
                  HBASE.obj IMP_MTDS.obj NAV_MTDS.obj RPT_MTDS.obj\
                  SCH_MTDS.obj TXT_STRS.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
