DB.obj \
DB.eobj: DB/DBMANAGER.ASM \
                GEODEXGEODE.DEF GEOS.DEF HEAP.DEF RESOURCE.DEF EC.DEF \
                GEODE.DEF OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF WIN.DEF \
                TIMER.DEF VM.DEF THREAD.DEF FILE.DEF INPUT.DEF HWR.DEF \
                SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF DRIVER.DEF \
                INITFILE.DEF LIBRARY.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                PRODUCT.DEF INTERNAL/PRODFEATURES.DEF \
                INTERNAL/VIDEODR.DEF HUGEARR.DEF UI.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SPOOL.DEF PRINT.DEF DBASE.DEF OBJECTS/VTEXTC.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF IMPEX.DEF IECOMMON.DEF FFILE.DEF \
                MATH.DEF SSMETA.DEF INTERNAL/CONVERT.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/SERIALDR.DEF ROLODEX.DEF \
                CALENDAR.DEF GEODEXCONSTANT.DEF GEODEXGLOBAL.DEF \
                GEODEXMACRO.DEF DBVARIABLE.DEF DBDISPLAY.ASM DBRECORD.ASM \
                DBUPDATE.ASM DBUTILS.ASM
DIAL.obj \
DIAL.eobj: Dial/DialMANAGER.ASM \
                GEODEXGEODE.DEF GEOS.DEF HEAP.DEF RESOURCE.DEF EC.DEF \
                GEODE.DEF OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF WIN.DEF \
                TIMER.DEF VM.DEF THREAD.DEF FILE.DEF INPUT.DEF HWR.DEF \
                SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF DRIVER.DEF \
                INITFILE.DEF LIBRARY.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                PRODUCT.DEF INTERNAL/PRODFEATURES.DEF \
                INTERNAL/VIDEODR.DEF HUGEARR.DEF UI.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SPOOL.DEF PRINT.DEF DBASE.DEF OBJECTS/VTEXTC.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF IMPEX.DEF IECOMMON.DEF FFILE.DEF \
                MATH.DEF SSMETA.DEF INTERNAL/CONVERT.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/SERIALDR.DEF ROLODEX.DEF \
                CALENDAR.DEF GEODEXCONSTANT.DEF GEODEXGLOBAL.DEF \
                GEODEXMACRO.DEF DIALVARIABLE.DEF DIALMODEM.ASM \
                DIALPHONE.ASM DIALQUICKDIAL.ASM DIALUTILS.ASM
FILE.obj \
FILE.eobj: File/FileMANAGER.ASM \
                
IMPEX.obj \
IMPEX.eobj: Impex/ImpexMANAGER.ASM \
                GEODEXGEODE.DEF GEOS.DEF HEAP.DEF RESOURCE.DEF EC.DEF \
                GEODE.DEF OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF WIN.DEF \
                TIMER.DEF VM.DEF THREAD.DEF FILE.DEF INPUT.DEF HWR.DEF \
                SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF DRIVER.DEF \
                INITFILE.DEF LIBRARY.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                PRODUCT.DEF INTERNAL/PRODFEATURES.DEF \
                INTERNAL/VIDEODR.DEF HUGEARR.DEF UI.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SPOOL.DEF PRINT.DEF DBASE.DEF OBJECTS/VTEXTC.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF IMPEX.DEF IECOMMON.DEF FFILE.DEF \
                MATH.DEF SSMETA.DEF INTERNAL/CONVERT.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/SERIALDR.DEF ROLODEX.DEF \
                CALENDAR.DEF GEODEXCONSTANT.DEF GEODEXGLOBAL.DEF \
                GEODEXMACRO.DEF IMPEXVARIABLE.DEF CELL.DEF PARSE.DEF \
                SSHEET.DEF IMPEXIMPORT.ASM IMPEXEXPORT.ASM
MAIN.obj \
MAIN.eobj: Main/MainMANAGER.ASM \
                GEODEXGEODE.DEF GEOS.DEF HEAP.DEF RESOURCE.DEF EC.DEF \
                GEODE.DEF OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF WIN.DEF \
                TIMER.DEF VM.DEF THREAD.DEF FILE.DEF INPUT.DEF HWR.DEF \
                SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF DRIVER.DEF \
                INITFILE.DEF LIBRARY.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                PRODUCT.DEF INTERNAL/PRODFEATURES.DEF \
                INTERNAL/VIDEODR.DEF HUGEARR.DEF UI.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SPOOL.DEF PRINT.DEF DBASE.DEF OBJECTS/VTEXTC.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF IMPEX.DEF IECOMMON.DEF FFILE.DEF \
                MATH.DEF SSMETA.DEF INTERNAL/CONVERT.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/SERIALDR.DEF ROLODEX.DEF \
                CALENDAR.DEF GEODEXCONSTANT.DEF GEODEXGLOBAL.DEF \
                GEODEXMACRO.DEF MAINVARIABLE.DEF MAINEXIT.ASM \
                MAININIT.ASM MAINGEODEX.ASM MAINUTILS.ASM MAINEDIT.ASM
MISC.obj \
MISC.eobj: Misc/MiscMANAGER.ASM \
                GEODEXGEODE.DEF GEOS.DEF HEAP.DEF RESOURCE.DEF EC.DEF \
                GEODE.DEF OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF WIN.DEF \
                TIMER.DEF VM.DEF THREAD.DEF FILE.DEF INPUT.DEF HWR.DEF \
                SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF DRIVER.DEF \
                INITFILE.DEF LIBRARY.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                PRODUCT.DEF INTERNAL/PRODFEATURES.DEF \
                INTERNAL/VIDEODR.DEF HUGEARR.DEF UI.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SPOOL.DEF PRINT.DEF DBASE.DEF OBJECTS/VTEXTC.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF IMPEX.DEF IECOMMON.DEF FFILE.DEF \
                MATH.DEF SSMETA.DEF INTERNAL/CONVERT.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/SERIALDR.DEF ROLODEX.DEF \
                CALENDAR.DEF GEODEXCONSTANT.DEF GEODEXGLOBAL.DEF \
                GEODEXMACRO.DEF MISCVARIABLE.DEF MISCCONSTANT.DEF \
                MISCTOPCOLORBITMAP.ASM MISCTOPBWBITMAP.ASM \
                MISCMIDDLECOLORBITMAP.ASM MISCMIDDLEBWBITMAP.ASM \
                MISCMIDDLECGABITMAP.ASM MISCBOTTOMCOLORBITMAP.ASM \
                MISCBOTTOMBWBITMAP.ASM MISCSEARCH.ASM MISCLETTERS.ASM \
                MISCLETTERTABINVERT.ASM MISCLETTERSDRAW.ASM MISCTITLE.ASM \
                MISCPRINT.ASM MISCVIEWMENU.ASM MISCUTILS.ASM
UI.obj \
UI.eobj: UI/UIMANAGER.ASM \
                GEODEXGEODE.DEF GEOS.DEF HEAP.DEF RESOURCE.DEF EC.DEF \
                GEODE.DEF OBJECT.DEF LMEM.DEF GRAPHICS.DEF FONTID.DEF \
                FONT.DEF COLOR.DEF GSTRING.DEF TEXT.DEF CHAR.DEF WIN.DEF \
                TIMER.DEF VM.DEF THREAD.DEF FILE.DEF INPUT.DEF HWR.DEF \
                SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF DRIVER.DEF \
                INITFILE.DEF LIBRARY.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                PRODUCT.DEF INTERNAL/PRODFEATURES.DEF \
                INTERNAL/VIDEODR.DEF HUGEARR.DEF UI.DEF \
                OBJECTS/PROCESSC.DEF OBJECTS/METAC.DEF CHUNKARR.DEF \
                GEOWORKS.DEF GCNLIST.DEF TIMEDATE.DEF \
                OBJECTS/TEXT/TCOMMON.DEF STYLESH.DEF IACP.DEF \
                OBJECTS/UIINPUTC.DEF OBJECTS/VISC.DEF OBJECTS/VCOMPC.DEF \
                OBJECTS/VCNTC.DEF INTERNAL/VUTILS.DEF OBJECTS/GENC.DEF \
                UDIALOG.DEF OBJECTS/GINTERC.DEF TOKEN.DEF \
                OBJECTS/CLIPBRD.DEF OBJECTS/GSYSC.DEF OBJECTS/GPROCC.DEF \
                ALB.DEF OBJECTS/GFIELDC.DEF OBJECTS/GSCREENC.DEF \
                OBJECTS/GFSELC.DEF OBJECTS/GVIEWC.DEF OBJECTS/GCONTC.DEF \
                OBJECTS/GCTRLC.DEF OBJECTS/GDOCC.DEF OBJECTS/GDOCCTRL.DEF \
                OBJECTS/GDOCGRPC.DEF OBJECTS/GEDITCC.DEF \
                OBJECTS/GVIEWCC.DEF OBJECTS/GTOOLCC.DEF \
                OBJECTS/GPAGECC.DEF OBJECTS/GPENICC.DEF \
                OBJECTS/GGLYPHC.DEF OBJECTS/GTRIGC.DEF \
                OBJECTS/GBOOLGC.DEF OBJECTS/GITEMGC.DEF \
                OBJECTS/GDLISTC.DEF OBJECTS/GITEMC.DEF OBJECTS/GBOOLC.DEF \
                OBJECTS/GDISPC.DEF OBJECTS/GDCTRLC.DEF OBJECTS/GPRIMC.DEF \
                OBJECTS/GAPPC.DEF OBJECTS/GTEXTC.DEF OBJECTS/GGADGETC.DEF \
                OBJECTS/GVALUEC.DEF OBJECTS/GTOOLGC.DEF \
                INTERNAL/GUTILS.DEF OBJECTS/HELPCC.DEF OBJECTS/EMENUC.DEF \
                OBJECTS/EMOMC.DEF OBJECTS/EMTRIGC.DEF INTERNAL/UPROCC.DEF \
                SPOOL.DEF PRINT.DEF DBASE.DEF OBJECTS/VTEXTC.DEF \
                OBJECTS/TEXT/TCTRLC.DEF RULER.DEF OBJECTS/COLORC.DEF \
                OBJECTS/STYLES.DEF IMPEX.DEF IECOMMON.DEF FFILE.DEF \
                MATH.DEF SSMETA.DEF INTERNAL/CONVERT.DEF \
                INTERNAL/STREAMDR.DEF INTERNAL/SERIALDR.DEF ROLODEX.DEF \
                CALENDAR.DEF GEODEXCONSTANT.DEF GEODEXGLOBAL.DEF \
                GEODEXMACRO.DEF MAILBOX/SPOOLTD.DEF MAILBOX/FAXSENDTD.DEF \
                UIMAIN.RDEF
UIMAIN.rdef: 