#!/bin/sh -
#
#
# Project:	PC GEOS
# Module:	Solitaire
# File:		convert
#
# Author:	atw
#
#	This file contains the convert information for this application.
#
# 	$Id: convert,v 1.1.26.1 97/03/29 10:04:59 canavese Exp $
#
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
maskColor=6			#Brown mask
cvtfile /staff/pcgeos/Appl/Art/Art.20/ggame2.pcx 0 Uki $appArgs

