#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = instf
MAIN            = dosicon.goc iconedi.goc instf.goc instf2.goc tools.goc\
                  dosicon.goh iconedi.goh
UI              = appui.goc appui.goh
UI_TO_RDFS      =
OBJS            = dosicon.obj iconedi.obj instf.obj instf2.obj tools.obj\
                  appui.obj
COMMON          = instf.goh
MODULES         =
CMODULES        = Main UI
SRCS            = $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
