DBCS/GDIKEYBOARDMANAGER.obj \
DBCS/GDIKEYBOARDMANAGER.eobj: GEOS.DEF GEODE.DEF RESOURCE.DEF EC.DEF DRIVER.DEF LMEM.DEF \
                HEAP.DEF INPUT.DEF CHAR.DEF UNICODE.DEF GRAPHICS.DEF \
                FONTID.DEF FONT.DEF COLOR.DEF HWR.DEF TIMEDATE.DEF \
                SYSTEM.DEF LOCALIZE.DEF SLLANG.DEF INITFILE.DEF FILE.DEF \
                SYSSTATS.DEF ASSERT.DEF DISK.DEF DRIVE.DEF \
                OBJECTS/INPUTC.DEF OBJECTS/METAC.DEF OBJECT.DEF \
                CHUNKARR.DEF GEOWORKS.DEF INTERNAL/IM.DEF \
                INTERNAL/SEMINT.DEF OBJECTS/PROCESSC.DEF \
                INTERNAL/INTERRUP.DEF GDI.DEF INTERNAL/KBDDR.DEF \
                INTERNAL/KBDMAP.DEF OBJECTS/UIINPUTC.DEF \
                GDIKEYBOARDCONSTANT.DEF GDIKEYBOARDVARIABLE.DEF \
                GDIKEYBOARDSTRATEGY.ASM GDIKEYBOARDINIT.ASM \
                GDIKEYBOARDPROCESS.ASM

DBCS/gdiKbdEC.geo DBCS/gdiKbd.geo : geos.ldf 
