#!/bin/sh
##############################################################################
#
# 	Copyright (c) Geoworks 1993 -- All Rights Reserved
#
# PROJECT:	PC GEOS
# MODULE:	Tools/scripts -- branchpoint analysis
# FILE: 	bp
# AUTHOR: 	John Wedgwood,  9/17/93
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	jcw	 9/17/93	Initial Revision
#
# DESCRIPTION:
#	This file prints out a list of functions and the number of
#	decisions made in each function.
#
#	$Id: bp,v 1.4 94/04/20 00:33:05 don Exp $
#
###############################################################################

if [ "$*" ]; then
    files=$*
else
    files=`find . \( \( -name \*.asm \) -a \( \! \( -name \*_loc.asm \) \) \) -type f -print`
fi

if [ -f /staff/pcgeos/$USER/Tools/scripts/profile/bpData.awk ]; then
    data=/staff/pcgeos/$USER/Tools/scripts/profile/bpData.awk
    echo "using private awk file: $data"
else
    data=/staff/pcgeos/Tools/scripts/profile/bpData.awk
fi

awk -f $data $files | sort -r -n +0 +2 - | cut -c5- -
