#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = nonts
ASM_TO_OBJS     = nontsManager.asm
UI_TO_RDFS      =
SRCS            = nontsEntry.asm nontsExec.asm nontsManager.asm\
                  nontsShutdown.asm nontsStart.asm nontsStrings.asm\
                  nontsConstant.def nontsVariable.def
OBJS            = nontsManager.obj
LOBJS           =

PRODUCTS        = DBCS 

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(DBCS/$(DEPFILE))
#include "DBCS/$(DEPFILE)"
#endif
