#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = GPCBrow
JS              = browser.goc sebrowse.goc
ASMTOOLS        = asmtoolsManager.asm
HTMLVIEW        = AWATCHER.GOC GLBANIM.GOC HTMLVIEW.GOC IMPORTG.GOC\
                  LoadURL.goc OpenClos.goc scrapbk.goc STATTEXT.GOC\
                  UIAction.goc UIOften.goc UIRare.goc
INIT            = EXPIRE.GOC INIT.GOC EXPIREUI.GOH
NAVIGATE        = BOOKCLAS.GOC BOOKMARK.GOC FAVORCLS.GOC FAVORITE.GOC\
                  NAVCACHE.GOC NAVIGATE.GOC
URLDOC          = LOCALPAG.GOC URLDOC.GOC
URLDOCCT        = URLDOCCT.GOC
URLFETCH        = URLFETCH.GOC
URLFRAME        = FRFETCH.GOC URLFRAME.GOC
URLTEXT         = URLTEXT.GOC URLTEXT2.GOC
UI_TO_RDFS      =
OBJS            = browser.obj sebrowse.obj AWATCHER.obj GLBANIM.obj\
                  HTMLVIEW.obj IMPORTG.obj LoadURL.obj OpenClos.obj\
                  scrapbk.obj STATTEXT.obj UIAction.obj UIOften.obj\
                  UIRare.obj EXPIRE.obj INIT.obj BOOKCLAS.obj BOOKMARK.obj\
                  FAVORCLS.obj FAVORITE.obj NAVCACHE.obj NAVIGATE.obj\
                  LOCALPAG.obj URLDOC.obj URLDOCCT.obj URLFETCH.obj\
                  FRFETCH.obj URLFRAME.obj URLTEXT.obj URLTEXT2.obj
COMMON          = BOOKCLAS.GOH BOOKMARK.GOH BOOKUI.GOH EXPIRE.GOH\
                  FAVORCLS.GOH FAVORITE.GOH FAVORUI.GOH GLBANIM.GOH\
                  HTMLVIEW.GOH HTMLV_UI.GOH IMPORTG.GOH javascr.h\
                  LOCALUI.GOH OPTIONS.GOH prodGPC.goh prodNDO.goh\
                  sebrowse.h STATTEXT.GOH URLFETCH.GOH
MODULES         = ASMTOOLS
CMODULES        = JS HTMLVIEW INIT NAVIGATE URLDOC URLDOCCT URLFETCH\
                  URLFRAME URLTEXT
SRCS            = $(JS) $(ASMTOOLS) $(HTMLVIEW) $(INIT) $(NAVIGATE)\
                  $(URLDOC) $(URLDOCCT) $(URLFETCH) $(URLFRAME) $(URLTEXT)\
                  $(COMMON)
LOBJS           =

PRODUCTS        = AB  JS JSAB #JSABDBCS JSDBCS ABDBCS DBCS

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(AB/$(DEPFILE))
#include "AB/$(DEPFILE)"
#endif

#if exists(ABDBCS/$(DEPFILE))
#include "ABDBCS/$(DEPFILE)"
#endif

#if exists(DBCS/$(DEPFILE))
#include "DBCS/$(DEPFILE)"
#endif

#if exists(JS/$(DEPFILE))
#include "JS/$(DEPFILE)"
#endif

#if exists(JSAB/$(DEPFILE))
#include "JSAB/$(DEPFILE)"
#endif

#if exists(JSABDBCS/$(DEPFILE))
#include "JSABDBCS/$(DEPFILE)"
#endif

#if exists(JSDBCS/$(DEPFILE))
#include "JSDBCS/$(DEPFILE)"
#endif
