MROOM.obj \
MROOM.eobj: STDAPP.GOH OBJECT.GOH UI.GOH OBJECTS/METAC.GOH \
                OBJECTS/INPUTC.GOH OBJECTS/CLIPBRD.GOH \
                OBJECTS/UIINPUTC.GOH IACP.GOH OBJECTS/WINC.GOH \
                OBJECTS/GPROCC.GOH ALB.GOH OBJECTS/PROCESSC.GOH \
                OBJECTS/VISC.GOH OBJECTS/VCOMPC.GOH OBJECTS/VCNTC.GOH \
                OBJECTS/GAPPC.GOH OBJECTS/GENC.GOH OBJECTS/GINTERC.GOH \
                OBJECTS/GPRIMC.GOH OBJECTS/GDISPC.GOH OBJECTS/GTRIGC.GOH \
                OBJECTS/GVIEWC.GOH OBJECTS/GTEXTC.GOH OBJECTS/VTEXTC.GOH \
                OBJECTS/GCTRLC.GOH GCNLIST.GOH SPOOL.GOH \
                OBJECTS/GFSELC.GOH OBJECTS/GGLYPHC.GOH \
                OBJECTS/GDOCCTRL.GOH OBJECTS/GDOCGRPC.GOH \
                OBJECTS/GDOCC.GOH OBJECTS/GCONTC.GOH OBJECTS/GDCTRLC.GOH \
                OBJECTS/GEDITCC.GOH OBJECTS/GBOOLGC.GOH \
                OBJECTS/GITEMGC.GOH OBJECTS/GDLISTC.GOH \
                OBJECTS/GITEMC.GOH OBJECTS/GBOOLC.GOH \
                OBJECTS/GGADGETC.GOH OBJECTS/GTOOLCC.GOH \
                OBJECTS/GVALUEC.GOH OBJECTS/GTOOLGC.GOH \
                OBJECTS/HELPCC.GOH SOCKET.GOH OBJECTS/TEXT/TCTRLC.GOH \
                RULER.GOH OBJECTS/COLORC.GOH OBJECTS/STYLES.GOH \
                ACCPNT.GOH SOURCE/CLASSES/CLASSES.GOH \
                SOURCE/CLASSES/IPROCESS.GOH SOURCE/CLASSES/ITEXTLIM.GOH \
                SOURCE/CLASSES/ISORTLIS.GOH SOURCE/CLASSES/IEXPIRE.GOH \
                SOURCE/UI/UIMANAGE.GOH SOURCE/UI/APPLICAT.GOH \
                ART/TLICONS.GOH SOURCE/UI/INTERFAC.GOH \
                SOURCE/UI/BLUEBB.GOH SOURCE/UI/EXPIREUI.GOH \
                SOURCE/ROUTINES/PARSING.GOH SOURCE/ROUTINES/TEXTOUTP.GOH \
                SOURCE/ROUTINES/IRC.GOH SOURCE/CLASSES/CTEXTLIM.GOH \
                SOURCE/CLASSES/CSORTLIS.GOH SOURCE/CLASSES/CPROCESS.GOH \
                SOURCE/CLASSES/CEXPIRE.GOH
MROOM.obj \
MROOM.eobj: MROOM.GOC GEOS.H HEAP.H GEODE.H RESOURCE.H EC.H OBJECT.H \
                LMEM.H GRAPHICS.H FONTID.H FONT.H COLOR.H GSTRING.H \
                TIMER.H VM.H DBASE.H LOCALIZE.H ANSI/CTYPE.H TIMEDATE.H \
                FILE.H SLLANG.H SYSTEM.H GEOWORKS.H CHUNKARR.H \
                OBJECTS/HELPCC.H DISK.H DRIVE.H INPUT.H CHAR.H HWR.H \
                WIN.H UDIALOG.H OBJECTS/GINTERC.H OBJECTS/TEXT/TCOMMON.H \
                STYLESH.H DRIVER.H THREAD.H PRINT.H INTERNAL/SPOOLINT.H \
                SERIALDR.H PARALLDR.H HUGEARR.H FILEENUM.H MEDIUM.H \
                SOCKMISC.H INITFILE.H ANSI/STRING.H ANSI/STDIO.H \
                ANSI/STDLIB.H
TXT_STRS.obj \
TXT_STRS.eobj: 
TXT_STRS.obj \
TXT_STRS.eobj: TXT_STRS.GOC GEOS.H GEODE.H OBJECT.H LMEM.H

TLoungeEC.geo TLounge.geo : GEOS.LDF UI.LDF SOCKET.LDF ANSIC.LDF TEXT.LDF ACCPNT.LDF 