#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = stub
ASM_TO_OBJS     = rpc.asm break.asm kernel.asm netware.asm atron.asm\
                  tbreak.asm timebreak.asm com.asm bsw.asm bpt.asm\
                  wincom.asm main.asm cbreak.asm intelbpt.asm
UI_TO_RDFS      =
SRCS            = rpc.asm break.asm kernel.asm netware.asm atron.asm\
                  tbreak.asm timebreak.asm com.asm bsw.asm bpt.asm\
                  wincom.asm main.asm cbreak.asm intelbpt.asm bsw.def\
                  atron.def zoomer.def use32.def gulliver.def wincom.def\
                  rpc.def netware.def respcom.def pcmcia.def pscope.def\
                  resp.def penelope.def stub.def com.def
OBJS            = rpc.obj break.obj kernel.obj netware.obj atron.obj\
                  tbreak.obj timebreak.obj com.obj bsw.obj bpt.obj\
                  wincom.obj main.obj cbreak.obj intelbpt.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
