#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bnf
ASM_TO_OBJS     = bnfManager.asm
UI_TO_RDFS      = bnf.ui
SRCS            = bnfApplication.asm bnfClipboard.asm bnfDriver.asm\
                  bnfInitExit.asm bnfItem.asm bnfMain.asm bnfManager.asm\
                  bnfStrings.asm bnfSummons.asm bnfUtils.asm\
                  taskStrings.asm taskInit.asm taskSwitch.asm\
                  taskApplication.asm taskDriver.asm taskTrigger.asm\
                  taskItem.asm taskUtils.asm taskClipboard.asm\
                  bnfConstant.def bnfVariable.def bnf.ui
OBJS            = bnfManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
