#!/usr/public/perl
# -*- perl -*-
##############################################################################
#
#       Copyright (c) Geoworks 1996 -- All Rights Reserved
#	GEOWORKS CONFIDENTIAL
#
# PROJECT:      Spock
# MODULE:       Tools/scripts/perl -- pgp extraction tool 
# FILE:         depgp
# AUTHOR:       Chris Hawley-Ruppel
#
# REVISION HISTORY:
#       Name    Date            Description
#       ----    ----            -----------
#	CBH	12/ 6/96	Initial version
#
# DESCRIPTION:
#       Allows users to de-pgp multiple files.
#
# USAGE:
#	Run "depgp" with no arguments for help.
#
#       $Id: depgp,v 1.1 96/12/06 12:30:03 chris Exp $
#
###############################################################################

$0 =~ s,.*/([^/]+),\1,;		# munge argv[0]

if ($#ARGV eq "-1") {
    print "Usage: $0 file1 <file2> ..\n";
    exit;
}

print "Enter your PGP pass phrase: ";
chop($ENV{"PGPPASS"} = <STDIN>);

$errors = 0;

foreach $i (0 .. $#ARGV) {
    if (system ("pgp +batchMode +force $ARGV[$i]") > 256) {
	$errors ++;
	$errorFiles .= "\t" . $ARGV[$i] . "\n"
    }
}

print "\n\n";
if ($errors) {
    print "ERRORS OCCURRED IN:\n";
    print $errorFiles;
}



