#!/usr/public/perl
# -*- perl -*-
##############################################################################
#
# 	Copyright (c) Geoworks 1996.  All rights reserved.
#       GEOWORKS CONFIDENTIAL
#
# PROJECT:	PCGEOS
# MODULE:	Tools
# FILE: 	dirtree.pl
# AUTHOR: 	Paul Canavese, Sep  5, 1996
#
# REVISION HISTORY:
#	Name		Date		Description
#	----		----		-----------
#	canavese        9/ 5/96   	Initial Revision
#
# DESCRIPTION:
#	Generate an indented directory tree for the specified (or current)
#	directory.
#
# USAGE:
#       dirtree [<directory list>]
#
#	$Id: dirtree,v 1.1 96/09/18 12:36:55 canavese Exp $
#
###############################################################################

$indent=0;

if ( @ARGV ) {
    foreach $arg (@ARGV) {
	chdir("$arg");
	$cwd=`pwd`;
	chop($cwd);
	print "[$cwd]\n\n";
	&PrintDir();
	print "\n";
    }
} else {
    $cwd=`pwd`;
    chop($cwd);
    print "[$cwd]\n\n";
    &PrintDir();
}

sub PrintDir {

    opendir(CURRENTDIR, ".");
    local(@files)=readdir(CURRENTDIR);
    local(@dirs);
    closedir(CURRENTDIR);

    @files=sort(@files);
    foreach $file (@files) {

	if ( -l "$file" ) {
	    &Indent();
	    if ( -d "$file" ) {
		print "[$file]\@\n";
	    } else {
		print "$file\@\n";
	    }
	} elsif ( -f "$file" ) {
	    &Indent();
	    if ( -x "$file" ) {
		print "$file*\n";
	    } else {
		print "$file\n";
	    }
	} elsif ( -d "$file" ) {
	    push(@dirs, "$file");
	}
    }
    @dirs=sort(@dirs);
    foreach $dir (@dirs) {
	if ( "$dir" eq "." || "$dir" eq ".."  ) {
	    next;
	}
	if ( "$dir" eq "RCS" ) {
	    next;
	}
	&Indent();
	print "[$dir]\n";
	chdir "$dir";
	$indent+=3;
	&PrintDir();
	$indent-=3;
	chdir "..";
    }
}

sub Indent {
    print " " x $indent ;
    print "\\_";
}


