#!/bin/sh
###############################################################################
#
#	Copyright (C) GeoWorks 1991, 1992 -- All Rights Reserved
#
#	PROJECT:	PC/GEOS
#	FILE:		dsgames
#
#	AUTHOR:		Chris Hawley-Ruppel 3/ 1/95
#
#	REVISION HISTORY:
#		Name	Date		Description
#		----	----		-----------
#		cbh	3/ 1/95		Initial Revision
#
#	$Id: dsgames,v 1.3 95/03/01 18:09:49 chris Exp $
#
###############################################################################
sedit="sed -e 's/ /beat/' -e 's/ /,/' -e 's/ /-/' -e 's/ /on/' -e 's+ +/+' -e 's/beat/ beat /' -e 's/on/ on /' -e 's/1994//'"

if [ $3 ]; then
	if [ $3 = "all" ]; then
		grep $1 /usr/games/lib/ds/log | grep $2 | eval $sedit | sed -e 's/,/,	/'
	else
		grep $1 /usr/games/lib/ds/log | grep $2 | tail -$3 | eval $sedit | sed -e 's/,/,	/'
	fi
else
	if [ $2 = "all" ]; then
		grep $1 /usr/games/lib/ds/log | eval $sedit | sed -e 's/,/,	/'
	else
		grep $1 /usr/games/lib/ds/log | tail -$2 | eval $sedit | sed -e 's/,/,	/'
	fi
fi



#	echo    Usage:
#	echo	dsgames andrew 20	- Shows Andrew's last 20 games
#	echo 	dsgames andrew all	- Shows all of Andrew's games
#	echo 	dsgames andrew jimw 5	- Shows Andrew and Jimw's last 5 games
#	echo 	dsgames andrew jimw all	- Shows all of Andrew and Jimw's games
#else


