#!/usr/public/perl
# -*- perl -*-
# $Id: heapspace,v 1.1 95/09/20 16:59:49 jacob Exp $
# Written by Chris Thomas

if ($#ARGV < 0) {
    print "Usage: $0 <geode_file> [<paragraphs> | <kilobytes>K]\n";
    exit;
}

$heapspace_offset = 0x104;

open(input, "+<$ARGV[0]");
binmode input;
seek(input, $heapspace_offset, 0);
sysread(input, $buf, 2);
$heapspace = unpack("v", $buf);

if ($#ARGV == 0) {
    printf "Heapspace = %d paragraphs, %d bytes, %dK\n",
    $heapspace,
    $heapspace*16,
    $heapspace*16/1024;
}

if ($#ARGV > 0) {
    if ($ARGV[1] =~ /([0-9]+)[kK]/) {
	$ARGV[1] = $1 * 1024/16;
    }
    seek(input, $heapspace_offset, 0);
    $buf = pack("v", $ARGV[1]);
    syswrite(input, $buf, 2);
}

close(input);
