#!/usr/public/perl
# -*- perl -*-
# $Id: jedi-bug-report,v 1.2 95/05/08 11:09:50 jacob Exp $

require("newgetopt.pl");

$0 =~ s,.*/([^/]+),\1,;		# munge argv[0]

$PREFIX		= "/staff/pcgeos/Release20X";
$INCLUDE	= "$PREFIX/Include";
$CINCLUDE	= "$PREFIX/CInclude";
$IIJEDI		= "$INCLUDE/Internal/Jedi";
$CIIJEDI	= "$CINCLUDE/Internal/Jedi";
$INSTALLED	= "$PREFIX/Installed";
$EXT		= $INSTALLED . "/Library/Extensions";
$JEDI		= $INSTALLED . "/Library/Jedi";

@libs = ("gadgets", 
	 "mtable",
	 "table", 
	 "jedidemo",
	 "jedit", 
	 "jerror",
 	 "jhardware",
	 "jkbd",
	 "jlib", 
	 "jmotif",
	 "jotter",
	 "jpref",
	 "jtable", 
	 "jutils",
	 "jwtime",
	 "rtcm",
	 "vadem"
);

&NGetOpt("d=s") || &usage;
$opt_d || &usage;

foreach $lib (sort @libs) {
    print "\U$lib\E bugs FIXED since $opt_d:\n";
    open(FIXED, "-|") || exec "showbugs -f FULL -g $lib -d DF gt $opt_d";
    while (<FIXED>) {print};
    close(FIXED);

    print "\U$lib\E bugs still OPEN:\n";
    open(OPEN, "-|") || exec "showbugs -c OPEN -f FULL -g $lib";
    while (<OPEN>) {print};
    close(OPEN);
    print;
}

sub usage {
    die "usage: $0 -d mm/dd/yy";
}
