#!/usr/public/perl
# -*- perl -*-
##############################################################################
#
# 	Copyright (c) Geoworks 1996 -- All Rights Reserved
#       GEOWORKS CONFIDENTIAL
#
# PROJECT:	PCGEOS
# MODULE:	Tools
# FILE: 	makepath
# AUTHOR: 	Paul Canavese, Aug 15, 1996
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	PC	8/15/96   	Initial Revision
#
# DESCRIPTION:
#	Make the specified path if it doesn't exist.
#
#	$Id: makepath,v 1.1 96/09/04 12:14:42 canavese Exp $
#
###############################################################################


do "/staff/pcgeos/Tools/scripts/perl/lib/include.pl";
&Include("unixfile.pl");

if ( ! "@ARGV" ) {
    print "Usage: makepath <path>\n";
    exit -1;
} else {
    $result=&MakePath("@ARGV");
    exit "$result";
}

