#!/usr/public/perl
# -*- perl -*-
##############################################################################
#
# 	Copyright (c) Geoworks 1996 -- All Rights Reserved
#       GEOWORKS CONFIDENTIAL
#
# PROJECT:	PCGEOS
# MODULE:	Tools
# FILE: 	otherbdir
# AUTHOR: 	Paul Canavese, Aug 15, 1996
#
# REVISION HISTORY:
#	Name	Date		Description
#	----	----		-----------
#	PC	8/15/96   	Initial Revision
#
# DESCRIPTION:
#	Print the "other" branch directory.
#
#	$Id: otherbdir,v 1.1 96/12/18 20:00:57 canavese Exp $
#
###############################################################################

do "/staff/pcgeos/Tools/scripts/perl/lib/branch.pl";

chop($dir=`pwd`);
if ( $dir !~ m|.*/pcgeos/[A-Z]| ) {
    print STDERR "Error: not in source or installed tree.\n";
    print ".\n";
    exit 0;
}
if ( "@ARGV" ) {
    if ( ("@ARGV" eq "Trunk") || ("@ARGV" eq "trunk") ) {
	if ( &Branch() eq "Trunk" ) {
	    print STDERR "Error: you are already on the trunk.\n";
	    exit 0;
	} else {
	    @ARGV=".";
	}
    } elsif ( "@ARGV" !~ /^[A-Z]/ ) {
	print STDERR "Error: @ARGV is not a valid branch name.\n";
	print ".\n";
	exit 0;
    }
    if ( &Branch() eq "Trunk" ) {
	$dir =~ s|.*/pcgeos(.*)|/staff/pcgeos/@ARGV$1|;
    } else {
	$dir =~ s|.*/pcgeos/[^/]*(.*)|/staff/pcgeos/@ARGV$1|;
    }
} else {
    if ( &Branch() eq "Trunk" ) {
	print STDERR "Error: you are already on the trunk.\n";
	exit 0;
    } else {
	$dir =~ s|.*/pcgeos/[^/]*(.*)|/staff/pcgeos$1|;
    }
}

if ( "$dir" ) {
    print "$dir\n";
    exit 1;
} else {
    print STDERR "Error: not in source or installed tree.\n";
    print ".\n";
    exit 0;
}
