#!/bin/sh
###############################################################################
#
#	Copyright (C) GeoWorks 1991, 1992 -- All Rights Reserved
#
#	PROJECT:	PC/GEOS
#	FILE:		makeRespDist
#
#	AUTHOR:		Chris Hawley-Ruppel 8/ 8/94
#
#	REVISION HISTORY:
#		Name	Date		Description
#		----	----		-----------
#		cbh	8/ 8/94		Initial Revision
#
#	$Id: ponggames,v 1.3 96/10/04 17:29:46 chris Exp $
#
###############################################################################
sedit="sed -e 's/ /beat/' -e 's/ /,/' -e 's/ /-/' -e 's/ /#on#/' -e 's+ +/+' -e 's/beat/ beat /' -e 's/#on#/ on /' -e 's/1994//'"

if [ ! $1 ]; then
	echo    Usage:
	echo	games andrew 20		- Shows Andrew's last 20 games
	echo 	games andrew all	- Shows all of Andrew's games
	echo 	games andrew jimw 5	- Shows Andrew and Jimw's last 5 games
	echo 	games andrew jimw all	- Shows all of Andrew and Jimw's games
fi

if [ $3 ]; then
	if [ $3 = "all" ]; then
		grep $1 /n/yb/pong/log | grep $2 | eval $sedit | sed -e 's/,/,	/'
	else
		grep $1 /n/yb/pong/log | grep $2 | tail -$3 | eval $sedit | sed -e 's/,/,	/'
	fi
else
	if [ $2 = "all" ]; then
		grep $1 /n/yb/pong/log | eval $sedit | sed -e 's/,/,	/'
	else
		grep $1 /n/yb/pong/log | tail -$2 | eval $sedit | sed -e 's/,/,	/'
	fi
fi

