#!/usr/public/perl
# -*- perl -*-
##############################################################################
#
# 	Copyright (c) Geoworks 1996.  All rights reserved.
#       GEOWORKS CONFIDENTIAL
#
# PROJECT:	PCGEOS
# MODULE:	Tools
# FILE: 	rcmpgeo
# AUTHOR: 	Paul Canavese, Sep  3, 1996
#
# REVISION HISTORY:
#	Name		Date		Description
#	----		----		-----------
#	canavese	9/ 3/96   	Initial Revision
#
# DESCRIPTION:
#	Runs cmpgeo on all geodes in this directory or below.
#
#	$Id: rcmpgeo,v 1.1 96/09/04 11:54:26 canavese Exp $
#
###############################################################################
#

$cwd=`pwd`;
chop($cwd);
@geodes=`find . -name '*.geo' -print`;

foreach $geode (@geodes) {
    chop($geode);
    print "Running cmpgeo on $geode...\n";
    ($path=$geode)=~s|/[^/]*$||;
    chdir($path);
    ($geodeshortname=$geode)=~s|.*/([^/]*)\.geo|\1|;
    system("cmpgeo $geodeshortname");
    print "\n";
    chdir("$cwd");
}

