#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bbgrmt
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = CR8_MTDS.goc DOC_MTDS.goc LST_MTDS.goc RBOXUI.goc\
                  SEL_MTDS.goc SRV_MTDS.goc rba_icon.goh rbd_icon.goh\
                  rbox.goh
OBJS            = CR8_MTDS.obj DOC_MTDS.obj LST_MTDS.obj RBOXUI.obj\
                  SEL_MTDS.obj SRV_MTDS.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
