#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = ttf2
FREETYPE        = ftxkern.c ttcache.c ttcalc.c ttcmap.c ttdebug.c\
                  ttextend.c ttfile.c ttgload.c ttinterp.c ttload.c\
                  ttmemory.c ttmutex.c ttobjs.c ttraster.c ttapi.c\
                  freetype.h ft_conf.h fterrid.h ftnameid.h ftxkern.h\
                  header.h ttcache.h ttcalc.h ttcmap.h ttconfig.h ttdebug.h\
                  ttengine.h ttextend.h ttfile.h ttgload.h ttinterp.h\
                  ttload.h ttmemory.h ttmutex.h ttobjs.h ttraster.h\
                  tttables.h tttags.h tttypes.h
UI              = ttf2.goc
UI_TO_RDFS      =
OBJS            = ftxkern.obj ttcache.obj ttcalc.obj ttcmap.obj ttdebug.obj\
                  ttextend.obj ttfile.obj ttgload.obj ttinterp.obj\
                  ttload.obj ttmemory.obj ttmutex.obj ttobjs.obj\
                  ttraster.obj ttapi.obj ttf2.obj
COMMON          =
MODULES         =
CMODULES        = FreeType Ui
SRCS            = $(FREETYPE) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
