#!/bin/sh -
#
#
# Project:	PC GEOS
# Module:	Solitaire
# File:		convert
#
# Author:	atw
#
#	This file contains the convert information for this application.
#
# 	$Id: convert,v 1.2.3.1 97/03/29 10:01:47 canavese Exp $
#
#
. /staff/pcgeos/Appl/Art/Art.20/cvtcommon
cvtfile /staff/pcgeos/Appl/Art/Art.20/gshuf1.pcx 4 Hearts $appArgs


