#
#  ==CONFIDENTIAL INFORMATION==
#  COPYRIGHT 1994-99 BREADBOX COMPUTER COMPANY --
#  ALL RIGHTS RESERVED  --
#  THE FOLLOWING CONFIDENTIAL INFORMATION IS BEING DISCLOSED TO YOU UNDER A
#  NON-DISCLOSURE AGREEMENT AND MAY NOT BE DISCLOSED OR FORWARDED BY THE
#  RECIPIENT TO ANY OTHER PERSON OR ENTITY NOT COVERED BY THE SAME
#  NON-DISCLOSURE AGREEMENT COVERING THE RECIPIENT. USE OF THE FOLLOWING
#  CONFIDENTIAL INFORMATION IS RESTRICTED TO THE TERMS OF THE NON-DISCLOSURE
#  AGREEMENT.
#

#
#	Local makefile for: gpcchat
#
#
# Pass flag for multi-launchability
#             removed - jfh
#LINKFLAGS	+= -r

#include <$(SYSMAKEFILE)>
