rem All Rem'd so I don't accidentally regenerate ;-)

rem cvtpcx -2 -w78 -h52 -m1 -G -nQTip1 -oQTip1.goh vac_tip1.pcx
rem cvtpcx -2 -w48 -h30 -m1 -G -nQTip2 -oQTip2.goh vac_tip2.pcx
rem cvtpcx -2 -w48 -h30 -m1 -G -nQTip3 -oQTip3.goh vac_tip3.pcx

rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJbun -o8bun.goh vac001-8.pcx
rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJbag -o8bag.goh vac002-8.pcx

rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJvac1l -o8vac1l.goh vac005-8.pcx
rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJvac2l -o8vac2l.goh vac015-8.pcx
rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJvac3l -o8vac3l.goh vac006-8.pcx
rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJvac1r -o8vac1r.goh vac005a-8.pcx
rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJvac2r -o8vac2r.goh vac015a-8.pcx
rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJvac3r -o8vac3r.goh vac006a-8.pcx
rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJvac1u -o8vac1u.goh vac007-8.pcx
rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJvac2u -o8vac2u.goh vac016-8.pcx
rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJvac3u -o8vac3u.goh vac008-8.pcx
rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJvac1d -o8vac1d.goh vac007a-8.pcx
rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJvac2d -o8vac2d.goh vac016a-8.pcx
rem cvtpcx -2 -w21 -h21 -m1 -G -g -nJvac3d -o8vac3d.goh vac008a-8.pcx

rem cvtpcx -2 -w63 -h63 -m1 -G -g -nCloud1 -oCloud1.goh vac010-8.pcx
rem cvtpcx -2 -w63 -h63 -m1 -G -g -nCloud2 -oCloud2.goh vac011-8.pcx
rem cvtpcx -2 -w63 -h63 -m1 -G -g -nCloud3 -oCloud3.goh vac012-8.pcx
