#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = mflash
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = MATHFLSH.GOC PASSWORD.GOC SOUND.GOC STUD_DB.GOC\
                  MAPBOARD.GOC CLASSES.GOH EQUATION.GOH MAPBOARD.GOH\
                  MATHFLSH.GOH PASSWDUI.GOH PASSWORD.GOH STUD_DB.GOH
OBJS            = MATHFLSH.obj PASSWORD.obj SOUND.obj STUD_DB.obj\
                  MAPBOARD.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
