#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = mflash
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = STUD_DB.goc MAPBOARD.goc PASSWORD.goc SOUND.goc\
                  MATHFLSH.goc classes.goh mapboard.goh mathflsh.goh\
                  stud_db.goh password.goh passwdui.goh
OBJS            = STUD_DB.obj MAPBOARD.obj PASSWORD.obj SOUND.obj\
                  MATHFLSH.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
