#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = geozip
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = apptools.goc compress.goc dialogs.goc extract.goc\
                  newdoc.goc process.goc Strings.goc view.goc zipui.goc\
                  compress.goh extract.goh geozip.goh process.goh view.goh\
                  zipui.goh
OBJS            = apptools.obj compress.obj dialogs.obj extract.obj\
                  newdoc.obj process.obj Strings.obj view.obj zipui.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
