#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = GEOZIP
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = APPTOOLS.GOC COMPRESS.GOC DIALOGS.GOC EXTRACT.GOC\
                  NEWDOC.GOC PROCESS.GOC Strings.goc VIEW.GOC ZIPUI.GOC\
                  COMPRESS.GOH EXTRACT.GOH GEOZIP.GOH PROCESS.GOH VIEW.GOH\
                  ZIPUI.GOH
OBJS            = APPTOOLS.obj COMPRESS.obj DIALOGS.obj EXTRACT.obj\
                  NEWDOC.obj PROCESS.obj Strings.obj VIEW.obj ZIPUI.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
