#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = geozip
ASM_TO_OBJS     =
UI_TO_RDFS      =
SRCS            = apptools.goc dialogs.goc view.goc newdoc.goc zipui.goc\
                  Strings.goc extract.goc compress.goc process.goc\
                  compress.goh zipui.goh process.goh view.goh geozip.goh\
                  extract.goh
OBJS            = apptools.obj dialogs.obj view.obj newdoc.obj zipui.obj\
                  Strings.obj extract.obj compress.obj process.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
