#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = gwpoker
ASM_TO_OBJS     = gwpoker.asm
UI_TO_RDFS      = gwpoker.ui
SRCS            = pokerGame.asm payoffDisplay.asm pokerSound.asm\
                  gwpoker.asm sizes.def myMacros.def mkrHearts.ui\
                  gwpoker.ui
OBJS            = gwpoker.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
