#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = GWPOKER
ASM_TO_OBJS     = gwpoker.asm
UI_TO_RDFS      = GWPOKER.UI
SRCS            = gwpoker.asm payoffDisplay.asm pokerGame.asm\
                  pokerSound.asm myMacros.def sizes.def gwpoker.ui\
                  mkrHearts.ui
OBJS            = gwpoker.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
